import 'rollable_table.dart';

/// Complete 5e SRD datasets for Gemstones, Art Objects, Magic Item Tables A-I,
/// Individual Loot Drops, and Treasure Hoards.
class SrdLootTables {
  SrdLootTables._();

  // ==========================================
  // GEMSTONES (10 GP to 5,000 GP)
  // ==========================================
  static const List<GemArtItem> gemstones10gp = [
    GemArtItem(name: 'Azurite', gpValue: 10, category: '10 gp Gemstone', description: 'Opaque mottled deep blue'),
    GemArtItem(name: 'Banded Agate', gpValue: 10, category: '10 gp Gemstone', description: 'Translucent striped brown, blue, white, or red'),
    GemArtItem(name: 'Blue Quartz', gpValue: 10, category: '10 gp Gemstone', description: 'Transparent pale blue'),
    GemArtItem(name: 'Eye Agate', gpValue: 10, category: '10 gp Gemstone', description: 'Translucent circles of gray, white, brown, blue, or green'),
    GemArtItem(name: 'Hematite', gpValue: 10, category: '10 gp Gemstone', description: 'Opaque gray-black with metallic luster'),
    GemArtItem(name: 'Lapis Lazuli', gpValue: 10, category: '10 gp Gemstone', description: 'Opaque light and dark blue with yellow flecks'),
    GemArtItem(name: 'Malachite', gpValue: 10, category: '10 gp Gemstone', description: 'Opaque striated light and dark green'),
    GemArtItem(name: 'Moss Agate', gpValue: 10, category: '10 gp Gemstone', description: 'Translucent pink or yellow-white with mossy gray or green markings'),
    GemArtItem(name: 'Obsidian', gpValue: 10, category: '10 gp Gemstone', description: 'Opaque black volcanic glass'),
    GemArtItem(name: 'Rhodochrosite', gpValue: 10, category: '10 gp Gemstone', description: 'Opaque light pink'),
    GemArtItem(name: 'Tiger Eye', gpValue: 10, category: '10 gp Gemstone', description: 'Translucent brown with golden center'),
    GemArtItem(name: 'Turquoise', gpValue: 10, category: '10 gp Gemstone', description: 'Opaque light blue-green'),
  ];

  static const List<GemArtItem> gemstones50gp = [
    GemArtItem(name: 'Bloodstone', gpValue: 50, category: '50 gp Gemstone', description: 'Opaque dark gray with red flecks'),
    GemArtItem(name: 'Carnelian', gpValue: 50, category: '50 gp Gemstone', description: 'Opaque orange to red-brown'),
    GemArtItem(name: 'Chalcedony', gpValue: 50, category: '50 gp Gemstone', description: 'Opaque white'),
    GemArtItem(name: 'Chrysoprase', gpValue: 50, category: '50 gp Gemstone', description: 'Translucent green'),
    GemArtItem(name: 'Citrine', gpValue: 50, category: '50 gp Gemstone', description: 'Transparent pale yellow-brown'),
    GemArtItem(name: 'Jasper', gpValue: 50, category: '50 gp Gemstone', description: 'Opaque blue, black, or brown'),
    GemArtItem(name: 'Moonstone', gpValue: 50, category: '50 gp Gemstone', description: 'Translucent white with pale blue glow'),
    GemArtItem(name: 'Onyx', gpValue: 50, category: '50 gp Gemstone', description: 'Opaque bands of black and white'),
    GemArtItem(name: 'Quartz', gpValue: 50, category: '50 gp Gemstone', description: 'Transparent white, smoky gray, or yellow'),
    GemArtItem(name: 'Sardonyx', gpValue: 50, category: '50 gp Gemstone', description: 'Opaque bands of red and white'),
    GemArtItem(name: 'Star Rose Quartz', gpValue: 50, category: '50 gp Gemstone', description: 'Translucent rosy stone with white star-shaped center'),
    GemArtItem(name: 'Zircon', gpValue: 50, category: '50 gp Gemstone', description: 'Transparent pale blue-green'),
  ];

  static const List<GemArtItem> gemstones100gp = [
    GemArtItem(name: 'Amber', gpValue: 100, category: '100 gp Gemstone', description: 'Transparent watery gold to rich gold'),
    GemArtItem(name: 'Amethyst', gpValue: 100, category: '100 gp Gemstone', description: 'Transparent deep purple'),
    GemArtItem(name: 'Chrysoberyl', gpValue: 100, category: '100 gp Gemstone', description: 'Transparent yellow-green to pale green'),
    GemArtItem(name: 'Coral', gpValue: 100, category: '100 gp Gemstone', description: 'Opaque crimson'),
    GemArtItem(name: 'Garnet', gpValue: 100, category: '100 gp Gemstone', description: 'Transparent red, brown-green, or violet'),
    GemArtItem(name: 'Jade', gpValue: 100, category: '100 gp Gemstone', description: 'Translucent light green, deep green, or white'),
    GemArtItem(name: 'Pearl', gpValue: 100, category: '100 gp Gemstone', description: 'Opaque lustrous white, yellow, or pink'),
    GemArtItem(name: 'Spinel', gpValue: 100, category: '100 gp Gemstone', description: 'Transparent red, red-brown, or deep green'),
    GemArtItem(name: 'Tourmaline', gpValue: 100, category: '100 gp Gemstone', description: 'Transparent pale green, blue, brown, or red'),
  ];

  static const List<GemArtItem> gemstones500gp = [
    GemArtItem(name: 'Alexandrite', gpValue: 500, category: '500 gp Gemstone', description: 'Transparent dark green that shines red under candlelight'),
    GemArtItem(name: 'Aquamarine', gpValue: 500, category: '500 gp Gemstone', description: 'Transparent pale blue-green'),
    GemArtItem(name: 'Black Pearl', gpValue: 500, category: '500 gp Gemstone', description: 'Opaque pure black with iridescence'),
    GemArtItem(name: 'Blue Spinel', gpValue: 500, category: '500 gp Gemstone', description: 'Transparent deep blue'),
    GemArtItem(name: 'Peridot', gpValue: 500, category: '500 gp Gemstone', description: 'Transparent rich olive green'),
    GemArtItem(name: 'Topaz', gpValue: 500, category: '500 gp Gemstone', description: 'Transparent golden yellow'),
  ];

  static const List<GemArtItem> gemstones1000gp = [
    GemArtItem(name: 'Black Opal', gpValue: 1000, category: '1,000 gp Gemstone', description: 'Translucent dark green with black mottling and golden flecks'),
    GemArtItem(name: 'Blue Sapphire', gpValue: 1000, category: '1,000 gp Gemstone', description: 'Transparent gleaming blue-white to deep blue'),
    GemArtItem(name: 'Emerald', gpValue: 1000, category: '1,000 gp Gemstone', description: 'Transparent brilliant green'),
    GemArtItem(name: 'Fire Opal', gpValue: 1000, category: '1,000 gp Gemstone', description: 'Translucent fiery red'),
    GemArtItem(name: 'Opal', gpValue: 1000, category: '1,000 gp Gemstone', description: 'Translucent pale blue with green and golden play of light'),
    GemArtItem(name: 'Star Ruby', gpValue: 1000, category: '1,000 gp Gemstone', description: 'Translucent ruby with a glowing six-pointed star'),
    GemArtItem(name: 'Star Sapphire', gpValue: 1000, category: '1,000 gp Gemstone', description: 'Translucent blue sapphire with a glowing six-pointed star'),
    GemArtItem(name: 'Yellow Sapphire', gpValue: 1000, category: '1,000 gp Gemstone', description: 'Transparent fiery yellow or yellow-green'),
  ];

  static const List<GemArtItem> gemstones5000gp = [
    GemArtItem(name: 'Black Sapphire', gpValue: 5000, category: '5,000 gp Gemstone', description: 'Translucent lustrous black with glowing highlights'),
    GemArtItem(name: 'Diamond', gpValue: 5000, category: '5,000 gp Gemstone', description: 'Transparent brilliant blue-white crystalline perfection'),
    GemArtItem(name: 'Jacinth', gpValue: 5000, category: '5,000 gp Gemstone', description: 'Transparent fiery orange-red stone of power'),
    GemArtItem(name: 'Ruby', gpValue: 5000, category: '5,000 gp Gemstone', description: 'Transparent pure clear crimson perfection'),
  ];

  // ==========================================
  // ART OBJECTS (25 GP to 7,500 GP)
  // ==========================================
  static const List<GemArtItem> artObjects25gp = [
    GemArtItem(name: 'Silver Ewer', gpValue: 25, category: '25 gp Art Object', description: 'Elegantly shaped pitcher of polished silver'),
    GemArtItem(name: 'Carved Bone Statuette', gpValue: 25, category: '25 gp Art Object', description: 'Intricate statuette depicting a roaring beast'),
    GemArtItem(name: 'Small Gold Bracelet', gpValue: 25, category: '25 gp Art Object', description: 'Thin bracelet of hammered gold'),
    GemArtItem(name: 'Cloth-of-Gold Vestments', gpValue: 25, category: '25 gp Art Object', description: 'Ceremonial clerical robe woven with gold thread'),
    GemArtItem(name: 'Black Velvet Mask with Silver Thread', gpValue: 25, category: '25 gp Art Object', description: 'Masquerade mask lined with silver embroidery'),
    GemArtItem(name: 'Copper Chalice with Silver Filigree', gpValue: 25, category: '25 gp Art Object', description: 'Goblet adorned with entwined vines'),
    GemArtItem(name: 'Pair of Engraved Bone Dice', gpValue: 25, category: '25 gp Art Object', description: 'Carved dice with obsidian inlaid pips'),
    GemArtItem(name: 'Small Mirror in Painted Wooden Frame', gpValue: 25, category: '25 gp Art Object', description: 'Polished silver glass with floral lacquer border'),
    GemArtItem(name: 'Embroidered Silk Handkerchief', gpValue: 25, category: '25 gp Art Object', description: 'Fine elven silk embroidered with a noble crest'),
    GemArtItem(name: 'Gold Locket with Painted Portrait', gpValue: 25, category: '25 gp Art Object', description: 'Hinged keepsake holding a delicate watercolor mini'),
  ];

  static const List<GemArtItem> artObjects250gp = [
    GemArtItem(name: 'Gold Ring with Bloodstones', gpValue: 250, category: '250 gp Art Object', description: 'Heavy signet ring inlaid with 4 bloodstones'),
    GemArtItem(name: 'Carved Ivory Statuette', gpValue: 250, category: '250 gp Art Object', description: 'Exquisite carving of a soaring dragon'),
    GemArtItem(name: 'Large Gold Bracelet', gpValue: 250, category: '250 gp Art Object', description: 'Broad cuff bracelet etched with celestial runes'),
    GemArtItem(name: 'Silver Chalice with Lapis Lazuli', gpValue: 250, category: '250 gp Art Object', description: 'Ceremonial chalice studded with deep blue gems'),
    GemArtItem(name: 'Silk Robe with Gold Embroidery', gpValue: 250, category: '250 gp Art Object', description: 'Gown fit for high court nobility'),
    GemArtItem(name: 'Bronze Crown with Obsidian Spikes', gpValue: 250, category: '250 gp Art Object', description: 'Warrior king coronal with dark volcanic glass'),
    GemArtItem(name: 'Jeweled Anklet with Tiny Bells', gpValue: 250, category: '250 gp Art Object', description: 'Platinum chain with turquoise and chiming silver bells'),
    GemArtItem(name: 'Painted Gold Mask', gpValue: 250, category: '250 gp Art Object', description: 'Solid gold theater mask depicting joy and sorrow'),
  ];

  static const List<GemArtItem> artObjects750gp = [
    GemArtItem(name: 'Silver Chalice with Moonstones', gpValue: 750, category: '750 gp Art Object', description: 'Chalice set with glowing moonstones'),
    GemArtItem(name: 'Gilded Wooden Harp with Zircon Pegs', gpValue: 750, category: '750 gp Art Object', description: 'Masterwork instrument that rings with pure chime'),
    GemArtItem(name: 'Solid Gold Idol of a Forgotten Deity', gpValue: 750, category: '750 gp Art Object', description: 'Heavy statuette with garnet eyes'),
    GemArtItem(name: 'Gold Dragon Comb Set with Red Garnets', gpValue: 750, category: '750 gp Art Object', description: 'Hairpiece shaped like a coiled red dragon'),
    GemArtItem(name: 'Gold Ceremonial Dagger with Amethyst Pommel', gpValue: 750, category: '750 gp Art Object', description: 'Blade etched with warding glyphs'),
    GemArtItem(name: 'Silver and Gold Brooch with Coral Inlay', gpValue: 750, category: '750 gp Art Object', description: 'Brooch resembling an ocean crest'),
    GemArtItem(name: 'Engraved Platinum Censer', gpValue: 750, category: '750 gp Art Object', description: 'Incense burner adorned with sacred scripture'),
  ];

  static const List<GemArtItem> artObjects2500gp = [
    GemArtItem(name: 'Fine Gold Chain with Fire Opal Pendant', gpValue: 2500, category: '2,500 gp Art Object', description: 'Necklace bearing a glowing 100-carat fire opal'),
    GemArtItem(name: 'Carved Ivory Drinking Horn with Gold Filigree', gpValue: 2500, category: '2,500 gp Art Object', description: 'Behemoth tusk engraved with heroic saga'),
    GemArtItem(name: 'Solid Gold Music Box with Clockwork Dancers', gpValue: 2500, category: '2,500 gp Art Object', description: 'Plays ethereal ancient lullabies on miniature chimes'),
    GemArtItem(name: 'Jeweled Platinum Circlet with Emeralds', gpValue: 2500, category: '2,500 gp Art Object', description: 'Royal diadem flashing with brilliant emeralds'),
    GemArtItem(name: 'Embroidered Silk Tapestry with Pearl Accents', gpValue: 2500, category: '2,500 gp Art Object', description: 'Wall hanging depicting a legendary planar battle'),
    GemArtItem(name: 'Gold Reliquary with Aquamarine Windows', gpValue: 2500, category: '2,500 gp Art Object', description: 'Ornate casket preserving sacred saintly relics'),
  ];

  static const List<GemArtItem> artObjects7500gp = [
    GemArtItem(name: 'Jeweled Gold Crown Set with Rubies and Sapphires', gpValue: 7500, category: '7,500 gp Art Object', description: 'The grand imperial coronal of an ancient dynasty'),
    GemArtItem(name: 'Jeweled Platinum Scepter Set with a Giant Diamond', gpValue: 7500, category: '7,500 gp Art Object', description: 'Emblem of sovereign power holding a 500-carat diamond star'),
    GemArtItem(name: 'Gold Goblet Set with Fire Opals and Emeralds', gpValue: 7500, category: '7,500 gp Art Object', description: 'A chalice of mythic beauty used in imperial coronations'),
    GemArtItem(name: 'Platinum and Ruby Ceremonial Pauldrons', gpValue: 7500, category: '7,500 gp Art Object', description: 'Ornamental armor pieces encrusted with matched star rubies'),
  ];

  // ==========================================
  // MAGIC ITEM TABLES A THROUGH I
  // ==========================================

  static const RollableTable magicItemTableA = RollableTable(
    id: 'magic_item_table_a',
    name: 'Magic Item Table A',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Minor common and uncommon consumable magic items, cantrip and 1st-level spell scrolls, and standard potions.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 50, label: 'Potion of Healing', itemRefId: 'potion_of_healing'),
      TableEntry(minRoll: 51, maxRoll: 60, label: 'Spell Scroll (Cantrip)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 61, maxRoll: 70, label: 'Potion of Climbing', itemRefId: 'potion_of_climbing'),
      TableEntry(minRoll: 71, maxRoll: 90, label: 'Spell Scroll (1st Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 91, maxRoll: 94, label: 'Spell Scroll (2nd Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 95, maxRoll: 98, label: 'Potion of Greater Healing', itemRefId: 'potion_of_greater_healing'),
      TableEntry(minRoll: 99, maxRoll: 99, label: 'Bag of Holding', itemRefId: 'bag_of_holding'),
      TableEntry(minRoll: 100, maxRoll: 100, label: 'Driftglobe', itemRefId: 'driftglobe'),
    ],
  );

  static const RollableTable magicItemTableB = RollableTable(
    id: 'magic_item_table_b',
    name: 'Magic Item Table B',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Uncommon utility items, potions, 2nd-3rd level scrolls, and foundational adventuring gear.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 15, label: 'Potion of Greater Healing', itemRefId: 'potion_of_greater_healing'),
      TableEntry(minRoll: 16, maxRoll: 22, label: 'Potion of Fire Breath', itemRefId: 'potion_of_fire_breath'),
      TableEntry(minRoll: 23, maxRoll: 29, label: 'Potion of Resistance', itemRefId: 'potion_of_resistance'),
      TableEntry(minRoll: 30, maxRoll: 34, label: 'Ammunition, +1', itemRefId: 'ammunition_plus_1'),
      TableEntry(minRoll: 35, maxRoll: 39, label: 'Potion of Animal Friendship', itemRefId: 'potion_of_animal_friendship'),
      TableEntry(minRoll: 40, maxRoll: 44, label: 'Potion of Hill Giant Strength', itemRefId: 'potion_of_hill_giant_strength'),
      TableEntry(minRoll: 45, maxRoll: 49, label: 'Potion of Growth', itemRefId: 'potion_of_growth'),
      TableEntry(minRoll: 50, maxRoll: 54, label: 'Potion of Water Breathing', itemRefId: 'potion_of_water_breathing'),
      TableEntry(minRoll: 55, maxRoll: 59, label: 'Spell Scroll (2nd Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 60, maxRoll: 64, label: 'Spell Scroll (3rd Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 65, maxRoll: 67, label: 'Bag of Holding', itemRefId: 'bag_of_holding'),
      TableEntry(minRoll: 68, maxRoll: 70, label: 'Keoghtom\'s Ointment', itemRefId: 'keoghtoms_ointment'),
      TableEntry(minRoll: 71, maxRoll: 73, label: 'Oil of Slipperiness', itemRefId: 'oil_of_slipperiness'),
      TableEntry(minRoll: 74, maxRoll: 75, label: 'Dust of Disappearance', itemRefId: 'dust_of_disappearance'),
      TableEntry(minRoll: 76, maxRoll: 77, label: 'Dust of Dryness', itemRefId: 'dust_of_dryness'),
      TableEntry(minRoll: 78, maxRoll: 79, label: 'Dust of Sneezing and Choking', itemRefId: 'dust_of_sneezing_and_choking'),
      TableEntry(minRoll: 80, maxRoll: 81, label: 'Elemental Gem', itemRefId: 'elemental_gem'),
      TableEntry(minRoll: 82, maxRoll: 83, label: 'Philter of Love', itemRefId: 'philter_of_love'),
      TableEntry(minRoll: 84, maxRoll: 84, label: 'Alchemy Jug', itemRefId: 'alchemy_jug'),
      TableEntry(minRoll: 85, maxRoll: 85, label: 'Cap of Water Breathing', itemRefId: 'cap_of_water_breathing'),
      TableEntry(minRoll: 86, maxRoll: 86, label: 'Cloak of the Manta Ray', itemRefId: 'cloak_of_the_manta_ray'),
      TableEntry(minRoll: 87, maxRoll: 87, label: 'Driftglobe', itemRefId: 'driftglobe'),
      TableEntry(minRoll: 88, maxRoll: 88, label: 'Goggles of Night', itemRefId: 'goggles_of_night'),
      TableEntry(minRoll: 89, maxRoll: 89, label: 'Helm of Comprehending Languages', itemRefId: 'helm_of_comprehending_languages'),
      TableEntry(minRoll: 90, maxRoll: 90, label: 'Immovable Rod', itemRefId: 'immovable_rod'),
      TableEntry(minRoll: 91, maxRoll: 91, label: 'Lantern of Revealing', itemRefId: 'lantern_of_revealing'),
      TableEntry(minRoll: 92, maxRoll: 92, label: 'Mariner\'s Armor', itemRefId: 'mariners_armor'),
      TableEntry(minRoll: 93, maxRoll: 93, label: 'Mithral Armor', itemRefId: 'mithral_armor'),
      TableEntry(minRoll: 94, maxRoll: 94, label: 'Potion of Poison', itemRefId: 'potion_of_poison'),
      TableEntry(minRoll: 95, maxRoll: 95, label: 'Ring of Swimming', itemRefId: 'ring_of_swimming'),
      TableEntry(minRoll: 96, maxRoll: 96, label: 'Robe of Useful Items', itemRefId: 'robe_of_useful_items'),
      TableEntry(minRoll: 97, maxRoll: 97, label: 'Rope of Climbing', itemRefId: 'rope_of_climbing'),
      TableEntry(minRoll: 98, maxRoll: 98, label: 'Saddle of the Cavalier', itemRefId: 'saddle_of_the_cavalier'),
      TableEntry(minRoll: 99, maxRoll: 99, label: 'Wand of Magic Detection', itemRefId: 'wand_of_magic_detection'),
      TableEntry(minRoll: 100, maxRoll: 100, label: 'Wand of Secrets', itemRefId: 'wand_of_secrets'),
    ],
  );

  static const RollableTable magicItemTableC = RollableTable(
    id: 'magic_item_table_c',
    name: 'Magic Item Table C',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Rare consumables, superior healing potions, 4th-5th level scrolls, and potent elixirs.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 15, label: 'Potion of Superior Healing', itemRefId: 'potion_of_superior_healing'),
      TableEntry(minRoll: 16, maxRoll: 22, label: 'Spell Scroll (4th Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 23, maxRoll: 27, label: 'Ammunition, +2', itemRefId: 'ammunition_plus_2'),
      TableEntry(minRoll: 28, maxRoll: 32, label: 'Potion of Clairvoyance', itemRefId: 'potion_of_clairvoyance'),
      TableEntry(minRoll: 33, maxRoll: 37, label: 'Potion of Diminution', itemRefId: 'potion_of_diminution'),
      TableEntry(minRoll: 38, maxRoll: 42, label: 'Potion of Gaseous Form', itemRefId: 'potion_of_gaseous_form'),
      TableEntry(minRoll: 43, maxRoll: 47, label: 'Potion of Frost Giant Strength', itemRefId: 'potion_of_frost_giant_strength'),
      TableEntry(minRoll: 48, maxRoll: 52, label: 'Potion of Stone Giant Strength', itemRefId: 'potion_of_stone_giant_strength'),
      TableEntry(minRoll: 53, maxRoll: 57, label: 'Potion of Heroism', itemRefId: 'potion_of_heroism'),
      TableEntry(minRoll: 58, maxRoll: 62, label: 'Potion of Invulnerability', itemRefId: 'potion_of_invulnerability'),
      TableEntry(minRoll: 63, maxRoll: 67, label: 'Potion of Mind Reading', itemRefId: 'potion_of_mind_reading'),
      TableEntry(minRoll: 68, maxRoll: 72, label: 'Spell Scroll (5th Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 73, maxRoll: 75, label: 'Elixir of Health', itemRefId: 'elixir_of_health'),
      TableEntry(minRoll: 76, maxRoll: 78, label: 'Oil of Etherealness', itemRefId: 'oil_of_etherealness'),
      TableEntry(minRoll: 79, maxRoll: 81, label: 'Potion of Fire Giant Strength', itemRefId: 'potion_of_fire_giant_strength'),
      TableEntry(minRoll: 82, maxRoll: 84, label: 'Quaal\'s Feather Token', itemRefId: 'quaals_feather_token'),
      TableEntry(minRoll: 85, maxRoll: 87, label: 'Scroll of Protection', itemRefId: 'scroll_of_protection'),
      TableEntry(minRoll: 88, maxRoll: 89, label: 'Bag of Beans', itemRefId: 'bag_of_beans'),
      TableEntry(minRoll: 90, maxRoll: 91, label: 'Bead of Force', itemRefId: 'bead_of_force'),
      TableEntry(minRoll: 92, maxRoll: 92, label: 'Chime of Opening', itemRefId: 'chime_of_opening'),
      TableEntry(minRoll: 93, maxRoll: 93, label: 'Decanter of Endless Water', itemRefId: 'decanter_of_endless_water'),
      TableEntry(minRoll: 94, maxRoll: 94, label: 'Eyes of Minute Seeing', itemRefId: 'eyes_of_minute_seeing'),
      TableEntry(minRoll: 95, maxRoll: 95, label: 'Folding Boat', itemRefId: 'folding_boat'),
      TableEntry(minRoll: 96, maxRoll: 96, label: 'Heward\'s Handy Haversack', itemRefId: 'hewards_handy_haversack'),
      TableEntry(minRoll: 97, maxRoll: 97, label: 'Horseshoes of Speed', itemRefId: 'horseshoes_of_speed'),
      TableEntry(minRoll: 98, maxRoll: 98, label: 'Necklace of Fireballs', itemRefId: 'necklace_of_fireballs'),
      TableEntry(minRoll: 99, maxRoll: 99, label: 'Periapt of Health', itemRefId: 'periapt_of_health'),
      TableEntry(minRoll: 100, maxRoll: 100, label: 'Sending Stones', itemRefId: 'sending_stones'),
    ],
  );

  static const RollableTable magicItemTableD = RollableTable(
    id: 'magic_item_table_d',
    name: 'Magic Item Table D',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Very rare consumables, supreme healing, high-tier scrolls (6th-8th level), and exotic oils.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 20, label: 'Potion of Supreme Healing', itemRefId: 'potion_of_supreme_healing'),
      TableEntry(minRoll: 21, maxRoll: 30, label: 'Potion of Invisibility', itemRefId: 'potion_of_invisibility'),
      TableEntry(minRoll: 31, maxRoll: 40, label: 'Potion of Speed', itemRefId: 'potion_of_speed'),
      TableEntry(minRoll: 41, maxRoll: 50, label: 'Spell Scroll (6th Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 51, maxRoll: 57, label: 'Spell Scroll (7th Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 58, maxRoll: 62, label: 'Ammunition, +3', itemRefId: 'ammunition_plus_3'),
      TableEntry(minRoll: 63, maxRoll: 67, label: 'Oil of Sharpness', itemRefId: 'oil_of_sharpness'),
      TableEntry(minRoll: 68, maxRoll: 72, label: 'Potion of Flying', itemRefId: 'potion_of_flying'),
      TableEntry(minRoll: 73, maxRoll: 77, label: 'Potion of Cloud Giant Strength', itemRefId: 'potion_of_cloud_giant_strength'),
      TableEntry(minRoll: 78, maxRoll: 82, label: 'Potion of Longevity', itemRefId: 'potion_of_longevity'),
      TableEntry(minRoll: 83, maxRoll: 87, label: 'Potion of Vitality', itemRefId: 'potion_of_vitality'),
      TableEntry(minRoll: 88, maxRoll: 92, label: 'Spell Scroll (8th Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 93, maxRoll: 95, label: 'Horseshoes of a Zephyr', itemRefId: 'horseshoes_of_a_zephyr'),
      TableEntry(minRoll: 96, maxRoll: 98, label: 'Nolzur\'s Marvelous Pigments', itemRefId: 'nolzurs_marvelous_pigments'),
      TableEntry(minRoll: 99, maxRoll: 99, label: 'Bag of Devouring', itemRefId: 'bag_of_devouring'),
      TableEntry(minRoll: 100, maxRoll: 100, label: 'Portable Hole', itemRefId: 'portable_hole'),
    ],
  );

  static const RollableTable magicItemTableE = RollableTable(
    id: 'magic_item_table_e',
    name: 'Magic Item Table E',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Legendary consumables, 9th-level scrolls, and storm giant strength potions.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 30, label: 'Spell Scroll (8th Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 31, maxRoll: 55, label: 'Potion of Storm Giant Strength', itemRefId: 'potion_of_storm_giant_strength'),
      TableEntry(minRoll: 56, maxRoll: 70, label: 'Potion of Supreme Healing', itemRefId: 'potion_of_supreme_healing'),
      TableEntry(minRoll: 71, maxRoll: 85, label: 'Spell Scroll (9th Level)', itemRefId: 'spell_scroll'),
      TableEntry(minRoll: 86, maxRoll: 93, label: 'Universal Solvent', itemRefId: 'universal_solvent'),
      TableEntry(minRoll: 94, maxRoll: 98, label: 'Arrow of Slaying', itemRefId: 'arrow_of_slaying'),
      TableEntry(minRoll: 99, maxRoll: 100, label: 'Sovereign Glue', itemRefId: 'sovereign_glue'),
    ],
  );

  static const RollableTable magicItemTableF = RollableTable(
    id: 'magic_item_table_f',
    name: 'Magic Item Table F',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Uncommon permanent magic items: weapons (+1), armor (+1), boots of elvenkind, cloak of protection, and wands.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 15, label: 'Weapon, +1', itemRefId: 'weapon_plus_1'),
      TableEntry(minRoll: 16, maxRoll: 18, label: 'Shield, +1', itemRefId: 'shield_plus_1'),
      TableEntry(minRoll: 19, maxRoll: 21, label: 'Sentinel Shield', itemRefId: 'sentinel_shield'),
      TableEntry(minRoll: 22, maxRoll: 23, label: 'Amulet of Proof against Detection and Location', itemRefId: 'amulet_of_proof_against_detection_and_location'),
      TableEntry(minRoll: 24, maxRoll: 25, label: 'Boots of Elvenkind', itemRefId: 'boots_of_elvenkind'),
      TableEntry(minRoll: 26, maxRoll: 27, label: 'Boots of Striding and Springing', itemRefId: 'boots_of_striding_and_springing'),
      TableEntry(minRoll: 28, maxRoll: 29, label: 'Boots of the Winterlands', itemRefId: 'boots_of_the_winterlands'),
      TableEntry(minRoll: 30, maxRoll: 31, label: 'Bracers of Archery', itemRefId: 'bracers_of_archery'),
      TableEntry(minRoll: 32, maxRoll: 33, label: 'Brooch of Shielding', itemRefId: 'brooch_of_shielding'),
      TableEntry(minRoll: 34, maxRoll: 35, label: 'Broom of Flying', itemRefId: 'broom_of_flying'),
      TableEntry(minRoll: 36, maxRoll: 37, label: 'Cloak of Elvenkind', itemRefId: 'cloak_of_elvenkind'),
      TableEntry(minRoll: 38, maxRoll: 39, label: 'Cloak of Protection', itemRefId: 'cloak_of_protection'),
      TableEntry(minRoll: 40, maxRoll: 41, label: 'Gauntlets of Ogre Power', itemRefId: 'gauntlets_of_ogre_power'),
      TableEntry(minRoll: 42, maxRoll: 43, label: 'Hat of Disguise', itemRefId: 'hat_of_disguise'),
      TableEntry(minRoll: 44, maxRoll: 45, label: 'Javelin of Lightning', itemRefId: 'javelin_of_lightning'),
      TableEntry(minRoll: 46, maxRoll: 47, label: 'Pearl of Power', itemRefId: 'pearl_of_power'),
      TableEntry(minRoll: 48, maxRoll: 49, label: 'Rod of the Pact Keeper, +1', itemRefId: 'rod_of_the_pact_keeper_plus_1'),
      TableEntry(minRoll: 50, maxRoll: 51, label: 'Slippers of Spider Climbing', itemRefId: 'slippers_of_spider_climbing'),
      TableEntry(minRoll: 52, maxRoll: 53, label: 'Staff of the Adder', itemRefId: 'staff_of_the_adder'),
      TableEntry(minRoll: 54, maxRoll: 55, label: 'Staff of the Python', itemRefId: 'staff_of_the_python'),
      TableEntry(minRoll: 56, maxRoll: 57, label: 'Sword of Vengeance', itemRefId: 'sword_of_vengeance'),
      TableEntry(minRoll: 58, maxRoll: 59, label: 'Trident of Fish Command', itemRefId: 'trident_of_fish_command'),
      TableEntry(minRoll: 60, maxRoll: 61, label: 'Wand of Magic Missiles', itemRefId: 'wand_of_magic_missiles'),
      TableEntry(minRoll: 62, maxRoll: 63, label: 'Wand of the War Mage, +1', itemRefId: 'wand_of_the_war_mage_plus_1'),
      TableEntry(minRoll: 64, maxRoll: 65, label: 'Wand of Web', itemRefId: 'wand_of_web'),
      TableEntry(minRoll: 66, maxRoll: 67, label: 'Weapon of Warning', itemRefId: 'weapon_of_warning'),
      TableEntry(minRoll: 68, maxRoll: 68, label: 'Adamantine Armor (Chain Mail)', itemRefId: 'adamantine_armor'),
      TableEntry(minRoll: 69, maxRoll: 69, label: 'Adamantine Armor (Chain Shirt)', itemRefId: 'adamantine_armor'),
      TableEntry(minRoll: 70, maxRoll: 70, label: 'Adamantine Armor (Scale Mail)', itemRefId: 'adamantine_armor'),
      TableEntry(minRoll: 71, maxRoll: 71, label: 'Bag of Tricks (Gray)', itemRefId: 'bag_of_tricks'),
      TableEntry(minRoll: 72, maxRoll: 72, label: 'Bag of Tricks (Rust)', itemRefId: 'bag_of_tricks'),
      TableEntry(minRoll: 73, maxRoll: 73, label: 'Bag of Tricks (Tan)', itemRefId: 'bag_of_tricks'),
      TableEntry(minRoll: 74, maxRoll: 74, label: 'Circlet of Blasting', itemRefId: 'circlet_of_blasting'),
      TableEntry(minRoll: 75, maxRoll: 75, label: 'Deck of Illusions', itemRefId: 'deck_of_illusions'),
      TableEntry(minRoll: 76, maxRoll: 76, label: 'Eversmoking Bottle', itemRefId: 'eversmoking_bottle'),
      TableEntry(minRoll: 77, maxRoll: 77, label: 'Eyes of Charming', itemRefId: 'eyes_of_charming'),
      TableEntry(minRoll: 78, maxRoll: 78, label: 'Eyes of the Eagle', itemRefId: 'eyes_of_the_eagle'),
      TableEntry(minRoll: 79, maxRoll: 79, label: 'Figurine of Wondrous Power (Silver Raven)', itemRefId: 'figurine_of_wondrous_power'),
      TableEntry(minRoll: 80, maxRoll: 80, label: 'Gem of Brightness', itemRefId: 'gem_of_brightness'),
      TableEntry(minRoll: 81, maxRoll: 81, label: 'Gloves of Missile Snaring', itemRefId: 'gloves_of_missile_snaring'),
      TableEntry(minRoll: 82, maxRoll: 82, label: 'Gloves of Swimming and Climbing', itemRefId: 'gloves_of_swimming_and_climbing'),
      TableEntry(minRoll: 83, maxRoll: 83, label: 'Gloves of Thievery', itemRefId: 'gloves_of_thievery'),
      TableEntry(minRoll: 84, maxRoll: 84, label: 'Headband of Intellect', itemRefId: 'headband_of_intellect'),
      TableEntry(minRoll: 85, maxRoll: 85, label: 'Helm of Telepathy', itemRefId: 'helm_of_telepathy'),
      TableEntry(minRoll: 86, maxRoll: 86, label: 'Instrument of the Bards (Doss Lute)', itemRefId: 'instrument_of_the_bards'),
      TableEntry(minRoll: 87, maxRoll: 87, label: 'Instrument of the Bards (Fochlucan Bandore)', itemRefId: 'instrument_of_the_bards'),
      TableEntry(minRoll: 88, maxRoll: 88, label: 'Instrument of the Bards (Mac-Fuirmidh Cittern)', itemRefId: 'instrument_of_the_bards'),
      TableEntry(minRoll: 89, maxRoll: 89, label: 'Medallion of Thoughts', itemRefId: 'medallion_of_thoughts'),
      TableEntry(minRoll: 90, maxRoll: 90, label: 'Mourning Ring', itemRefId: 'mourning_ring'),
      TableEntry(minRoll: 91, maxRoll: 91, label: 'Periapt of Wound Closure', itemRefId: 'periapt_of_wound_closure'),
      TableEntry(minRoll: 92, maxRoll: 92, label: 'Pipes of Haunting', itemRefId: 'pipes_of_haunting'),
      TableEntry(minRoll: 93, maxRoll: 93, label: 'Pipes of the Sewers', itemRefId: 'pipes_of_the_sewers'),
      TableEntry(minRoll: 94, maxRoll: 94, label: 'Ring of Jumping', itemRefId: 'ring_of_jumping'),
      TableEntry(minRoll: 95, maxRoll: 95, label: 'Ring of Mind Shielding', itemRefId: 'ring_of_mind_shielding'),
      TableEntry(minRoll: 96, maxRoll: 96, label: 'Ring of Warmth', itemRefId: 'ring_of_warmth'),
      TableEntry(minRoll: 97, maxRoll: 97, label: 'Ring of Water Walking', itemRefId: 'ring_of_water_walking'),
      TableEntry(minRoll: 98, maxRoll: 98, label: 'Quiver of Ehlonna', itemRefId: 'quiver_of_ehlonna'),
      TableEntry(minRoll: 99, maxRoll: 99, label: 'Stone of Good Luck (Luckstone)', itemRefId: 'stone_of_good_luck'),
      TableEntry(minRoll: 100, maxRoll: 100, label: 'Wind Fan', itemRefId: 'wind_fan'),
    ],
  );

  static const RollableTable magicItemTableG = RollableTable(
    id: 'magic_item_table_g',
    name: 'Magic Item Table G',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Rare permanent magic items: weapons (+2), flame tongue, sun blade, cloak of the bat, and rings.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 11, label: 'Weapon, +2', itemRefId: 'weapon_plus_2'),
      TableEntry(minRoll: 12, maxRoll: 14, label: 'Figurine of Wondrous Power (Bronze Griffon)', itemRefId: 'figurine_of_wondrous_power'),
      TableEntry(minRoll: 15, maxRoll: 17, label: 'Adamantine Armor (Breastplate)', itemRefId: 'adamantine_armor'),
      TableEntry(minRoll: 18, maxRoll: 20, label: 'Adamantine Armor (Splint)', itemRefId: 'adamantine_armor'),
      TableEntry(minRoll: 21, maxRoll: 23, label: 'Amulet of Health', itemRefId: 'amulet_of_health'),
      TableEntry(minRoll: 24, maxRoll: 26, label: 'Armor of Vulnerability', itemRefId: 'armor_of_vulnerability'),
      TableEntry(minRoll: 27, maxRoll: 29, label: 'Arrow-Catching Shield', itemRefId: 'arrow_catching_shield'),
      TableEntry(minRoll: 30, maxRoll: 32, label: 'Belt of Dwarvenkind', itemRefId: 'belt_of_dwarvenkind'),
      TableEntry(minRoll: 33, maxRoll: 35, label: 'Belt of Hill Giant Strength', itemRefId: 'belt_of_hill_giant_strength'),
      TableEntry(minRoll: 36, maxRoll: 38, label: 'Berserker Axe', itemRefId: 'berserker_axe'),
      TableEntry(minRoll: 39, maxRoll: 41, label: 'Boots of Levitation', itemRefId: 'boots_of_levitation'),
      TableEntry(minRoll: 42, maxRoll: 44, label: 'Boots of Speed', itemRefId: 'boots_of_speed'),
      TableEntry(minRoll: 45, maxRoll: 47, label: 'Bowl of Commanding Water Elementals', itemRefId: 'bowl_of_commanding_water_elementals'),
      TableEntry(minRoll: 48, maxRoll: 50, label: 'Bracers of Defense', itemRefId: 'bracers_of_defense'),
      TableEntry(minRoll: 51, maxRoll: 53, label: 'Brazier of Commanding Fire Elementals', itemRefId: 'brazier_of_commanding_fire_elementals'),
      TableEntry(minRoll: 54, maxRoll: 56, label: 'Cape of the Mountebank', itemRefId: 'cape_of_the_mountebank'),
      TableEntry(minRoll: 57, maxRoll: 59, label: 'Censer of Controlling Air Elementals', itemRefId: 'censer_of_controlling_air_elementals'),
      TableEntry(minRoll: 60, maxRoll: 62, label: 'Armor, +1 (Chain Mail)', itemRefId: 'armor_plus_1'),
      TableEntry(minRoll: 63, maxRoll: 65, label: 'Cloak of the Bat', itemRefId: 'cloak_of_the_bat'),
      TableEntry(minRoll: 66, maxRoll: 68, label: 'Cloak of Displacement', itemRefId: 'cloak_of_displacement'),
      TableEntry(minRoll: 69, maxRoll: 71, label: 'Dragon Slayer', itemRefId: 'dragon_slayer'),
      TableEntry(minRoll: 72, maxRoll: 74, label: 'Flame Tongue', itemRefId: 'flame_tongue'),
      TableEntry(minRoll: 75, maxRoll: 77, label: 'Gem of Seeing', itemRefId: 'gem_of_seeing'),
      TableEntry(minRoll: 78, maxRoll: 80, label: 'Giant Slayer', itemRefId: 'giant_slayer'),
      TableEntry(minRoll: 81, maxRoll: 83, label: 'Glamoured Studded Leather', itemRefId: 'glamoured_studded_leather'),
      TableEntry(minRoll: 84, maxRoll: 86, label: 'Helm of Teleportation', itemRefId: 'helm_of_teleportation'),
      TableEntry(minRoll: 87, maxRoll: 89, label: 'Mace of Disruption', itemRefId: 'mace_of_disruption'),
      TableEntry(minRoll: 90, maxRoll: 92, label: 'Mace of Smiting', itemRefId: 'mace_of_smiting'),
      TableEntry(minRoll: 93, maxRoll: 95, label: 'Ring of Evasion', itemRefId: 'ring_of_evasion'),
      TableEntry(minRoll: 96, maxRoll: 98, label: 'Ring of Feather Falling', itemRefId: 'ring_of_feather_falling'),
      TableEntry(minRoll: 99, maxRoll: 99, label: 'Ring of Free Action', itemRefId: 'ring_of_free_action'),
      TableEntry(minRoll: 100, maxRoll: 100, label: 'Sun Blade', itemRefId: 'sun_blade'),
    ],
  );

  static const RollableTable magicItemTableH = RollableTable(
    id: 'magic_item_table_h',
    name: 'Magic Item Table H',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Very rare permanent items: weapons (+3), armor (+2), frost brand, rod of lordly might, and animated shield.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 10, label: 'Weapon, +3', itemRefId: 'weapon_plus_3'),
      TableEntry(minRoll: 11, maxRoll: 12, label: 'Amulet of the Planes', itemRefId: 'amulet_of_the_planes'),
      TableEntry(minRoll: 13, maxRoll: 14, label: 'Animated Shield', itemRefId: 'animated_shield'),
      TableEntry(minRoll: 15, maxRoll: 16, label: 'Belt of Fire Giant Strength', itemRefId: 'belt_of_fire_giant_strength'),
      TableEntry(minRoll: 17, maxRoll: 18, label: 'Belt of Frost Giant Strength', itemRefId: 'belt_of_frost_giant_strength'),
      TableEntry(minRoll: 19, maxRoll: 20, label: 'Belt of Stone Giant Strength', itemRefId: 'belt_of_stone_giant_strength'),
      TableEntry(minRoll: 21, maxRoll: 22, label: 'Candle of Invocation', itemRefId: 'candle_of_invocation'),
      TableEntry(minRoll: 23, maxRoll: 24, label: 'Armor, +2 (Breastplate)', itemRefId: 'armor_plus_2'),
      TableEntry(minRoll: 25, maxRoll: 26, label: 'Cloak of Arachnida', itemRefId: 'cloak_of_arachnida'),
      TableEntry(minRoll: 27, maxRoll: 28, label: 'Dancing Sword', itemRefId: 'dancing_sword'),
      TableEntry(minRoll: 29, maxRoll: 30, label: 'Demon Armor', itemRefId: 'demon_armor'),
      TableEntry(minRoll: 31, maxRoll: 32, label: 'Dragon Scale Mail', itemRefId: 'dragon_scale_mail'),
      TableEntry(minRoll: 33, maxRoll: 34, label: 'Dwarven Plate', itemRefId: 'dwarven_plate'),
      TableEntry(minRoll: 35, maxRoll: 36, label: 'Dwarven Thrower', itemRefId: 'dwarven_thrower'),
      TableEntry(minRoll: 37, maxRoll: 38, label: 'Efreeti Bottle', itemRefId: 'efreeti_bottle'),
      TableEntry(minRoll: 39, maxRoll: 40, label: 'Frost Brand', itemRefId: 'frost_brand'),
      TableEntry(minRoll: 41, maxRoll: 42, label: 'Helm of Brilliance', itemRefId: 'helm_of_brilliance'),
      TableEntry(minRoll: 43, maxRoll: 44, label: 'Horn of Valhalla (Bronze)', itemRefId: 'horn_of_valhalla'),
      TableEntry(minRoll: 45, maxRoll: 46, label: 'Instrument of the Bards (Anstruth Harp)', itemRefId: 'instrument_of_the_bards'),
      TableEntry(minRoll: 47, maxRoll: 48, label: 'Ioun Stone (Absorption)', itemRefId: 'ioun_stone'),
      TableEntry(minRoll: 49, maxRoll: 50, label: 'Ioun Stone (Agility)', itemRefId: 'ioun_stone'),
      TableEntry(minRoll: 51, maxRoll: 52, label: 'Manual of Bodily Health', itemRefId: 'manual_of_bodily_health'),
      TableEntry(minRoll: 53, maxRoll: 54, label: 'Manual of Gainful Exercise', itemRefId: 'manual_of_gainful_exercise'),
      TableEntry(minRoll: 55, maxRoll: 56, label: 'Manual of Golems', itemRefId: 'manual_of_golems'),
      TableEntry(minRoll: 57, maxRoll: 58, label: 'Mirror of Life Trapping', itemRefId: 'mirror_of_life_trapping'),
      TableEntry(minRoll: 59, maxRoll: 60, label: 'Nine Lives Stealer', itemRefId: 'nine_lives_stealer'),
      TableEntry(minRoll: 61, maxRoll: 62, label: 'Oathbow', itemRefId: 'oathbow'),
      TableEntry(minRoll: 63, maxRoll: 64, label: 'Ring of Regeneration', itemRefId: 'ring_of_regeneration'),
      TableEntry(minRoll: 65, maxRoll: 66, label: 'Ring of Shooting Stars', itemRefId: 'ring_of_shooting_stars'),
      TableEntry(minRoll: 67, maxRoll: 68, label: 'Ring of Telekinesis', itemRefId: 'ring_of_telekinesis'),
      TableEntry(minRoll: 69, maxRoll: 70, label: 'Robe of Scintillating Colors', itemRefId: 'robe_of_scintillating_colors'),
      TableEntry(minRoll: 71, maxRoll: 72, label: 'Robe of Stars', itemRefId: 'robe_of_stars'),
      TableEntry(minRoll: 73, maxRoll: 74, label: 'Rod of Lordly Might', itemRefId: 'rod_of_lordly_might'),
      TableEntry(minRoll: 75, maxRoll: 76, label: 'Rod of Security', itemRefId: 'rod_of_security'),
      TableEntry(minRoll: 77, maxRoll: 78, label: 'Scimitar of Speed', itemRefId: 'scimitar_of_speed'),
      TableEntry(minRoll: 79, maxRoll: 80, label: 'Shield, +3', itemRefId: 'shield_plus_3'),
      TableEntry(minRoll: 81, maxRoll: 82, label: 'Spellguard Shield', itemRefId: 'spellguard_shield'),
      TableEntry(minRoll: 83, maxRoll: 84, label: 'Staff of Fire', itemRefId: 'staff_of_fire'),
      TableEntry(minRoll: 85, maxRoll: 86, label: 'Staff of Frost', itemRefId: 'staff_of_frost'),
      TableEntry(minRoll: 87, maxRoll: 88, label: 'Staff of Power', itemRefId: 'staff_of_power'),
      TableEntry(minRoll: 89, maxRoll: 90, label: 'Staff of Striking', itemRefId: 'staff_of_striking'),
      TableEntry(minRoll: 91, maxRoll: 92, label: 'Staff of Thunder and Lightning', itemRefId: 'staff_of_thunder_and_lightning'),
      TableEntry(minRoll: 93, maxRoll: 94, label: 'Sword of Sharpness', itemRefId: 'sword_of_sharpness'),
      TableEntry(minRoll: 95, maxRoll: 96, label: 'Tome of Clear Thought', itemRefId: 'tome_of_clear_thought'),
      TableEntry(minRoll: 97, maxRoll: 98, label: 'Tome of Leadership and Influence', itemRefId: 'tome_of_leadership_and_influence'),
      TableEntry(minRoll: 99, maxRoll: 100, label: 'Tome of Understanding', itemRefId: 'tome_of_understanding'),
    ],
  );

  static const RollableTable magicItemTableI = RollableTable(
    id: 'magic_item_table_i',
    name: 'Magic Item Table I',
    category: TableCategory.loot,
    diceFormula: '1d100',
    description: 'Legendary permanent artifacts: Holy Avenger, Vorpal Sword, Ring of Three Wishes, Armor +3, and Staff of the Magi.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 5, label: 'Defender', itemRefId: 'defender'),
      TableEntry(minRoll: 6, maxRoll: 10, label: 'Hammer of Thunderbolts', itemRefId: 'hammer_of_thunderbolts'),
      TableEntry(minRoll: 11, maxRoll: 15, label: 'Holy Avenger', itemRefId: 'holy_avenger'),
      TableEntry(minRoll: 16, maxRoll: 20, label: 'Ring of Three Wishes', itemRefId: 'ring_of_three_wishes'),
      TableEntry(minRoll: 21, maxRoll: 25, label: 'Rod of Resurrection', itemRefId: 'rod_of_resurrection'),
      TableEntry(minRoll: 26, maxRoll: 30, label: 'Staff of the Magi', itemRefId: 'staff_of_the_magi'),
      TableEntry(minRoll: 31, maxRoll: 35, label: 'Vorpal Sword', itemRefId: 'vorpal_sword'),
      TableEntry(minRoll: 36, maxRoll: 40, label: 'Belt of Cloud Giant Strength', itemRefId: 'belt_of_cloud_giant_strength'),
      TableEntry(minRoll: 41, maxRoll: 45, label: 'Armor, +3 (Full Plate)', itemRefId: 'armor_plus_3'),
      TableEntry(minRoll: 46, maxRoll: 50, label: 'Belt of Storm Giant Strength', itemRefId: 'belt_of_storm_giant_strength'),
      TableEntry(minRoll: 51, maxRoll: 55, label: 'Cloak of Invisibility', itemRefId: 'cloak_of_invisibility'),
      TableEntry(minRoll: 56, maxRoll: 60, label: 'Crystal Ball (Legendary)', itemRefId: 'crystal_ball'),
      TableEntry(minRoll: 61, maxRoll: 65, label: 'Dread Helm of Supremacy', itemRefId: 'dread_helm'),
      TableEntry(minRoll: 66, maxRoll: 70, label: 'Horn of Valhalla (Iron)', itemRefId: 'horn_of_valhalla'),
      TableEntry(minRoll: 71, maxRoll: 75, label: 'Instrument of the Bards (Ollamh Harp)', itemRefId: 'instrument_of_the_bards'),
      TableEntry(minRoll: 76, maxRoll: 80, label: 'Ioun Stone (Greater Absorption)', itemRefId: 'ioun_stone'),
      TableEntry(minRoll: 81, maxRoll: 85, label: 'Plate Armor of Etherealness', itemRefId: 'plate_armor_of_etherealness'),
      TableEntry(minRoll: 86, maxRoll: 90, label: 'Ring of Air Elemental Command', itemRefId: 'ring_of_elemental_command'),
      TableEntry(minRoll: 91, maxRoll: 95, label: 'Ring of Earth Elemental Command', itemRefId: 'ring_of_elemental_command'),
      TableEntry(minRoll: 96, maxRoll: 100, label: 'Scarab of Protection', itemRefId: 'scarab_of_protection'),
    ],
  );

  // ==========================================
  // 100 SRD TRINKETS TABLE
  // ==========================================
  static const RollableTable trinketsTable = RollableTable(
    id: 'srd_trinkets_table',
    name: '100 SRD Trinkets',
    category: TableCategory.trinkets,
    diceFormula: '1d100',
    description: 'A comprehensive table of 100 mysterious, curious, and eccentric trinkets found across dungeons, ruins, and monster lairs.',
    entries: [
      TableEntry(minRoll: 1, maxRoll: 1, label: 'Mummified goblin hand', description: 'A dried, desiccated hand curled into a fist.'),
      TableEntry(minRoll: 2, maxRoll: 2, label: 'Piece of crystal that glows faintly in moonlight', description: 'A quartz shard that catches moonlight and emits an azure luminescence.'),
      TableEntry(minRoll: 3, maxRoll: 3, label: 'Gold coin minted in an unknown land', description: 'A heavy coin stamped with the portrait of a three-eyed monarch.'),
      TableEntry(minRoll: 4, maxRoll: 4, label: 'Diary written in an undecipherable script', description: 'Vellum journal bound in snakeskin with shimmering ink.'),
      TableEntry(minRoll: 5, maxRoll: 5, label: 'Brass ring that never tarnishes', description: 'A simple band of gleaming metal that repels dirt and soot.'),
      TableEntry(minRoll: 6, maxRoll: 6, label: 'Old chess piece made from glass', description: 'A glass knight with a tiny imprisoned spark of light inside.'),
      TableEntry(minRoll: 7, maxRoll: 7, label: 'Pair of knucklebone dice with skull symbols', description: 'Weighted bone dice carved from the finger of an ancient warrior.'),
      TableEntry(minRoll: 8, maxRoll: 8, label: 'Small idol depicting a nightmarish creature', description: 'Squat stone carving that induces unsettling dreams when slept near.'),
      TableEntry(minRoll: 9, maxRoll: 9, label: 'Rope of woven hair from four different beasts', description: 'Three-foot cord made of owlbear, displacer beast, wolf, and chimera mane.'),
      TableEntry(minRoll: 10, maxRoll: 10, label: 'Mechanical canary inside a brass cage', description: 'Wound with a key, it flaps brass wings and whistles a forgotten tune.'),
      TableEntry(minRoll: 11, maxRoll: 11, label: 'Tiny silver bell without a clapper', description: 'Rings with a faint telepathic chime heard only in the mind of the shaker.'),
      TableEntry(minRoll: 12, maxRoll: 12, label: 'Mechanical pocket watch that runs backward', description: 'Tick-tocks counterclockwise, keeping time in reverse.'),
      TableEntry(minRoll: 13, maxRoll: 13, label: 'Urn holding the ashes of a deceased hero', description: 'Bronze urn inscribed with a poem praising a forgotten champion.'),
      TableEntry(minRoll: 14, maxRoll: 14, label: 'Four-leaf clover pressed inside a glass locket', description: 'Preserved emerald clover plucked from a fey grove.'),
      TableEntry(minRoll: 15, maxRoll: 15, label: 'Glass jar filled with dead glowing bugs', description: 'Fireflies whose shells maintain a faint phosphorescent glow.'),
      TableEntry(minRoll: 16, maxRoll: 16, label: 'Shard of stained glass from a destroyed cathedral', description: 'Colored glass displaying the radiant halo of a sun god.'),
      TableEntry(minRoll: 17, maxRoll: 17, label: 'Silver spoon with an M engraved on the handle', description: 'Polished spoon that always feels pleasantly warm to the touch.'),
      TableEntry(minRoll: 18, maxRoll: 18, label: 'Whistle made from golden wood', description: 'Sounds like the cry of a majestic hawk when blown.'),
      TableEntry(minRoll: 19, maxRoll: 19, label: 'Dead sprite inside a clear glass bottle', description: 'Preserved winged fairy suspended in sweet-smelling amber resin.'),
      TableEntry(minRoll: 20, maxRoll: 20, label: 'Iron nail that cannot be bent or blunted', description: 'Forged in dragonfire, impervious to mundane hammers.'),
      TableEntry(minRoll: 21, maxRoll: 21, label: 'Small pouch of scented dried herbs', description: 'Fragrant blend of lavender and dreamroot that repels moths.'),
      TableEntry(minRoll: 22, maxRoll: 22, label: 'Statuette of a dragon made from dragon bone', description: 'Four-inch carving that emits a faint wisp of harmless smoke from its nostrils.'),
      TableEntry(minRoll: 23, maxRoll: 23, label: 'Old brass compass that points toward the nearest portal', description: 'Needle spins erratically until within 500 feet of planar nexus.'),
      TableEntry(minRoll: 24, maxRoll: 24, label: 'Key made from petrified wood', description: 'Intricate ward cuts shaped like entwined boughs.'),
      TableEntry(minRoll: 25, maxRoll: 25, label: 'Silver music box that plays a mournful melody', description: 'Engraved with weeping willows and moonlight.'),
      TableEntry(minRoll: 26, maxRoll: 26, label: 'Vial of silvery liquid that moves on its own', description: 'Mercurial essence that ripples in time with the owner\'s heartbeat.'),
      TableEntry(minRoll: 27, maxRoll: 27, label: 'Old iron key with no visible wards', description: 'Heavy and cold, fits an ancient subterranean vault.'),
      TableEntry(minRoll: 28, maxRoll: 28, label: 'Glass eye that follows whoever holds it', description: 'Intricate glass prosthetic with an iris that dilates in light.'),
      TableEntry(minRoll: 29, maxRoll: 29, label: 'Leather pouch containing various small animal skulls', description: 'Rodent, bird, and reptile skulls painted with red runes.'),
      TableEntry(minRoll: 30, maxRoll: 30, label: 'Piece of petrified dragon excrement', description: 'Rock-hard fossilized specimen with mineral deposits.'),
      TableEntry(minRoll: 31, maxRoll: 31, label: 'Silken sash that changes color with the wearer\'s mood', description: 'Shifts between blue (calm), red (angry), and gold (confident).'),
      TableEntry(minRoll: 32, maxRoll: 32, label: 'Small stone that always rolls uphill', description: 'Defies gravity slightly when placed on gentle inclines.'),
      TableEntry(minRoll: 33, maxRoll: 33, label: 'Tiny copper figurine of a cat that purrs', description: 'Vibrates gently with a warm purring hum when stroked.'),
      TableEntry(minRoll: 34, maxRoll: 34, label: 'Glass vial containing swamp fog', description: 'Murky vapor that swirls eternally without dissipating.'),
      TableEntry(minRoll: 35, maxRoll: 35, label: 'Set of bone dominoes carved with celestial symbols', description: 'Twenty-eight ivory tiles marked with constellation stars.'),
      TableEntry(minRoll: 36, maxRoll: 36, label: 'Fossilized dinosaur tooth', description: 'Four-inch serrated carnivore fang encased in stone.'),
      TableEntry(minRoll: 37, maxRoll: 37, label: 'Brass monocle with a cracked ruby lens', description: 'Shows mundane objects with an eerie crimson tint.'),
      TableEntry(minRoll: 38, maxRoll: 38, label: 'Piece of dried fungus that smells like roasted garlic', description: 'Culinary relic from an underdark gourmet chef.'),
      TableEntry(minRoll: 39, maxRoll: 39, label: 'Iron locket containing a lock of raven hair', description: 'Engraved with the initials "V.R." on the interior.'),
      TableEntry(minRoll: 40, maxRoll: 40, label: 'Spool of invisible thread', description: 'Tactile thread that can be felt and tied, but not seen.'),
      TableEntry(minRoll: 41, maxRoll: 41, label: 'Tiny glass globe containing a miniature winter storm', description: 'Shaking it triggers miniature blizzards and lightning inside.'),
      TableEntry(minRoll: 42, maxRoll: 42, label: 'Small silver cage holding an origami crane', description: 'Paper bird that occasionally shifts position when unobserved.'),
      TableEntry(minRoll: 43, maxRoll: 43, label: 'Old pair of spectacles that turn all ink golden', description: 'Allows reader to view handwritten script as glowing gold text.'),
      TableEntry(minRoll: 44, maxRoll: 44, label: 'Petrified aberration eyestalk', description: 'Stone stalk ending in a dormant, stony pupil.'),
      TableEntry(minRoll: 45, maxRoll: 45, label: 'Tiny iron anvil that weighs exactly 10 pounds', description: 'Dense palm-sized blacksmith keepsake.'),
      TableEntry(minRoll: 46, maxRoll: 46, label: 'Set of wooden worry beads from a planar monastery', description: 'Strung on dragon sinew, worn smooth by centuries of prayer.'),
      TableEntry(minRoll: 47, maxRoll: 47, label: 'Parchment map of an underground city in a language you don\'t speak', description: 'Shows tunnels, reservoirs, and a grand central citadel.'),
      TableEntry(minRoll: 48, maxRoll: 48, label: 'Brass key that turns any lock it opens upside down', description: 'Quirky magical side-effect on mechanical deadbolts.'),
      TableEntry(minRoll: 49, maxRoll: 49, label: 'Glass beaker containing harmless purple sparks', description: 'Static charge that dances across the glass interior.'),
      TableEntry(minRoll: 50, maxRoll: 50, label: 'Small wooden puzzle box that hums when shaken', description: 'Thirty-step puzzle box containing a mysterious hollow chamber.'),
      TableEntry(minRoll: 51, maxRoll: 51, label: 'Old silver coin with a hole drilled through the center', description: 'Worn as a good-luck talisman on a leather cord.'),
      TableEntry(minRoll: 52, maxRoll: 52, label: 'Tiny clay pot containing soil from an extinct kingdom', description: 'Smells of ancient cedar and rain.'),
      TableEntry(minRoll: 53, maxRoll: 53, label: 'Dried scorpion encased in amber', description: 'Translucent golden fossil with venomous barb intact.'),
      TableEntry(minRoll: 54, maxRoll: 54, label: 'Piece of cloth torn from a celestial\'s robe', description: 'Cloth that never accumulates stains or dust.'),
      TableEntry(minRoll: 55, maxRoll: 55, label: 'Small lead box lined with velvet containing a tooth', description: 'Pointed canine tooth belonging to a vampire or ghoul.'),
      TableEntry(minRoll: 56, maxRoll: 56, label: 'Old brass key shaped like a serpent', description: 'Twisted wards resembling a striking cobra head.'),
      TableEntry(minRoll: 57, maxRoll: 57, label: 'Glass sphere filled with swirling mercury', description: 'Reflects the observer\'s image with a silver halo.'),
      TableEntry(minRoll: 58, maxRoll: 58, label: 'Silver needle that points toward the sun when balanced on water', description: 'Functions as a solar compass on overcast days.'),
      TableEntry(minRoll: 59, maxRoll: 59, label: 'Small leather pouch of iridescent bird feathers', description: 'Feathers that shimmer with fey luminescence.'),
      TableEntry(minRoll: 60, maxRoll: 60, label: 'Old copper coin that always lands on tails', description: 'Magically biased towards the crest side on any flip.'),
      TableEntry(minRoll: 61, maxRoll: 61, label: 'Tiny crystal prism that casts double rainbows', description: 'Splits direct sunlight into paired vibrant spectrums.'),
      TableEntry(minRoll: 62, maxRoll: 62, label: 'Small bone flute carved from a griffon wing bone', description: 'Produces a piercing high-pitched whistle.'),
      TableEntry(minRoll: 63, maxRoll: 63, label: 'Carved wooden figurine of a warrior with a removable shield', description: 'Handcrafted toy with moving joints.'),
      TableEntry(minRoll: 64, maxRoll: 64, label: 'Glass bottle containing ocean water from the Astral Sea', description: 'Silver-flecked seawater that sparkles in darkness.'),
      TableEntry(minRoll: 65, maxRoll: 65, label: 'Small brass gear that spins perpetually on a pin', description: 'Never slows down, frictionless perpetual motion toy.'),
      TableEntry(minRoll: 66, maxRoll: 66, label: 'Piece of dried parchment with a drawing of your face', description: 'Sketch made years before you were born by an unknown artist.'),
      TableEntry(minRoll: 67, maxRoll: 67, label: 'Tiny iron padlock without a keyhole', description: 'Can only be unlocked with a specific knock pattern.'),
      TableEntry(minRoll: 68, maxRoll: 68, label: 'Small stone that feels freezing cold in summer and warm in winter', description: 'Inverts thermal sensations relative to surroundings.'),
      TableEntry(minRoll: 69, maxRoll: 69, label: 'Set of five multicolored glass marbles', description: 'Swirled with red, sapphire, emerald, violet, and gold.'),
      TableEntry(minRoll: 70, maxRoll: 70, label: 'Silver thimble engraved with protective ward runes', description: 'Prevents needle pricks from drawing blood.'),
      TableEntry(minRoll: 71, maxRoll: 71, label: 'Dried leaf that never crumbles or decays', description: 'Autumn oak leaf preserved in perpetual crisp gold.'),
      TableEntry(minRoll: 72, maxRoll: 72, label: 'Small brass telescope that shows things 1 second into the past', description: 'Brief temporal distortion lens.'),
      TableEntry(minRoll: 73, maxRoll: 73, label: 'Pair of bone dice with blank faces', description: 'Used for blind divination and gambling.'),
      TableEntry(minRoll: 74, maxRoll: 74, label: 'Tiny glass bottle containing the scent of baking bread', description: 'Uncorking it fills a 10-foot radius with fresh bakery aroma.'),
      TableEntry(minRoll: 75, maxRoll: 75, label: 'Old iron horseshoe that sparks when struck with wood', description: 'Emits harmless yellow sparks against timber.'),
      TableEntry(minRoll: 76, maxRoll: 76, label: 'Small silver locket holding a pressed four-leaf clover', description: 'Keepsake from a halfling elder.'),
      TableEntry(minRoll: 77, maxRoll: 77, label: 'Petrified flower with metallic silver petals', description: 'Heavy bloom carved by elemental earth magic.'),
      TableEntry(minRoll: 78, maxRoll: 78, label: 'Tiny wooden barrel that smells of spiced rum', description: 'Holds 1 ounce of liquid, keeps spirits perfectly chilled.'),
      TableEntry(minRoll: 79, maxRoll: 79, label: 'Glass eye with an emerald iris', description: 'Smooth polished prosthetic with realistic depth.'),
      TableEntry(minRoll: 80, maxRoll: 80, label: 'Brass sundial that works by moonlight', description: 'Gnomish ingenuity calculating lunar time.'),
      TableEntry(minRoll: 81, maxRoll: 81, label: 'Small pouch of magnetic sand that sticks to nothing but copper', description: 'Curious mineral powder with inverted magnetic polarity.'),
      TableEntry(minRoll: 82, maxRoll: 82, label: 'Carved ivory chess knight that changes expression', description: 'Stern in victory, sorrowful in capture.'),
      TableEntry(minRoll: 83, maxRoll: 83, label: 'Old copper key that feels warm when near gold', description: 'Conducts heat when within 5 feet of treasure piles.'),
      TableEntry(minRoll: 84, maxRoll: 84, label: 'Tiny glass bell that only chimes when shaken by a child', description: 'Responds only to innocent hands.'),
      TableEntry(minRoll: 85, maxRoll: 85, label: 'Piece of volcanic rock that floats on water', description: 'Ultra-lightweight pumice stone with air pockets.'),
      TableEntry(minRoll: 86, maxRoll: 86, label: 'Small silver mirror that shows no reflection', description: 'Completely clear glass that reflects the background, ignoring foreground viewer.'),
      TableEntry(minRoll: 87, maxRoll: 87, label: 'Dried sea horse with shimmering scales', description: 'Preserved oceanic keepsake from a mermaid queen.'),
      TableEntry(minRoll: 88, maxRoll: 88, label: 'Tiny leather pouch of salt from the Dead Sea of Baator', description: 'Crimson-tinted salt crystals with sulfurous scent.'),
      TableEntry(minRoll: 89, maxRoll: 89, label: 'Brass coin that displays a different royal crest every morning', description: 'Cycles through dynasties of human realms.'),
      TableEntry(minRoll: 90, maxRoll: 90, label: 'Small crystal prism that makes shadows colorful', description: 'Casts rainbow shadows on walls when positioned near candles.'),
      TableEntry(minRoll: 91, maxRoll: 91, label: 'Wooden peg leg carved with an intricate treasure map', description: 'Left behind by a retired buccaneer captain.'),
      TableEntry(minRoll: 92, maxRoll: 92, label: 'Tiny glass bottle holding a glowing ember that never burns out', description: 'Elemental fire spark trapped in enchanted crystal.'),
      TableEntry(minRoll: 93, maxRoll: 93, label: 'Old iron key with seven teeth, each carved like a tooth', description: 'Opens a set of 7 chained dungeon locks.'),
      TableEntry(minRoll: 94, maxRoll: 94, label: 'Small leather journal filled with recipes for mythical pies', description: 'Dragonberry tarts, owlbear pot pie, and roc egg custard.'),
      TableEntry(minRoll: 95, maxRoll: 95, label: 'Petrified dragon egg fragment with golden veins', description: 'Smooth shell piece from an ancient gold wyrm.'),
      TableEntry(minRoll: 96, maxRoll: 96, label: 'Tiny silver hourglass where the sand falls up', description: 'Inverted gravity sand that cycles over 1 minute.'),
      TableEntry(minRoll: 97, maxRoll: 97, label: 'Brass gear that whispers a secret when wound', description: 'Softly whispers a forgotten proverb in Elvish.'),
      TableEntry(minRoll: 98, maxRoll: 98, label: 'Small wooden box with an unopenable lid that rattles', description: 'Sounds like 3 metal ball bearings roll inside.'),
      TableEntry(minRoll: 99, maxRoll: 99, label: 'Glass vial of rainwater collected during a total solar eclipse', description: 'Dark water that holds the chill of a shadow world.'),
      TableEntry(minRoll: 100, maxRoll: 100, label: 'A mysterious black iron key that you swear you\'ve never seen before', description: 'It appeared in your pocket this morning, cold and heavy.'),
    ],
  );
}
