import '../spellbook_data.dart';

const List<SpellItem> srdHighLevelSpells = [
  // ---------------------------------------------------------
  // 6TH LEVEL SPELLS
  // ---------------------------------------------------------
  SpellItem(
    id: 'spell_create_undead',
    name: 'Create Undead',
    level: 6,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'High-tier necromancy: Animates 3 Ghouls (or Ghasts, Wights, and Mummies with higher spell slots) for 24 hours.',
    tags: ['undead', 'ghoul', 'ghast', 'wight', 'mummy', 'necromancy', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '10 feet',
      components: 'V, S, M (one clay pot filled with grave dirt, one clay pot filled with brackish water, and 150 gp black onyx per corpse)',
      materialDetails: SpellMaterialComponent(
        description: 'clay pots with grave dirt, brackish water, and 150 gp black onyx per corpse',
        hasCost: true,
        costInGp: 150,
        isConsumed: false,
      ),
      duration: 'Instantaneous (24 hours control)',
      classes: [SpellClass.cleric, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You can cast this spell only at night. Choose up to three corpses of Medium or Small humanoids within range.',
        'Each corpse becomes a ghoul under your control.',
        'As a bonus action on each of your turns, you can mentally command any creature you animated with this spell if within 120 feet.',
      ],
      higherLevels: 'Slot 7th: 4 Ghouls. Slot 8th: 5 Ghouls or 2 Ghasts/Wights. Slot 9th: 6 Ghouls, 3 Ghasts/Wights, or 2 Mummies.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: '10 feet',
      components: 'V, S, M (grave dirt, brackish water, and black onyx worth 150+ gp per corpse)',
      materialDetails: SpellMaterialComponent(
        description: 'grave dirt, brackish water, and black onyx worth 150+ gp per corpse',
        hasCost: true,
        costInGp: 150,
        isConsumed: false,
      ),
      duration: 'Instantaneous (24 hours control)',
      classes: [SpellClass.cleric, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You animate up to three Medium or Small corpses into Ghouls under your mental command.',
        'Control lasts 24 hours before reassertion is required.',
      ],
      higherLevels: 'Slot 7th: 4 Ghouls. Slot 8th: 5 Ghouls or 2 Ghasts/Wights. Slot 9th: 6 Ghouls, 3 Ghasts/Wights, or 2 Mummies.',
    ),
  ),

  SpellItem(
    id: 'spell_chain_lightning',
    name: 'Chain Lightning',
    level: 6,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Fires a bolt of lightning dealing 10d8 lightning damage on Dexterity save, arcing to up to 3 additional targets within 30 feet.',
    tags: ['lightning', 'aoe', 'arc', 'damage', 'evocation', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (a bit of fur, a piece of amber, glass, or a crystal rod, and three silver pins)',
      materialDetails: SpellMaterialComponent(description: 'fur, amber/crystal rod, and three silver pins'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 8),
      damageOrHealType: 'Lightning',
      savingThrow: 'Dexterity',
      description: [
        'You create a bolt of lightning that arcs toward a target of your choice that you can see within range. Three bolts then leap from that target to as many as three other targets, each of which must be within 30 feet of the first target.',
        'A target can be a creature or an object and can be targeted by only one of the bolts. A target must make a Dexterity saving throw, taking 10d8 lightning damage on a failed save, or half as much on a successful one.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, one additional bolt leaps from the first target to another target for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (fur, amber rod, and silver pins)',
      materialDetails: SpellMaterialComponent(description: 'fur, amber rod, and silver pins'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 8),
      damageOrHealType: 'Lightning',
      savingThrow: 'Dexterity',
      description: [
        'You create a bolt of lightning that hits a primary target and arcs to up to 3 secondary targets within 30 feet. Each target takes 10d8 Lightning damage on a failed Dexterity save (half on success).',
      ],
      higherLevels: 'One additional secondary bolt leaps for each slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_disintegrate',
    name: 'Disintegrate',
    level: 6,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Deals 10d6 + 40 force damage on Dexterity save; a creature reduced to 0 HP is turned into a pile of fine gray dust.',
    tags: ['force', 'disintegrate', 'high-damage', 'transmutation', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a lodestone and a pinch of dust)',
      materialDetails: SpellMaterialComponent(description: 'a lodestone and a pinch of dust'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d6 + 40',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 6, dicePerSlotLevel: 3, staticBonus: 40),
      damageOrHealType: 'Force',
      savingThrow: 'Dexterity',
      description: [
        'A thin green ray springs from your pointing finger to a target that you can see within range.',
        'The target must succeed on a Dexterity saving throw or take 10d6 + 40 force damage. If this damage reduces the target to 0 hit points, it is disintegrated.',
        'A disintegrated creature and everything it is wearing and carrying, except magic items, are reduced to a pile of fine gray dust.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, the damage increases by 3d6 for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a lodestone and a pinch of dust)',
      materialDetails: SpellMaterialComponent(description: 'a lodestone and a pinch of dust'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d6 + 40',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 6, dicePerSlotLevel: 3, staticBonus: 40),
      damageOrHealType: 'Force',
      savingThrow: 'Dexterity',
      description: [
        'A thin green ray deals 10d6 + 40 Force damage on a failed Dexterity save. Reduces target to gray dust if brought to 0 HP.',
      ],
      higherLevels: 'Damage increases by 3d6 for each slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_heal',
    name: 'Heal',
    level: 6,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Restores a flat 70 Hit Points to a target and ends blindness, deafness, and all diseases (classified as Abjuration in 2024).',
    tags: ['healing', 'flat-heal', 'cure', 'abjuration', 'level 6'],
    rules2014: SpellEditionDetails(
      schoolOverride: SpellSchool.evocation,
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid],
      damageOrHealType: '70 Hit Points',
      description: [
        'Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points.',
        'This spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, the amount of healing increases by 10 for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      schoolOverride: SpellSchool.abjuration,
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid],
      damageOrHealType: '70 Hit Points',
      description: [
        'A target creature regains 70 Hit Points. Also ends the Blinded, Deafened, and Poisoned conditions.',
      ],
      higherLevels: 'Healing increases by 10 Hit Points for each slot level above 6th.',
    ),
  ),

  // ---------------------------------------------------------
  // 7TH LEVEL SPELLS
  // ---------------------------------------------------------
  SpellItem(
    id: 'spell_teleport',
    name: 'Teleport',
    level: 7,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Instantly transports you and up to eight willing creatures to any destination you designate on the same plane.',
    tags: ['teleport', 'long-range', 'conjuration', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '10 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'This spell instantly transports you and up to eight willing creatures of your choice that you can see within range, or a single object that you can see within range, to a destination you select.',
        'The destination must be known to you, and it must be on the same plane of existence as you. Your familiarity with the destination determines whether you arrive there successfully.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '10 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Instantly transports you and up to 8 willing creatures or 1 object to a known destination on the same plane. Roll d100 on familiarity table to determine accuracy.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_forcecage',
    name: 'Forcecage',
    level: 7,
    school: SpellSchool.evocation,
    isChangedIn2024: true,
    diffSummary: 'Creates an invisible cube or cage of force trapping creatures without an initial saving throw (now requires Concentration and consumes 1,500 gp ruby dust in 2024).',
    diffHighlights: [
      '2014: 1 Action, 1 hour duration (NO CONCENTRATION). 1,500 gp ruby dust NOT consumed. No initial save.',
      '2024: 1 Action, Concentration up to 1 hour. Consumes 1,500 gp ruby dust. Trapped creatures must make Charisma saves to teleport out.',
    ],
    tags: ['force', 'trap', 'no-save', 'concentration', 'evocation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '100 feet',
      components: 'V, S, M (ruby dust worth 1,500 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'ruby dust worth 1,500 gp',
        hasCost: true,
        costInGp: 1500,
        isConsumed: false,
      ),
      duration: '1 hour',
      concentration: false,
      classes: [SpellClass.bard, SpellClass.warlock, SpellClass.wizard],
      description: [
        'An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose within range.',
        'A prison in the shape of a cage can be up to 20 feet on a side and is made from 1/2-inch diameter bars spaced 1/2 inch apart. A prison in the shape of a solid box can be up to 10 feet on a side, creating a solid barrier that prevents any matter from passing through it.',
        'When you cast the spell, any creature that is completely inside the cage’s area is trapped with no initial saving throw. Teleportation out requires a successful Charisma saving throw.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '100 feet',
      components: 'V, S, M (ruby dust worth 1,500 gp, consumed by the spell)',
      materialDetails: SpellMaterialComponent(
        description: 'ruby dust worth 1,500 gp, consumed by the spell',
        hasCost: true,
        costInGp: 1500,
        isConsumed: true,
      ),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.warlock, SpellClass.wizard],
      description: [
        'An invisible cube of force traps creatures within range without an initial save. Requires Concentration. Escaping via teleportation requires a Charisma save.',
      ],
    ),
  ),

  // ---------------------------------------------------------
  // 8TH LEVEL SPELLS
  // ---------------------------------------------------------
  SpellItem(
    id: 'spell_antimagic_field',
    name: 'Antimagic Field',
    level: 8,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Creates a 10-foot invisible sphere around you where all magic, spells, summons, and magical properties of items are suppressed.',
    tags: ['anti-magic', 'suppression', 'aura', 'concentration', 'abjuration', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (10-foot-radius sphere)',
      components: 'V, S, M (a pinch of powdered iron or iron filings)',
      materialDetails: SpellMaterialComponent(description: 'a pinch of powdered iron or iron filings'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.wizard],
      description: [
        'A 10-foot-radius invisible sphere of antimagic surrounds you. This area is divorced from the magical energy that suffuses the multiverse.',
        'Within the sphere, spells can’t be cast, summoned creatures disappear, and even magic items become mundane.',
        'Spells and other magical effects, except those created by an artifact or a deity, are suppressed in the sphere and can’t protrude into it.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (10-foot-radius sphere)',
      components: 'V, S, M (powdered iron)',
      materialDetails: SpellMaterialComponent(description: 'powdered iron'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.wizard],
      description: [
        'A 10-foot-radius sphere of antimagic surrounds you. All spells, magic items, and summon effects are suppressed within the area.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_sunburst',
    name: 'Sunburst',
    level: 8,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Brilliant sunlight flashes in a massive 60-foot radius sphere dealing 12d6 radiant damage and blinding targets on failed Constitution save.',
    tags: ['radiant', 'sunlight', 'blind', 'aoe', 'evocation', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (fire and a piece of sunstone)',
      materialDetails: SpellMaterialComponent(description: 'fire and a piece of sunstone'),
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '12d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 12, diceSides: 6),
      damageOrHealType: 'Radiant',
      savingThrow: 'Constitution',
      description: [
        'Brilliant sunlight flashes in a 60-foot-radius sphere centered on a point you choose within range.',
        'Each creature in that light must make a Constitution saving throw. On a failed save, a creature takes 12d6 radiant damage and is blinded for 1 minute.',
        'Undead and oozes have disadvantage on this saving throw. This spell dispels any darkness in its area that was created by a spell.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (sunstone)',
      materialDetails: SpellMaterialComponent(description: 'sunstone'),
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '12d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 12, diceSides: 6),
      damageOrHealType: 'Radiant',
      savingThrow: 'Constitution',
      description: [
        'Brilliant sunlight erupts in a 60-foot-radius sphere dealing 12d6 Radiant damage and imposing the Blinded condition for 1 minute on failed Constitution save (Undead/Oozes have Disadvantage).',
      ],
    ),
  ),

  // ---------------------------------------------------------
  // 9TH LEVEL SPELLS
  // ---------------------------------------------------------
  SpellItem(
    id: 'spell_meteor_swarm',
    name: 'Meteor Swarm',
    level: 9,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Blasts four 40-foot radius spheres with blazing orbs dealing 20d6 fire damage and 20d6 bludgeoning damage (40d6 total) on Dexterity save.',
    tags: ['ultimate', 'fire', 'bludgeoning', 'apocalypse', 'aoe', 'evocation', 'level 9'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '1 mile',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '20d6 + 20d6',
      damageOrHealType: 'Fire & Bludgeoning (40d6 total)',
      savingThrow: 'Dexterity',
      description: [
        'Blazing orbs of fire plummet to the ground at four different points you can see within range. You can form each point into a 40-foot-radius sphere centered on that point.',
        'Each creature in the sphere must make a Dexterity saving throw. A creature takes 20d6 fire damage and 20d6 bludgeoning damage on a failed save, or half as much on a successful one. A creature in the area of more than one fiery burst is affected only once.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '1 mile',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '20d6 + 20d6',
      damageOrHealType: 'Fire & Bludgeoning (40d6 total)',
      savingThrow: 'Dexterity',
      description: [
        'Blazing orbs plummet at 4 separate points within 1 mile. Each 40-foot-radius sphere deals 20d6 Fire + 20d6 Bludgeoning damage on a failed Dexterity save (half on success).',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_power_word_kill',
    name: 'Power Word Kill',
    level: 9,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Utters a word of power that instantly kills one creature within 60 feet if it has 100 hit points or fewer (no saving throw).',
    tags: ['death', 'instant-kill', 'no-save', 'enchantment', 'level 9'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You utter a word of power that can compel one creature you can see within range to die instantly.',
        'If the creature you choose has 100 hit points or fewer, it dies. Otherwise, the spell has no effect.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You utter a word of power. If the target has 100 Hit Points or fewer, it dies instantly. Otherwise, the spell has no effect.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_wish',
    name: 'Wish',
    level: 9,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'The pinnacle of mortal magic: Duplicates any spell of 8th level or lower with no components or costs, or produces reality-altering custom effects with severe stress.',
    tags: ['ultimate', 'duplicate', 'reality-warping', 'level 9'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires.',
        'The basic use of this spell is to duplicate any other spell of 8th level or lower. You don’t need to meet any requirements in that spell, including costly components. The spell simply takes effect.',
        'Alternatively, you can create other effects (create an object up to 25,000 gp, allow 20 creatures to recover all HP, grant 10 creatures resistance, etc.). The stress of casting this for non-spell duplication causes strength drop to 3 for 2d4 days, necrotic damage on subsequent casting, and a 33 percent chance you can never cast Wish again.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Wish is the mightiest spell a mortal creature can cast.',
        'The basic use of this spell is to duplicate any other spell of level 8 or lower. You don’t need to meet any requirements in that spell, including costly components. The spell simply takes effect.',
        'Alternatively, you can produce other powerful effects with the stress penalty (Strength drops to 3 for 2d4 days, 1d10 Necrotic damage per spell level when casting until long rest, and a 33% chance of never being able to cast Wish again).',
      ],
    ),
  ),
];
