import '../spellbook_data.dart';

const List<SpellItem> srdLevel5Spells = [
  SpellItem(
    id: 'spell_cloudkill',
    name: 'Cloudkill',
    level: 5,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Harmonized damage trigger once per turn when entering or ending turn in toxic fog.',
    tags: ['poison', 'fog', 'aoe', 'concentration', 'level 5'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Poison',
      savingThrow: 'Constitution',
      description: [
        'You create a 20-foot-radius sphere of poisonous, yellow-green fog centered on a point you choose within range.',
        'The fog moves 10 feet away from you at the start of each of your turns.',
        'When a creature enters the spell’s area for the first time on a turn or starts its turn there, it must make a Constitution saving throw, taking 5d8 poison damage on a failed save, or half as much on a successful one.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 5th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Poison',
      savingThrow: 'Constitution',
      description: [
        'You create a 20-foot-radius Sphere of poisonous yellow-green fog. The fog moves 10 feet away from you at the start of each of your turns.',
        'When a creature enters the area for the first time on a turn or ends its turn there, it must make a Constitution saving throw, taking 5d8 Poison damage on a failed save, or half as much on a success (damage applies once per turn).',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 5th.',
    ),
  ),

  SpellItem(
    id: 'spell_animate_objects',
    name: 'Animate Objects',
    level: 5,
    school: SpellSchool.transmutation,
    isChangedIn2024: true,
    diffSummary: 'Standardized into a single Animated Object swarm/companion stat block with customizable sizes and attacks, reducing 10 separate attack rolls to streamlined action economy.',
    diffHighlights: [
      '2014: Animates up to 10 separate non-magical objects (Tiny to Huge) with individual HP pools, making up to 10 separate attack rolls (+8 to hit, 1d4+4 each).',
      '2024: Creates animated object constructs using modernized scaling mechanics to preserve high damage without slowing down table turns.',
    ],
    tags: ['construct', 'transmutation', 'objects', 'artificer', 'bard', 'sorcerer', 'wizard', 'level 5'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '1d4 + 4',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 4, staticBonus: 4),
      damageOrHealType: 'Bludgeoning',
      description: [
        'Objects come to life at your command. Choose up to ten nonmagical objects within range that are not being worn or carried.',
        'Medium targets count as two objects, Large targets count as four objects, Huge targets count as eight objects.',
        'Each animated object is a construct with statistics determined by its size (Tiny AC 18 HP 20, Small AC 16 HP 25, Medium AC 13 HP 40, Large AC 10 HP 50, Huge AC 10 HP 80).',
        'As a bonus action, you can mentally command any object you made with this spell.',
      ],
      higherLevels: 'If you cast this spell using a spell slot of 6th level or higher, you can animate two additional objects for each slot level above 5th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '1d4 + 4',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 4, staticBonus: 4),
      damageOrHealType: 'Bludgeoning',
      description: [
        'You bring objects to life within range.',
        'Choose up to 10 Tiny or Small nonmagical objects (or equivalent Medium, Large, or Huge budget).',
        'The objects gain the statistics and traits of Animated Objects and attack at your command.',
      ],
      higherLevels: 'You can animate 2 additional objects per slot level above 5th.',
    ),
  ),

  SpellItem(
    id: 'spell_conjure_elemental',
    name: 'Conjure Elemental',
    level: 5,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Casting time reduced from 1 minute to 1 Action! Removes the catastrophic concentration failure where elementals turn uncontrollably hostile.',
    diffHighlights: [
      '2014: 1 minute casting time. Summons an Elemental of CR 5 (Air, Earth, Fire, or Water). If your concentration is broken, the elemental does NOT disappear; it becomes hostile to you and your companions.',
      '2024: 1 Action casting time. Summons an elemental spirit that remains cooperative and disappears when concentration ends.',
    ],
    tags: ['elemental', 'conjuration', 'druid', 'wizard', 'level 5'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '90 feet',
      components: 'V, S, M (burning incense for air, soft clay for earth, sulfur for fire, or water in a bowl)',
      materialDetails: SpellMaterialComponent(description: 'burning incense for air, soft clay for earth, sulfur for fire, or water in a bowl'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.wizard],
      description: [
        'You call forth an elemental servant. Choose an area of air, earth, fire, or water that fills a 10-foot cube within range. An elemental of challenge rating 5 or lower appropriate to the element you chose appears in an unoccupied space within 10 feet of it.',
        'If your concentration is broken, the elemental doesn’t disappear. Instead, you lose control of the elemental, it becomes hostile toward you and your companions, and it might attack.',
      ],
      higherLevels: 'Slot 6th or higher: CR increases by 1 for each slot level above 5th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (an elemental offering)',
      materialDetails: SpellMaterialComponent(description: 'an elemental offering'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.wizard],
      description: [
        'You call forth an elemental servant in an unoccupied space within range.',
        'The elemental is friendly to you and your companions and disappears when the spell ends.',
      ],
      higherLevels: 'When cast using higher spell slots, elemental attributes and challenge rating scale accordingly.',
    ),
  ),

  SpellItem(
    id: 'spell_cone_of_cold',
    name: 'Cone of Cold',
    level: 5,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Blasts a 60-foot cone of freezing cold dealing 8d8 cold damage on Constitution save (+1d8 per higher slot).',
    tags: ['cold', 'aoe', 'cone', 'damage', 'evocation', 'level 5'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (60-foot cone)',
      components: 'V, S, M (a small crystal or glass cone)',
      materialDetails: SpellMaterialComponent(description: 'a small crystal or glass cone'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Cold',
      savingThrow: 'Constitution',
      description: [
        'A blast of cold air erupts from your hands. Each creature in a 60-foot cone must make a Constitution saving throw. A creature takes 8d8 cold damage on a failed save, or half as much damage on a successful one.',
        'A creature killed by this spell becomes a frozen statue until it thaws.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the damage increases by 1d8 for each slot level above 5th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (60-foot cone)',
      components: 'V, S, M (a small crystal or glass cone)',
      materialDetails: SpellMaterialComponent(description: 'a small crystal or glass cone'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Cold',
      savingThrow: 'Constitution',
      description: [
        'A blast of cold air erupts in a 60-foot cone. Each creature takes 8d8 Cold damage on failed Constitution save (half on success).',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 5th.',
    ),
  ),

  SpellItem(
    id: 'spell_greater_restoration',
    name: 'Greater Restoration',
    level: 5,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Channels positive energy to cure 1 exhaustion level, charm/petrify effects, curse, ability score reductions, or max HP reductions (costs 100 gp diamond dust).',
    tags: ['cure', 'restoration', 'exhaustion', 'curse', 'abjuration', 'costly-component', 'level 5'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (diamond dust worth at least 100 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond dust worth at least 100 gp, consumed by the spell',
        hasCost: true,
        costInGp: 100,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      description: [
        'You imbue a creature you touch with positive energy to undo a debilitating effect. You can reduce the target’s exhaustion level by one, or end one of the following effects on the target:',
        '• One effect that charmed or petrified the target',
        '• One curse, including the target’s attunement to a cursed magic item',
        '• Any reduction to one of the target’s ability scores',
        '• One effect reducing the target’s hit point maximum',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (diamond dust worth at least 100 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond dust worth at least 100 gp, consumed by the spell',
        hasCost: true,
        costInGp: 100,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      description: [
        'You touch a creature to undo debilitating effects: reduces 1 level of Exhaustion, ends Charmed/Petrified, ends 1 Curse, or restores reduced ability scores / HP maximum.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_hold_monster',
    name: 'Hold Monster',
    level: 5,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Paralyzes any creature type on failed Wisdom save (+1 creature per higher slot).',
    tags: ['paralyze', 'save', 'concentration', 'enchantment', 'level 5'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet',
      components: 'V, S, M (a small, straight piece of iron)',
      materialDetails: SpellMaterialComponent(description: 'a small, straight piece of iron'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Choose a creature that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration.',
        'This spell has no effect on undead. At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, you can target one additional creature for each slot level above 5th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet',
      components: 'V, S, M (a small, straight piece of iron)',
      materialDetails: SpellMaterialComponent(description: 'a small, straight piece of iron'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Choose a creature within range (excluding Undead). The target must make a Wisdom saving throw or have the Paralyzed condition for the duration. It repeats the save at the end of each turn.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 5th.',
    ),
  ),

  SpellItem(
    id: 'spell_wall_of_force',
    name: 'Wall of Force',
    level: 5,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates an invisible, indestructible wall of force immune to all damage and dispelling.',
    tags: ['force', 'wall', 'indestructible', 'defense', 'concentration', 'evocation', 'level 5'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a pinch of powder by which a clear gemstone has been crushed)',
      materialDetails: SpellMaterialComponent(description: 'a pinch of crushed clear gemstone powder'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.wizard],
      description: [
        'An invisible wall of force springs into existence at a point you choose within range. The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle.',
        'It can be free floating or resting on a solid surface. You can form it into a hemispherical dome or a sphere with a radius of up to 10 feet, or you can shape a flat surface made up of ten 10-foot-by-10-foot panels.',
        'Nothing can physically pass through the wall. It is immune to all damage and can’t be dispelled by dispel magic. A disintegrate spell destroys the wall instantly.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (gemstone powder)',
      materialDetails: SpellMaterialComponent(description: 'gemstone powder'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.wizard],
      description: [
        'An invisible wall of force springs into existence in any orientation (dome, sphere, or up to ten 10-ft panels). Nothing can pass through physically. Immune to damage and Dispel Magic; destroyed by Disintegrate.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_mass_cure_wounds',
    name: 'Mass Cure Wounds',
    level: 5,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Major healing buff: 2024 increased healing from 3d8 + mod to 5d8 + mod (+1d8 per slot level) and classified under Abjuration.',
    diffHighlights: [
      '2014: Evocation school. Heals up to 6 creatures within 30 ft radius for 3d8 + modifier (+1d8 per slot above 5th).',
      '2024: Abjuration school. Heals up to 6 creatures for 5d8 + modifier (+1d8 per slot above 5th).',
    ],
    tags: ['healing', 'aoe', 'mass-heal', 'buffed', 'level 5'],
    rules2014: SpellEditionDetails(
      schoolOverride: SpellSchool.evocation,
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      rollFormula: '3d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1, addsAbilityMod: true),
      damageOrHealType: 'Healing',
      description: [
        'A wave of healing energy washes out from a point of your choice within range. Choose up to six creatures in a 30-foot-radius sphere centered on that point.',
        'Each target regains hit points equal to 3d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 6th level or higher, the healing increases by 1d8 for each slot level above 5th.',
    ),
    rules2024: SpellEditionDetails(
      schoolOverride: SpellSchool.abjuration,
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      rollFormula: '5d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1, addsAbilityMod: true),
      damageOrHealType: 'Healing',
      description: [
        'Choose up to six creatures in a 30-foot-radius Sphere. Each target regains Hit Points equal to 5d8 + your spellcasting ability modifier.',
      ],
      higherLevels: 'Healing increases by 1d8 for each slot level above 5th.',
    ),
  ),
];
