import '../spellbook_data.dart';

const List<SpellItem> srdLevel8Spells = [
  SpellItem(
    id: 'spell_holy_aura',
    name: 'Holy Aura',
    level: 8,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Divine radiance envelops allies within 30 feet, granting advantage on all saving throws, imposing disadvantage on incoming attacks, and blinding fiends/undead on hit.',
    tags: ['aura', 'divine', 'advantage-saves', 'disadvantage-attacks', 'blind', 'concentration', 'abjuration', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (30-foot radius)',
      components: 'V, S, M (a tiny reliquary worth at least 1,000 gp containing a sacred relic)',
      materialDetails: SpellMaterialComponent(
        description: 'tiny reliquary worth 1,000 gp with holy relic',
        hasCost: true,
        costInGp: 1000,
        isConsumed: false,
      ),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric],
      savingThrow: 'Constitution',
      description: [
        'A holy aura surrounds you in a 30-foot radius. Chosen creatures in the aura shed dim light and have advantage on all saving throws, and other creatures have disadvantage on attack rolls against them.',
        'When a fiend or undead hits an affected creature with a melee attack, the aura flashes with divine light: the attacker must succeed on a Constitution save or be blinded until the spell ends.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (30-foot radius)',
      components: 'V, S, M (holy reliquary worth 1,000 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'holy reliquary worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: false,
      ),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric],
      savingThrow: 'Constitution',
      description: [
        'Grants Advantage on all saving throws and Disadvantage to enemy attacks within 30 ft. Blinds Fiends/Undead that make melee hits on failed Constitution save.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_earthquake',
    name: 'Earthquake',
    level: 8,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates an intense seismic tremor in a 100-foot radius, tearing fissures, toppling structures, knocking creatures prone, and breaking concentration automatically.',
    tags: ['earthquake', 'aoe', 'structural-damage', 'fissures', 'concentration', 'evocation', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '500 feet (100-foot radius)',
      components: 'V, S, M (a pinch of dirt, a piece of rock, and a lump of clay)',
      materialDetails: SpellMaterialComponent(description: 'dirt, rock, and clay'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer],
      savingThrow: 'Dexterity / Constitution',
      description: [
        'You create a seismic tremor in a 100-foot radius centered on a point within range. The ground becomes difficult terrain, and casters concentrating in the area must make Constitution saving throws to maintain spells.',
        'Each round, creatures on the ground must make a Dexterity save or be knocked prone. Fissures open in the earth, potentially dropping creatures inside (taking 1d10 bludgeoning and being trapped). Structures take 50 bludgeoning damage each round.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '500 feet (100-foot radius)',
      components: 'V, S, M (dirt, rock, clay)',
      materialDetails: SpellMaterialComponent(description: 'dirt, rock, clay'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer],
      savingThrow: 'Dexterity / Constitution',
      description: [
        'Massive 100-ft radius quake knocks targets Prone on Dexterity save, creates fissures, and deals 50 Bludgeoning damage per round to buildings.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_control_weather',
    name: 'Control Weather',
    level: 8,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Takes control of the weather within a 5-mile radius for up to 8 hours, altering precipitation, temperature, and wind speed stage-by-stage.',
    tags: ['weather', 'environment', 'large-scale', 'concentration', 'transmutation', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Self (5-mile radius)',
      components: 'V, S, M (burning incense and bits of earth and wood mixed in water)',
      materialDetails: SpellMaterialComponent(description: 'burning incense, earth, wood, and water'),
      duration: 'Concentration, up to 8 hours',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'You take control of the weather within 5 miles of you for the duration. You can change precipitation (Clear to Torrential rain), temperature (Unbearable heat to Arctic cold), and wind (Calm to Gale/Storm). Takes 1d4 × 10 minutes for new conditions to take effect.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Self (5-mile radius)',
      components: 'V, S, M (incense, earth, wood, water)',
      materialDetails: SpellMaterialComponent(description: 'incense, earth, wood, water'),
      duration: 'Concentration, up to 8 hours',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'Alters precipitation, temperature, and wind across a 5-mile radius for 8 hours.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_antimagic_field',
    name: 'Antimagic Field',
    level: 8,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Creates a 10-foot invisible sphere around you where all magic, spells, summons, and magical properties of items are suppressed.',
    tags: ['anti-magic', 'suppression', 'aura', 'concentration', 'abjuration', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (10-foot-radius sphere)',
      components: 'V, S, M (a pinch of powdered iron or iron filings)',
      materialDetails: SpellMaterialComponent(description: 'powdered iron or iron filings'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.wizard],
      description: [
        'A 10-foot-radius invisible sphere of antimagic surrounds you. Spells can’t be cast, summoned creatures disappear, and magic items become mundane inside.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (10-foot-radius sphere)',
      components: 'V, S, M (powdered iron)',
      materialDetails: SpellMaterialComponent(description: 'powdered iron'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.wizard],
      description: [
        '10-foot sphere suppresses all spells, magic items, and summon effects.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_sunburst',
    name: 'Sunburst',
    level: 8,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Brilliant sunlight flashes in a massive 60-foot radius sphere dealing 12d6 radiant damage and blinding targets on failed Constitution save.',
    tags: ['radiant', 'sunlight', 'blind', 'aoe', 'evocation', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (fire and a piece of sunstone)',
      materialDetails: SpellMaterialComponent(description: 'fire and sunstone'),
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '12d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 12, diceSides: 6),
      damageOrHealType: 'Radiant',
      savingThrow: 'Constitution',
      description: [
        'Brilliant sunlight flashes in a 60-foot-radius sphere. Each creature takes 12d6 radiant damage and is blinded for 1 minute on failed Constitution save (half damage, not blinded on success). Undead/oozes have disadvantage.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (sunstone)',
      materialDetails: SpellMaterialComponent(description: 'sunstone'),
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '12d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 12, diceSides: 6),
      damageOrHealType: 'Radiant',
      savingThrow: 'Constitution',
      description: [
        'Deals 12d6 Radiant damage and Blinded in a 60-ft radius on failed Constitution save.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_dominate_monster',
    name: 'Dominate Monster',
    level: 8,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Telepathically controls any creature on a failed Wisdom save, commanding it to take specific actions or taking total control of its turns.',
    tags: ['charm', 'mind-control', 'dominate', 'concentration', 'enchantment', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'You attempt to beguile a creature that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration.',
        'While charmed, you have a telepathic link with it and can issue precise commands or take direct control of its actions.',
      ],
      higherLevels: 'Duration is Concentration, up to 8 hours with a 9th-level slot.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Telepathically commands any creature on a failed Wisdom save.',
      ],
      higherLevels: 'Concentration up to 8 hours at 9th level.',
    ),
  ),

  SpellItem(
    id: 'spell_feeblemind',
    name: 'Feeblemind',
    name2024: 'Befuddle',
    level: 8,
    school: SpellSchool.enchantment,
    isChangedIn2024: true,
    diffSummary: 'Deals 4d6 psychic damage and shatters the target’s mind (renamed to Befuddle in 2024, setting INT/CHA to 1 and stripping spellcasting/communication for 30 days).',
    diffHighlights: [
      '2014: Named Feeblemind. Target’s Intelligence and Charisma scores become 1. The creature can’t cast spells, activate magic items, understand language, or communicate. Repeats save every 30 days.',
      '2024: Renamed Befuddle. Target takes 4d6 Psychic damage and cannot cast spells or take Bonus Actions for 30 days on failed Intelligence save.',
    ],
    tags: ['psychic', 'mind-break', 'anti-caster', 'enchantment', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (a handful of clay, crystal, glass, or mineral spheres)',
      materialDetails: SpellMaterialComponent(description: 'spheres of clay, crystal, or glass'),
      duration: 'Instantaneous (30 days recovery cycle)',
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '4d6',
      damageOrHealType: 'Psychic',
      savingThrow: 'Intelligence',
      description: [
        'You blast the mind of a creature that you can see within range, dealing 4d6 psychic damage and piercing its intellect. On a failed Intelligence save, the creature’s Intelligence and Charisma become 1, and it can’t cast spells or communicate for at least 30 days.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (mineral spheres)',
      materialDetails: SpellMaterialComponent(description: 'mineral spheres'),
      duration: 'Instantaneous (30 days recovery cycle)',
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '4d6',
      damageOrHealType: 'Psychic',
      savingThrow: 'Intelligence',
      description: [
        'Renamed Befuddle. Deals 4d6 Psychic damage and prevents spellcasting and language understanding on failed Intelligence save.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_maze',
    name: 'Maze',
    level: 8,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Banishes a creature to a labyrinthine demiplane without an initial saving throw; escaping requires a DC 20 Intelligence check as an Action.',
    tags: ['banish', 'labyrinth', 'no-save', 'concentration', 'conjuration', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.wizard],
      description: [
        'You banish a creature that you can see within range into a labyrinthine demiplane. The target remains there for the duration or until it escapes the maze.',
        'The target can use its action to attempt an escape by making a DC 20 Intelligence check (Minotaurs succeed automatically).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.wizard],
      description: [
        'Banishes target to an extradimensional maze with no initial save; requires DC 20 Intelligence check to escape.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_mind_blank',
    name: 'Mind Blank',
    level: 8,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Grants immunity to psychic damage, divination spells, mind-reading, and the charmed condition for 24 hours without concentration.',
    tags: ['immunity', 'psychic-immunity', 'charm-immunity', 'no-concentration', 'abjuration', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: '24 hours',
      concentration: false,
      classes: [SpellClass.bard, SpellClass.wizard],
      description: [
        'Until the spell ends, one willing creature you touch is immune to psychic damage, any effect that would sense its emotions or read its thoughts, divination spells, and the charmed condition.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: '24 hours',
      concentration: false,
      classes: [SpellClass.bard, SpellClass.wizard],
      description: [
        'Target gains 24-hour total immunity to Psychic damage, mind reading, divination spying, and the Charmed condition.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_power_word_stun',
    name: 'Power Word Stun',
    level: 8,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Utters a word of power that instantly stuns a creature with 150 Hit Points or fewer (no initial save).',
    tags: ['stun', 'no-save', 'power-word', 'enchantment', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Constitution',
      description: [
        'You speak a word of power that overwhelms the mind of one creature within range. If the target has 150 hit points or fewer, it is stunned. At the end of each of its turns, it makes a Constitution saving throw to end the stun.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Constitution',
      description: [
        'Instantly Stuns a target with 150 HP or fewer (repeats Constitution save at the end of each turn).',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_clone',
    name: 'Clone',
    level: 8,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Grows an inert duplicate of a living creature in a vessel over 120 days that receives the creature’s soul upon death, providing true immortality.',
    tags: ['clone', 'immortality', 'necromancy', 'costly-component', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 hour',
      range: 'Touch',
      components: 'V, S, M (a diamond worth at least 1,000 gp and at least 1 cubic inch of flesh, plus a vessel worth at least 2,000 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond worth 1,000 gp, flesh sample, and sealable vessel worth 2,000 gp',
        hasCost: true,
        costInGp: 3000,
        isConsumed: false,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.wizard],
      description: [
        'Grows an inert duplicate of a living creature that takes 120 days to mature. When the original creature dies, its soul instantly transfers to the clone if free and willing.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 hour',
      range: 'Touch',
      components: 'V, S, M (a diamond worth at least 1,000 gp and at least 1 cubic inch of flesh, plus a vessel worth at least 2,000 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond worth 1,000 gp, flesh sample, and sealable vessel worth 2,000 gp',
        hasCost: true,
        costInGp: 3000,
        isConsumed: false,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.wizard],
      description: [
        'Grows an inert duplicate of a living creature that takes 120 days to mature. When the original creature dies, its soul instantly transfers to the clone if free and willing.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_demiplane',
    name: 'Demiplane',
    level: 8,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Creates a shadowy door on a flat solid surface that leads to a 30-foot empty cubic extradimensional demiplane (or connects to a previously created demiplane) for 1 hour.',
    tags: ['extradimensional', 'storage', 'secret-base', 'warlock', 'wizard', 'conjuration', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'S',
      duration: '1 hour',
      classes: [SpellClass.warlock, SpellClass.wizard],
      description: [
        'You create a shadowy door on a flat solid surface that you can see within range. The door is large enough to admit Medium creatures easily. When opened, the door leads to a demiplane that appears to be an empty room 30 feet in each dimension, made of wood or stone.',
        'When the spell ends, the door disappears, and any creatures or objects inside remain trapped there.',
        'Each time you cast this spell, you can create a new demiplane or connect the shadowy door to a demiplane you created with a previous casting of this spell.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'S',
      duration: '1 hour',
      classes: [SpellClass.warlock, SpellClass.wizard],
      description: [
        'You create a shadowy door on a flat solid surface that you can see within range. The door is large enough to admit Medium creatures easily. When opened, the door leads to a demiplane that appears to be an empty room 30 feet in each dimension, made of wood or stone.',
        'When the spell ends, the door disappears, and any creatures or objects inside remain trapped there.',
        'Each time you cast this spell, you can create a new demiplane or connect the shadowy door to a demiplane you created with a previous casting of this spell.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_incendiary_cloud',
    name: 'Incendiary Cloud',
    level: 8,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'A swirling cloud of white-hot embers spreads in a 20-foot-radius sphere dealing 10d8 fire damage on Dexterity save and moving 10 feet away each turn. Concentration.',
    tags: ['fire', 'cloud', 'aoe', 'concentration', 'druid', 'sorcerer', 'wizard', 'conjuration', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet (20-foot-radius sphere)',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d8',
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A swirling cloud of smoke shot with white-hot embers appears in a 20-foot-radius sphere centered on a point within range. The cloud heavily obscures its area.',
        'A creature takes 10d8 fire damage when it enters the spell’s area for the first time on a turn or starts its turn there (Dexterity save for half). At the start of each of your turns, the cloud moves 10 feet directly away from you.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet (20-foot-radius sphere)',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d8',
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A swirling cloud of smoke shot with white-hot embers appears in a 20-foot-radius sphere centered on a point within range. The cloud heavily obscures its area.',
        'A creature takes 10d8 fire damage when it enters the spell’s area for the first time on a turn or starts its turn there (Dexterity save for half). At the start of each of your turns, the cloud moves 10 feet directly away from you.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_animal_shapes',
    name: 'Animal Shapes',
    level: 8,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Transform up to any number of willing creatures into Large or smaller beasts of CR 4 or lower for up to 24 hours. Can transform them into new beast forms as an Action.',
    tags: ['mass-polymorph', 'army-buff', 'beasts', 'concentration', 'druid', 'transmutation', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Concentration, up to 24 hours',
      concentration: true,
      classes: [SpellClass.druid],
      description: [
        'A magic mist radiates from you, transforming up to any number of willing creatures you can see within range into beasts. You choose the form of each creature: Large or smaller beast of challenge rating 4 or lower.',
        'On subsequent turns, you can use your action to transform affected creatures into new forms. The target’s game statistics are replaced by the statistics of the chosen beast.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Concentration, up to 24 hours',
      concentration: true,
      classes: [SpellClass.druid],
      description: [
        'A magic mist radiates from you, transforming up to any number of willing creatures you can see within range into beasts. You choose the form of each creature: Large or smaller beast of challenge rating 4 or lower.',
        'On subsequent turns, you can use your action to transform affected creatures into new forms. The target’s game statistics are replaced by the statistics of the chosen beast.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_antipathy_sympathy',
    name: 'Antipathy/Sympathy',
    level: 8,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Attracts (Sympathy) or repels (Antipathy) a specific kind of intelligent creature from a target object or creature for 10 days on failed Wisdom save.',
    tags: ['repel', 'attract', 'area-denial', 'mind-affecting', 'druid', 'wizard', 'enchantment', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 hour',
      range: '60 feet',
      components: 'V, S, M (either a lump of alum soaked in vinegar for antipathy, or a drop of honey for sympathy)',
      materialDetails: SpellMaterialComponent(description: 'alum soaked in vinegar or drop of honey'),
      duration: '10 days',
      classes: [SpellClass.druid, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'This spell attracts or repels creatures of your choice. You target something within range, either a Huge or smaller object or creature or an area within 200 feet.',
        'Antipathy: Causes creatures of the chosen kind to feel an urge to leave the area and avoid the target (frightened on failed Wisdom save).',
        'Sympathy: Causes creatures of the chosen kind to feel an overwhelming urge to approach the target and remain within 60 feet of it.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 hour',
      range: '60 feet',
      components: 'V, S, M (either a lump of alum soaked in vinegar for antipathy, or a drop of honey for sympathy)',
      materialDetails: SpellMaterialComponent(description: 'alum soaked in vinegar or drop of honey'),
      duration: '10 days',
      classes: [SpellClass.druid, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'This spell attracts or repels creatures of your choice. You target something within range, either a Huge or smaller object or creature or an area within 200 feet.',
        'Antipathy: Causes creatures of the chosen kind to feel an urge to leave the area and avoid the target (frightened on failed Wisdom save).',
        'Sympathy: Causes creatures of the chosen kind to feel an overwhelming urge to approach the target and remain within 60 feet of it.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_tsunami',
    name: 'Tsunami',
    level: 8,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Conjures a wall of water up to 300 feet long, 300 feet high, and 50 feet thick that moves away from you dealing 6d10 bludgeoning damage and dragging creatures along.',
    tags: ['massive-water-wall', 'bludgeoning', 'forced-movement', 'concentration', 'druid', 'conjuration', 'level 8'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: 'Sight',
      components: 'V, S',
      duration: 'Concentration, up to 6 rounds',
      concentration: true,
      classes: [SpellClass.druid],
      rollFormula: '6d10',
      damageOrHealType: 'Bludgeoning',
      savingThrow: 'Strength',
      description: [
        'A wall of water springs into existence at a point you choose within range (up to 300 feet long, 300 feet high, and 50 feet thick).',
        'When the wall appears, each creature within its area must make a Strength saving throw, taking 6d10 bludgeoning damage on a failed save, or half on success. At the start of each of your turns, the wall moves 50 feet away from you, dragging caught creatures with it and dealing damage.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: 'Sight',
      components: 'V, S',
      duration: 'Concentration, up to 6 rounds',
      concentration: true,
      classes: [SpellClass.druid],
      rollFormula: '6d10',
      damageOrHealType: 'Bludgeoning',
      savingThrow: 'Strength',
      description: [
        'A wall of water springs into existence at a point you choose within range (up to 300 feet long, 300 feet high, and 50 feet thick).',
        'When the wall appears, each creature within its area must make a Strength saving throw, taking 6d10 bludgeoning damage on a failed save, or half on success. At the start of each of your turns, the wall moves 50 feet away from you, dragging caught creatures with it and dealing damage.',
      ],
    ),
  ),
];
