import '../spellbook_data.dart';

const List<SpellItem> srdLevel4Spells = [
  SpellItem(
    id: 'spell_polymorph',
    name: 'Polymorph',
    level: 4,
    school: SpellSchool.transmutation,
    isChangedIn2024: true,
    diffSummary: 'Changed from giving a fresh full pool of Beast HP into giving Temporary Hit Points based on the new form.',
    diffHighlights: [
      '2014: Target takes on the beast’s full HP. Damage dealt first reduces the beast’s HP; excess damage carries over to the original form. Acted as a massive second health bar.',
      '2024: Target gains Temporary Hit Points equal to the Beast form’s HP. When those temporary HP run out or the spell ends, the form reverts.',
    ],
    tags: ['transmutation', 'beast', 'temp-hp', 'major-rebalance', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a caterpillar cocoon)',
      materialDetails: SpellMaterialComponent(description: 'a caterpillar cocoon'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'This spell transforms a creature with at least 1 hit point that you can see within range into a new form.',
        'An unwilling creature must make a Wisdom saving throw to avoid the effect.',
        'The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target’s CR/level.',
        'The target assumes the hit points of its new form. When it reverts to its normal form, the creature returns to the number of hit points it had before it transformed.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a caterpillar cocoon)',
      materialDetails: SpellMaterialComponent(description: 'a caterpillar cocoon'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'This spell transforms a creature you can see within range into a Beast of equal or lower Challenge Rating.',
        'An unwilling creature must make a Wisdom saving throw to resist.',
        'The target gains Temporary Hit Points equal to the Beast form’s Hit Points. When the Temporary Hit Points drop to 0, the spell ends and the creature reverts to its true form.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_banishment',
    name: 'Banishment',
    level: 4,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Banished creatures now get a repeated saving throw at the end of each of their turns, preventing single-failed-save permanent combat removals.',
    diffHighlights: [
      '2014: Single Charisma save. If failed, banished for full 1-minute concentration. If native to another plane and spell lasts full minute, permanently banished.',
      '2024: Banished target can repeat the Charisma saving throw at the end of each of its turns, ending the spell early on a success.',
    ],
    tags: ['abjuration', 'banish', 'charisma-save', 'concentration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (an item distasteful to the target)',
      materialDetails: SpellMaterialComponent(description: 'an item distasteful to the target'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.paladin, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Charisma',
      description: [
        'You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished.',
        'If the target is native to the plane of existence you’re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left.',
        'If the target is native to a different plane of existence, it is banished there. If the spell lasts for its full duration, the target doesn’t return.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (an item distasteful to the target)',
      materialDetails: SpellMaterialComponent(description: 'an item distasteful to the target'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.paladin, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Charisma',
      description: [
        'You attempt to send one creature within range to another plane of existence. The target must make a Charisma saving throw or be banished.',
        'While banished, the target is Incapacitated. At the end of each of its turns, the target can repeat the save, ending the spell on a success.',
        'If the spell lasts the full 1 minute and the creature is not native to this plane, it remains on its home plane.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_dimension_door',
    name: 'Dimension Door',
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Teleports you and up to one willing creature of your size or smaller up to 500 feet to any location you can describe or visualize.',
    tags: ['teleport', 'escape', 'mobility', 'conjuration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '500 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction.',
        'You can bring along objects as long as their weight doesn’t exceed what you can carry. You can also bring one willing creature of your size or smaller who is carrying gear up to its carrying capacity.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '500 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You teleport yourself and up to one willing creature up to 500 feet to any spot you can see, visualize, or specify by distance and direction.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_greater_invisibility',
    name: 'Greater Invisibility',
    level: 4,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Superior invisibility that does NOT end when the target attacks or casts spells.',
    tags: ['invisible', 'stealth', 'combat', 'concentration', 'illusion', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'You or a creature you touch becomes invisible until the spell ends.',
        'Unlike Invisibility, this spell does not end if the target attacks or casts a spell.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'A creature you touch gains the Invisible condition until the spell ends. It remains invisible even while attacking or casting spells.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_wall_of_fire',
    name: 'Wall of Fire',
    level: 4,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates a blazing wall of fire up to 60 ft long or 20 ft ring dealing 5d8 fire damage on Dexterity save (+1d8 per higher slot).',
    tags: ['fire', 'wall', 'aoe', 'concentration', 'evocation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a small piece of phosphorus)',
      materialDetails: SpellMaterialComponent(description: 'a small piece of phosphorus'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick.',
        'When the wall appears, each creature within its area must make a Dexterity saving throw, taking 5d8 fire damage on a failed save, or half on success.',
        'One side of the wall deals 5d8 fire damage to each creature that ends its turn within 10 feet of that side or inside the wall.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a small piece of phosphorus)',
      materialDetails: SpellMaterialComponent(description: 'a small piece of phosphorus'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'You create a wall of fire up to 60 feet long or a 20-foot ring. Deals 5d8 Fire damage on creation and to creatures ending turns near its heat.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_conjure_minor_elementals',
    name: 'Conjure Minor Elementals',
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Complete redesign: Instead of summoning 1-8 small elementals (like Mephits), it creates a personal elemental shroud that adds 2d8 elemental damage to all your attacks (+2d8 per upcast slot).',
    diffHighlights: [
      '2014: 1 minute casting time, Concentration (1 hr). Summons 1-8 minor elementals (e.g. 8 steam mephits).',
      '2024: 1 Action casting time, Concentration (10 min). Creates a 15-ft emanation of swirling spirits around you. Whenever you hit with an attack roll, you deal an extra 2d8 damage of chosen elemental type (+2d8 per slot level above 4th).',
    ],
    tags: ['elemental', 'buff', 'emanation', 'redesign', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '90 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.wizard],
      description: [
        'You summon elementals that appear in unoccupied spaces that you can see within range.',
        'Choose one option: One elemental of CR 2 or lower, Two elementals of CR 1 or lower, Four elementals of CR 1/2 or lower, or Eight elementals of CR 1/4 or lower.',
        'An elemental summoned by this spell disappears when it drops to 0 hit points or when the spell ends.',
      ],
      higherLevels: 'Slot 6th: twice the creatures. Slot 8th: three times the creatures.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot emanation)',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.wizard],
      rollFormula: '2d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 2),
      damageOrHealType: 'Acid, Cold, Fire, or Lightning',
      description: [
        'You summon spirits of nature that flit around you in a 15-foot Emanation.',
        'Until the spell ends, any attack roll you make deals an extra 2d8 damage of a type chosen from Acid, Cold, Fire, or Lightning on a hit.',
        'The area within the emanation is also Difficult Terrain for your enemies.',
      ],
      higherLevels: 'When cast using a 5th-level slot or higher, the extra damage increases by 2d8 for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_conjure_woodland_beings',
    name: 'Conjure Woodland Beings',
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Complete redesign: Replaces the 8-Pixie polymorph army exploit with a 10-ft aura dealing 5d8 force/radiant damage and enabling Disengage.',
    diffHighlights: [
      '2014: 1 Action, Concentration (1 hr). Summons 1-8 fey creatures (CR 2 down to 8 Pixies with individual spell slots).',
      '2024: 1 Action, Concentration (10 min). Creates a 10-ft emanation that deals 5d8 Force damage on failed Wisdom save (+1d8 per slot level above 4th) and lets you Disengage as a Bonus Action.',
    ],
    tags: ['fey', 'emanation', 'druid', 'ranger', 'redesign', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (one holly berry per creature summoned)',
      materialDetails: SpellMaterialComponent(description: 'one holly berry per creature summoned'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      description: [
        'You summon fey creatures that appear in unoccupied spaces that you can see within range.',
        'Choose one option: One fey creature of CR 2 or lower, Two fey of CR 1 or lower, Four fey of CR 1/2 or lower, or Eight fey of CR 1/4 or lower.',
        'Summoned creatures obey your verbal commands.',
      ],
      higherLevels: 'Slot 6th: twice the creatures. Slot 8th: three times the creatures.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (10-foot emanation)',
      components: 'V, S, M (a sprig of holly)',
      materialDetails: SpellMaterialComponent(description: 'a sprig of holly'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Force',
      savingThrow: 'Wisdom',
      description: [
        'You summon fey spirits that flit around you in a 10-foot Emanation.',
        'When a creature hostile to you enters the emanation for the first time on a turn or ends its turn there, it must make a Wisdom saving throw, taking 5d8 Force damage on a failed save, or half as much on a successful one.',
        'You can also take the Disengage action as a Bonus Action while the spell is active.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_giant_insect',
    name: 'Giant Insect',
    level: 4,
    school: SpellSchool.transmutation,
    isChangedIn2024: true,
    diffSummary: 'Standardized into a single versatile Giant Insect companion stat block with customizable traits (Centipede, Spider, Wasp, Scorpion).',
    tags: ['insect', 'transmutation', 'druid', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid],
      description: [
        'You transform up to ten centipedes, three spiders, five wasps, or one scorpion within range into giant versions of their natural forms.',
        'A centipede becomes a giant centipede, a spider becomes a giant spider, a wasp becomes a giant wasp, and a scorpion becomes a giant scorpion.',
        'The DM will have the statistics for these creatures and resolves their actions and movements.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid],
      description: [
        'You transform an insect within range into a Large Giant Insect.',
        'The creature uses the Giant Insect stat block and takes on traits of a Centipede, Spider, Wasp, or Scorpion.',
        'It is friendly to you and obeys your verbal commands.',
      ],
      higherLevels: 'Using higher spell slots increases the creature’s AC, HP, and damage bonuses.',
    ),
  ),

  SpellItem(
    id: 'spell_death_ward',
    name: 'Death Ward',
    level: 4,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Protects a creature from death for 8 hours without concentration: drops to 1 HP instead of 0 HP on first lethal instance, or negates instant-death effects.',
    tags: ['buff', 'anti-death', 'cheat-death', 'no-concentration', 'cleric', 'paladin', 'abjuration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: '8 hours',
      concentration: false,
      classes: [SpellClass.cleric, SpellClass.paladin],
      description: [
        'You touch a creature and grant it a measure of protection from death. The first time the target would drop to 0 hit points as a result of taking damage, the target instead drops to 1 hit point, and the spell ends.',
        'If the spell is still in effect when the target is subjected to an effect that would kill it instantaneously without dealing damage, that effect is instead negated against the target, and the spell ends.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: '8 hours',
      concentration: false,
      classes: [SpellClass.cleric, SpellClass.paladin],
      description: [
        'Prevents target from dropping to 0 HP (drops to 1 HP instead) or negates an instant-death effect for 8 hours.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_divination',
    name: 'Divination',
    level: 4,
    school: SpellSchool.divination,
    isChangedIn2024: false,
    diffSummary: 'Offers a sacrifice to contact a deity, receiving a cryptic or direct omen concerning a specific goal, event, or activity occurring within 7 days.',
    tags: ['ritual', 'omen', 'future-sight', 'divination', 'costly-component', 'cleric', 'druid', 'wizard', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S, M (incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'incense and sacrificial offering worth 25 gp',
        hasCost: true,
        costInGp: 25,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      ritual: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'Your magic and an offering put you in contact with a god or a god’s servants. You ask a single question concerning a specific goal, event, or activity to occur within 7 days. The DM offers a truthful reply (short phrase, cryptic rhyme, or omen).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S, M (incense and offering worth 25 gp, consumed)',
      materialDetails: SpellMaterialComponent(
        description: 'incense and sacrificial offering worth 25 gp',
        hasCost: true,
        costInGp: 25,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      ritual: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'Contacts deity for an omen or truthful answer regarding events in the next 7 days.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_guardian_of_faith',
    name: 'Guardian of Faith',
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Summons a Large spectral guardian occupying a 10-foot space for 8 hours without concentration that strikes hostile creatures for 20 radiant damage (up to 60 total).',
    tags: ['summon', 'ward', 'radiant', 'no-concentration', 'cleric', 'conjuration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V',
      duration: '8 hours',
      concentration: false,
      classes: [SpellClass.cleric],
      rollFormula: '20',
      damageOrHealType: 'Radiant (20 flat / 10 on save)',
      savingThrow: 'Dexterity',
      description: [
        'A Large spectral guardian appears and hovers for the duration in an unoccupied space of your choice that you can see within range.',
        'Any hostile creature that moves to a space within 10 feet of the guardian for the first time on a turn must succeed on a Dexterity saving throw. The creature takes 20 radiant damage on a failed save, or 10 on success. The guardian vanishes when it has dealt a total of 60 damage.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V',
      duration: '8 hours',
      concentration: false,
      classes: [SpellClass.cleric],
      rollFormula: '20',
      damageOrHealType: 'Radiant',
      savingThrow: 'Dexterity',
      description: [
        'Spectral guardian deals 20 Radiant damage on failed Dexterity save (10 on success) to enemies approaching within 10 ft; lasts 8 hours or 60 total damage.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_freedom_of_movement',
    name: 'Freedom of Movement',
    level: 4,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Grants immunity to paralyzed/restrained conditions, difficult terrain, and movement penalties from water/spells for 1 hour without concentration.',
    tags: ['buff', 'movement', 'paralyze-immunity', 'restrain-immunity', 'no-concentration', 'cleric', 'druid', 'bard', 'ranger', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a strap of leather, wrapped around the arm or a similar limb)',
      materialDetails: SpellMaterialComponent(description: 'a strap of leather'),
      duration: '1 hour',
      concentration: false,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.ranger],
      description: [
        'You touch a willing creature. For the duration, the target’s movement is unaffected by difficult terrain, and spells and other magical effects can neither reduce the target’s speed nor cause the target to be paralyzed or restrained.',
        'The target can also spend 5 feet of movement to automatically escape from nonmagical restraints (such as manacles or a creature’s grapple). Underwater movement and attacks suffer no penalties.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (leather strap)',
      materialDetails: SpellMaterialComponent(description: 'leather strap'),
      duration: '1 hour',
      concentration: false,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.ranger],
      description: [
        'Target ignores Difficult Terrain, immunity to Paralyzed and Restrained conditions, and escapes grapples/restraints for 5 ft of movement.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_blight',
    name: 'Blight',
    level: 4,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Drains moisture and vitality dealing 8d8 necrotic damage on Constitution save (maximizes damage against nonmagical plants).',
    tags: ['necrotic', 'single-target', 'plant-killer', 'druid', 'sorcerer', 'warlock', 'wizard', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '8d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'Necromantic energy washes over a creature within range. The target must make a Constitution saving throw, taking 8d8 necrotic damage on a failed save, or half on success. Has no effect on undead or constructs.',
        'If you target a plant creature or magical plant, it makes the saving throw with disadvantage, and the spell deals maximum damage to it.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '8d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'Deals 8d8 Necrotic damage on failed Constitution save (maximized vs plants).',
      ],
      higherLevels: 'Damage increases by 1d8 per slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_ice_storm',
    name: 'Ice Storm',
    level: 4,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'A hail of rock-hard ice pounds down in a 20-foot radius, 40-foot high cylinder dealing 2d8 bludgeoning and 4d6 cold damage and creating difficult terrain.',
    tags: ['ice', 'cold', 'bludgeoning', 'aoe', 'difficult-terrain', 'evocation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '300 feet (20-foot radius cylinder)',
      components: 'V, S, M (a pinch of dust and a few drops of water)',
      materialDetails: SpellMaterialComponent(description: 'dust and drops of water'),
      duration: 'Instantaneous',
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d8 + 4d6',
      damageOrHealType: 'Bludgeoning & Cold (2d8+4d6)',
      savingThrow: 'Dexterity',
      description: [
        'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder. Each creature in the cylinder takes 2d8 bludgeoning damage and 4d6 cold damage on a failed Dexterity save (half on success). The ground becomes difficult terrain until end of next turn.',
      ],
      higherLevels: 'The bludgeoning damage increases by 1d8 for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '300 feet (20-foot radius cylinder)',
      components: 'V, S, M (dust and water drops)',
      materialDetails: SpellMaterialComponent(description: 'dust and water drops'),
      duration: 'Instantaneous',
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d8 + 4d6',
      damageOrHealType: 'Bludgeoning & Cold',
      savingThrow: 'Dexterity',
      description: [
        'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder. Each creature in the cylinder takes 2d8 bludgeoning damage and 4d6 cold damage on a failed Dexterity save (half on success). The ground becomes difficult terrain until end of next turn.',
      ],
      higherLevels: 'The bludgeoning damage increases by 1d8 for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_black_tentacles',
    name: "Evard's Black Tentacles",
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Squirming black tentacles fill a 20-foot square turning it into difficult terrain: deals 3d6 bludgeoning damage and restrains creatures failing Dexterity save (+3d6 bludgeoning each turn restrained).',
    tags: ['restrain', 'hazard', 'difficult-terrain', 'bludgeoning', 'concentration', 'wizard', 'conjuration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet (20-foot square)',
      components: 'V, S, M (a piece of tentacle from a giant octopus or giant squid)',
      materialDetails: SpellMaterialComponent(description: 'giant octopus or squid tentacle'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.wizard],
      rollFormula: '3d6',
      damageOrHealType: 'Bludgeoning',
      savingThrow: 'Dexterity',
      description: [
        'Squirming, ebony tentacles fill a 20-foot square on ground that you can see within range. For the duration, these tentacles turn the ground into difficult terrain.',
        'When a creature enters the affected area for the first time on a turn or starts its turn there, the creature must succeed on a Dexterity saving throw or take 3d6 bludgeoning damage and be restrained by the tentacles until the spell ends. A creature that starts its turn in the area and is already restrained takes 3d6 bludgeoning damage.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet (20-foot square)',
      components: 'V, S, M (a piece of tentacle from a giant octopus or giant squid)',
      materialDetails: SpellMaterialComponent(description: 'giant octopus or squid tentacle'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.wizard],
      rollFormula: '3d6',
      damageOrHealType: 'Bludgeoning',
      savingThrow: 'Dexterity',
      description: [
        'Squirming, ebony tentacles fill a 20-foot square on ground that you can see within range. For the duration, these tentacles turn the ground into difficult terrain.',
        'When a creature enters the affected area for the first time on a turn or starts its turn there, the creature must succeed on a Dexterity saving throw or take 3d6 bludgeoning damage and be restrained by the tentacles until the spell ends. A creature that starts its turn in the area and is already restrained takes 3d6 bludgeoning damage.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_confusion',
    name: 'Confusion',
    level: 4,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Assaults minds in a 10-foot-radius sphere on failed Wisdom save: d10 roll determines erratic behavior each turn (wander, do nothing, attack nearest creature, or act normally).',
    tags: ['control', 'confusion', 'aoe', 'concentration', 'bard', 'druid', 'sorcerer', 'wizard', 'enchantment', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet (10-foot-radius sphere)',
      components: 'V, S, M (three nut shells)',
      materialDetails: SpellMaterialComponent(description: 'three nut shells'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'This spell assaults and twists creatures’ minds, spawning delusions and uncontrolled actions. Each creature in a 10-foot-radius sphere must succeed on a Wisdom saving throw when you cast this spell or be affected by it.',
        'An affected target can’t take reactions and must roll a d10 at the start of each of its turns: 1 (move random direction), 2-6 (do nothing), 7-8 (melee attack random creature), 9-10 (act normally). Repeat save at end of each turn.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the radius of the sphere increases by 5 feet for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet (10-foot-radius sphere)',
      components: 'V, S, M (three nut shells)',
      materialDetails: SpellMaterialComponent(description: 'three nut shells'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'This spell assaults and twists creatures’ minds, spawning delusions and uncontrolled actions. Each creature in a 10-foot-radius sphere must succeed on a Wisdom saving throw when you cast this spell or be affected by it.',
        'An affected target can’t take reactions and must roll a d10 at the start of each of its turns: 1 (move random direction), 2-6 (do nothing), 7-8 (melee attack random creature), 9-10 (act normally). Repeat save at end of each turn.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the radius of the sphere increases by 5 feet for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_fire_shield',
    name: 'Fire Shield',
    level: 4,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Wreathes yourself in Warm Flames (Cold resistance) or Chill Flames (Fire resistance). Deals 2d8 damage of opposing type whenever a creature hits you with a melee attack within 5 feet. Non-concentration.',
    tags: ['retaliation', 'resistance', 'fire', 'cold', 'non-concentration', 'sorcerer', 'wizard', 'evocation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S, M (a bit of phosphorus or a firefly)',
      materialDetails: SpellMaterialComponent(description: 'phosphorus or a firefly'),
      duration: '10 minutes',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d8',
      damageOrHealType: 'Fire or Cold (on melee hit)',
      description: [
        'Thin and wispy flames wreathe your body for the duration, shedding bright light in a 10-foot radius. You can choose Warm Shield (grants cold resistance and deals 2d8 fire damage to attackers) or Chill Shield (grants fire resistance and deals 2d8 cold damage to attackers).',
        'Whenever a creature within 5 feet of you hits you with a melee attack, the shield erupts with flame dealing 2d8 damage to the attacker.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S, M (a bit of phosphorus or a firefly)',
      materialDetails: SpellMaterialComponent(description: 'phosphorus or a firefly'),
      duration: '10 minutes',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d8',
      damageOrHealType: 'Fire or Cold (on melee hit)',
      description: [
        'Thin and wispy flames wreathe your body for the duration, shedding bright light in a 10-foot radius. You can choose Warm Shield (grants cold resistance and deals 2d8 fire damage to attackers) or Chill Shield (grants fire resistance and deals 2d8 cold damage to attackers).',
        'Whenever a creature within 5 feet of you hits you with a melee attack, the shield erupts with flame dealing 2d8 damage to the attacker.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_phantasmal_killer',
    name: 'Phantasmal Killer',
    level: 4,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Taps into nightmares to create an illusion visible only to the target: target becomes frightened on failed Wisdom save, taking 4d10 psychic damage at the end of each turn until saved.',
    tags: ['fear', 'psychic', 'nightmare', 'concentration', 'bard', 'wizard', 'illusion', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.wizard],
      rollFormula: '4d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 4, diceSides: 10, dicePerSlotLevel: 1),
      damageOrHealType: 'Psychic',
      savingThrow: 'Wisdom',
      description: [
        'You tap into the nightmares of a creature you can see within range and create an illusory manifestation of its deepest fears, visible only to it. The target must make a Wisdom saving throw. On a failed save, the target becomes frightened for the duration.',
        'At the end of each of the target’s turns, the target must succeed on a Wisdom saving throw or take 4d10 psychic damage. On a successful save, the spell ends.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d10 for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.wizard],
      rollFormula: '4d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 4, diceSides: 10, dicePerSlotLevel: 1),
      damageOrHealType: 'Psychic',
      savingThrow: 'Wisdom',
      description: [
        'You tap into the nightmares of a creature you can see within range and create an illusory manifestation of its deepest fears, visible only to it. The target must make a Wisdom saving throw. On a failed save, the target becomes frightened for the duration.',
        'At the end of each of the target’s turns, the target must succeed on a Wisdom saving throw or take 4d10 psychic damage. On a successful save, the spell ends.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d10 for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_resilient_sphere',
    name: "Otiluke's Resilient Sphere",
    level: 4,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Encloses a Large or smaller creature in an impenetrable shimmering sphere of force for 1 minute on failed Dexterity save (immune to all damage and effects from outside, cannot be passed through).',
    tags: ['invulnerable', 'barrier', 'containment', 'concentration', 'artificer', 'wizard', 'evocation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a hemispherical piece of clear crystal and a matching hemispherical piece of gum arabic)',
      materialDetails: SpellMaterialComponent(description: 'crystal and gum arabic hemispheres'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.wizard],
      savingThrow: 'Dexterity',
      description: [
        'A sphere of shimmering force encloses a creature or object of Large size or smaller within range. An unwilling creature must make a Dexterity saving throw. On a failed save, the creature is enclosed for the duration.',
        'Nothing—not physical objects, energy, or other spell effects—can pass through the barrier, in or out, though a creature in the sphere can breathe there. The sphere is immune to all damage, and a creature or object inside can’t be damaged by attacks or effects originating from, or passing through, the outside.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a hemispherical piece of clear crystal and a matching hemispherical piece of gum arabic)',
      materialDetails: SpellMaterialComponent(description: 'crystal and gum arabic hemispheres'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.wizard],
      savingThrow: 'Dexterity',
      description: [
        'A sphere of shimmering force encloses a creature or object of Large size or smaller within range. An unwilling creature must make a Dexterity saving throw. On a failed save, the creature is enclosed for the duration.',
        'Nothing—not physical objects, energy, or other spell effects—can pass through the barrier, in or out, though a creature in the sphere can breathe there. The sphere is immune to all damage, and a creature or object inside can’t be damaged by attacks or effects originating from, or passing through, the outside.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_stoneskin',
    name: 'Stoneskin',
    level: 4,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Touch a willing creature to turn its flesh as hard as stone, granting Resistance to nonmagical bludgeoning, piercing, and slashing damage.',
    tags: ['resistance', 'physical-defense', 'costly-component', 'concentration', 'druid', 'ranger', 'sorcerer', 'wizard', 'artificer', 'transmutation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (diamond dust worth at least 100 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond dust worth 100 gp',
        hasCost: true,
        costInGp: 100,
        isConsumed: true,
      ),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.druid, SpellClass.ranger, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'This spell turns the flesh of a willing creature you touch as hard as stone. Until the spell ends, the target has resistance to nonmagical bludgeoning, piercing, and slashing damage.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (diamond dust worth at least 100 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond dust worth 100 gp',
        hasCost: true,
        costInGp: 100,
        isConsumed: true,
      ),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.druid, SpellClass.ranger, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'This spell turns the flesh of a willing creature you touch as hard as stone. Until the spell ends, the target has resistance to nonmagical bludgeoning, piercing, and slashing damage.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_arcane_eye',
    name: 'Arcane Eye',
    level: 4,
    school: SpellSchool.divination,
    isChangedIn2024: false,
    diffSummary: 'Creates an invisible, floating eye with 30-foot darkvision for 1 hour. Mentally move the eye up to 30 feet as an Action through any opening as small as 1 inch in diameter.',
    tags: ['scouting', 'sensor', 'invisible-eye', 'concentration', 'artificer', 'cleric', 'wizard', 'divination', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a bit of bat fur)',
      materialDetails: SpellMaterialComponent(description: 'a bit of bat fur'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.wizard],
      description: [
        'You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet.',
        'As an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can’t enter another plane of existence. A solid barrier blocks the eye’s movement, but the eye can pass through an opening as small as 1 inch in diameter.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a bit of bat fur)',
      materialDetails: SpellMaterialComponent(description: 'a bit of bat fur'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.wizard],
      description: [
        'You create an invisible, magical eye within range that hovers in the air for the duration. You mentally receive visual information from the eye, which has normal vision and darkvision out to 30 feet.',
        'As an action, you can move the eye up to 30 feet in any direction. There is no limit to how far away from you the eye can move, but it can’t enter another plane of existence. A solid barrier blocks the eye’s movement, but the eye can pass through an opening as small as 1 inch in diameter.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_control_water',
    name: 'Control Water',
    level: 4,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Control water in a 100-foot cube for up to 10 minutes: Flood (raise level 20 ft), Part Water (trench 20 ft wide), Redirect Flow, or Whirlpool (5d8 bludgeoning & trapped).',
    tags: ['water-manipulation', 'flood', 'part-water', 'whirlpool', 'concentration', 'cleric', 'druid', 'wizard', 'transmutation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '300 feet (100-foot cube)',
      components: 'V, S, M (a drop of water and a pinch of dust)',
      materialDetails: SpellMaterialComponent(description: 'water drop and pinch of dust'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'Until the spell ends, you control any freestanding water inside an area you choose that is a cube up to 100 feet on a side.',
        'Modes: Flood (causes water level to rise by up to 20 feet), Part Water (creates a trench through the water up to 20 feet wide), Redirect Flow (directs moving water in any direction), Whirlpool (creates a 25-foot-radius vortex dealing 5d8 bludgeoning damage).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '300 feet (100-foot cube)',
      components: 'V, S, M (a drop of water and a pinch of dust)',
      materialDetails: SpellMaterialComponent(description: 'water drop and pinch of dust'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'Until the spell ends, you control any freestanding water inside an area you choose that is a cube up to 100 feet on a side.',
        'Modes: Flood (causes water level to rise by up to 20 feet), Part Water (creates a trench through the water up to 20 feet wide), Redirect Flow (directs moving water in any direction), Whirlpool (creates a 25-foot-radius vortex dealing 5d8 bludgeoning damage).',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_dominate_beast',
    name: 'Dominate Beast',
    level: 4,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Telepathically control a beast on failed Wisdom save: target is charmed and takes only actions you choose (Advantage on save if fighting you).',
    tags: ['control', 'mind-control', 'beast', 'concentration', 'druid', 'sorcerer', 'enchantment', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer],
      savingThrow: 'Wisdom',
      description: [
        'You attempt to beguile a beast that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration (with advantage if fighting you).',
        'While the beast is charmed, you have a telepathic link with it and can issue commands that it does its best to obey. You can specify a simple course of action or take total and precise control of the target.',
      ],
      higherLevels: '5th level: up to 10 minutes. 6th level: up to 1 hour. 7th level or higher: up to 8 hours.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer],
      savingThrow: 'Wisdom',
      description: [
        'You attempt to beguile a beast that you can see within range. It must succeed on a Wisdom saving throw or be charmed by you for the duration (with advantage if fighting you).',
        'While the beast is charmed, you have a telepathic link with it and can issue commands that it does its best to obey. You can specify a simple course of action or take total and precise control of the target.',
      ],
      higherLevels: '5th level: up to 10 minutes. 6th level: up to 1 hour. 7th level or higher: up to 8 hours.',
    ),
  ),

  SpellItem(
    id: 'spell_locate_creature',
    name: 'Locate Creature',
    level: 4,
    school: SpellSchool.divination,
    isChangedIn2024: false,
    diffSummary: 'Sense the direction to a specific or general creature within 1,000 feet of you as long as running water at least 10 feet wide does not block the path.',
    tags: ['locate', 'tracking', 'search', 'concentration', 'bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard', 'divination', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (1,000 feet)',
      components: 'V, S, M (a bit of hound fur)',
      materialDetails: SpellMaterialComponent(description: 'a bit of hound fur'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.wizard],
      description: [
        'Describe or name a creature that is familiar to you. You sense the direction to the creature’s location, as long as that creature is within 1,000 feet of you. If the creature is in motion, you know the direction of its movement.',
        'This spell can locate a specific creature known to you, or the nearest creature of a specific kind. The spell can’t locate a creature if running water at least 10 feet wide blocks a direct path between you and the creature.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (1,000 feet)',
      components: 'V, S, M (a bit of hound fur)',
      materialDetails: SpellMaterialComponent(description: 'a bit of hound fur'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.wizard],
      description: [
        'Describe or name a creature that is familiar to you. You sense the direction to the creature’s location, as long as that creature is within 1,000 feet of you. If the creature is in motion, you know the direction of its movement.',
        'This spell can locate a specific creature known to you, or the nearest creature of a specific kind. The spell can’t locate a creature if running water at least 10 feet wide blocks a direct path between you and the creature.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_stone_shape',
    name: 'Stone Shape',
    level: 4,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Touch a stone object or section of stone no more than 5 feet in any dimension and shape it into any form suited to your purpose (doorway, coffer, weapon, or idol).',
    tags: ['utility', 'stone-craft', 'breach', 'artificer', 'cleric', 'druid', 'wizard', 'transmutation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (soft clay to be worked into roughly the desired shape)',
      materialDetails: SpellMaterialComponent(description: 'soft clay'),
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension and form it into any shape that suits your purpose.',
        'So, for example, you could shape a large rock into a weapon, idol, or coffer, or make a small passage through a stone wall, as long as the wall is less than 5 feet thick. You could also shape a stone door or its frame to seal the door shut.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (soft clay to be worked into roughly the desired shape)',
      materialDetails: SpellMaterialComponent(description: 'soft clay'),
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'You touch a stone object of Medium size or smaller or a section of stone no more than 5 feet in any dimension and form it into any shape that suits your purpose.',
        'So, for example, you could shape a large rock into a weapon, idol, or coffer, or make a small passage through a stone wall, as long as the wall is less than 5 feet thick. You could also shape a stone door or its frame to seal the door shut.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_fabricate',
    name: 'Fabricate',
    level: 4,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Convert raw materials into products of the same material in 10 minutes (raw wood into bridge, hemp into rope, linen into clothes). Non-magical only.',
    tags: ['crafting', 'construction', 'utility', 'artificer', 'wizard', 'transmutation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '10 minutes',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.wizard],
      description: [
        'You convert raw materials into products of the same material. For example, you can fabricate a wooden bridge from a clump of trees, a rope from a patch of hemp, and clothes from flax or wool.',
        'Choose raw materials that you can see within range. You can fabricate a Large or smaller object (contained within a 10-foot cube). You also need the appropriate artisan’s tools proficiency to craft items requiring a high degree of craftsmanship (such as jewelry, weapons, or armor).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '10 minutes',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.wizard],
      description: [
        'You convert raw materials into products of the same material. For example, you can fabricate a wooden bridge from a clump of trees, a rope from a patch of hemp, and clothes from flax or wool.',
        'Choose raw materials that you can see within range. You can fabricate a Large or smaller object (contained within a 10-foot cube). You also need the appropriate artisan’s tools proficiency to craft items requiring a high degree of craftsmanship (such as jewelry, weapons, or armor).',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_private_sanctum',
    name: "Mordenkainen's Private Sanctum",
    level: 4,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Wards a 100-foot cubic area for 24 hours against sensors, divination, teleportation, planar travel, and sound/vision from outside. Casting daily for 1 year makes it permanent.',
    tags: ['ward', 'anti-scrying', 'teleport-block', 'security', 'artificer', 'wizard', 'abjuration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '10 minutes',
      range: '120 feet',
      components: 'V, S, M (a thin sheet of lead, a piece of opaque glass, a wad of cotton or cloth, and powdered chrysolite)',
      materialDetails: SpellMaterialComponent(description: 'sheet of lead, glass, cotton, chrysolite'),
      duration: '24 hours',
      classes: [SpellClass.artificer, SpellClass.wizard],
      description: [
        'You make a perimeter around an area within range (up to 100 feet on a side) impenetrable to sensors and scrying. Sound can’t pass through the barrier, sensors can’t appear inside, targets inside can’t be targeted by divination, and teleportation or planar travel into/out of the area fails.',
        'Casting this spell on the same spot every day for a year makes this effect permanent.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '10 minutes',
      range: '120 feet',
      components: 'V, S, M (a thin sheet of lead, a piece of opaque glass, a wad of cotton or cloth, and powdered chrysolite)',
      materialDetails: SpellMaterialComponent(description: 'sheet of lead, glass, cotton, chrysolite'),
      duration: '24 hours',
      classes: [SpellClass.artificer, SpellClass.wizard],
      description: [
        'You make a perimeter around an area within range (up to 100 feet on a side) impenetrable to sensors and scrying. Sound can’t pass through the barrier, sensors can’t appear inside, targets inside can’t be targeted by divination, and teleportation or planar travel into/out of the area fails.',
        'Casting this spell on the same spot every day for a year makes this effect permanent.',
      ],
    ),
  ),
];
