import '../spellbook_data.dart';

const List<SpellItem> srdLevel3Spells = [
  SpellItem(
    id: 'spell_counterspell',
    name: 'Counterspell',
    level: 3,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Major redesign: Instead of an ability check vs DC (10 + level), the opposing caster makes a Constitution saving throw. On failure, the spell is wasted.',
    diffHighlights: [
      '2014: Automatic success against 3rd level or lower. For 4th+ level spells, roll an ability check using your spellcasting modifier (DC = 10 + spell’s level).',
      '2024: Target caster makes a Constitution saving throw against your Spell Save DC. On a failure, the spell is interrupted and has no effect, and the spell slot is consumed.',
      'Affects all spell levels equally through the save DC, making High-Constitution enemy bosses harder to counterspell.',
    ],
    tags: ['abjuration', 'reaction', 'counter', 'con-save', 'major-rebalance', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Reaction, which you take when you see a creature within 60 feet of you casting a spell',
      reactionTrigger: 'You see a creature within 60 feet casting a spell',
      range: '60 feet',
      components: 'S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect.',
        'If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell’s level. On a success, the creature’s spell fails and has no effect.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Reaction, which you take when you see a creature within 60 feet of you casting a spell',
      reactionTrigger: 'You see a creature within 60 feet casting a spell',
      range: '60 feet',
      components: 'S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Constitution',
      description: [
        'You attempt to interrupt a creature in the process of casting a spell.',
        'The creature must make a Constitution saving throw against your Spell Save DC. On a failed save, the spell is interrupted and has no effect, and the creature’s action or reaction used to cast the spell is wasted along with any spell slot expended.',
      ],
      higherLevels: 'Casting with higher slots does not alter the saving throw DC.',
    ),
  ),

  SpellItem(
    id: 'spell_spirit_guardians',
    name: 'Spirit Guardians',
    level: 3,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Harmonized damage trigger: Damage triggers once per turn when a creature enters or ends its turn in the area, resolving "double-dipping" movement exploits.',
    diffHighlights: [
      '2014: 15 ft emanation, deals 3d8 Radiant/Necrotic on Wisdom save when target enters area or starts turn there.',
      '2024: 15 ft emanation, clarifies once per turn trigger upon entry or end of turn, dealing 3d8 Radiant/Necrotic damage.',
    ],
    tags: ['cleric', 'aoe', 'radiant', 'necrotic', 'concentration', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot radius)',
      components: 'V, S, M (a holy symbol)',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '3d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant or Necrotic',
      savingThrow: 'Wisdom',
      description: [
        'You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. When you cast this spell, you can designate any number of creatures you can see to be unaffected by it.',
        'An affected creature’s speed is halved in the area, and when the creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, it takes 3d8 radiant damage (if good or neutral) or 3d8 necrotic damage (if evil). Half damage on success.',
      ],
      higherLevels: 'Slot 4th+: Damage increases by 1d8 for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot emanation)',
      components: 'V, S, M (a holy symbol)',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '3d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant or Necrotic',
      savingThrow: 'Wisdom',
      description: [
        'Spirits flit around you in a 15-foot Emanation. You designate creatures to be unaffected. An affected creature’s speed is halved within the emanation.',
        'When a creature enters the emanation for the first time on a turn or ends its turn there, it must make a Wisdom saving throw, taking 3d8 Radiant or Necrotic damage on a failure, or half as much on a success (a creature can take this damage only once per turn).',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_fireball',
    name: 'Fireball',
    level: 3,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'The iconic 8d6 fire AOE remains mechanically identical in 2024 with modernized wording.',
    tags: ['fire', 'aoe', 'damage', 'evocation', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (a tiny ball of bat guano and pitch)',
      materialDetails: SpellMaterialComponent(description: 'a tiny ball of bat guano and pitch'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.',
        'Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.',
        'The fire spreads around corners. It ignites flammable objects in the area that aren’t being worn or carried.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (a ball of bat guano and pitch)',
      materialDetails: SpellMaterialComponent(description: 'a ball of bat guano and pitch'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A bright streak flashes from you to a point you choose within range and blossoms into an explosion of flame.',
        'Each creature in a 20-foot-radius Sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 Fire damage on a failed save, or half as much on a successful one.',
        'The fire spreads around corners and ignites flammable objects in the area that aren’t being worn or carried.',
      ],
      higherLevels: 'Damage increases by 1d6 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_lightning_bolt',
    name: 'Lightning Bolt',
    level: 3,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out dealing 8d6 lightning damage on Dexterity save.',
    tags: ['lightning', 'aoe', 'line', 'damage', 'evocation', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (100-foot line)',
      components: 'V, S, M (a bit of fur and a rod of amber, crystal, or glass)',
      materialDetails: SpellMaterialComponent(description: 'a bit of fur and a rod of amber, crystal, or glass'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Lightning',
      savingThrow: 'Dexterity',
      description: [
        'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose.',
        'Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one.',
        'The lightning ignites flammable objects in the area that aren’t being worn or carried.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (100-foot line)',
      components: 'V, S, M (fur and a rod of amber or crystal)',
      materialDetails: SpellMaterialComponent(description: 'fur and a rod of amber or crystal'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Lightning',
      savingThrow: 'Dexterity',
      description: [
        'A stroke of lightning forming a 100-foot line 5 feet wide deals 8d6 Lightning damage on failed Dexterity save (half on success).',
      ],
      higherLevels: 'Damage increases by 1d6 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_fly',
    name: 'Fly',
    level: 3,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Grants a creature a flying speed of 60 feet for the duration (+1 creature per higher slot).',
    tags: ['flight', 'mobility', 'buff', 'concentration', 'transmutation', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a wing feather from any bird)',
      materialDetails: SpellMaterialComponent(description: 'a wing feather from any bird'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You touch a willing creature. The target gains a flying speed of 60 feet for the duration.',
        'When the spell ends, the target falls if it is still aloft, unless it can stop the fall.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a wing feather)',
      materialDetails: SpellMaterialComponent(description: 'a wing feather'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You touch a willing creature. The target gains a flying speed of 60 feet for the duration.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_haste',
    name: 'Haste',
    level: 3,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Doubles target speed, +2 AC, advantage on Dex saves, and gives an additional action each turn (with 1 round lethargy when it ends).',
    tags: ['speed', 'extra-action', 'ac', 'buff', 'concentration', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a shaving of licorice root)',
      materialDetails: SpellMaterialComponent(description: 'a shaving of licorice root'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Choose a willing creature that you can see within range. Until the spell ends, the target’s speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns.',
        'That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action.',
        'When the spell ends, the target can’t move or take actions until after its next turn, as a wave of lethargy sweeps over it.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a shaving of licorice root)',
      materialDetails: SpellMaterialComponent(description: 'a shaving of licorice root'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Target willing creature doubles speed, gains +2 AC, Advantage on Dexterity saves, and gains an extra action each turn (Attack with 1 strike, Dash, Disengage, Hide, or Utilize). Lethargy triggers when it ends.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_revivify',
    name: 'Revivify',
    level: 3,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Restores life with 1 HP to a creature that died within the last minute (costs 300 gp diamonds).',
    tags: ['revive', 'resurrection', 'life', 'healing', 'costly-component', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (diamonds worth 300 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamonds worth 300 gp, consumed by the spell',
        hasCost: true,
        costInGp: 300,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.cleric, SpellClass.paladin, SpellClass.ranger],
      description: [
        'You touch a creature that has died within the last minute. That creature returns to life with 1 hit point.',
        'This spell can’t return to life a creature that has died of old age, nor can it restore any missing body parts.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (diamonds worth 300+ gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamonds worth 300+ gp, consumed by the spell',
        hasCost: true,
        costInGp: 300,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.cleric, SpellClass.paladin, SpellClass.ranger],
      description: [
        'You touch a creature that died within the last minute. It returns to life with 1 Hit Point. Missing body parts are not restored.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_dispel_magic',
    name: 'Dispel Magic',
    level: 3,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Ends any spell of 3rd level or lower on the target, or requires an ability check vs DC (10 + level) for higher spells.',
    tags: ['dispel', 'anti-magic', 'abjuration', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends.',
        'For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell’s level. On a successful check, the spell ends.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell’s level is equal to or less than the level of the spell slot you used.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For higher level spells, make an ability check against DC (10 + spell’s level).',
      ],
      higherLevels: 'Automatically dispels spells of equal or lower level to the slot expended.',
    ),
  ),

  SpellItem(
    id: 'spell_conjure_animals',
    name: 'Conjure Animals',
    level: 3,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Complete redesign: No longer summons 1-8 individual creature tokens that flood combat initiative. Now creates a 10-ft spiritual pack emanation that deals 3d10 radiant damage on Dexterity save and grants advantage on Opportunity Attacks.',
    diffHighlights: [
      '2014: 1 Action, 60 ft, Concentration (1 hr). Summons 1-8 physical beast stat blocks (e.g. 8 wolves/velociraptors with Pack Tactics) rolling separate initiatives.',
      '2024: 1 Action, 60 ft (10-ft emanation), Concentration (10 min). Summons spectral nature spirits that move with you or to a point. Deals 3d10 Radiant damage on failed Dex save (+1d10 per slot above 3rd). Prevents initiative clutter.',
    ],
    tags: ['summon', 'beasts', 'druid', 'ranger', 'emanation', 'redesign', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      rollFormula: '2d4',
      damageOrHealType: 'Beast Minions',
      description: [
        'You summon fey spirits that take the form of beasts and appear in unoccupied spaces that you can see within range.',
        'Choose one of the following options: One beast of CR 2 or lower, Two beasts of CR 1 or lower, Four beasts of CR 1/2 or lower, or Eight beasts of CR 1/4 or lower.',
        'Each beast is considered fey, and it disappears when it drops to 0 hit points or when the spell ends. The summoned creatures are friendly to you and your companions, roll initiative as a group, and obey verbal commands.',
      ],
      higherLevels: 'Slot 5th: twice the creatures. Slot 7th: three times the creatures. Slot 9th: four times the creatures.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet (10-foot emanation)',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      rollFormula: '3d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 10, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant',
      savingThrow: 'Dexterity',
      description: [
        'You summon spirits of nature that take the form of a pack of spectral animals in a 10-foot-radius Emanation centered on a point you choose within range.',
        'When the emanation appears and whenever a creature hostile to you enters the area for the first time on a turn or ends its turn there, it must make a Dexterity saving throw, taking 3d10 Radiant damage on a failure, or half as much on a success.',
        'Once on your turn, you can move the spirits up to 30 feet to an unoccupied space within range as a Bonus Action.',
      ],
      higherLevels: 'When cast using a 4th-level slot or higher, damage increases by 1d10 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_animate_dead',
    name: 'Animate Dead',
    level: 3,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Classic necromancy spell that creates a Skeleton or Zombie servant from a pile of bones or corpse for 24 hours.',
    tags: ['undead', 'skeleton', 'zombie', 'necromancy', 'minion', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '10 feet',
      components: 'V, S, M (a drop of blood, a piece of flesh, and a pinch of bone dust)',
      materialDetails: SpellMaterialComponent(description: 'a drop of blood, a piece of flesh, and a pinch of bone dust'),
      duration: 'Instantaneous (24 hours control)',
      classes: [SpellClass.cleric, SpellClass.wizard],
      description: [
        'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range.',
        'Your spell imbues the target with a foul mimicry of life, raising it as an undead creature (a skeleton if bones, or a zombie if corpse).',
        'On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you. The creature is under your control for 24 hours, after which you must cast this spell again to reassert control.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you animate or assert control over two additional undead creatures for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: '10 feet',
      components: 'V, S, M (a drop of blood, flesh, and bone dust)',
      materialDetails: SpellMaterialComponent(description: 'a drop of blood, flesh, and bone dust'),
      duration: 'Instantaneous (24 hours control)',
      classes: [SpellClass.cleric, SpellClass.wizard],
      description: [
        'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range.',
        'The spell raises it as a Skeleton (from bones) or Zombie (from corpse).',
        'You can use a Bonus Action to mentally command the creature if it is within 60 feet. Control lasts 24 hours before reassertion is required.',
      ],
      higherLevels: 'Cast with a 4th-level slot or higher to animate or reassert control over two additional undead per slot level above 3rd.',
    ),
  ),
];
