import '../spellbook_data.dart';

const List<SpellItem> srdLevel3Spells = [
  SpellItem(
    id: 'spell_counterspell',
    name: 'Counterspell',
    level: 3,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Major redesign: Instead of an ability check vs DC (10 + level), the opposing caster makes a Constitution saving throw. On failure, the spell is wasted.',
    diffHighlights: [
      '2014: Automatic success against 3rd level or lower. For 4th+ level spells, roll an ability check using your spellcasting modifier (DC = 10 + spell’s level).',
      '2024: Target caster makes a Constitution saving throw against your Spell Save DC. On a failure, the spell is interrupted and has no effect, and the spell slot is consumed.',
      'Affects all spell levels equally through the save DC, making High-Constitution enemy bosses harder to counterspell.',
    ],
    tags: ['abjuration', 'reaction', 'counter', 'con-save', 'major-rebalance', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Reaction, which you take when you see a creature within 60 feet of you casting a spell',
      reactionTrigger: 'You see a creature within 60 feet casting a spell',
      range: '60 feet',
      components: 'S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect.',
        'If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell’s level. On a success, the creature’s spell fails and has no effect.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Reaction, which you take when you see a creature within 60 feet of you casting a spell',
      reactionTrigger: 'You see a creature within 60 feet casting a spell',
      range: '60 feet',
      components: 'S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Constitution',
      description: [
        'You attempt to interrupt a creature in the process of casting a spell.',
        'The creature must make a Constitution saving throw against your Spell Save DC. On a failed save, the spell is interrupted and has no effect, and the creature’s action or reaction used to cast the spell is wasted along with any spell slot expended.',
      ],
      higherLevels: 'Casting with higher slots does not alter the saving throw DC.',
    ),
  ),

  SpellItem(
    id: 'spell_spirit_guardians',
    name: 'Spirit Guardians',
    level: 3,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Harmonized damage trigger: Damage triggers once per turn when a creature enters or ends its turn in the area, resolving "double-dipping" movement exploits.',
    diffHighlights: [
      '2014: 15 ft emanation, deals 3d8 Radiant/Necrotic on Wisdom save when target enters area or starts turn there.',
      '2024: 15 ft emanation, clarifies once per turn trigger upon entry or end of turn, dealing 3d8 Radiant/Necrotic damage.',
    ],
    tags: ['cleric', 'aoe', 'radiant', 'necrotic', 'concentration', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot radius)',
      components: 'V, S, M (a holy symbol)',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '3d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant or Necrotic',
      savingThrow: 'Wisdom',
      description: [
        'You call forth spirits to protect you. They flit around you to a distance of 15 feet for the duration. When you cast this spell, you can designate any number of creatures you can see to be unaffected by it.',
        'An affected creature’s speed is halved in the area, and when the creature enters the area for the first time on a turn or starts its turn there, it must make a Wisdom saving throw. On a failed save, it takes 3d8 radiant damage (if good or neutral) or 3d8 necrotic damage (if evil). Half damage on success.',
      ],
      higherLevels: 'Slot 4th+: Damage increases by 1d8 for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot emanation)',
      components: 'V, S, M (a holy symbol)',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '3d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant or Necrotic',
      savingThrow: 'Wisdom',
      description: [
        'Spirits flit around you in a 15-foot Emanation. You designate creatures to be unaffected. An affected creature’s speed is halved within the emanation.',
        'When a creature enters the emanation for the first time on a turn or ends its turn there, it must make a Wisdom saving throw, taking 3d8 Radiant or Necrotic damage on a failure, or half as much on a success (a creature can take this damage only once per turn).',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_fireball',
    name: 'Fireball',
    level: 3,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'The iconic 8d6 fire AOE remains mechanically identical in 2024 with modernized wording.',
    tags: ['fire', 'aoe', 'damage', 'evocation', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (a tiny ball of bat guano and pitch)',
      materialDetails: SpellMaterialComponent(description: 'a tiny ball of bat guano and pitch'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame.',
        'Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.',
        'The fire spreads around corners. It ignites flammable objects in the area that aren’t being worn or carried.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (a ball of bat guano and pitch)',
      materialDetails: SpellMaterialComponent(description: 'a ball of bat guano and pitch'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A bright streak flashes from you to a point you choose within range and blossoms into an explosion of flame.',
        'Each creature in a 20-foot-radius Sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 Fire damage on a failed save, or half as much on a successful one.',
        'The fire spreads around corners and ignites flammable objects in the area that aren’t being worn or carried.',
      ],
      higherLevels: 'Damage increases by 1d6 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_lightning_bolt',
    name: 'Lightning Bolt',
    level: 3,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out dealing 8d6 lightning damage on Dexterity save.',
    tags: ['lightning', 'aoe', 'line', 'damage', 'evocation', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (100-foot line)',
      components: 'V, S, M (a bit of fur and a rod of amber, crystal, or glass)',
      materialDetails: SpellMaterialComponent(description: 'a bit of fur and a rod of amber, crystal, or glass'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Lightning',
      savingThrow: 'Dexterity',
      description: [
        'A stroke of lightning forming a line 100 feet long and 5 feet wide blasts out from you in a direction you choose.',
        'Each creature in the line must make a Dexterity saving throw. A creature takes 8d6 lightning damage on a failed save, or half as much damage on a successful one.',
        'The lightning ignites flammable objects in the area that aren’t being worn or carried.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (100-foot line)',
      components: 'V, S, M (fur and a rod of amber or crystal)',
      materialDetails: SpellMaterialComponent(description: 'fur and a rod of amber or crystal'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Lightning',
      savingThrow: 'Dexterity',
      description: [
        'A stroke of lightning forming a 100-foot line 5 feet wide deals 8d6 Lightning damage on failed Dexterity save (half on success).',
      ],
      higherLevels: 'Damage increases by 1d6 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_fly',
    name: 'Fly',
    level: 3,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Grants a creature a flying speed of 60 feet for the duration (+1 creature per higher slot).',
    tags: ['flight', 'mobility', 'buff', 'concentration', 'transmutation', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a wing feather from any bird)',
      materialDetails: SpellMaterialComponent(description: 'a wing feather from any bird'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You touch a willing creature. The target gains a flying speed of 60 feet for the duration.',
        'When the spell ends, the target falls if it is still aloft, unless it can stop the fall.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you can target one additional creature for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a wing feather)',
      materialDetails: SpellMaterialComponent(description: 'a wing feather'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You touch a willing creature. The target gains a flying speed of 60 feet for the duration.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_haste',
    name: 'Haste',
    level: 3,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Doubles target speed, +2 AC, advantage on Dex saves, and gives an additional action each turn (with 1 round lethargy when it ends).',
    tags: ['speed', 'extra-action', 'ac', 'buff', 'concentration', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a shaving of licorice root)',
      materialDetails: SpellMaterialComponent(description: 'a shaving of licorice root'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Choose a willing creature that you can see within range. Until the spell ends, the target’s speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns.',
        'That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action.',
        'When the spell ends, the target can’t move or take actions until after its next turn, as a wave of lethargy sweeps over it.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a shaving of licorice root)',
      materialDetails: SpellMaterialComponent(description: 'a shaving of licorice root'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Target willing creature doubles speed, gains +2 AC, Advantage on Dexterity saves, and gains an extra action each turn (Attack with 1 strike, Dash, Disengage, Hide, or Utilize). Lethargy triggers when it ends.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_revivify',
    name: 'Revivify',
    level: 3,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Restores life with 1 HP to a creature that died within the last minute (costs 300 gp diamonds).',
    tags: ['revive', 'resurrection', 'life', 'healing', 'costly-component', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (diamonds worth 300 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamonds worth 300 gp, consumed by the spell',
        hasCost: true,
        costInGp: 300,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.cleric, SpellClass.paladin, SpellClass.ranger],
      description: [
        'You touch a creature that has died within the last minute. That creature returns to life with 1 hit point.',
        'This spell can’t return to life a creature that has died of old age, nor can it restore any missing body parts.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (diamonds worth 300+ gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamonds worth 300+ gp, consumed by the spell',
        hasCost: true,
        costInGp: 300,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.cleric, SpellClass.paladin, SpellClass.ranger],
      description: [
        'You touch a creature that died within the last minute. It returns to life with 1 Hit Point. Missing body parts are not restored.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_dispel_magic',
    name: 'Dispel Magic',
    level: 3,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Ends any spell of 3rd level or lower on the target, or requires an ability check vs DC (10 + level) for higher spells.',
    tags: ['dispel', 'anti-magic', 'abjuration', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends.',
        'For each spell of 4th level or higher on the target, make an ability check using your spellcasting ability. The DC equals 10 + the spell’s level. On a successful check, the spell ends.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you automatically end the effects of a spell on the target if the spell’s level is equal to or less than the level of the spell slot you used.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Choose one creature, object, or magical effect within range. Any spell of 3rd level or lower on the target ends. For higher level spells, make an ability check against DC (10 + spell’s level).',
      ],
      higherLevels: 'Automatically dispels spells of equal or lower level to the slot expended.',
    ),
  ),

  SpellItem(
    id: 'spell_conjure_animals',
    name: 'Conjure Animals',
    level: 3,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Complete redesign: No longer summons 1-8 individual creature tokens that flood combat initiative. Now creates a 10-ft spiritual pack emanation that deals 3d10 radiant damage on Dexterity save and grants advantage on Opportunity Attacks.',
    diffHighlights: [
      '2014: 1 Action, 60 ft, Concentration (1 hr). Summons 1-8 physical beast stat blocks (e.g. 8 wolves/velociraptors with Pack Tactics) rolling separate initiatives.',
      '2024: 1 Action, 60 ft (10-ft emanation), Concentration (10 min). Summons spectral nature spirits that move with you or to a point. Deals 3d10 Radiant damage on failed Dex save (+1d10 per slot above 3rd). Prevents initiative clutter.',
    ],
    tags: ['summon', 'beasts', 'druid', 'ranger', 'emanation', 'redesign', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      rollFormula: '2d4',
      damageOrHealType: 'Beast Minions',
      description: [
        'You summon fey spirits that take the form of beasts and appear in unoccupied spaces that you can see within range.',
        'Choose one of the following options: One beast of CR 2 or lower, Two beasts of CR 1 or lower, Four beasts of CR 1/2 or lower, or Eight beasts of CR 1/4 or lower.',
        'Each beast is considered fey, and it disappears when it drops to 0 hit points or when the spell ends. The summoned creatures are friendly to you and your companions, roll initiative as a group, and obey verbal commands.',
      ],
      higherLevels: 'Slot 5th: twice the creatures. Slot 7th: three times the creatures. Slot 9th: four times the creatures.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet (10-foot emanation)',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      rollFormula: '3d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 10, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant',
      savingThrow: 'Dexterity',
      description: [
        'You summon spirits of nature that take the form of a pack of spectral animals in a 10-foot-radius Emanation centered on a point you choose within range.',
        'When the emanation appears and whenever a creature hostile to you enters the area for the first time on a turn or ends its turn there, it must make a Dexterity saving throw, taking 3d10 Radiant damage on a failure, or half as much on a success.',
        'Once on your turn, you can move the spirits up to 30 feet to an unoccupied space within range as a Bonus Action.',
      ],
      higherLevels: 'When cast using a 4th-level slot or higher, damage increases by 1d10 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_animate_dead',
    name: 'Animate Dead',
    level: 3,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Classic necromancy spell that creates a Skeleton or Zombie servant from a pile of bones or corpse for 24 hours.',
    tags: ['undead', 'skeleton', 'zombie', 'necromancy', 'minion', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '10 feet',
      components: 'V, S, M (a drop of blood, a piece of flesh, and a pinch of bone dust)',
      materialDetails: SpellMaterialComponent(description: 'a drop of blood, a piece of flesh, and a pinch of bone dust'),
      duration: 'Instantaneous (24 hours control)',
      classes: [SpellClass.cleric, SpellClass.wizard],
      description: [
        'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range.',
        'Your spell imbues the target with a foul mimicry of life, raising it as an undead creature (a skeleton if bones, or a zombie if corpse).',
        'On each of your turns, you can use a bonus action to mentally command any creature you made with this spell if the creature is within 60 feet of you. The creature is under your control for 24 hours, after which you must cast this spell again to reassert control.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, you animate or assert control over two additional undead creatures for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: '10 feet',
      components: 'V, S, M (a drop of blood, flesh, and bone dust)',
      materialDetails: SpellMaterialComponent(description: 'a drop of blood, flesh, and bone dust'),
      duration: 'Instantaneous (24 hours control)',
      classes: [SpellClass.cleric, SpellClass.wizard],
      description: [
        'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range.',
        'The spell raises it as a Skeleton (from bones) or Zombie (from corpse).',
        'You can use a Bonus Action to mentally command the creature if it is within 60 feet. Control lasts 24 hours before reassertion is required.',
      ],
      higherLevels: 'Cast with a 4th-level slot or higher to animate or reassert control over two additional undead per slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_beacon_of_hope',
    name: 'Beacon of Hope',
    level: 3,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Grants advantage on Wisdom saves and death saving throws to chosen creatures within 30 feet, and maximizes all healing received.',
    tags: ['buff', 'max-healing', 'death-save-advantage', 'concentration', 'cleric', 'level 3', 'abjuration'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric],
      description: [
        'This spell bestows hope and vitality. Choose any number of creatures within range. For the duration, each target has advantage on Wisdom saving throws and death saving throws, and regains the maximum number of hit points possible from any healing.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric],
      description: [
        'Grants Advantage on Wisdom & Death saving throws, and maximizes all incoming healing dice for chosen allies.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_bestow_curse',
    name: 'Bestow Curse',
    level: 3,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Places a curse on a creature (disadvantage on ability checks/saves of one stat, disadvantage on attacks against you, wasted turns on Wisdom save, or extra 1d8 necrotic damage).',
    tags: ['curse', 'debuff', 'concentration', 'cleric', 'bard', 'wizard', 'level 3', 'necromancy'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'You touch a creature, and that creature must succeed on a Wisdom saving throw or become cursed for the duration of the spell.',
        'Choose the nature of the curse: disadvantage on ability checks and saving throws of one ability score; disadvantage on attack rolls against you; DC save each turn or do nothing; or attacks against target deal extra 1d8 necrotic damage.',
      ],
      higherLevels: '5th/6th level slot: 8 hours (no concentration). 7th/8th: 24 hours (no conc). 9th: until dispelled (no conc).',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Curses target with stat disadvantage, turn skipping, or +1d8 Necrotic damage on attacks on failed Wisdom save.',
      ],
      higherLevels: 'Removes concentration at 5th level or higher and scales duration up to permanent at 9th level.',
    ),
  ),

  SpellItem(
    id: 'spell_daylight',
    name: 'Daylight',
    level: 3,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Sheds bright daylight in a 60-foot radius sphere and dispels any magical darkness created by a spell of 3rd level or lower.',
    tags: ['light', 'darkness-counter', 'evocation', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: '1 hour',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.sorcerer],
      description: [
        'A 60-foot-radius sphere of light spreads out from a point you choose within range. The sphere is bright light and sheds dim light for an additional 60 feet.',
        'If any of this spell’s area overlaps with an area of darkness created by a spell of 3rd level or lower, the spell that created the darkness is dispelled.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: '1 hour',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.sorcerer],
      description: [
        'Creates a 60-foot radius sphere of bright daylight that dispels magical darkness of level 3 or lower.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_mass_healing_word',
    name: 'Mass Healing Word',
    level: 3,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Bonus Action healing spell restoring 2d4 + mod to up to 6 creatures within 60 feet (dice doubled in 2024, Abjuration).',
    diffHighlights: [
      '2014: 1 Bonus Action, Evocation. Restores 1d4 + spellcasting ability modifier.',
      '2024: 1 Bonus Action, Abjuration. Restores 2d4 + spellcasting ability modifier.',
    ],
    tags: ['healing', 'bonus-action', 'group-heal', 'cleric', 'bard', 'level 3'],
    rules2014: SpellEditionDetails(
      schoolOverride: SpellSchool.evocation,
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric],
      rollFormula: '1d4 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 4, dicePerSlotLevel: 1),
      damageOrHealType: 'Healing',
      description: [
        'As you call out words of restoration, up to six creatures of your choice that you can see within range regain hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 4th level or higher, the healing increases by 1d4 for each slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      schoolOverride: SpellSchool.abjuration,
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric],
      rollFormula: '2d4 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 4, dicePerSlotLevel: 2),
      damageOrHealType: 'Healing',
      description: [
        'Up to six creatures of your choice within 60 feet regain 2d4 + spellcasting ability modifier Hit Points.',
      ],
      higherLevels: 'Healing increases by 2d4 for each slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_remove_curse',
    name: 'Remove Curse',
    level: 3,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Instantly ends all curses affecting one creature or object you touch, and breaks attunement to cursed items.',
    tags: ['curse-removal', 'utility', 'cleric', 'paladin', 'warlock', 'wizard', 'abjuration', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.paladin, SpellClass.warlock, SpellClass.wizard],
      description: [
        'At your touch, all curses affecting one creature or object end. If the object is a cursed magic item, its curse remains, but the spell breaks its owner’s attunement to the object so it can be removed or discarded.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.paladin, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Lifts all curses from touched creature or object and breaks attunement to cursed items.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_sending',
    name: 'Sending',
    level: 3,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Sends a short mental message of 25 words or fewer to any creature with whom you are familiar, across any distance or plane (5% chance of failure across planes).',
    tags: ['communication', 'telepathy', 'cross-plane', 'cleric', 'bard', 'wizard', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Unlimited',
      components: 'V, S, M (a short piece of fine copper wire)',
      materialDetails: SpellMaterialComponent(description: 'a short piece of fine copper wire'),
      duration: '1 round',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.wizard],
      description: [
        'You send a short message of twenty-five words or fewer to a creature with which you are familiar. The creature hears the message in its mind, recognizes you as the sender if it knows you, and can answer in a like manner immediately.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Unlimited',
      components: 'V, S, M (fine copper wire)',
      materialDetails: SpellMaterialComponent(description: 'fine copper wire'),
      duration: '1 round',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.wizard],
      description: [
        'Sends 25-word mental message across any distance with an immediate 25-word mental response.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_speak_with_dead',
    name: 'Speak with Dead',
    level: 3,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Grants the semblance of life to a corpse, allowing you to ask it up to 5 questions.',
    tags: ['interrogation', 'corpse', 'divination', 'cleric', 'bard', 'necromancy', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '10 feet',
      components: 'V, S, M (burning incense)',
      materialDetails: SpellMaterialComponent(description: 'burning incense'),
      duration: '10 minutes',
      classes: [SpellClass.bard, SpellClass.cleric],
      description: [
        'You grant the semblance of life and intelligence to a corpse of your choice within range, allowing it to answer the questions you pose. You can ask the corpse up to five questions.',
        'The corpse knows only what it knew in life, including the languages it knew. Answers are usually brief, cryptic, or repetitive.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '10 feet',
      components: 'V, S, M (burning incense)',
      materialDetails: SpellMaterialComponent(description: 'burning incense'),
      duration: '10 minutes',
      classes: [SpellClass.bard, SpellClass.cleric],
      description: [
        'Allows you to ask up to five questions to a deceased corpse.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_glyph_of_warding',
    name: 'Glyph of Warding',
    level: 3,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Inscribes an explosive rune (5d8 damage) or spell glyph storing a spell of 3rd level or lower that triggers upon a condition.',
    tags: ['trap', 'prep', 'store-spell', 'abjuration', 'costly-component', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 hour',
      range: 'Touch',
      components: 'V, S, M (incense and powdered diamond worth at least 200 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'incense and powdered diamond worth 200 gp',
        hasCost: true,
        costInGp: 200,
        isConsumed: true,
      ),
      duration: 'Until dispelled or triggered',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.wizard],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Acid, Cold, Fire, Lightning, or Thunder',
      savingThrow: 'Dexterity',
      description: [
        'When you cast this spell, you inscribe a glyph that harms other creatures, either upon a surface or within an object.',
        'Explosive Runes deal 5d8 damage in a 20-foot sphere on failed Dexterity save. Spell Glyph stores a spell of 3rd level or lower that activates on trigger.',
      ],
      higherLevels: 'Damage increases by 1d8, or stores spell 1 level higher, per slot level above 3rd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 hour',
      range: 'Touch',
      components: 'V, S, M (powdered diamond worth 200 gp, consumed)',
      materialDetails: SpellMaterialComponent(
        description: 'powdered diamond worth 200 gp',
        hasCost: true,
        costInGp: 200,
        isConsumed: true,
      ),
      duration: 'Until triggered',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.wizard],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Elemental / Stored Spell',
      savingThrow: 'Dexterity',
      description: [
        'Magical trap dealing 5d8 elemental damage or releasing a stored spell when triggered.',
      ],
      higherLevels: 'Damage increases by 1d8 per slot level above 3rd.',
    ),
  ),

  SpellItem(
    id: 'spell_slow',
    name: 'Slow',
    level: 3,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Alters time around up to six creatures in a 40-foot cube: halves speed, -2 AC and DEX saves, prevents reactions, and limits actions on failed Wisdom save.',
    tags: ['debuff', 'action-denial', 'aoe', 'concentration', 'sorcerer', 'wizard', 'level 3'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet (40-foot cube)',
      components: 'V, S, M (a drop of molasses)',
      materialDetails: SpellMaterialComponent(description: 'a drop of molasses'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'You alter time around up to six creatures in a 40-foot cube. On a failed Wisdom save: speed is halved, takes -2 penalty to AC and DEX saves, can’t use reactions, and can take either an action or a bonus action on its turn, not both. Spells with 1 action casting time have a 50% chance of being delayed.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet (40-foot cube)',
      components: 'V, S, M (molasses)',
      materialDetails: SpellMaterialComponent(description: 'molasses'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Halves speed, gives -2 AC/DEX saves, and denies Reactions and extra attacks for up to 6 targets on failed Wisdom save.',
      ],
    ),
  ),
];
