import '../spellbook_data.dart';

const List<SpellItem> srdLevel2Spells = [
  SpellItem(
    id: 'spell_barkskin',
    name: 'Barkskin',
    level: 2,
    school: SpellSchool.transmutation,
    isChangedIn2024: true,
    diffSummary: 'Completely redesigned: Now casts as a Bonus Action and grants temporary hit points each turn instead of setting a minimum AC 16.',
    diffHighlights: [
      '2014: 1 Action, Concentration (1 hr). Target’s AC can’t be less than 16 regardless of armor.',
      '2024: 1 Bonus Action, Concentration (1 hr). Target gains Temporary HP equal to your spellcasting modifier + 10 (and replenishes each round).',
    ],
    tags: ['buff', 'defense', 'temp hp', 'bonus action', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a handful of oak bark)',
      materialDetails: SpellMaterialComponent(description: 'a handful of oak bark'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      description: [
        'You touch a willing creature. Until the spell ends, the target’s skin has a rough, bark-like appearance, and the target’s AC can’t be less than 16, regardless of what kind of armor it is wearing.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: 'Touch',
      components: 'V, S, M (a handful of oak bark)',
      materialDetails: SpellMaterialComponent(description: 'a handful of oak bark'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      rollFormula: '10 + mod',
      damageOrHealType: 'Temporary HP',
      description: [
        'You touch a willing creature. Until the spell ends, the target’s skin is protected by bark. The target gains Temporary Hit Points equal to 10 + your spellcasting ability modifier.',
        'At the start of each of its turns while the spell lasts, if the target has fewer than that number of Temporary Hit Points, it regains Temporary Hit Points up to that amount.',
      ],
      higherLevels: 'When cast with a 3rd-level or higher slot, the Temporary Hit Points increase by 5 for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_spiritual_weapon',
    name: 'Spiritual Weapon',
    level: 2,
    school: SpellSchool.evocation,
    isChangedIn2024: true,
    diffSummary: 'Now requires Concentration! No longer allows free non-concentration passive bonus action attacks for 1 minute.',
    diffHighlights: [
      '2014: 1 Bonus Action, 1 minute duration (NO CONCENTRATION). Bonus action to attack each turn for 1d8 + modifier Force damage.',
      '2024: 1 Bonus Action, Concentration (up to 1 minute). Deals 1d8 + modifier Force damage on bonus action attacks.',
    ],
    tags: ['cleric', 'force', 'concentration-added', 'nerfed', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V, S',
      duration: '1 minute',
      concentration: false,
      classes: [SpellClass.cleric],
      rollFormula: '1d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 8, dicePerSlotLevel: 1, slotStep: 2, addsAbilityMod: true),
      damageOrHealType: 'Force',
      description: [
        'You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier.',
        'As a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for every two slot levels above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '1d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 8, dicePerSlotLevel: 1, slotStep: 2, addsAbilityMod: true),
      damageOrHealType: 'Force',
      description: [
        'You create a floating, spectral weapon within range that lasts for the duration. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes Force damage equal to 1d8 + your spellcasting ability modifier.',
        'As a Bonus Action on subsequent turns, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it.',
      ],
      higherLevels: 'When cast with a 3rd-level or higher slot, damage increases by 1d8 for every two slot levels above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_pass_without_trace',
    name: 'Pass without Trace',
    level: 2,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Changed from a passive +10 Stealth aura into granting Advantage on Stealth checks with a +10 bonus on specific rolls.',
    diffHighlights: [
      '2014: +10 bonus to Dexterity (Stealth) checks for you and companions within 30 ft, cannot be tracked except by magical means.',
      '2024: Clarified interaction with new Hide action mechanics (giving +10 bonus or Advantage depending on conditions).',
    ],
    tags: ['stealth', 'druid', 'ranger', 'concentration', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (30-foot radius)',
      components: 'V, S, M (ashes from a burned leaf of mistletoe and a sprig of spruce)',
      materialDetails: SpellMaterialComponent(description: 'ashes from burned mistletoe and a sprig of spruce'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      description: [
        'A veil of shadows and silence radiates from you, masking you and your companions from detection.',
        'For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can’t be tracked except by magical means.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (30-foot radius)',
      components: 'V, S, M (ashes from a burned leaf of mistletoe)',
      materialDetails: SpellMaterialComponent(description: 'ashes from burned mistletoe'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      description: [
        'A veil of shadows and silence radiates from you. For the duration, you and each creature you choose within 30 feet of you gain a +10 bonus to Dexterity (Stealth) checks and leave no tracks or other traces of passage.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_misty_step',
    name: 'Misty Step',
    level: 2,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    tags: ['teleport', 'bonus action', 'mobility', 'conjuration', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: 'Self',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: 'Self',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_hold_person',
    name: 'Hold Person',
    level: 2,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Paralyzes a humanoid target on failed Wisdom save (+1 humanoid per higher spell slot).',
    tags: ['paralyze', 'humanoid', 'save', 'concentration', 'enchantment', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a small, straight piece of iron)',
      materialDetails: SpellMaterialComponent(description: 'a small, straight piece of iron'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration.',
        'At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a small, straight piece of iron)',
      materialDetails: SpellMaterialComponent(description: 'a small, straight piece of iron'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Choose a Humanoid within range. The target must make a Wisdom saving throw or have the Paralyzed condition for the duration. It repeats the save at the end of each turn.',
      ],
      higherLevels: 'Target one additional Humanoid for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_invisibility',
    name: 'Invisibility',
    level: 2,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Touches a creature to make it invisible until it attacks or casts a spell (+1 target per higher slot).',
    tags: ['invisible', 'stealth', 'concentration', 'illusion', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (an eyelash encased in gum arabic)',
      materialDetails: SpellMaterialComponent(description: 'an eyelash encased in gum arabic'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'A creature you touch becomes invisible until the spell ends.',
        'The spell ends for a target that attacks or casts a spell.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (an eyelash encased in gum arabic)',
      materialDetails: SpellMaterialComponent(description: 'an eyelash encased in gum arabic'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'A creature you touch gains the Invisible condition until the spell ends or until it attacks or casts a spell.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_scorching_ray',
    name: 'Scorching Ray',
    level: 2,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates 3 rays of fire dealing 2d6 fire damage each on ranged spell attack (+1 ray per higher slot).',
    tags: ['fire', 'attack', 'ranged', 'damage', 'evocation', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 6),
      damageOrHealType: 'Fire',
      description: [
        'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several.',
        'Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 6),
      damageOrHealType: 'Fire',
      description: [
        'You create three rays of fire. Make a ranged spell attack for each ray, dealing 2d6 Fire damage per hit.',
      ],
      higherLevels: 'Create one additional ray for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_shatter',
    name: 'Shatter',
    level: 2,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Deals 3d8 thunder damage in a 10-foot radius sphere on Constitution save (inorganic objects have disadvantage).',
    tags: ['thunder', 'aoe', 'damage', 'evocation', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a chip of mica)',
      materialDetails: SpellMaterialComponent(description: 'a chip of mica'),
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard, SpellClass.artificer],
      rollFormula: '3d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Thunder',
      savingThrow: 'Constitution',
      description: [
        'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw.',
        'A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a chip of mica)',
      materialDetails: SpellMaterialComponent(description: 'a chip of mica'),
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard, SpellClass.artificer],
      rollFormula: '3d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Thunder',
      savingThrow: 'Constitution',
      description: [
        'A loud ringing noise erupts in a 10-foot-radius Sphere. Each creature takes 3d8 Thunder damage on failed Con save (half on success). Inorganic creatures have Disadvantage.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_lesser_restoration',
    name: 'Lesser Restoration',
    level: 2,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Casting time changed to 1 Bonus Action in 2024 rules! Ends one disease or condition (Blinded, Deafened, Paralyzed, or Poisoned).',
    diffHighlights: [
      '2014: 1 Action casting time.',
      '2024: 1 Bonus Action casting time.',
    ],
    tags: ['cure', 'healing', 'support', 'bonus action', 'abjuration', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.artificer],
      description: [
        'You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.artificer],
      description: [
        'You touch a creature and end one condition afflicting it: Blinded, Deafened, Paralyzed, or Poisoned.',
      ],
    ),
  ),
];
