import '../spellbook_data.dart';

const List<SpellItem> srdLevel6Spells = [
  SpellItem(
    id: 'spell_heal',
    name: 'Heal',
    level: 6,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Restores 70 Hit Points to a target and ends blindness, deafness, and diseases (classified as Abjuration in 2024).',
    tags: ['healing', 'flat-heal', 'cure', 'abjuration', 'level 6'],
    rules2014: SpellEditionDetails(
      schoolOverride: SpellSchool.evocation,
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid],
      damageOrHealType: '70 Hit Points',
      description: [
        'Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points.',
        'This spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 7th level or higher, the amount of healing increases by 10 for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      schoolOverride: SpellSchool.abjuration,
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid],
      damageOrHealType: '70 Hit Points',
      description: [
        'A target creature regains 70 Hit Points. Also ends the Blinded, Deafened, and Poisoned conditions.',
      ],
      higherLevels: 'Healing increases by 10 Hit Points for each slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_harm',
    name: 'Harm',
    level: 6,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Deals 14d6 necrotic damage on Constitution save and reduces maximum HP by the amount taken for 1 hour or until removed.',
    tags: ['necrotic', 'debuff', 'max-hp-reduction', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      rollFormula: '14d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 14, diceSides: 6),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'You unleash a virulent disease on a creature that you can see within range.',
        'The target must make a Constitution saving throw. On a failed save, it takes 14d6 necrotic damage, or half as much on a successful save. The damage can’t reduce the target’s hit points below 1.',
        'If the target fails the saving throw, its hit point maximum is reduced for 1 hour by an amount equal to the necrotic damage it took.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      rollFormula: '14d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 14, diceSides: 6),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'A virulent disease deals 14d6 Necrotic damage on a Constitution save (half on success; cannot reduce below 1 HP). Target’s HP max is reduced by the damage taken for 1 hour.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_heroes_feast',
    name: "Heroes' Feast",
    level: 6,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Brings forth a magnificent feast for up to 12 creatures granting poison immunity, fear immunity, max HP increase (+2d10), and Wisdom save advantage for 24 hours.',
    tags: ['buff', 'feast', 'max-hp', 'immunity', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Self (30-foot radius)',
      components: 'V, S, M (a gem-encrusted bowl worth at least 1,000 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'a gem-encrusted bowl worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: true,
      ),
      duration: 'Instantaneous (24 hours benefits)',
      classes: [SpellClass.cleric, SpellClass.druid],
      description: [
        'You bring forth a magnificent feast that takes 1 hour to consume and disappears at the end of that time. Up to twelve other creatures can partake.',
        'Creatures gain immunity to poison and being frightened, make Wisdom saving throws with advantage, and their hit point maximum increases by 2d10 for 24 hours.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Self (30-foot radius)',
      components: 'V, S, M (a gem-encrusted bowl worth at least 1,000 gp, consumed)',
      materialDetails: SpellMaterialComponent(
        description: 'gem-encrusted bowl worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: true,
      ),
      duration: 'Instantaneous (24 hours benefits)',
      classes: [SpellClass.cleric, SpellClass.druid],
      description: [
        'Partakers gain immunity to Poison and Frightened, Advantage on Wisdom saves, and +2d10 max HP for 24 hours.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_planar_ally',
    name: 'Planar Ally',
    level: 6,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Beseeches an otherworldly celestial, elemental, or fiend to perform a task for payment or service.',
    tags: ['summon', 'negotiation', 'planar', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '10 minutes',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      description: [
        'You beseech an otherworldly entity for aid. The entity sends a celestial, an elemental, or a fiend loyal to it to aid you.',
        'You must negotiate a payment or sacrifice for the ally’s service (typically 100 to 1,000 gp per minute/hour/day depending on the task).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '10 minutes',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      description: [
        'You call upon a cosmic patron to send an extraplanar ally (Celestial, Elemental, or Fiend). You negotiate a price in gold or services for its aid.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_forbiddance',
    name: 'Forbiddance',
    level: 6,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Wards up to 40,000 sq ft against teleportation/planar travel and deals 5d10 radiant or necrotic damage to specified creature types.',
    tags: ['ward', 'anti-teleport', 'ritual', 'radiant', 'necrotic', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Touch',
      components: 'V, S, M (holy water, rare incense, and ruby dust worth at least 1,000 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'holy water, incense, and ruby dust worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: false,
      ),
      duration: '1 day (or permanent if cast every day for 30 days)',
      ritual: true,
      classes: [SpellClass.cleric],
      rollFormula: '5d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 10),
      damageOrHealType: 'Radiant or Necrotic',
      description: [
        'You create a magical ward protecting up to 40,000 square feet of floor space.',
        'Prevents planar travel, portal creation, and teleportation into the area. Deals 5d10 Radiant or Necrotic damage when designated creature types (celestials, elementals, fey, fiends, or undead) enter or start their turn in the area.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Touch',
      components: 'V, S, M (holy water, rare incense, and ruby dust worth 1,000 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'holy water, incense, and ruby dust worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: false,
      ),
      duration: '1 day (or permanent if cast 30 consecutive days)',
      ritual: true,
      classes: [SpellClass.cleric],
      rollFormula: '5d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 10),
      damageOrHealType: 'Radiant or Necrotic',
      description: [
        'Creates an anti-teleportation ward over 40,000 sq ft that damages specified otherworldly creature types for 5d10 Radiant/Necrotic damage.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_word_of_recall',
    name: 'Word of Recall',
    level: 6,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Instantly teleports you and up to 5 willing creatures to a sanctuary dedicated to your deity that you previously designated.',
    tags: ['teleport', 'sanctuary', 'escape', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '5 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      description: [
        'You and up to five willing creatures within 5 feet are instantly teleported to a designated sanctuary previously prepared by casting this spell there.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '5 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      description: [
        'Teleports caster and up to 5 willing allies within 5 ft to your designated holy sanctuary.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_blade_barrier',
    name: 'Blade Barrier',
    level: 6,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates a whirling wall of razor-sharp blades dealing 6d10 slashing damage and providing three-quarters cover.',
    tags: ['wall', 'slashing', 'area-control', 'concentration', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '6d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 6, diceSides: 10),
      damageOrHealType: 'Slashing',
      savingThrow: 'Dexterity',
      description: [
        'You create a vertical wall of whirling, razor-sharp blades made of magical energy up to 100 feet long, 20 feet high, and 5 feet thick (or a 60-ft ring).',
        'Provides three-quarters cover and difficult terrain. Creatures entering or starting their turn in the area take 6d10 slashing damage on a failed Dexterity save (half on success).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '6d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 6, diceSides: 10),
      damageOrHealType: 'Slashing',
      savingThrow: 'Dexterity',
      description: [
        'Whirling blade wall deals 6d10 Slashing damage on Dexterity save, provides 3/4 cover, and is Difficult Terrain.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_find_the_path',
    name: 'Find the Path',
    level: 6,
    school: SpellSchool.divination,
    isChangedIn2024: false,
    diffSummary: 'Reveals the shortest, most direct physical path to a specific known location on the same plane.',
    tags: ['navigation', 'pathfinding', 'divination', 'concentration', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: 'Self',
      components: 'V, S, M (a set of divinatory tools worth 100 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'divinatory tools worth 100 gp',
        hasCost: true,
        costInGp: 100,
        isConsumed: false,
      ),
      duration: 'Concentration, up to 1 day',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      description: [
        'This spell allows you to find the shortest, most direct physical route to a specific fixed location that you are familiar with on the same plane of existence.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: 'Self',
      components: 'V, S, M (divinatory tools worth 100 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'divinatory tools worth 100 gp',
        hasCost: true,
        costInGp: 100,
        isConsumed: false,
      ),
      duration: 'Concentration, up to 1 day',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      description: [
        'Grants knowledge of the most direct route to a known destination on your plane.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_true_seeing',
    name: 'True Seeing',
    level: 6,
    school: SpellSchool.divination,
    isChangedIn2024: false,
    diffSummary: 'Grants truesight out to 120 feet, seeing through normal/magical darkness, illusions, shapechangers, and the Ethereal Plane.',
    tags: ['truesight', 'illusion-counter', 'ethereal', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (an eye ointment worth 250 gp, consumed by the spell)',
      materialDetails: SpellMaterialComponent(
        description: 'eye ointment worth 250 gp',
        hasCost: true,
        costInGp: 250,
        isConsumed: true,
      ),
      duration: '1 hour',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You give a willing creature the ability to see things as they actually are out to a range of 120 feet.',
        'The creature has truesight, notices secret doors hidden by magic, and can see into the Ethereal Plane.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (eye ointment worth 250 gp, consumed)',
      materialDetails: SpellMaterialComponent(
        description: 'eye ointment worth 250 gp',
        hasCost: true,
        costInGp: 250,
        isConsumed: true,
      ),
      duration: '1 hour',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Grants Truesight 120 ft, revealing invisible creatures, illusions, shapechangers, secret doors, and the Ethereal Plane.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_create_undead',
    name: 'Create Undead',
    level: 6,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Animates 3 Ghouls (or Ghasts, Wights, and Mummies with higher spell slots) for 24 hours.',
    tags: ['undead', 'ghoul', 'ghast', 'wight', 'mummy', 'necromancy', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '10 feet',
      components: 'V, S, M (clay pots with grave dirt, brackish water, and 150 gp black onyx per corpse)',
      materialDetails: SpellMaterialComponent(
        description: 'clay pots with grave dirt, brackish water, and 150 gp black onyx per corpse',
        hasCost: true,
        costInGp: 150,
        isConsumed: false,
      ),
      duration: 'Instantaneous (24 hours control)',
      classes: [SpellClass.cleric, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You can cast this spell only at night. Choose up to three corpses within range to become ghouls under your command.',
      ],
      higherLevels: 'Slot 7th: 4 Ghouls. Slot 8th: 5 Ghouls or 2 Ghasts/Wights. Slot 9th: 6 Ghouls, 3 Ghasts/Wights, or 2 Mummies.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: '10 feet',
      components: 'V, S, M (grave dirt, brackish water, and black onyx worth 150+ gp per corpse)',
      materialDetails: SpellMaterialComponent(
        description: 'grave dirt, brackish water, and black onyx worth 150+ gp per corpse',
        hasCost: true,
        costInGp: 150,
        isConsumed: false,
      ),
      duration: 'Instantaneous (24 hours control)',
      classes: [SpellClass.cleric, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Animates up to three corpses into Ghouls under your command for 24 hours.',
      ],
      higherLevels: 'Slot 7th: 4 Ghouls. Slot 8th: 5 Ghouls or 2 Ghasts/Wights. Slot 9th: 6 Ghouls, 3 Ghasts/Wights, or 2 Mummies.',
    ),
  ),

  SpellItem(
    id: 'spell_chain_lightning',
    name: 'Chain Lightning',
    level: 6,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Fires a bolt of lightning dealing 10d8 lightning damage on Dexterity save, arcing to up to 3 additional targets within 30 feet.',
    tags: ['lightning', 'aoe', 'arc', 'damage', 'evocation', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (fur, amber or glass rod, and silver pins)',
      materialDetails: SpellMaterialComponent(description: 'fur, amber/glass rod, and silver pins'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 8),
      damageOrHealType: 'Lightning',
      savingThrow: 'Dexterity',
      description: [
        'Deals 10d8 Lightning damage to primary target and up to 3 secondary targets within 30 feet on failed Dexterity save (half on success).',
      ],
      higherLevels: 'One additional secondary bolt leaps for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (fur, amber rod, and silver pins)',
      materialDetails: SpellMaterialComponent(description: 'fur, amber rod, and silver pins'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 8),
      damageOrHealType: 'Lightning',
      savingThrow: 'Dexterity',
      description: [
        'Deals 10d8 Lightning damage to primary target and up to 3 secondary targets on failed Dexterity save (half on success).',
      ],
      higherLevels: 'One additional secondary bolt leaps for each slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_disintegrate',
    name: 'Disintegrate',
    level: 6,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Deals 10d6 + 40 force damage on Dexterity save; a creature reduced to 0 HP is turned into a pile of fine gray dust.',
    tags: ['force', 'disintegrate', 'high-damage', 'transmutation', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a lodestone and a pinch of dust)',
      materialDetails: SpellMaterialComponent(description: 'a lodestone and a pinch of dust'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d6 + 40',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 6, dicePerSlotLevel: 3, staticBonus: 40),
      damageOrHealType: 'Force',
      savingThrow: 'Dexterity',
      description: [
        'A thin green ray deals 10d6 + 40 force damage on a failed Dexterity save. Turns target to dust if reduced to 0 HP.',
      ],
      higherLevels: 'Damage increases by 3d6 for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a lodestone and a pinch of dust)',
      materialDetails: SpellMaterialComponent(description: 'a lodestone and a pinch of dust'),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d6 + 40',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 6, dicePerSlotLevel: 3, staticBonus: 40),
      damageOrHealType: 'Force',
      savingThrow: 'Dexterity',
      description: [
        'Deals 10d6 + 40 Force damage on a failed Dexterity save. Turns target to dust if reduced to 0 HP.',
      ],
      higherLevels: 'Damage increases by 3d6 for each slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_sunbeam',
    name: 'Sunbeam',
    level: 6,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Unleashes a 60-foot line of radiant sunlight dealing 6d8 radiant damage and blinding targets; can be refired each turn as an Action.',
    tags: ['sunlight', 'radiant', 'blind', 'line', 'concentration', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (60-foot line)',
      components: 'V, S, M (a magnifying glass)',
      materialDetails: SpellMaterialComponent(description: 'a magnifying glass'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '6d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 6, diceSides: 8),
      damageOrHealType: 'Radiant',
      savingThrow: 'Constitution',
      description: [
        'A beam of brilliant light flashes in a 5-foot-wide, 60-foot-long line. Each creature takes 6d8 radiant damage and is blinded on failed Constitution save (half damage and not blinded on success). Undead and oozes have disadvantage.',
        'You can create a new line of radiance as your action on any turn until the spell ends.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (60-foot line)',
      components: 'V, S, M (a magnifying glass)',
      materialDetails: SpellMaterialComponent(description: 'a magnifying glass'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '6d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 6, diceSides: 8),
      damageOrHealType: 'Radiant',
      savingThrow: 'Constitution',
      description: [
        'Fires a 60-ft line dealing 6d8 Radiant damage and Blinded on failed Constitution save. Can fire again on subsequent turns as an Action.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_globe_of_invulnerability',
    name: 'Globe of Invulnerability',
    level: 6,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Creates an immobile 10-foot-radius barrier that completely blocks any spell of 5th level or lower.',
    tags: ['abjuration', 'spell-barrier', 'immunity', 'concentration', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (10-foot-radius sphere)',
      components: 'V, S, M (a glass or crystal bead)',
      materialDetails: SpellMaterialComponent(description: 'a glass or crystal bead'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'An immobile 10-foot-radius sphere surrounds you. Any spell of 5th level or lower cast from outside the barrier can’t affect creatures or objects inside it, even if cast using a higher-level slot.',
      ],
      higherLevels: 'The barrier blocks spells of 1 level higher for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (10-foot-radius sphere)',
      components: 'V, S, M (a glass bead)',
      materialDetails: SpellMaterialComponent(description: 'a glass bead'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Barrier suppresses all spells of 5th level or lower from affecting anyone inside.',
      ],
      higherLevels: 'Blocks spells 1 level higher per slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_mass_suggestion',
    name: 'Mass Suggestion',
    level: 6,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Influences up to twelve creatures within range to pursue a suggested course of activity for up to 24 hours without concentration.',
    tags: ['charm', 'social', 'multi-target', 'no-concentration', 'enchantment', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, M (a snake’s tongue and a honeycomb)',
      materialDetails: SpellMaterialComponent(description: 'a snake’s tongue and honeycomb'),
      duration: '24 hours',
      concentration: false,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'You suggest a course of activity (limited to a sentence or two) to up to twelve creatures within range. Each must make a Wisdom saving throw or follow the suggestion for 24 hours.',
      ],
      higherLevels: 'Slot 7th: 10 days duration. Slot 8th: 30 days duration. Slot 9th: 1 year and 1 day duration.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, M (snake tongue and honeycomb)',
      materialDetails: SpellMaterialComponent(description: 'snake tongue and honeycomb'),
      duration: '24 hours',
      concentration: false,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Up to 12 creatures follow a suggested course of action for 24 hours on failed Wisdom save.',
      ],
      higherLevels: '7th level: 10 days. 8th level: 30 days. 9th level: 1 year and 1 day.',
    ),
  ),

  SpellItem(
    id: 'spell_contingency',
    name: 'Contingency',
    level: 6,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Prepares an emergency contingency spell of 5th level or lower to trigger automatically upon a specified condition.',
    tags: ['contingency', 'prep', 'buff', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Self',
      components: 'V, S, M (a statuette of yourself carved from ivory and decorated with gems worth 1,500 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'ivory statuette with gems worth 1,500 gp',
        hasCost: true,
        costInGp: 1500,
        isConsumed: false,
      ),
      duration: '10 days',
      classes: [SpellClass.wizard],
      description: [
        'Choose a spell of 5th level or lower that you can cast, that has a casting time of 1 action, and that can target you. You cast that spell as part of creating the contingency.',
        'The contingent spell takes effect immediately when the designated trigger occurs.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Self',
      components: 'V, S, M (ivory statuette with gems worth 1,500 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'ivory statuette with gems worth 1,500 gp',
        hasCost: true,
        costInGp: 1500,
        isConsumed: false,
      ),
      duration: '10 days',
      classes: [SpellClass.wizard],
      description: [
        'Stores a 5th-level or lower spell targeting yourself that immediately activates when a set condition occurs.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_eyebite',
    name: 'Eyebite',
    level: 6,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Causes eyes to glow with dark power; can inflict Asleep, Panicked, or Sickened conditions on targets each turn as an Action.',
    tags: ['debuff', 'asleep', 'frightened', 'poisoned', 'concentration', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Your eyes become an inky void. Each turn as an Action, you can target one creature within 60 feet. On a failed Wisdom save, target suffers one effect: Asleep (unconscious), Panicked (frightened and must dash away), or Sickened (poisoned and disadvantage).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Allows targeting a creature each round to impose Asleep, Panicked, or Sickened on a failed Wisdom save.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_flesh_to_stone',
    name: 'Flesh to Stone',
    level: 6,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Restrains a creature and turns it to stone (petrified) after three failed Constitution saving throws.',
    tags: ['petrify', 'restrain', 'concentration', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a pinch of lime, water, and earth)',
      materialDetails: SpellMaterialComponent(description: 'lime, water, and earth'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Constitution',
      description: [
        'You attempt to turn one creature that you can see within range into stone. On a failed Constitution save, it is restrained. It makes saves each turn: 3 successes end it, 3 failures petrify it permanently (if concentration maintained for the full minute).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (lime, water, and earth)',
      materialDetails: SpellMaterialComponent(description: 'lime, water, and earth'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Constitution',
      description: [
        'Restrains and gradually turns a fleshy creature to stone upon 3 failed Constitution saves.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_circle_of_death',
    name: 'Circle of Death',
    level: 6,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'A massive 60-foot radius sphere of negative energy deals 8d6 necrotic damage on a Constitution save.',
    tags: ['necrotic', 'aoe', 'mass-damage', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet (60-foot radius sphere)',
      components: 'V, S, M (the powder of a crushed black pearl worth at least 500 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'powder of a crushed black pearl worth 500 gp',
        hasCost: true,
        costInGp: 500,
        isConsumed: false,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 2),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'A sphere of negative energy ripples out in a 60-foot radius. Each creature must make a Constitution save, taking 8d6 necrotic damage on a failed save, or half on success.',
      ],
      higherLevels: 'Damage increases by 2d6 for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet (60-foot radius sphere)',
      components: 'V, S, M (black pearl worth 500 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'black pearl worth 500 gp',
        hasCost: true,
        costInGp: 500,
        isConsumed: false,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '8d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 6, dicePerSlotLevel: 2),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'Deals 8d6 Necrotic damage in a 60-foot radius on failed Constitution save (half on success).',
      ],
      higherLevels: 'Damage increases by 2d6 per slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_wall_of_ice',
    name: 'Wall of Ice',
    level: 6,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates a wall of solid ice dealing 10d6 cold damage when created, and leaving a freezing cloud dealing 5d6 cold damage if breached.',
    tags: ['ice', 'cold', 'wall', 'concentration', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a piece of quartz)',
      materialDetails: SpellMaterialComponent(description: 'a piece of quartz'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.wizard],
      rollFormula: '10d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 6, dicePerSlotLevel: 2),
      damageOrHealType: 'Cold',
      savingThrow: 'Dexterity',
      description: [
        'You create a wall of ice up to 100 feet long or a 60-foot ring. Creatures in its path take 10d6 cold damage on a failed Dexterity save (half on success). Breaching a section leaves a freezing fog dealing 5d6 cold damage on a Constitution save.',
      ],
      higherLevels: 'Damage increases by 2d6 initial and 1d6 fog for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a piece of quartz)',
      materialDetails: SpellMaterialComponent(description: 'a piece of quartz'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.wizard],
      rollFormula: '10d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 6, dicePerSlotLevel: 2),
      damageOrHealType: 'Cold',
      savingThrow: 'Dexterity',
      description: [
        'Creates an icy wall dealing 10d6 Cold damage upon placement and creates cold fog when destroyed.',
      ],
      higherLevels: 'Damage increases by 2d6 per slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_wall_of_thorns',
    name: 'Wall of Thorns',
    level: 6,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Creates a barrier of pliable, tangled brush with sharp thorns dealing 7d8 piercing damage and 7d8 slashing damage on movement.',
    tags: ['thorns', 'piercing', 'slashing', 'wall', 'concentration', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a handful of thorns)',
      materialDetails: SpellMaterialComponent(description: 'a handful of thorns'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid],
      rollFormula: '7d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 7, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Piercing / Slashing',
      savingThrow: 'Dexterity',
      description: [
        'You create a wall of tough, pliable, tangled brush bristling with needle-sharp thorns up to 60 feet long, 10 feet high, and 5 feet thick. Deals 7d8 piercing damage upon appearing (Dexterity save for half), and 7d8 slashing damage for every 5 feet a creature moves through it.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 6th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a handful of thorns)',
      materialDetails: SpellMaterialComponent(description: 'a handful of thorns'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid],
      rollFormula: '7d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 7, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Piercing / Slashing',
      savingThrow: 'Dexterity',
      description: [
        'Thorn wall deals 7d8 Piercing damage upon placement and 7d8 Slashing damage per 5 ft moved through it.',
      ],
      higherLevels: 'Damage increases by 1d8 per slot level above 6th.',
    ),
  ),

  SpellItem(
    id: 'spell_wind_walk',
    name: 'Wind Walk',
    level: 6,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Transforms you and up to ten willing creatures into gaseous cloud form with a flying speed of 300 feet (approx. 30 mph) for up to 8 hours.',
    tags: ['travel', 'flight', 'gas-form', 'group-buff', 'transmutation', 'level 6'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '30 feet',
      components: 'V, S, M (fire and holy water)',
      materialDetails: SpellMaterialComponent(description: 'fire and holy water'),
      duration: '8 hours',
      classes: [SpellClass.druid],
      description: [
        'You and up to ten willing creatures you can see within range assume a gaseous form for the duration, gaining a flying speed of 300 feet and resistance to nonmagical damage.',
        'Reverting between cloud and solid form takes 1 minute.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: '30 feet',
      components: 'V, S, M (fire and holy water)',
      materialDetails: SpellMaterialComponent(description: 'fire and holy water'),
      duration: '8 hours',
      classes: [SpellClass.druid],
      description: [
        'Transmutes caster and up to 10 willing companions into swift clouds with 300 ft fly speed for 8 hours.',
      ],
    ),
  ),
];
