import '../spellbook_data.dart';

const List<SpellItem> srdLevel2Spells = [
  SpellItem(
    id: 'spell_barkskin',
    name: 'Barkskin',
    level: 2,
    school: SpellSchool.transmutation,
    isChangedIn2024: true,
    diffSummary: 'Completely redesigned: Now casts as a Bonus Action and grants temporary hit points each turn instead of setting a minimum AC 16.',
    diffHighlights: [
      '2014: 1 Action, Concentration (1 hr). Target’s AC can’t be less than 16 regardless of armor.',
      '2024: 1 Bonus Action, Concentration (1 hr). Target gains Temporary HP equal to your spellcasting modifier + 10 (and replenishes each round).',
    ],
    tags: ['buff', 'defense', 'temp hp', 'bonus action', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a handful of oak bark)',
      materialDetails: SpellMaterialComponent(description: 'a handful of oak bark'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      description: [
        'You touch a willing creature. Until the spell ends, the target’s skin has a rough, bark-like appearance, and the target’s AC can’t be less than 16, regardless of what kind of armor it is wearing.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: 'Touch',
      components: 'V, S, M (a handful of oak bark)',
      materialDetails: SpellMaterialComponent(description: 'a handful of oak bark'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      rollFormula: '10 + mod',
      damageOrHealType: 'Temporary HP',
      description: [
        'You touch a willing creature. Until the spell ends, the target’s skin is protected by bark. The target gains Temporary Hit Points equal to 10 + your spellcasting ability modifier.',
        'At the start of each of its turns while the spell lasts, if the target has fewer than that number of Temporary Hit Points, it regains Temporary Hit Points up to that amount.',
      ],
      higherLevels: 'When cast with a 3rd-level or higher slot, the Temporary Hit Points increase by 5 for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_spiritual_weapon',
    name: 'Spiritual Weapon',
    level: 2,
    school: SpellSchool.evocation,
    isChangedIn2024: true,
    diffSummary: 'Now requires Concentration! No longer allows free non-concentration passive bonus action attacks for 1 minute.',
    diffHighlights: [
      '2014: 1 Bonus Action, 1 minute duration (NO CONCENTRATION). Bonus action to attack each turn for 1d8 + modifier Force damage.',
      '2024: 1 Bonus Action, Concentration (up to 1 minute). Deals 1d8 + modifier Force damage on bonus action attacks.',
    ],
    tags: ['cleric', 'force', 'concentration-added', 'nerfed', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V, S',
      duration: '1 minute',
      concentration: false,
      classes: [SpellClass.cleric],
      rollFormula: '1d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 8, dicePerSlotLevel: 1, slotStep: 2, addsAbilityMod: true),
      damageOrHealType: 'Force',
      description: [
        'You create a floating, spectral weapon within range that lasts for the duration or until you cast this spell again. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes force damage equal to 1d8 + your spellcasting ability modifier.',
        'As a bonus action on your turn, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for every two slot levels above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '1d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 8, dicePerSlotLevel: 1, slotStep: 2, addsAbilityMod: true),
      damageOrHealType: 'Force',
      description: [
        'You create a floating, spectral weapon within range that lasts for the duration. When you cast the spell, you can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes Force damage equal to 1d8 + your spellcasting ability modifier.',
        'As a Bonus Action on subsequent turns, you can move the weapon up to 20 feet and repeat the attack against a creature within 5 feet of it.',
      ],
      higherLevels: 'When cast with a 3rd-level or higher slot, damage increases by 1d8 for every two slot levels above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_pass_without_trace',
    name: 'Pass without Trace',
    level: 2,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Changed from a passive +10 Stealth aura into granting Advantage on Stealth checks with a +10 bonus on specific rolls.',
    diffHighlights: [
      '2014: +10 bonus to Dexterity (Stealth) checks for you and companions within 30 ft, cannot be tracked except by magical means.',
      '2024: Clarified interaction with new Hide action mechanics (giving +10 bonus or Advantage depending on conditions).',
    ],
    tags: ['stealth', 'druid', 'ranger', 'concentration', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (30-foot radius)',
      components: 'V, S, M (ashes from a burned leaf of mistletoe and a sprig of spruce)',
      materialDetails: SpellMaterialComponent(description: 'ashes from burned mistletoe and a sprig of spruce'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      description: [
        'A veil of shadows and silence radiates from you, masking you and your companions from detection.',
        'For the duration, each creature you choose within 30 feet of you (including you) has a +10 bonus to Dexterity (Stealth) checks and can’t be tracked except by magical means.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (30-foot radius)',
      components: 'V, S, M (ashes from a burned leaf of mistletoe)',
      materialDetails: SpellMaterialComponent(description: 'ashes from burned mistletoe'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      description: [
        'A veil of shadows and silence radiates from you. For the duration, you and each creature you choose within 30 feet of you gain a +10 bonus to Dexterity (Stealth) checks and leave no tracks or other traces of passage.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_misty_step',
    name: 'Misty Step',
    level: 2,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    tags: ['teleport', 'bonus action', 'mobility', 'conjuration', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: 'Self',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: 'Self',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space you can see.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_hold_person',
    name: 'Hold Person',
    level: 2,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Paralyzes a humanoid target on failed Wisdom save (+1 humanoid per higher spell slot).',
    tags: ['paralyze', 'humanoid', 'save', 'concentration', 'enchantment', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a small, straight piece of iron)',
      materialDetails: SpellMaterialComponent(description: 'a small, straight piece of iron'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Choose a humanoid that you can see within range. The target must succeed on a Wisdom saving throw or be paralyzed for the duration.',
        'At the end of each of its turns, the target can make another Wisdom saving throw. On a success, the spell ends on the target.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional humanoid for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a small, straight piece of iron)',
      materialDetails: SpellMaterialComponent(description: 'a small, straight piece of iron'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'Choose a Humanoid within range. The target must make a Wisdom saving throw or have the Paralyzed condition for the duration. It repeats the save at the end of each turn.',
      ],
      higherLevels: 'Target one additional Humanoid for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_invisibility',
    name: 'Invisibility',
    level: 2,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Touches a creature to make it invisible until it attacks or casts a spell (+1 target per higher slot).',
    tags: ['invisible', 'stealth', 'concentration', 'illusion', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (an eyelash encased in gum arabic)',
      materialDetails: SpellMaterialComponent(description: 'an eyelash encased in gum arabic'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'A creature you touch becomes invisible until the spell ends.',
        'The spell ends for a target that attacks or casts a spell.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (an eyelash encased in gum arabic)',
      materialDetails: SpellMaterialComponent(description: 'an eyelash encased in gum arabic'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'A creature you touch gains the Invisible condition until the spell ends or until it attacks or casts a spell.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_scorching_ray',
    name: 'Scorching Ray',
    level: 2,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates 3 rays of fire dealing 2d6 fire damage each on ranged spell attack (+1 ray per higher slot).',
    tags: ['fire', 'attack', 'ranged', 'damage', 'evocation', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 6),
      damageOrHealType: 'Fire',
      description: [
        'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several.',
        'Make a ranged spell attack for each ray. On a hit, the target takes 2d6 fire damage.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, you create one additional ray for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 6),
      damageOrHealType: 'Fire',
      description: [
        'You create three rays of fire. Make a ranged spell attack for each ray, dealing 2d6 Fire damage per hit.',
      ],
      higherLevels: 'Create one additional ray for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_shatter',
    name: 'Shatter',
    level: 2,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Deals 3d8 thunder damage in a 10-foot radius sphere on Constitution save (inorganic objects have disadvantage).',
    tags: ['thunder', 'aoe', 'damage', 'evocation', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a chip of mica)',
      materialDetails: SpellMaterialComponent(description: 'a chip of mica'),
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard, SpellClass.artificer],
      rollFormula: '3d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Thunder',
      savingThrow: 'Constitution',
      description: [
        'A sudden loud ringing noise, painfully intense, erupts from a point of your choice within range. Each creature in a 10-foot-radius sphere centered on that point must make a Constitution saving throw.',
        'A creature takes 3d8 thunder damage on a failed save, or half as much damage on a successful one. A creature made of inorganic material such as stone, crystal, or metal has disadvantage on this saving throw.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, the damage increases by 1d8 for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a chip of mica)',
      materialDetails: SpellMaterialComponent(description: 'a chip of mica'),
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard, SpellClass.artificer],
      rollFormula: '3d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Thunder',
      savingThrow: 'Constitution',
      description: [
        'A loud ringing noise erupts in a 10-foot-radius Sphere. Each creature takes 3d8 Thunder damage on failed Con save (half on success). Inorganic creatures have Disadvantage.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_lesser_restoration',
    name: 'Lesser Restoration',
    level: 2,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Casting time changed to 1 Bonus Action in 2024 rules! Ends one disease or condition (Blinded, Deafened, Paralyzed, or Poisoned).',
    diffHighlights: [
      '2014: 1 Action casting time.',
      '2024: 1 Bonus Action casting time.',
    ],
    tags: ['cure', 'healing', 'support', 'bonus action', 'abjuration', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.artificer],
      description: [
        'You touch a creature and can end either one disease or one condition afflicting it. The condition can be blinded, deafened, paralyzed, or poisoned.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.artificer],
      description: [
        'You touch a creature and end one condition afflicting it: Blinded, Deafened, Paralyzed, or Poisoned.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_aid',
    name: 'Aid',
    level: 2,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Bolsters up to three allies within 30 feet, increasing both their current and maximum Hit Points by 5 for 8 hours without concentration.',
    tags: ['buff', 'max-hp', 'healing', 'no-concentration', 'cleric', 'paladin', 'level 2', 'abjuration'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a tiny strip of white cloth)',
      materialDetails: SpellMaterialComponent(description: 'a tiny strip of white cloth'),
      duration: '8 hours',
      classes: [SpellClass.artificer, SpellClass.cleric, SpellClass.paladin],
      damageOrHealType: 'Max HP (+5)',
      description: [
        'Your spell bolsters your allies with toughness and resolve. Choose up to three creatures within range. Each target’s hit point maximum and current hit points increase by 5 for the duration.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 3rd level or higher, a target’s hit points increase by an additional 5 for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (white cloth)',
      materialDetails: SpellMaterialComponent(description: 'white cloth'),
      duration: '8 hours',
      classes: [SpellClass.artificer, SpellClass.cleric, SpellClass.paladin],
      damageOrHealType: 'Max HP (+5)',
      description: [
        'Increases current and max Hit Points of up to 3 allies by 5 for 8 hours.',
      ],
      higherLevels: 'Hit Points increase by +5 per slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_prayer_of_healing',
    name: 'Prayer of Healing',
    level: 2,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Heals up to 6 creatures for 2d8 + mod (redesigned in 2024 as an Abjuration spell granting Short Rest benefits in 10 minutes).',
    diffHighlights: [
      '2014: 10 minutes casting time, Evocation. Restores 2d8 + spellcasting mod to up to 6 creatures.',
      '2024: 10 minutes casting time, Abjuration. Affected creatures gain the benefits of a Short Rest and heal.',
    ],
    tags: ['healing', 'group-heal', 'short-rest', 'cleric', 'level 2'],
    rules2014: SpellEditionDetails(
      schoolOverride: SpellSchool.evocation,
      castingTime: '10 minutes',
      range: '30 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      rollFormula: '2d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Healing',
      description: [
        'Up to six creatures of your choice that you can see within range each regain hit points equal to 2d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
      ],
      higherLevels: 'Healing increases by 1d8 for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      schoolOverride: SpellSchool.abjuration,
      castingTime: '10 minutes',
      range: '30 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      rollFormula: '2d8 + mod',
      damageOrHealType: 'Healing & Short Rest',
      description: [
        'Heals up to 6 creatures for 2d8 + mod and confers the benefits of a Short Rest.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_silence',
    name: 'Silence',
    level: 2,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Creates a 20-foot radius sphere of total silence: no sound can pass, creatures inside are immune to thunder damage and deafened, and spells requiring verbal components cannot be cast.',
    tags: ['anti-caster', 'stealth', 'ritual', 'concentration', 'cleric', 'bard', 'ranger', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet (20-foot radius sphere)',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      ritual: true,
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.ranger],
      description: [
        'For the duration, no sound can be created within or pass through a 20-foot-radius sphere centered on a point you choose within range.',
        'Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet (20-foot radius sphere)',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      ritual: true,
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.ranger],
      description: [
        'Mutes all sound in a 20-ft radius sphere, granting immunity to Thunder damage and completely preventing Verbal spellcasting.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_blindness_deafness',
    name: 'Blindness/Deafness',
    level: 2,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Inflicts either the Blinded or Deafened condition on a foe for 1 minute on a failed Constitution save without requiring concentration.',
    tags: ['debuff', 'blind', 'deaf', 'no-concentration', 'cleric', 'bard', 'sorcerer', 'wizard', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V',
      duration: '1 minute',
      concentration: false,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Constitution',
      description: [
        'You can blind or deafen a foe. Choose one creature that you can see within range to make a Constitution saving throw. If it fails, the target is either blinded or deafened (your choice) for the duration. At the end of each of its turns, the target can make a Constitution save to end the spell.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V',
      duration: '1 minute',
      concentration: false,
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Constitution',
      description: [
        'Inflicts Blinded or Deafened condition on failed Constitution save (repeats save at end of each turn).',
      ],
      higherLevels: 'Target +1 creature per slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_enhance_ability',
    name: 'Enhance Ability',
    level: 2,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Bestows magical enhancement: Bear’s Endurance (+2d6 temp HP), Bull’s Strength (advantage STR), Cat’s Grace (advantage DEX), Eagle’s Splendor (advantage CHA), Fox’s Cunning (advantage INT), or Owl’s Wisdom (advantage WIS).',
    tags: ['buff', 'advantage-checks', 'temp-hp', 'concentration', 'cleric', 'druid', 'bard', 'sorcerer', 'wizard', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (fur or a feather from a beast)',
      materialDetails: SpellMaterialComponent(description: 'fur or a feather from a beast'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'You touch a creature and bestow upon it a magical enhancement (Bear’s Endurance, Bull’s Strength, Cat’s Grace, Eagle’s Splendor, Fox’s Cunning, or Owl’s Wisdom), granting advantage on chosen ability checks and temporary hit points for Bear’s Endurance.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (beast fur/feather)',
      materialDetails: SpellMaterialComponent(description: 'beast fur/feather'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Grants Advantage on chosen ability checks and bonus temp HP for up to 1 hour.',
      ],
      higherLevels: 'Target +1 creature per slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_warding_bond',
    name: 'Warding Bond',
    level: 2,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Creates a mystic bond with a willing ally: grants +1 AC, +1 to all saves, and resistance to all damage, while you take the exact same damage they take.',
    tags: ['buff', 'damage-share', 'resistance', 'ac-bonus', 'cleric', 'abjuration', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a pair of platinum rings worth at least 50 gp each, which you and the target must wear for the duration)',
      materialDetails: SpellMaterialComponent(
        description: 'pair of platinum rings worth 50 gp each',
        hasCost: true,
        costInGp: 100,
        isConsumed: false,
      ),
      duration: '1 hour',
      classes: [SpellClass.cleric],
      description: [
        'This spell wards a willing creature you touch and creates a mystic connection between you and the target until the spell ends.',
        'While the target is within 60 feet of you, it gains a +1 bonus to AC and saving throws, and it has resistance to all damage. Each time it takes damage, you take the same amount of damage.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (pair of platinum rings worth 50 gp each)',
      materialDetails: SpellMaterialComponent(
        description: 'pair of platinum rings worth 50 gp each',
        hasCost: true,
        costInGp: 100,
        isConsumed: false,
      ),
      duration: '1 hour',
      classes: [SpellClass.cleric],
      description: [
        'Grants ally +1 AC, +1 saves, and Resistance to all damage while within 60 ft; you suffer equal shared damage.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_heat_metal',
    name: 'Heat Metal',
    level: 2,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Heats a metal object red-hot dealing 2d8 fire damage and forcing creature to drop it or suffer disadvantage on attacks/ability checks; can trigger as Bonus Action each turn.',
    tags: ['fire', 'anti-metal', 'bonus-action-trigger', 'concentration', 'druid', 'bard', 'artificer', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a piece of iron and a flame)',
      materialDetails: SpellMaterialComponent(description: 'a piece of iron and a flame'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.druid],
      rollFormula: '2d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Constitution',
      description: [
        'Choose a manufactured metal object within range. Any creature in physical contact with the object takes 2d8 fire damage. You can use a bonus action on each subsequent turn to cause this damage again.',
        'If a creature is holding or wearing the object and takes the damage, it must make a Constitution save or drop the object if possible; if it doesn’t drop it, it has disadvantage on attack rolls and ability checks until start of your next turn.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (iron and flame)',
      materialDetails: SpellMaterialComponent(description: 'iron and flame'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.druid],
      rollFormula: '2d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Constitution',
      description: [
        'Heats metal dealing 2d8 Fire damage and imposing Disadvantage or forcing target to drop it. Refire with Bonus Action.',
      ],
      higherLevels: 'Damage increases by 1d8 per slot level above 2nd.',
    ),
  ),

  SpellItem(
    id: 'spell_moonbeam',
    name: 'Moonbeam',
    level: 2,
    school: SpellSchool.evocation,
    isChangedIn2024: true,
    diffSummary: 'Calls down a 5-foot-radius cylinder of silvery moonlight dealing 2d10 radiant damage on Constitution save and forcing shapechangers back to true form.',
    diffHighlights: [
      '2014: 1 Action, Concentration up to 1 minute. Deals damage when a creature enters the area on a turn or starts its turn there.',
      '2024: 1 Action, Concentration up to 1 minute. Triggers damage when entering or moving the cylinder onto a creature.',
    ],
    tags: ['radiant', 'moonlight', 'shapechanger-counter', 'concentration', 'druid', 'level 2'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet (5-foot-radius cylinder)',
      components: 'V, S, M (several seeds of any moonseed plant and a piece of opalescent feldspar)',
      materialDetails: SpellMaterialComponent(description: 'moonseed seeds and feldspar'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid],
      rollFormula: '2d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 10, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant',
      savingThrow: 'Constitution',
      description: [
        'A silvery beam of pale light shines down in a 5-foot-radius, 40-foot-high cylinder. Deals 2d10 radiant damage on failed Constitution save (half on success). Shapechangers make save with disadvantage and revert to original form on failure.',
        'You can move the beam up to 60 feet in any direction as an action.',
      ],
      higherLevels: 'Damage increases by 1d10 for each slot level above 2nd.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet (5-foot-radius cylinder)',
      components: 'V, S, M (feldspar)',
      materialDetails: SpellMaterialComponent(description: 'feldspar'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid],
      rollFormula: '2d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 10, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant',
      savingThrow: 'Constitution',
      description: [
        'Silvery light cylinder deals 2d10 Radiant damage on failed Constitution save and reverts shapechangers to original form.',
      ],
      higherLevels: 'Damage increases by 1d10 per slot level above 2nd.',
    ),
  ),
];
