import '../spellbook_data.dart';

const List<SpellItem> srdLevel4Spells = [
  SpellItem(
    id: 'spell_polymorph',
    name: 'Polymorph',
    level: 4,
    school: SpellSchool.transmutation,
    isChangedIn2024: true,
    diffSummary: 'Changed from giving a fresh full pool of Beast HP into giving Temporary Hit Points based on the new form.',
    diffHighlights: [
      '2014: Target takes on the beast’s full HP. Damage dealt first reduces the beast’s HP; excess damage carries over to the original form. Acted as a massive second health bar.',
      '2024: Target gains Temporary Hit Points equal to the Beast form’s HP. When those temporary HP run out or the spell ends, the form reverts.',
    ],
    tags: ['transmutation', 'beast', 'temp-hp', 'major-rebalance', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a caterpillar cocoon)',
      materialDetails: SpellMaterialComponent(description: 'a caterpillar cocoon'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'This spell transforms a creature with at least 1 hit point that you can see within range into a new form.',
        'An unwilling creature must make a Wisdom saving throw to avoid the effect.',
        'The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target’s CR/level.',
        'The target assumes the hit points of its new form. When it reverts to its normal form, the creature returns to the number of hit points it had before it transformed.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a caterpillar cocoon)',
      materialDetails: SpellMaterialComponent(description: 'a caterpillar cocoon'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Wisdom',
      description: [
        'This spell transforms a creature you can see within range into a Beast of equal or lower Challenge Rating.',
        'An unwilling creature must make a Wisdom saving throw to resist.',
        'The target gains Temporary Hit Points equal to the Beast form’s Hit Points. When the Temporary Hit Points drop to 0, the spell ends and the creature reverts to its true form.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_banishment',
    name: 'Banishment',
    level: 4,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Banished creatures now get a repeated saving throw at the end of each of their turns, preventing single-failed-save permanent combat removals.',
    diffHighlights: [
      '2014: Single Charisma save. If failed, banished for full 1-minute concentration. If native to another plane and spell lasts full minute, permanently banished.',
      '2024: Banished target can repeat the Charisma saving throw at the end of each of its turns, ending the spell early on a success.',
    ],
    tags: ['abjuration', 'banish', 'charisma-save', 'concentration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (an item distasteful to the target)',
      materialDetails: SpellMaterialComponent(description: 'an item distasteful to the target'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.paladin, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Charisma',
      description: [
        'You attempt to send one creature that you can see within range to another plane of existence. The target must succeed on a Charisma saving throw or be banished.',
        'If the target is native to the plane of existence you’re on, you banish the target to a harmless demiplane. While there, the target is incapacitated. The target remains there until the spell ends, at which point the target reappears in the space it left.',
        'If the target is native to a different plane of existence, it is banished there. If the spell lasts for its full duration, the target doesn’t return.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (an item distasteful to the target)',
      materialDetails: SpellMaterialComponent(description: 'an item distasteful to the target'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.paladin, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Charisma',
      description: [
        'You attempt to send one creature within range to another plane of existence. The target must make a Charisma saving throw or be banished.',
        'While banished, the target is Incapacitated. At the end of each of its turns, the target can repeat the save, ending the spell on a success.',
        'If the spell lasts the full 1 minute and the creature is not native to this plane, it remains on its home plane.',
      ],
      higherLevels: 'Target one additional creature for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_dimension_door',
    name: 'Dimension Door',
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Teleports you and up to one willing creature of your size or smaller up to 500 feet to any location you can describe or visualize.',
    tags: ['teleport', 'escape', 'mobility', 'conjuration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '500 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You teleport yourself from your current location to any other spot within range. You arrive at exactly the spot desired. It can be a place you can see, one you can visualize, or one you can describe by stating distance and direction.',
        'You can bring along objects as long as their weight doesn’t exceed what you can carry. You can also bring one willing creature of your size or smaller who is carrying gear up to its carrying capacity.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '500 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You teleport yourself and up to one willing creature up to 500 feet to any spot you can see, visualize, or specify by distance and direction.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_greater_invisibility',
    name: 'Greater Invisibility',
    level: 4,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Superior invisibility that does NOT end when the target attacks or casts spells.',
    tags: ['invisible', 'stealth', 'combat', 'concentration', 'illusion', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'You or a creature you touch becomes invisible until the spell ends.',
        'Unlike Invisibility, this spell does not end if the target attacks or casts a spell.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'A creature you touch gains the Invisible condition until the spell ends. It remains invisible even while attacking or casting spells.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_wall_of_fire',
    name: 'Wall of Fire',
    level: 4,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates a blazing wall of fire up to 60 ft long or 20 ft ring dealing 5d8 fire damage on Dexterity save (+1d8 per higher slot).',
    tags: ['fire', 'wall', 'aoe', 'concentration', 'evocation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a small piece of phosphorus)',
      materialDetails: SpellMaterialComponent(description: 'a small piece of phosphorus'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'You create a wall of fire on a solid surface within range. You can make the wall up to 60 feet long, 20 feet high, and 1 foot thick, or a ringed wall up to 20 feet in diameter, 20 feet high, and 1 foot thick.',
        'When the wall appears, each creature within its area must make a Dexterity saving throw, taking 5d8 fire damage on a failed save, or half on success.',
        'One side of the wall deals 5d8 fire damage to each creature that ends its turn within 10 feet of that side or inside the wall.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 5th level or higher, the damage increases by 1d8 for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S, M (a small piece of phosphorus)',
      materialDetails: SpellMaterialComponent(description: 'a small piece of phosphorus'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'You create a wall of fire up to 60 feet long or a 20-foot ring. Deals 5d8 Fire damage on creation and to creatures ending turns near its heat.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_conjure_minor_elementals',
    name: 'Conjure Minor Elementals',
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Complete redesign: Instead of summoning 1-8 small elementals (like Mephits), it creates a personal elemental shroud that adds 2d8 elemental damage to all your attacks (+2d8 per upcast slot).',
    diffHighlights: [
      '2014: 1 minute casting time, Concentration (1 hr). Summons 1-8 minor elementals (e.g. 8 steam mephits).',
      '2024: 1 Action casting time, Concentration (10 min). Creates a 15-ft emanation of swirling spirits around you. Whenever you hit with an attack roll, you deal an extra 2d8 damage of chosen elemental type (+2d8 per slot level above 4th).',
    ],
    tags: ['elemental', 'buff', 'emanation', 'redesign', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '90 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.wizard],
      description: [
        'You summon elementals that appear in unoccupied spaces that you can see within range.',
        'Choose one option: One elemental of CR 2 or lower, Two elementals of CR 1 or lower, Four elementals of CR 1/2 or lower, or Eight elementals of CR 1/4 or lower.',
        'An elemental summoned by this spell disappears when it drops to 0 hit points or when the spell ends.',
      ],
      higherLevels: 'Slot 6th: twice the creatures. Slot 8th: three times the creatures.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot emanation)',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.wizard],
      rollFormula: '2d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 2),
      damageOrHealType: 'Acid, Cold, Fire, or Lightning',
      description: [
        'You summon spirits of nature that flit around you in a 15-foot Emanation.',
        'Until the spell ends, any attack roll you make deals an extra 2d8 damage of a type chosen from Acid, Cold, Fire, or Lightning on a hit.',
        'The area within the emanation is also Difficult Terrain for your enemies.',
      ],
      higherLevels: 'When cast using a 5th-level slot or higher, the extra damage increases by 2d8 for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_conjure_woodland_beings',
    name: 'Conjure Woodland Beings',
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Complete redesign: Replaces the 8-Pixie polymorph army exploit with a 10-ft aura dealing 5d8 force/radiant damage and enabling Disengage.',
    diffHighlights: [
      '2014: 1 Action, Concentration (1 hr). Summons 1-8 fey creatures (CR 2 down to 8 Pixies with individual spell slots).',
      '2024: 1 Action, Concentration (10 min). Creates a 10-ft emanation that deals 5d8 Force damage on failed Wisdom save (+1d8 per slot level above 4th) and lets you Disengage as a Bonus Action.',
    ],
    tags: ['fey', 'emanation', 'druid', 'ranger', 'redesign', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (one holly berry per creature summoned)',
      materialDetails: SpellMaterialComponent(description: 'one holly berry per creature summoned'),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      description: [
        'You summon fey creatures that appear in unoccupied spaces that you can see within range.',
        'Choose one option: One fey creature of CR 2 or lower, Two fey of CR 1 or lower, Four fey of CR 1/2 or lower, or Eight fey of CR 1/4 or lower.',
        'Summoned creatures obey your verbal commands.',
      ],
      higherLevels: 'Slot 6th: twice the creatures. Slot 8th: three times the creatures.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (10-foot emanation)',
      components: 'V, S, M (a sprig of holly)',
      materialDetails: SpellMaterialComponent(description: 'a sprig of holly'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.ranger],
      rollFormula: '5d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 5, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Force',
      savingThrow: 'Wisdom',
      description: [
        'You summon fey spirits that flit around you in a 10-foot Emanation.',
        'When a creature hostile to you enters the emanation for the first time on a turn or ends its turn there, it must make a Wisdom saving throw, taking 5d8 Force damage on a failed save, or half as much on a successful one.',
        'You can also take the Disengage action as a Bonus Action while the spell is active.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_giant_insect',
    name: 'Giant Insect',
    level: 4,
    school: SpellSchool.transmutation,
    isChangedIn2024: true,
    diffSummary: 'Standardized into a single versatile Giant Insect companion stat block with customizable traits (Centipede, Spider, Wasp, Scorpion).',
    tags: ['insect', 'transmutation', 'druid', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid],
      description: [
        'You transform up to ten centipedes, three spiders, five wasps, or one scorpion within range into giant versions of their natural forms.',
        'A centipede becomes a giant centipede, a spider becomes a giant spider, a wasp becomes a giant wasp, and a scorpion becomes a giant scorpion.',
        'The DM will have the statistics for these creatures and resolves their actions and movements.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.druid],
      description: [
        'You transform an insect within range into a Large Giant Insect.',
        'The creature uses the Giant Insect stat block and takes on traits of a Centipede, Spider, Wasp, or Scorpion.',
        'It is friendly to you and obeys your verbal commands.',
      ],
      higherLevels: 'Using higher spell slots increases the creature’s AC, HP, and damage bonuses.',
    ),
  ),

  SpellItem(
    id: 'spell_death_ward',
    name: 'Death Ward',
    level: 4,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Protects a creature from death for 8 hours without concentration: drops to 1 HP instead of 0 HP on first lethal instance, or negates instant-death effects.',
    tags: ['buff', 'anti-death', 'cheat-death', 'no-concentration', 'cleric', 'paladin', 'abjuration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: '8 hours',
      concentration: false,
      classes: [SpellClass.cleric, SpellClass.paladin],
      description: [
        'You touch a creature and grant it a measure of protection from death. The first time the target would drop to 0 hit points as a result of taking damage, the target instead drops to 1 hit point, and the spell ends.',
        'If the spell is still in effect when the target is subjected to an effect that would kill it instantaneously without dealing damage, that effect is instead negated against the target, and the spell ends.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: '8 hours',
      concentration: false,
      classes: [SpellClass.cleric, SpellClass.paladin],
      description: [
        'Prevents target from dropping to 0 HP (drops to 1 HP instead) or negates an instant-death effect for 8 hours.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_divination',
    name: 'Divination',
    level: 4,
    school: SpellSchool.divination,
    isChangedIn2024: false,
    diffSummary: 'Offers a sacrifice to contact a deity, receiving a cryptic or direct omen concerning a specific goal, event, or activity occurring within 7 days.',
    tags: ['ritual', 'omen', 'future-sight', 'divination', 'costly-component', 'cleric', 'druid', 'wizard', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S, M (incense and a sacrificial offering appropriate to your religion, together worth at least 25 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'incense and sacrificial offering worth 25 gp',
        hasCost: true,
        costInGp: 25,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      ritual: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'Your magic and an offering put you in contact with a god or a god’s servants. You ask a single question concerning a specific goal, event, or activity to occur within 7 days. The DM offers a truthful reply (short phrase, cryptic rhyme, or omen).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S, M (incense and offering worth 25 gp, consumed)',
      materialDetails: SpellMaterialComponent(
        description: 'incense and sacrificial offering worth 25 gp',
        hasCost: true,
        costInGp: 25,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      ritual: true,
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.wizard],
      description: [
        'Contacts deity for an omen or truthful answer regarding events in the next 7 days.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_guardian_of_faith',
    name: 'Guardian of Faith',
    level: 4,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Summons a Large spectral guardian occupying a 10-foot space for 8 hours without concentration that strikes hostile creatures for 20 radiant damage (up to 60 total).',
    tags: ['summon', 'ward', 'radiant', 'no-concentration', 'cleric', 'conjuration', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V',
      duration: '8 hours',
      concentration: false,
      classes: [SpellClass.cleric],
      rollFormula: '20',
      damageOrHealType: 'Radiant (20 flat / 10 on save)',
      savingThrow: 'Dexterity',
      description: [
        'A Large spectral guardian appears and hovers for the duration in an unoccupied space of your choice that you can see within range.',
        'Any hostile creature that moves to a space within 10 feet of the guardian for the first time on a turn must succeed on a Dexterity saving throw. The creature takes 20 radiant damage on a failed save, or 10 on success. The guardian vanishes when it has dealt a total of 60 damage.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V',
      duration: '8 hours',
      concentration: false,
      classes: [SpellClass.cleric],
      rollFormula: '20',
      damageOrHealType: 'Radiant',
      savingThrow: 'Dexterity',
      description: [
        'Spectral guardian deals 20 Radiant damage on failed Dexterity save (10 on success) to enemies approaching within 10 ft; lasts 8 hours or 60 total damage.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_freedom_of_movement',
    name: 'Freedom of Movement',
    level: 4,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Grants immunity to paralyzed/restrained conditions, difficult terrain, and movement penalties from water/spells for 1 hour without concentration.',
    tags: ['buff', 'movement', 'paralyze-immunity', 'restrain-immunity', 'no-concentration', 'cleric', 'druid', 'bard', 'ranger', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a strap of leather, wrapped around the arm or a similar limb)',
      materialDetails: SpellMaterialComponent(description: 'a strap of leather'),
      duration: '1 hour',
      concentration: false,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.ranger],
      description: [
        'You touch a willing creature. For the duration, the target’s movement is unaffected by difficult terrain, and spells and other magical effects can neither reduce the target’s speed nor cause the target to be paralyzed or restrained.',
        'The target can also spend 5 feet of movement to automatically escape from nonmagical restraints (such as manacles or a creature’s grapple). Underwater movement and attacks suffer no penalties.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (leather strap)',
      materialDetails: SpellMaterialComponent(description: 'leather strap'),
      duration: '1 hour',
      concentration: false,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.ranger],
      description: [
        'Target ignores Difficult Terrain, immunity to Paralyzed and Restrained conditions, and escapes grapples/restraints for 5 ft of movement.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_blight',
    name: 'Blight',
    level: 4,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Drains moisture and vitality dealing 8d8 necrotic damage on Constitution save (maximizes damage against nonmagical plants).',
    tags: ['necrotic', 'single-target', 'plant-killer', 'druid', 'sorcerer', 'warlock', 'wizard', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '8d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'Necromantic energy washes over a creature within range. The target must make a Constitution saving throw, taking 8d8 necrotic damage on a failed save, or half on success. Has no effect on undead or constructs.',
        'If you target a plant creature or magical plant, it makes the saving throw with disadvantage, and the spell deals maximum damage to it.',
      ],
      higherLevels: 'Damage increases by 1d8 for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '8d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 8, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'Deals 8d8 Necrotic damage on failed Constitution save (maximized vs plants).',
      ],
      higherLevels: 'Damage increases by 1d8 per slot level above 4th.',
    ),
  ),

  SpellItem(
    id: 'spell_ice_storm',
    name: 'Ice Storm',
    level: 4,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'A hail of rock-hard ice pounds down in a 20-foot radius, 40-foot high cylinder dealing 2d8 bludgeoning and 4d6 cold damage and creating difficult terrain.',
    tags: ['ice', 'cold', 'bludgeoning', 'aoe', 'difficult-terrain', 'evocation', 'level 4'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '300 feet (20-foot radius cylinder)',
      components: 'V, S, M (a pinch of dust and a few drops of water)',
      materialDetails: SpellMaterialComponent(description: 'dust and drops of water'),
      duration: 'Instantaneous',
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d8 + 4d6',
      damageOrHealType: 'Bludgeoning & Cold (2d8+4d6)',
      savingThrow: 'Dexterity',
      description: [
        'A hail of rock-hard ice pounds to the ground in a 20-foot-radius, 40-foot-high cylinder. Each creature in the cylinder takes 2d8 bludgeoning damage and 4d6 cold damage on a failed Dexterity save (half on success). The ground becomes difficult terrain until end of next turn.',
      ],
      higherLevels: 'The bludgeoning damage increases by 1d8 for each slot level above 4th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '300 feet (20-foot radius cylinder)',
      components: 'V, S, M (dust and water drops)',
      materialDetails: SpellMaterialComponent(description: 'dust and water drops'),
      duration: 'Instantaneous',
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '2d8 + 4d6',
      damageOrHealType: 'Bludgeoning & Cold',
      savingThrow: 'Dexterity',
      description: [
        'Deals 2d8 Bludgeoning + 4d6 Cold damage in 20-ft radius cylinder and creates Difficult Terrain.',
      ],
      higherLevels: 'Bludgeoning damage increases by 1d8 per slot level above 4th.',
    ),
  ),
];
