import '../spellbook_data.dart';

const List<SpellItem> srdLevel7Spells = [
  SpellItem(
    id: 'spell_divine_word',
    name: 'Divine Word',
    level: 7,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Utters a word imbued with divine power as a Bonus Action that blinds, deafens, stuns, or instantly kills creatures based on current HP, and banishes extraplanar creatures.',
    tags: ['divine', 'bonus-action', 'debuff', 'banish', 'instant-kill', 'evocation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '30 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      savingThrow: 'Charisma',
      description: [
        'You utter a divine word. Each creature of your choice within range must make a Charisma saving throw.',
        'On a failed save, a creature with <=50 HP is deafened (1 min); <=40 HP is blinded and deafened (10 min); <=30 HP is blinded, deafened, and stunned (1 hour); <=20 HP is instantly killed.',
        'Celestials, elementals, fey, or fiends that fail are banished to their home plane for 24 hours.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '30 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      savingThrow: 'Charisma',
      description: [
        'Divine word inflicts Deafened (<=50 HP), Blinded (<=40 HP), Stunned (<=30 HP), or instant death (<=20 HP) on failed Charisma save. Banishes extraplanar creatures.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_fire_storm',
    name: 'Fire Storm',
    level: 7,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates a storm of sheet flame consisting of up to ten 10-foot cubes dealing 7d10 fire damage on Dexterity save.',
    tags: ['fire', 'aoe', 'selective-shape', 'evocation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer],
      rollFormula: '7d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 7, diceSides: 10),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A storm made of sheets of roaring flame appears in a location you choose. The area consists of up to ten 10-foot cubes, which you can arrange as you wish (each must be contiguous).',
        'Each creature in the area must make a Dexterity saving throw, taking 7d10 fire damage on a failed save, or half on success.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer],
      rollFormula: '7d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 7, diceSides: 10),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'Roaring storm of up to ten 10-ft cubes dealing 7d10 Fire damage on Dexterity save (half on success). Plant life can be selectively spared.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_plane_shift',
    name: 'Plane Shift',
    level: 7,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Transports you and up to eight willing creatures to another plane of existence, or banishes an unwilling creature on a melee spell attack & Charisma save.',
    tags: ['planar-travel', 'teleport', 'banishment', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a forked, metal rod worth at least 250 gp, attuned to a particular plane of existence)',
      materialDetails: SpellMaterialComponent(
        description: 'a forked metal rod worth 250 gp attuned to target plane',
        hasCost: true,
        costInGp: 250,
        isConsumed: false,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Charisma',
      description: [
        'You and up to eight willing creatures who link hands in a circle are transported to a different plane of existence.',
        'Alternatively, you can use this spell to banish an unwilling creature by making a melee spell attack; on a hit, target must make a Charisma saving throw or be sent to the target plane.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (attuned forked metal rod worth 250 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'attuned forked metal rod worth 250 gp',
        hasCost: true,
        costInGp: 250,
        isConsumed: false,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.cleric, SpellClass.druid, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      savingThrow: 'Charisma',
      description: [
        'Transports you and up to 8 willing creatures to another plane, or banishes an unwilling foe on melee spell attack and failed Charisma save.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_regenerate',
    name: 'Regenerate',
    level: 7,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Restores 4d8 + 15 Hit Points instantly, causes target to regain 1 HP at the start of each of its turns for 1 hour, and regrows severed body parts in 2 minutes.',
    tags: ['healing', 'regeneration', 'severed-limbs', 'transmutation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: 'Touch',
      components: 'V, S, M (a prayer wheel and holy water)',
      materialDetails: SpellMaterialComponent(description: 'a prayer wheel and holy water'),
      duration: '1 hour',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      rollFormula: '4d8 + 15',
      scalingFormula: SpellScalingFormula(baseDiceCount: 4, diceSides: 8, staticBonus: 15),
      damageOrHealType: 'Healing (4d8+15 + 1 HP/turn)',
      description: [
        'You touch a creature and stimulate its natural healing ability. The target regains 4d8 + 15 hit points.',
        'For the duration of the spell (1 hour), the target regains 1 hit point at the start of each of its turns (600 hit points over 1 hour). Severed body parts are restored after 2 minutes.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: 'Touch',
      components: 'V, S, M (a prayer wheel and holy water)',
      materialDetails: SpellMaterialComponent(description: 'a prayer wheel and holy water'),
      duration: '1 hour',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      rollFormula: '4d8 + 15',
      scalingFormula: SpellScalingFormula(baseDiceCount: 4, diceSides: 8, staticBonus: 15),
      damageOrHealType: 'Healing (4d8+15 + 1 HP/turn)',
      description: [
        'Target heals 4d8 + 15 HP immediately and 1 HP at the start of every turn for 1 hour. Regrows severed limbs in 2 minutes.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_resurrection',
    name: 'Resurrection',
    level: 7,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Restores life to a creature that has been dead for no longer than a century, closing all mortal wounds and restoring missing body parts.',
    tags: ['revive', 'resurrection', 'costly-component', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 hour',
      range: 'Touch',
      components: 'V, S, M (a diamond worth at least 1,000 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric],
      description: [
        'You touch a dead creature that has been dead for no longer than 100 years and that didn’t die of old age.',
        'If its soul is free and willing, the target returns to life with all its hit points, neutralizes poisons, cures diseases, and closes mortal wounds and restores missing body parts.',
        'Imposes a -4 penalty to attack rolls, saving throws, and ability checks, reduced by 1 for each long rest.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 hour',
      range: 'Touch',
      components: 'V, S, M (diamond worth 1,000 gp, consumed)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric],
      description: [
        'Brings a creature dead up to 100 years back to life at full HP, curing poisons, diseases, and regenerating lost body parts.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_conjure_celestial',
    name: 'Conjure Celestial',
    level: 7,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Summons a celestial being of CR 4 or lower (such as a Couatl) in 2014, redesigned into a radiant burst pillar in 2024.',
    diffHighlights: [
      '2014: Summons a CR 4 Celestial statblock (or CR 5 with 9th level slot) with 1 minute casting time and Concentration up to 1 hour.',
      '2024: 1 Action, Concentration up to 10 minutes. Conjures a 10-foot-radius cylinder of radiant divine light dealing radiant damage and healing allies.',
    ],
    tags: ['celestial', 'summon', 'concentration', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '90 feet',
      components: 'V, S',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.cleric],
      description: [
        'You summon a celestial of challenge rating 4 or lower (such as a Couatl), which appears in an unoccupied space that you can see within range.',
        'It obeys any verbal commands that you issue to it.',
      ],
      higherLevels: 'When you cast this spell using a 9th-level spell slot, you summon a celestial of challenge rating 5 or lower.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '90 feet',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric],
      rollFormula: '4d12',
      scalingFormula: SpellScalingFormula(baseDiceCount: 4, diceSides: 12, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant / Healing',
      description: [
        'You conjure a column of divine light (10-ft radius, 40-ft high). Deals 4d12 Radiant damage on failed Dexterity save (half on success) or heals allies entering the light.',
      ],
      higherLevels: 'Damage and healing increase by 1d12 per slot level above 7th.',
    ),
  ),

  SpellItem(
    id: 'spell_symbol',
    name: 'Symbol',
    level: 7,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Inscribes a deadly magical glyph triggering one of eight debilitating effects (Death, Discord, Fear, Hopelessness, Insanity, Pain, Sleep, Stunning) in a 60-foot sphere.',
    tags: ['glyph', 'trap', 'abjuration', 'costly-component', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: 'Touch',
      components: 'V, S, M (mercury, phosphorus, and powdered diamond and opal worth at least 1,000 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'powdered diamond and opal worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: true,
      ),
      duration: 'Until dispelled or triggered',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.wizard],
      savingThrow: 'Constitution / Wisdom / Charisma',
      description: [
        'Inscribes a harmful glyph onto a surface or object. When triggered, activates one glyph effect across a 60-foot-radius sphere for 10 minutes (Death deals 10d10 necrotic, Discord causes infighting, Fear frightens, Hopelessness demoralizes, Insanity causes madness, Pain incapacitates, Sleep knocks unconscious, Stunning stuns).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: 'Touch',
      components: 'V, S, M (diamond and opal dust worth 1,000 gp, consumed)',
      materialDetails: SpellMaterialComponent(
        description: 'diamond and opal dust worth 1,000 gp',
        hasCost: true,
        costInGp: 1000,
        isConsumed: true,
      ),
      duration: 'Until dispelled or triggered',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.wizard],
      description: [
        'Creates an arcane ward triggering catastrophic area effects (Death, Pain, Stun, Insanity, Discord, Sleep, Fear, or Hopelessness) in a 60-ft radius.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_teleport',
    name: 'Teleport',
    level: 7,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Instantly transports you and up to eight willing creatures to any destination you designate on the same plane.',
    tags: ['teleport', 'long-range', 'conjuration', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '10 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'This spell instantly transports you and up to eight willing creatures of your choice that you can see within range to a destination you select on the same plane.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '10 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Instantly transports you and up to 8 willing creatures or 1 object to a known destination on the same plane.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_forcecage',
    name: 'Forcecage',
    level: 7,
    school: SpellSchool.evocation,
    isChangedIn2024: true,
    diffSummary: 'Creates an invisible cube or cage of force trapping creatures without an initial saving throw (requires Concentration and consumes ruby dust in 2024).',
    diffHighlights: [
      '2014: 1 Action, 1 hour duration (NO CONCENTRATION). 1,500 gp ruby dust NOT consumed. No initial save.',
      '2024: 1 Action, Concentration up to 1 hour. Consumes 1,500 gp ruby dust. Trapped creatures must make Charisma saves to teleport out.',
    ],
    tags: ['force', 'trap', 'no-save', 'concentration', 'evocation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '100 feet',
      components: 'V, S, M (ruby dust worth 1,500 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'ruby dust worth 1,500 gp',
        hasCost: true,
        costInGp: 1500,
        isConsumed: false,
      ),
      duration: '1 hour',
      concentration: false,
      classes: [SpellClass.bard, SpellClass.warlock, SpellClass.wizard],
      description: [
        'An immobile, invisible, cube-shaped prison composed of magical force springs into existence around an area you choose within range (up to 20-ft cage or 10-ft solid box). No initial save.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '100 feet',
      components: 'V, S, M (ruby dust worth 1,500 gp, consumed by the spell)',
      materialDetails: SpellMaterialComponent(
        description: 'ruby dust worth 1,500 gp, consumed by the spell',
        hasCost: true,
        costInGp: 1500,
        isConsumed: true,
      ),
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.warlock, SpellClass.wizard],
      description: [
        'An invisible cube of force traps creatures without initial save. Requires Concentration and consumes material component.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_delayed_blast_fireball',
    name: 'Delayed Blast Fireball',
    level: 7,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates a glowing yellow bead dealing 12d6 fire damage, increasing by 1d6 for every round delayed up to 1 minute (+10d6 max).',
    tags: ['fire', 'trap', 'delayed-damage', 'concentration', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (a tiny ball of bat guano and pitch)',
      materialDetails: SpellMaterialComponent(description: 'bat guano and pitch'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '12d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 12, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A beam of yellow light flashes and coalesces into a glowing bead at a chosen point. Deals 12d6 fire damage in a 20-foot radius when detonated, plus 1d6 fire damage for every full round it was delayed (up to 22d6 total).',
      ],
      higherLevels: 'Base damage increases by 1d6 for each slot level above 7th.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '150 feet',
      components: 'V, S, M (bat guano and pitch)',
      materialDetails: SpellMaterialComponent(description: 'bat guano and pitch'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '12d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 12, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'Glowing bead deals 12d6 Fire damage in 20-ft radius (+1d6 per turn concentrated) on Dexterity save.',
      ],
      higherLevels: 'Base damage increases by 1d6 per slot level above 7th.',
    ),
  ),

  SpellItem(
    id: 'spell_finger_of_death',
    name: 'Finger of Death',
    level: 7,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Sends negative energy through a creature dealing 7d8 + 30 necrotic damage on Constitution save; a slain humanoid rises as a permanent Zombie under your command.',
    tags: ['necrotic', 'zombie', 'single-target', 'high-damage', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '7d8 + 30',
      scalingFormula: SpellScalingFormula(baseDiceCount: 7, diceSides: 8, staticBonus: 30),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'You send negative energy coursing through a creature that you can see within range, causing it searing pain. The target must make a Constitution saving throw, taking 7d8 + 30 necrotic damage on a failed save, or half on success.',
        'A humanoid killed by this spell rises at the start of your next turn as a zombie under your permanent control.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      rollFormula: '7d8 + 30',
      scalingFormula: SpellScalingFormula(baseDiceCount: 7, diceSides: 8, staticBonus: 30),
      damageOrHealType: 'Necrotic',
      savingThrow: 'Constitution',
      description: [
        'Deals 7d8 + 30 Necrotic damage on failed Constitution save (half on success). A humanoid killed rises as a permanently commanded Zombie.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_prismatic_spray',
    name: 'Prismatic Spray',
    level: 7,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Unleashes eight multicolored rays in a 60-foot cone dealing 10d6 damage of various types (Fire, Acid, Lightning, Poison, Cold) or inflicting Petrification/Planar Banishment.',
    tags: ['prismatic', 'cone', 'random-effects', 'evocation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (60-foot cone)',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 6),
      damageOrHealType: 'Prismatic Multi-Type',
      savingThrow: 'Dexterity / Constitution / Wisdom',
      description: [
        'Eight multicolored rays of light flash from your hand in a 60-foot cone. For each target, roll a d8 to determine the ray (1: Red 10d6 Fire, 2: Orange 10d6 Acid, 3: Yellow 10d6 Lightning, 4: Green 10d6 Poison, 5: Blue 10d6 Cold, 6: Indigo Petrified, 7: Violet Banished to another plane, 8: Struck by two rays).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (60-foot cone)',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '10d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 10, diceSides: 6),
      damageOrHealType: 'Prismatic Multi-Type',
      savingThrow: 'Dexterity',
      description: [
        'Fires a 60-ft rainbow cone inflicting diverse elemental damage (10d6) or petrification/banishment based on d8 roll.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_reverse_gravity',
    name: 'Reverse Gravity',
    level: 7,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Reverses gravity in a 50-foot radius, 100-foot high cylinder, causing creatures and objects to fall upward and take falling damage when reversed.',
    tags: ['gravity', 'aoe', 'control', 'transmutation', 'concentration', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '100 feet',
      components: 'V, S, M (a lodestone and iron shavings)',
      materialDetails: SpellMaterialComponent(description: 'a lodestone and iron shavings'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Dexterity',
      description: [
        'This spell reverses gravity in a 50-foot-radius, 100-foot-high cylinder. All creatures and objects fall upward to the top of the cylinder. If an object/ceiling stops their fall, they suffer impact falling damage. When the spell ends, affected objects and creatures fall back down.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '100 feet',
      components: 'V, S, M (a lodestone and iron shavings)',
      materialDetails: SpellMaterialComponent(description: 'a lodestone and iron shavings'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard],
      savingThrow: 'Dexterity',
      description: [
        'Reverses gravity in a 50-ft radius, 100-ft high cylinder, dropping creatures upward into the air or ceiling.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_simulacrum',
    name: 'Simulacrum',
    level: 7,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Creates an illusory duplicate of one beast or humanoid with half max HP, all statistics, spell slots, and actions.',
    tags: ['clone', 'duplicate', 'costly-component', 'illusion', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '12 hours',
      range: 'Touch',
      components: 'V, S, M (snow or ice in quantities sufficient to made a life-size copy, hair/fingernail clippings, and powdered ruby worth 1,500 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'snow/ice, hair clippings, and ruby dust worth 1,500 gp',
        hasCost: true,
        costInGp: 1500,
        isConsumed: true,
      ),
      duration: 'Until dispelled',
      classes: [SpellClass.wizard],
      description: [
        'You shape an illusory duplicate of one beast or humanoid that is within range. The duplicate is a creature, partially real, formed from ice or snow.',
        'It has half the creature’s max HP and all statistics and abilities, but cannot regain spell slots or level up.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '12 hours',
      range: 'Touch',
      components: 'V, S, M (snow, hair clippings, and ruby dust worth 1,500 gp, consumed)',
      materialDetails: SpellMaterialComponent(
        description: 'ruby dust worth 1,500 gp, snow/ice, biological sample',
        hasCost: true,
        costInGp: 1500,
        isConsumed: true,
      ),
      duration: 'Until dispelled',
      classes: [SpellClass.wizard],
      description: [
        'Creates an exact magical duplicate of a creature with half its HP that obeys your mental commands.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_etherealness',
    name: 'Etherealness',
    level: 7,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Steps into the Border Ethereal for up to 8 hours, allowing you to move through solid objects and perceive the Material Plane as ghostly shades.',
    tags: ['ethereal', 'phasing', 'stealth', 'travel', 'transmutation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S',
      duration: '8 hours',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You step into the Border Ethereal. You remain in the Border Ethereal for the duration, moving through solid objects and creatures on the Material Plane at will.',
      ],
      higherLevels: 'Slot 8th: Target up to 3 willing creatures. Slot 9th: Target up to 5 willing creatures.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self',
      components: 'V, S',
      duration: '8 hours',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.sorcerer, SpellClass.warlock, SpellClass.wizard],
      description: [
        'You step into the Border Ethereal. You remain in the Border Ethereal for the duration, moving through solid objects and creatures on the Material Plane at will.',
      ],
      higherLevels: 'Slot 8th: Target up to 3 willing creatures. Slot 9th: Target up to 5 willing creatures.',
    ),
  ),

  SpellItem(
    id: 'spell_magnificent_mansion',
    name: 'Magnificent Mansion',
    level: 7,
    school: SpellSchool.conjuration,
    isChangedIn2024: false,
    diffSummary: 'Conjures an extradimensional grand mansion containing up to 50 rooms, 100 spectral servants, and a sumptuous 9-course banquet for up to 100 people for 24 hours.',
    tags: ['shelter', 'extradimensional', 'safe-rest', 'banquet', 'bard', 'wizard', 'conjuration', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 minute',
      range: '300 feet',
      components: 'V, S, M (a miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon, each worth at least 5 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'ivory portal, marble, silver spoon worth 15 gp',
        hasCost: true,
        costInGp: 15,
        isConsumed: false,
      ),
      duration: '24 hours',
      classes: [SpellClass.bard, SpellClass.wizard],
      description: [
        'You conjure an extradimensional dwelling in range that lasts for the duration. You choose where its portal appears. The portal is a 5-foot-wide, 10-foot-high door.',
        'You and any creatures you designate can enter the mansion as long as the portal remains open. The place has up to 50 rooms, is clean and warm, and contains 100 near-transparent spectral servants and enough food to serve a nine-course banquet for up to 100 people.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 minute',
      range: '300 feet',
      components: 'V, S, M (a miniature portal carved from ivory, a small piece of polished marble, and a tiny silver spoon, each worth at least 5 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'ivory portal, marble, silver spoon worth 15 gp',
        hasCost: true,
        costInGp: 15,
        isConsumed: false,
      ),
      duration: '24 hours',
      classes: [SpellClass.bard, SpellClass.wizard],
      description: [
        'You conjure an extradimensional dwelling in range that lasts for the duration. You choose where its portal appears. The portal is a 5-foot-wide, 10-foot-high door.',
        'You and any creatures you designate can enter the mansion as long as the portal remains open. The place has up to 50 rooms, is clean and warm, and contains 100 near-transparent spectral servants and enough food to serve a nine-course banquet for up to 100 people.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_mirage_arcane',
    name: 'Mirage Arcane',
    level: 7,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Makes terrain up to 1 square mile look, sound, smell, and even physically feel like another terrain (with real tactile structures, water, and difficult terrain) for 10 days.',
    tags: ['terrain', 'illusion-tangible', 'huge-area', 'bard', 'druid', 'wizard', 'illusion', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Sight (1 square mile)',
      components: 'V, S',
      duration: '10 days',
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.wizard],
      description: [
        'You make terrain in an area up to 1 square mile look, sound, smell, and even feel like some other sort of terrain. Open fields can become a swamp, hill, or crevassed wasteland; a pond can become a meadow.',
        'The terrain’s tactile elements are physically real: you can climb illusory trees, walk on illusory bridges, and drown in illusory water. Creatures with truesight see the true terrain superimposed on the illusion.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '10 minutes',
      range: 'Sight (1 square mile)',
      components: 'V, S',
      duration: '10 days',
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.wizard],
      description: [
        'You make terrain in an area up to 1 square mile look, sound, smell, and even feel like some other sort of terrain. Open fields can become a swamp, hill, or crevassed wasteland; a pond can become a meadow.',
        'The terrain’s tactile elements are physically real: you can climb illusory trees, walk on illusory bridges, and drown in illusory water. Creatures with truesight see the true terrain superimposed on the illusion.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_project_image',
    name: 'Project Image',
    level: 7,
    school: SpellSchool.illusion,
    isChangedIn2024: false,
    diffSummary: 'Creates an illusory copy of yourself at any spot within 500 miles that you have seen before for up to 1 day. See and hear through it and speak with your voice.',
    tags: ['astral-duplicate', 'long-range-avatar', 'illusion', 'concentration', 'bard', 'wizard', 'illusion', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '500 miles',
      components: 'V, S, M (a small replica of you worth at least 5 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'miniature statuette of you worth 5 gp',
        hasCost: true,
        costInGp: 5,
        isConsumed: false,
      ),
      duration: 'Concentration, up to 1 day',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.wizard],
      description: [
        'You create an illusory copy of yourself that lasts for the duration. The copy can appear at any location within range that you have seen before, regardless of intervening obstacles.',
        'You can see through its eyes and hear through its ears as if you were in its space. On your turn as a bonus action, you can switch from using its senses to using your own, or back again. Physical interaction reveals it as an illusion.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '500 miles',
      components: 'V, S, M (a small replica of you worth at least 5 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'miniature statuette of you worth 5 gp',
        hasCost: true,
        costInGp: 5,
        isConsumed: false,
      ),
      duration: 'Concentration, up to 1 day',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.wizard],
      description: [
        'You create an illusory copy of yourself that lasts for the duration. The copy can appear at any location within range that you have seen before, regardless of intervening obstacles.',
        'You can see through its eyes and hear through its ears as if you were in its space. On your turn as a bonus action, you can switch from using its senses to using your own, or back again. Physical interaction reveals it as an illusion.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_sequester',
    name: 'Sequester',
    level: 7,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Touch a willing creature or object to make it completely invisible, undetectable to divination and scrying, and in suspended animation indefinitely until a specified condition is met. Costly component.',
    tags: ['hide', 'suspended-animation', 'permanent-until-triggered', 'costly-component', 'wizard', 'transmutation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a powder composed of diamond, emerald, ruby, and sapphire dust worth at least 5,000 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'gemstone dust worth 5,000 gp',
        hasCost: true,
        costInGp: 5000,
        isConsumed: true,
      ),
      duration: 'Until dispelled',
      classes: [SpellClass.wizard],
      description: [
        'By means of this spell, a willing creature or an object is hidden away, safe from all detection for the duration. Upon casting the spell and touching the target, it becomes invisible and can’t be targeted by divination magic or perceived through scrying sensors.',
        'If the target is a creature, it falls into a state of suspended animation. Time ceases to flow for it, and it doesn’t grow older. You can set a condition for the spell to end (such as a time period or a specific event).',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a powder composed of diamond, emerald, ruby, and sapphire dust worth at least 5,000 gp, which the spell consumes)',
      materialDetails: SpellMaterialComponent(
        description: 'gemstone dust worth 5,000 gp',
        hasCost: true,
        costInGp: 5000,
        isConsumed: true,
      ),
      duration: 'Until dispelled',
      classes: [SpellClass.bard, SpellClass.wizard],
      description: [
        'By means of this spell, a willing creature or an object is hidden away, safe from all detection for the duration. Upon casting the spell and touching the target, it becomes invisible and can’t be targeted by divination magic or perceived through scrying sensors.',
        'If the target is a creature, it falls into a state of suspended animation. Time ceases to flow for it, and it doesn’t grow older. You can set a condition for the spell to end (such as a time period or a specific event).',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_arcane_sword',
    name: 'Arcane Sword',
    level: 7,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates a hovering sword-shaped plane of force: make melee spell attacks on cast and as a Bonus Action on subsequent turns dealing 3d10 force damage. Costly component (250 gp platinum sword).',
    tags: ['force-blade', 'bonus-action-attack', 'force-damage', 'concentration', 'costly-component', 'bard', 'wizard', 'evocation', 'level 7'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a miniature platinum sword with a grip and pommel of copper and zinc, worth 250 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'miniature platinum sword worth 250 gp',
        hasCost: true,
        costInGp: 250,
        isConsumed: false,
      ),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.wizard],
      rollFormula: '3d10',
      damageOrHealType: 'Force',
      description: [
        'You create a sword-shaped plane of force that hovers within range. It lasts for the duration.',
        'When the sword appears, you make a melee spell attack against a target of your choice within 5 feet of the sword. On a hit, the target takes 3d10 force damage. Until the spell ends, you can use a bonus action on each of your turns to move the sword up to 20 feet to a spot you can see and repeat this attack.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V, S, M (a miniature platinum sword with a grip and pommel of copper and zinc, worth 250 gp)',
      materialDetails: SpellMaterialComponent(
        description: 'miniature platinum sword worth 250 gp',
        hasCost: true,
        costInGp: 250,
        isConsumed: false,
      ),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.wizard],
      rollFormula: '3d10',
      damageOrHealType: 'Force',
      description: [
        'You create a sword-shaped plane of force that hovers within range. It lasts for the duration.',
        'When the sword appears, you make a melee spell attack against a target of your choice within 5 feet of the sword. On a hit, the target takes 3d10 force damage. Until the spell ends, you can use a bonus action on each of your turns to move the sword up to 20 feet to a spot you can see and repeat this attack.',
      ],
    ),
  ),
];
