import '../spellbook_data.dart';

const List<SpellItem> srdLevel1Spells = [
  SpellItem(
    id: 'spell_cure_wounds',
    name: 'Cure Wounds',
    level: 1,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Massive healing buff: Base healing increased from 1d8 + modifier to 2d8 + modifier, scaling by +2d8 per slot level.',
    diffHighlights: [
      '2014: Heals 1d8 + spellcasting ability modifier. +1d8 per slot level above 1st. (Evocation)',
      '2024: Heals 2d8 + spellcasting ability modifier. +2d8 per slot level above 1st. (Abjuration)',
    ],
    tags: ['healing', 'support', 'buffed', 'level 1'],
    rules2014: SpellEditionDetails(
      schoolOverride: SpellSchool.evocation,
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.artificer],
      rollFormula: '1d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 8, dicePerSlotLevel: 1, addsAbilityMod: true),
      damageOrHealType: 'Healing',
      description: [
        'A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier.',
        'This spell has no effect on undead or constructs.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      schoolOverride: SpellSchool.abjuration,
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.artificer],
      rollFormula: '2d8 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 2, addsAbilityMod: true),
      damageOrHealType: 'Healing',
      description: [
        'A creature you touch regains a number of Hit Points equal to 2d8 + your spellcasting ability modifier.',
        'This spell has no effect on Constructs or Undead.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 2d8 for each slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_healing_word',
    name: 'Healing Word',
    level: 1,
    school: SpellSchool.abjuration,
    isChangedIn2024: true,
    diffSummary: 'Healing doubled: Base healing increased from 1d4 + modifier to 2d4 + modifier, scaling by +2d4 per slot level.',
    diffHighlights: [
      '2014: Bonus Action, 60 ft range. Heals 1d4 + modifier (+1d4 per slot above 1st). (Evocation)',
      '2024: Bonus Action, 60 ft range. Heals 2d4 + modifier (+2d4 per slot above 1st). (Abjuration)',
    ],
    tags: ['healing', 'bonus action', 'ranged', 'buffed', 'level 1'],
    rules2014: SpellEditionDetails(
      schoolOverride: SpellSchool.evocation,
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      rollFormula: '1d4 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 4, dicePerSlotLevel: 1, addsAbilityMod: true),
      damageOrHealType: 'Healing',
      description: [
        'A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier.',
        'This spell has no effect on undead or constructs.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      schoolOverride: SpellSchool.abjuration,
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.cleric, SpellClass.druid],
      rollFormula: '2d4 + mod',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 4, dicePerSlotLevel: 2, addsAbilityMod: true),
      damageOrHealType: 'Healing',
      description: [
        'A creature of your choice that you can see within range regains Hit Points equal to 2d4 + your spellcasting ability modifier.',
        'This spell has no effect on Constructs or Undead.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 2d4 for each slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_divine_smite',
    name: 'Divine Smite',
    level: 1,
    school: SpellSchool.evocation,
    isChangedIn2024: true,
    diffSummary: 'Changed from a free class feature applied on hit into a 1st-level Bonus Action spell with Verbal component.',
    diffHighlights: [
      '2014: Class Feature (not a spell). When you hit with a melee weapon attack, expend a spell slot to deal 2d8 radiant (+1d8 per slot above 1st, +1d8 vs undead/fiends). No action cost, cannot be counterspelled.',
      '2024: 1st-level Spell. Casting time 1 Bonus Action immediately after hitting a target with a melee weapon or unarmed strike. Can be Counterspelled, consumes Bonus Action, prevents casting another level 1+ spell on that turn.',
    ],
    tags: ['paladin', 'smite', 'radiant', 'bonus action', 'nerfed', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: 'No Action (Upon hitting with melee weapon)',
      range: 'Self',
      components: 'None',
      duration: 'Instantaneous',
      classes: [SpellClass.paladin],
      rollFormula: '2d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant',
      description: [
        'Starting at 2nd level, when you hit a creature with a melee weapon attack, you can expend one spell slot to deal radiant damage to the target, in addition to the weapon’s damage.',
        'The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a maximum of 5d8. The damage increases by 1d8 if the target is an undead or a fiend, to a maximum of 6d8.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action, which you take immediately after hitting a target with a melee weapon or an Unarmed Strike',
      range: 'Self',
      components: 'V',
      duration: 'Instantaneous',
      classes: [SpellClass.paladin],
      rollFormula: '2d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant',
      description: [
        'As you strike, your weapon bursts with divine radiance. The target takes an extra 2d8 Radiant damage from the attack.',
        'The damage increases by 1d8 for each slot level above 1st. The extra damage increases by 1d8 if the target is a Fiend or an Undead.',
      ],
      higherLevels: 'Using a higher spell slot increases damage by 1d8 for each slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_hunters_mark',
    name: "Hunter's Mark",
    level: 1,
    school: SpellSchool.divination,
    isChangedIn2024: true,
    diffSummary: 'Damage changed from weapon-attacks-only to any attack hit, and ranger class features enhance it at higher levels.',
    diffHighlights: [
      '2014: 1 Bonus Action, Concentration (up to 1 hr). Deals 1d6 extra weapon damage when you hit with a weapon attack. Move to new target with Bonus Action when target drops to 0 HP.',
      '2024: 1 Bonus Action, Concentration (up to 1 hr). Deals 1d6 Force damage (or extra damage) whenever you hit the target with ANY attack roll. Directly keyed to Ranger core progression.',
    ],
    tags: ['ranger', 'mark', 'damage', 'tracking', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '90 feet',
      components: 'V',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.ranger],
      rollFormula: '1d6',
      damageOrHealType: 'Weapon Damage',
      description: [
        'You choose a creature you can see within range and mystically mark it as your quarry. Until the spell ends, you deal an extra 1d6 damage to the target whenever you hit it with a weapon attack.',
        'You have advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find it.',
        'If the target drops to 0 hit points before this spell ends, you can use a bonus action on a subsequent turn to mark a new creature.',
      ],
      higherLevels: 'Slot 3rd-4th: duration up to 8 hours. Slot 5th+: duration up to 24 hours.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '90 feet',
      components: 'V',
      duration: 'Concentration, up to 1 hour',
      concentration: true,
      classes: [SpellClass.ranger],
      rollFormula: '1d6',
      damageOrHealType: 'Force',
      description: [
        'You mystically mark a creature as your quarry. Until the spell ends, you deal an extra 1d6 Force damage to the target whenever you hit it with an attack roll.',
        'You also have Advantage on any Wisdom (Perception) or Wisdom (Survival) check you make to find the quarry.',
        'If the target drops to 0 Hit Points before the spell ends, you can use a Bonus Action to move the mark to a new creature within range.',
      ],
      higherLevels: 'When cast with a 3rd- or 4th-level slot, duration is up to 8 hours. With a 5th-level slot or higher, duration is up to 24 hours.',
    ),
  ),

  SpellItem(
    id: 'spell_shield',
    name: 'Shield',
    level: 1,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Remains the staple +5 AC reaction spell that completely nullifies Magic Missile.',
    tags: ['defense', 'ac', 'reaction', 'abjuration', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Reaction, which you take when you are hit by an attack roll or targeted by the Magic Missile spell',
      reactionTrigger: 'You are hit by an attack roll or targeted by Magic Missile',
      range: 'Self',
      components: 'V, S',
      duration: '1 round',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'An invisible barrier of magical force appears and protects you.',
        'Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from Magic Missile.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Reaction, which you take when you are hit by an attack roll or targeted by the Magic Missile spell',
      reactionTrigger: 'You are hit by an attack roll or targeted by Magic Missile',
      range: 'Self',
      components: 'V, S',
      duration: '1 round',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'An invisible barrier of magical force appears and protects you.',
        'Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from Magic Missile.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_magic_missile',
    name: 'Magic Missile',
    level: 1,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Creates 3 glowing darts of magical force that unerringly hit targets for 1d4 + 1 force damage each (+1 dart per higher slot).',
    tags: ['force', 'damage', 'auto-hit', 'evocation', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '1d4 + 1',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 4, staticBonus: 1),
      damageOrHealType: 'Force',
      description: [
        'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range.',
        'A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '1d4 + 1',
      scalingFormula: SpellScalingFormula(baseDiceCount: 1, diceSides: 4, staticBonus: 1),
      damageOrHealType: 'Force',
      description: [
        'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range.',
        'A dart deals 1d4 + 1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_guiding_bolt',
    name: 'Guiding Bolt',
    level: 1,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Deals 4d8 radiant damage on hit and grants Advantage on the next attack roll made against the target.',
    tags: ['radiant', 'attack', 'advantage', 'cleric', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: '1 round',
      classes: [SpellClass.cleric],
      rollFormula: '4d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 4, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant',
      description: [
        'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target.',
        'On a hit, the target takes 4d8 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage, thanks to the mystical dim light glittering on the target until then.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '120 feet',
      components: 'V, S',
      duration: '1 round',
      classes: [SpellClass.cleric],
      rollFormula: '4d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 4, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Radiant',
      description: [
        'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target.',
        'On a hit, the target takes 4d8 radiant damage, and the next attack roll made against this target before the end of your next turn has advantage, thanks to the mystical dim light glittering on the target until then.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_bless',
    name: 'Bless',
    level: 1,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Blesses up to three creatures, adding +1d4 to all their attack rolls and saving throws.',
    tags: ['buff', 'support', 'attack-bonus', 'save-bonus', 'concentration', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a sprinkling of holy water)',
      materialDetails: SpellMaterialComponent(description: 'a sprinkling of holy water'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.paladin],
      description: [
        'You bless up to three creatures of your choice within range.',
        'Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a sprinkling of holy water)',
      materialDetails: SpellMaterialComponent(description: 'a sprinkling of holy water'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.paladin],
      description: [
        'You bless up to three creatures of your choice within range.',
        'Whenever a target makes an attack roll or a saving throw before the spell ends, the target can roll a d4 and add the number rolled to the attack roll or saving throw.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_mage_armor',
    name: 'Mage Armor',
    level: 1,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Touches a willing unarmored creature to set its base AC to 13 + Dexterity modifier for 8 hours.',
    tags: ['defense', 'ac', 'abjuration', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a piece of cured leather)',
      materialDetails: SpellMaterialComponent(description: 'a piece of cured leather'),
      duration: '8 hours',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends.',
        'The target’s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S, M (a piece of cured leather)',
      materialDetails: SpellMaterialComponent(description: 'a piece of cured leather'),
      duration: '8 hours',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'You touch a willing creature who isn’t wearing armor, and a protective magical force surrounds it until the spell ends.',
        'The target’s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_thunderwave',
    name: 'Thunderwave',
    level: 1,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Deals 2d8 thunder damage and pushes creatures 10 feet away in a 15-foot cube on failed Constitution save.',
    tags: ['thunder', 'aoe', 'push', 'evocation', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot cube)',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard, SpellClass.artificer],
      rollFormula: '2d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Thunder',
      savingThrow: 'Constitution',
      description: [
        'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw.',
        'On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn’t pushed.',
        'Unsecured objects in the area are automatically pushed 10 feet away, and the spell emits a thunderous boom audible out to 300 feet.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot cube)',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.bard, SpellClass.druid, SpellClass.sorcerer, SpellClass.wizard, SpellClass.artificer],
      rollFormula: '2d8',
      scalingFormula: SpellScalingFormula(baseDiceCount: 2, diceSides: 8, dicePerSlotLevel: 1),
      damageOrHealType: 'Thunder',
      savingThrow: 'Constitution',
      description: [
        'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a Constitution saving throw.',
        'On a failed save, a creature takes 2d8 thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn’t pushed.',
        'Unsecured objects in the area are automatically pushed 10 feet away, and the spell emits a thunderous boom audible out to 300 feet.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d8 for each slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_find_familiar',
    name: 'Find Familiar',
    level: 1,
    school: SpellSchool.conjuration,
    isChangedIn2024: true,
    diffSummary: 'Summons a loyal celestial, fey, or fiend spirit taking the form of an animal companion (modernized stat block in 2024).',
    tags: ['minion', 'companion', 'ritual', 'conjuration', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 hour',
      ritual: true,
      range: '10 feet',
      components: 'V, S, M (10 gp worth of charcoal, incense, and herbs that must be consumed by fire in a brass brazier)',
      materialDetails: SpellMaterialComponent(
        description: '10 gp charcoal, incense, and herbs consumed in a brass brazier',
        hasCost: true,
        costInGp: 10,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.wizard],
      description: [
        'You gain the service of a familiar, a spirit that takes an animal form you choose (bat, cat, crab, frog, hawk, lizard, octopus, owl, poisonous snake, fish, rat, raven, sea horse, spider, or weasel).',
        'The familiar acts independently of you, but it always obeys your commands. In combat, it rolls its own initiative and acts on its own turn. A familiar can’t attack, but it can take other actions as normal.',
        'You can communicate with it telepathically and see through its senses while within 100 feet. When you cast a spell with a range of touch, your familiar can deliver the spell as if it had cast it.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 hour',
      ritual: true,
      range: '10 feet',
      components: 'V, S, M (10 gp worth of charcoal, incense, and herbs consumed in a brass brazier)',
      materialDetails: SpellMaterialComponent(
        description: '10 gp charcoal, incense, and herbs consumed in a brass brazier',
        hasCost: true,
        costInGp: 10,
        isConsumed: true,
      ),
      duration: 'Instantaneous',
      classes: [SpellClass.wizard],
      description: [
        'You gain the service of a familiar spirit that takes the form of an animal and obeys your commands. It can deliver touch spells and share its senses.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_inflict_wounds',
    name: 'Inflict Wounds',
    level: 1,
    school: SpellSchool.necromancy,
    isChangedIn2024: false,
    diffSummary: 'Make a melee spell attack dealing 3d10 necrotic damage on a hit.',
    tags: ['necrotic', 'melee-spell-attack', 'high-damage', 'cleric', 'level 1', 'necromancy'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      rollFormula: '3d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 10, dicePerSlotLevel: 1),
      damageOrHealType: 'Necrotic',
      description: [
        'Make a melee spell attack against a creature you can reach. On a hit, the target takes 3d10 necrotic damage.',
      ],
      higherLevels: 'When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d10 for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Touch',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.cleric],
      rollFormula: '3d10',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 10, dicePerSlotLevel: 1),
      damageOrHealType: 'Necrotic',
      description: [
        'Melee spell attack dealing 3d10 Necrotic damage on a hit.',
      ],
      higherLevels: 'Damage increases by 1d10 for each slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_command',
    name: 'Command',
    level: 1,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Speaks a one-word command (Approach, Drop, Flee, Grovel, Halt) that the target must obey on its next turn on failed Wisdom save.',
    tags: ['control', 'enchantment', 'wisdom-save', 'cleric', 'paladin', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V',
      duration: '1 round',
      classes: [SpellClass.cleric, SpellClass.paladin],
      savingThrow: 'Wisdom',
      description: [
        'You speak a one-word command to a creature you can see within range. The target must succeed on a Wisdom saving throw or follow the command on its next turn (Approach, Drop, Flee, Grovel, Halt).',
      ],
      higherLevels: 'You can target one additional creature for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet',
      components: 'V',
      duration: '1 round',
      classes: [SpellClass.cleric, SpellClass.paladin],
      savingThrow: 'Wisdom',
      description: [
        'Target obeys a 1-word command on its turn on failed Wisdom save.',
      ],
      higherLevels: 'Target +1 creature per slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_bane',
    name: 'Bane',
    level: 1,
    school: SpellSchool.enchantment,
    isChangedIn2024: false,
    diffSummary: 'Up to three creatures must subtract 1d4 from attack rolls and saving throws on failed Charisma save.',
    tags: ['debuff', 'save-penalty', 'attack-penalty', 'concentration', 'cleric', 'bard', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a drop of blood)',
      materialDetails: SpellMaterialComponent(description: 'a drop of blood'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric],
      savingThrow: 'Charisma',
      description: [
        'Up to three creatures of your choice that you can see within range must make Charisma saving throws. Whenever a target that fails makes an attack roll or saving throw before the spell ends, it must roll a d4 and subtract the number rolled from the total.',
      ],
      higherLevels: 'You can target one additional creature for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '30 feet',
      components: 'V, S, M (a drop of blood)',
      materialDetails: SpellMaterialComponent(description: 'a drop of blood'),
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.bard, SpellClass.cleric],
      savingThrow: 'Charisma',
      description: [
        'Forces up to 3 targets to subtract 1d4 from attack rolls and saving throws on failed Charisma save.',
      ],
      higherLevels: 'Target +1 creature per slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_sanctuary',
    name: 'Sanctuary',
    level: 1,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'Wards a creature: any enemy attacking or targeting it with a harmful spell must pass a Wisdom save or lose the attack or choose a new target.',
    tags: ['ward', 'defense', 'bonus-action', 'cleric', 'abjuration', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '30 feet',
      components: 'V, S, M (a small silver mirror)',
      materialDetails: SpellMaterialComponent(description: 'a small silver mirror'),
      duration: '1 minute',
      classes: [SpellClass.artificer, SpellClass.cleric],
      savingThrow: 'Wisdom',
      description: [
        'You ward a creature within range against attack. Any creature who targets the warded creature with an attack or a harmful spell must first make a Wisdom saving throw. On a failed save, the creature must choose a new target or lose the attack or spell.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '30 feet',
      components: 'V, S, M (small silver mirror)',
      materialDetails: SpellMaterialComponent(description: 'small silver mirror'),
      duration: '1 minute',
      classes: [SpellClass.artificer, SpellClass.cleric],
      savingThrow: 'Wisdom',
      description: [
        'Enemies must pass a Wisdom save to target the warded creature with attacks or harmful spells.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_shield_of_faith',
    name: 'Shield of Faith',
    level: 1,
    school: SpellSchool.abjuration,
    isChangedIn2024: false,
    diffSummary: 'A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC.',
    tags: ['buff', 'ac-bonus', 'bonus-action', 'concentration', 'cleric', 'paladin', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V, S, M (a small parchment with a bit of holy text written on it)',
      materialDetails: SpellMaterialComponent(description: 'parchment with holy text'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.paladin],
      description: [
        'A shimmering field appears and surrounds a creature of your choice within range, granting it a +2 bonus to AC for the duration.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Bonus Action',
      range: '60 feet',
      components: 'V, S, M (parchment with holy text)',
      materialDetails: SpellMaterialComponent(description: 'parchment with holy text'),
      duration: 'Concentration, up to 10 minutes',
      concentration: true,
      classes: [SpellClass.cleric, SpellClass.paladin],
      description: [
        'Grants +2 bonus to AC to target creature for up to 10 minutes.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_detect_magic',
    name: 'Detect Magic',
    level: 1,
    school: SpellSchool.divination,
    isChangedIn2024: false,
    diffSummary: 'Senses the presence of magic within 30 feet and reveals the school of magic of any active aura.',
    tags: ['utility', 'detect', 'ritual', 'concentration', 'divination', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (30-foot radius)',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      ritual: true,
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'For the duration, you sense the presence of magic within 30 feet of you. You can use your action to see a faint aura around any visible creature or object in the area that bears magic, and learn its school of magic.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (30-foot radius)',
      components: 'V, S',
      duration: 'Concentration, up to 10 minutes',
      ritual: true,
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.cleric, SpellClass.druid, SpellClass.paladin, SpellClass.ranger, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Detects magical presence and schools within 30 feet.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_burning_hands',
    name: 'Burning Hands',
    level: 1,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'A thin sheet of flames erupts from outstretched fingertips dealing 3d6 fire damage in a 15-foot cone on Dexterity save.',
    tags: ['fire', 'aoe', 'cone', 'evocation', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot cone)',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '3d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        'A 15-foot cone of flame deals 3d6 fire damage to creatures on a failed Dexterity save, or half on success. Ignites flammable objects.',
      ],
      higherLevels: 'Damage increases by 1d6 for each slot level above 1st.',
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: 'Self (15-foot cone)',
      components: 'V, S',
      duration: 'Instantaneous',
      classes: [SpellClass.sorcerer, SpellClass.wizard],
      rollFormula: '3d6',
      scalingFormula: SpellScalingFormula(baseDiceCount: 3, diceSides: 6, dicePerSlotLevel: 1),
      damageOrHealType: 'Fire',
      savingThrow: 'Dexterity',
      description: [
        '15-foot cone deals 3d6 Fire damage on failed Dexterity save (half on success).',
      ],
      higherLevels: 'Damage increases by 1d6 per slot level above 1st.',
    ),
  ),

  SpellItem(
    id: 'spell_faerie_fire',
    name: 'Faerie Fire',
    level: 1,
    school: SpellSchool.evocation,
    isChangedIn2024: false,
    diffSummary: 'Outlines objects and creatures in a 20-foot cube with colorful light on failed Dexterity save; attack rolls against them have advantage.',
    tags: ['advantage-attacks', 'invisibility-counter', 'aoe', 'concentration', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet (20-foot cube)',
      components: 'V',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.druid],
      savingThrow: 'Dexterity',
      description: [
        'Each object in a 20-foot cube is outlined in blue, green, or violet light. Any creature in the area must succeed on a Dexterity save or be outlined. Attack rolls against an affected creature have advantage, and it cannot benefit from being invisible.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Action',
      range: '60 feet (20-foot cube)',
      components: 'V',
      duration: 'Concentration, up to 1 minute',
      concentration: true,
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.druid],
      savingThrow: 'Dexterity',
      description: [
        'Outlines creatures in 20-ft cube in light, giving Advantage on attacks against them and negating Invisibility.',
      ],
    ),
  ),

  SpellItem(
    id: 'spell_feather_fall',
    name: 'Feather Fall',
    level: 1,
    school: SpellSchool.transmutation,
    isChangedIn2024: false,
    diffSummary: 'Reaction spell when falling: slows rate of descent of up to 5 falling creatures to 60 feet per round and negates fall damage.',
    tags: ['reaction', 'save-from-fall', 'transmutation', 'level 1'],
    rules2014: SpellEditionDetails(
      castingTime: '1 Reaction',
      range: '60 feet',
      components: 'V, M (a small feather or piece of down)',
      materialDetails: SpellMaterialComponent(description: 'a small feather or down'),
      duration: '1 minute',
      reactionTrigger: 'When you or a creature within 60 feet falls',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Choose up to five falling creatures within range. A falling creature’s rate of descent slows to 60 feet per round until the spell ends. If the creature lands before the spell ends, it takes no falling damage and can land on its feet.',
      ],
    ),
    rules2024: SpellEditionDetails(
      castingTime: '1 Reaction',
      range: '60 feet',
      components: 'V, M (a feather)',
      materialDetails: SpellMaterialComponent(description: 'a feather'),
      duration: '1 minute',
      reactionTrigger: 'When you or a creature within 60 feet falls',
      classes: [SpellClass.artificer, SpellClass.bard, SpellClass.sorcerer, SpellClass.wizard],
      description: [
        'Slows fall rate of up to 5 creatures to 60 ft/rnd and prevents fall damage entirely.',
      ],
    ),
  ),
];
