import '../magic_item_data.dart';

/// Complete catalog of canonical SRD 5.1 / 5.2 nonmagical adventuring gear, equipment, and tools.
class SrdAdventuringGear {
  static const List<MagicItem> items = [
    MagicItem(
      id: 'backpack',
      name: 'Backpack',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'container', 'storage', 'equipment'],
      rules2014: ItemEditionDetails(
        summary: 'Holds 1 cubic foot or 30 pounds of gear. You can strap items like a bedroll or rope to the outside.',
        description: 'A standard leather or canvas backpack designed for carrying adventuring supplies across dungeons and wilderness.',
        properties: [
          'Capacity: 1 cubic foot / 30 pounds.',
          'Weight: 5 lbs.',
          'Cost: 2 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Holds 1 cubic foot or 30 pounds of gear. You can strap items like a bedroll or rope to the outside.',
        description: 'A standard leather or canvas backpack designed for carrying adventuring supplies across dungeons and wilderness.',
        properties: [
          'Capacity: 1 cubic foot / 30 pounds.',
          'Weight: 5 lbs.',
          'Cost: 2 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'bedroll',
      name: 'Bedroll',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'camp', 'rest', 'equipment'],
      rules2014: ItemEditionDetails(
        summary: 'Comfortable padded sleeping roll for taking short and long rests in the wild.',
        description: 'A quilted blanket and waterproof ground cloth rolled together with leather straps.',
        properties: [
          'Weight: 7 lbs.',
          'Cost: 1 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Comfortable padded sleeping roll for taking short and long rests in the wild.',
        description: 'A quilted blanket and waterproof ground cloth rolled together with leather straps.',
        properties: [
          'Weight: 7 lbs.',
          'Cost: 1 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'crowbar',
      name: 'Crowbar',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'tool', 'utility', 'leverage'],
      rules2014: ItemEditionDetails(
        summary: 'Grants Advantage on Strength checks where the crowbar\'s leverage can be applied.',
        description: 'A sturdy iron bar with a flattened, curved end designed for prying open stuck doors and chests.',
        properties: [
          'Advantage on applicable Strength ability checks.',
          'Weight: 5 lbs.',
          'Cost: 2 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Grants Advantage on Strength (Athletics) checks where leverage is applicable.',
        description: 'A sturdy iron bar with a flattened, curved end designed for prying open stuck doors and chests.',
        properties: [
          'Advantage on applicable Strength checks.',
          'Weight: 5 lbs.',
          'Cost: 2 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'grappling_hook',
      name: 'Grappling Hook',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'climbing', 'utility'],
      rules2014: ItemEditionDetails(
        summary: 'Four-pronged iron hook tied to a rope to secure climbs over walls and ledges.',
        description: 'An anchor hook forged of resilient iron, essential for scale ascents and securing rope lines.',
        properties: [
          'Weight: 4 lbs.',
          'Cost: 2 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Four-pronged iron hook tied to a rope to secure climbs over walls and ledges.',
        description: 'An anchor hook forged of resilient iron, essential for scale ascents and securing rope lines.',
        properties: [
          'Weight: 4 lbs.',
          'Cost: 2 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'healers_kit',
      name: 'Healer\'s Kit',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'healing', 'stabilize', 'medical'],
      rules2014: ItemEditionDetails(
        summary: 'Contains 10 uses. As an action, expend 1 use to stabilize a dying creature without making a Medicine check.',
        description: 'A leather pouch containing bandages, salves, and splints to treat battlefield casualties.',
        activation: '1 Action',
        properties: [
          '10 uses per kit.',
          'Stabilizes a creature at 0 HP with no roll required.',
          'Weight: 3 lbs.',
          'Cost: 5 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Contains 10 uses. As an action, expend 1 use to stabilize a dying creature without making a Medicine check.',
        description: 'A leather pouch containing bandages, salves, and splints to treat battlefield casualties.',
        activation: '1 Action',
        properties: [
          '10 uses per kit.',
          'Stabilizes a creature at 0 HP with no check.',
          'Weight: 3 lbs.',
          'Cost: 5 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'holy_water',
      name: 'Holy Water (Flask)',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'radiant', 'undead', 'fiend', 'combat'],
      damageAccent: DamageAccent.radiant,
      rules2014: ItemEditionDetails(
        summary: 'Improvised ranged attack (range 20 ft). On hit against a Fiend or Undead, deals 2d6 radiant damage.',
        description: 'Water blessed by a cleric or paladin through a ritual in a consecrated sanctuary.',
        activation: '1 Action',
        properties: [
          'Ranged Improvised Weapon Attack (20 ft).',
          'Deals 2d6 radiant damage against Fiends and Undead.',
          'Weight: 1 lb.',
          'Cost: 25 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Improvised ranged attack (range 20 ft). On hit against a Fiend or Undead, deals 2d6 radiant damage.',
        description: 'Water blessed by a cleric or paladin through a ritual in a consecrated sanctuary.',
        activation: '1 Action',
        properties: [
          'Ranged Improvised Weapon Attack (20 ft).',
          'Deals 2d6 radiant damage against Fiends and Undead.',
          'Weight: 1 lb.',
          'Cost: 25 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'bullseye_lantern',
      name: 'Lantern, Bullseye',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'light', 'vision', 'exploration'],
      rules2014: ItemEditionDetails(
        summary: 'Casts bright light in a 60-foot cone and dim light for an additional 60 feet for 6 hours on 1 flask of oil.',
        description: 'A hooded lantern with an adjustable shutter and reflective lens to focus light in a long directional beam.',
        properties: [
          'Bright light: 60-ft cone; Dim light: additional 60 ft.',
          'Burns for 6 hours per 1 pint (flask) of oil.',
          'Weight: 2 lbs.',
          'Cost: 10 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Casts bright light in a 60-foot cone and dim light for an additional 60 feet for 6 hours on 1 flask of oil.',
        description: 'A hooded lantern with an adjustable shutter and reflective lens to focus light in a long directional beam.',
        properties: [
          'Bright light: 60-ft cone; Dim light: additional 60 ft.',
          'Burns for 6 hours per flask of oil.',
          'Weight: 2 lbs.',
          'Cost: 10 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'hooded_lantern',
      name: 'Lantern, Hooded',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'light', 'vision', 'exploration'],
      rules2014: ItemEditionDetails(
        summary: 'Casts bright light in a 30-foot radius and dim light for an additional 30 feet for 6 hours on 1 flask of oil.',
        description: 'A cylindrical glass lantern with a movable metal hood that can be lowered to reduce light to 5-foot dim light.',
        properties: [
          'Bright light: 30-ft radius; Dim light: additional 30 ft.',
          'Hood down: 5-ft dim light.',
          'Weight: 2 lbs.',
          'Cost: 5 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Casts bright light in a 30-foot radius and dim light for an additional 30 feet for 6 hours on 1 flask of oil.',
        description: 'A cylindrical glass lantern with a movable metal hood that can be lowered to reduce light to 5-foot dim light.',
        properties: [
          'Bright light: 30-ft radius; Dim light: additional 30 ft.',
          'Hood down: 5-ft dim light.',
          'Weight: 2 lbs.',
          'Cost: 5 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'oil_flask',
      name: 'Oil (Flask)',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'fire', 'fuel', 'combat', 'utility'],
      damageAccent: DamageAccent.fire,
      rules2014: ItemEditionDetails(
        summary: 'Used as fuel for lanterns (6 hrs) or splashed as a ranged attack (20 ft) to add 5 fire damage when ignited.',
        description: 'A clay flask containing 1 pint of combustible mineral oil.',
        activation: '1 Action',
        properties: [
          'Fuel: 6 hours in a lantern.',
          'Attack: Ranged improvised weapon (20 ft).',
          'Ignition: Deals 5 extra fire damage on hit from fire sources for 2 rounds.',
          'Weight: 1 lb.',
          'Cost: 1 sp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Used as fuel for lanterns (6 hrs) or splashed as a ranged attack (20 ft) to add 5 fire damage when ignited.',
        description: 'A clay flask containing 1 pint of combustible mineral oil.',
        activation: '1 Action',
        properties: [
          'Fuel: 6 hours in a lantern.',
          'Attack: Ranged improvised weapon (20 ft).',
          'Ignition: Deals 5 extra fire damage on fire attacks.',
          'Weight: 1 lb.',
          'Cost: 1 sp.',
        ],
      ),
    ),
    MagicItem(
      id: 'rations',
      name: 'Rations (1 Day)',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'food', 'survival'],
      rules2014: ItemEditionDetails(
        summary: 'Compact dry food suitable for extended travel, including jerky, dried fruit, hardtack, and nuts.',
        description: 'One day\'s worth of preserved survival sustenance for a Medium creature.',
        properties: [
          'Weight: 2 lbs.',
          'Cost: 5 sp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Compact dry food suitable for extended travel, including jerky, dried fruit, hardtack, and nuts.',
        description: 'One day\'s worth of preserved survival sustenance for a Medium creature.',
        properties: [
          'Weight: 2 lbs.',
          'Cost: 5 sp.',
        ],
      ),
    ),
    MagicItem(
      id: 'rope_silk',
      name: 'Rope, Silk (50 Feet)',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'utility', 'climbing', 'restraint'],
      rules2014: ItemEditionDetails(
        summary: '50-foot lightweight braided silk rope. Has 2 hit points and can be burst with a DC 17 Strength check.',
        description: 'Strong, supple rope woven from spider or silkworm thread, much lighter than hempen rope.',
        properties: [
          'Length: 50 feet.',
          'HP: 2; Burst DC: 17 Strength.',
          'Weight: 5 lbs.',
          'Cost: 10 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: '50-foot lightweight braided silk rope. Has 2 hit points and can be burst with a DC 17 Strength check.',
        description: 'Strong, supple rope woven from spider or silkworm thread, much lighter than hempen rope.',
        properties: [
          'Length: 50 feet.',
          'HP: 2; Burst DC: 17 Strength.',
          'Weight: 5 lbs.',
          'Cost: 10 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'spyglass',
      name: 'Spyglass',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'vision', 'scouting', 'optical'],
      rules2014: ItemEditionDetails(
        summary: 'Objects viewed through the spyglass are magnified to twice their size.',
        description: 'A telescoping brass tube with polished glass lenses for naval navigation and long-range scouting.',
        properties: [
          '2x visual magnification.',
          'Weight: 1 lb.',
          'Cost: 1,000 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Objects viewed through the spyglass are magnified to twice their size.',
        description: 'A telescoping brass tube with polished glass lenses for naval navigation and long-range scouting.',
        properties: [
          '2x visual magnification.',
          'Weight: 1 lb.',
          'Cost: 1,000 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'torch',
      name: 'Torch',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'light', 'fire', 'exploration'],
      damageAccent: DamageAccent.fire,
      rules2014: ItemEditionDetails(
        summary: 'Burns for 1 hour, shedding bright light in a 20-foot radius and dim light for an additional 20 feet. Deals 1 fire damage on hit.',
        description: 'A wooden rod wrapped in pitch-soaked cloth.',
        properties: [
          'Bright light: 20-ft radius; Dim light: additional 20 ft.',
          'Burns for 1 hour.',
          'Melee attack deals 1 fire damage.',
          'Weight: 1 lb.',
          'Cost: 1 cp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Burns for 1 hour, shedding bright light in a 20-foot radius and dim light for an additional 20 feet. Deals 1 fire damage on hit.',
        description: 'A wooden rod wrapped in pitch-soaked cloth.',
        properties: [
          'Bright light: 20-ft radius; Dim light: additional 20 ft.',
          'Burns for 1 hour.',
          'Melee attack deals 1 fire damage.',
          'Weight: 1 lb.',
          'Cost: 1 cp.',
        ],
      ),
    ),
    MagicItem(
      id: 'waterskin',
      name: 'Waterskin',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['gear', 'container', 'survival'],
      rules2014: ItemEditionDetails(
        summary: 'Holds 4 pints (half a gallon) of liquid.',
        description: 'A leather bladder with a wooden plug and shoulder strap.',
        properties: [
          'Capacity: 4 pints liquid.',
          'Weight: 5 lbs (full).',
          'Cost: 2 sp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Holds 4 pints (half a gallon) of liquid.',
        description: 'A leather bladder with a wooden plug and shoulder strap.',
        properties: [
          'Capacity: 4 pints liquid.',
          'Weight: 5 lbs (full).',
          'Cost: 2 sp.',
        ],
      ),
    ),
    MagicItem(
      id: 'thieves_tools',
      name: 'Thieves\' Tools',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['tools', 'lockpicking', 'traps', 'dexterity'],
      rules2014: ItemEditionDetails(
        summary: 'Allows adding proficiency bonus to ability checks made to disarm traps or pick mechanical locks.',
        description: 'A set of lock picks, tension wrenches, small mirror, narrow file, and pliers in a folding leather case.',
        properties: [
          'Used for picking locks and disarming mechanical traps.',
          'Weight: 1 lb.',
          'Cost: 25 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'Allows adding proficiency bonus to Dexterity checks made with thieves\' tools to pick locks or disarm traps. Uses DC rules specified in the 2024 equipment chapter.',
        description: 'A set of lock picks, tension wrenches, small mirror, narrow file, and pliers in a folding leather case.',
        properties: [
          'Used for Pick Lock (Sleight of Hand) and Disarm Trap checks.',
          'Weight: 1 lb.',
          'Cost: 25 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'arcane_focus_wand',
      name: 'Arcane Focus (Wand / Crystal / Orb)',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['focus', 'spellcasting', 'arcane', 'wizard', 'sorcerer', 'warlock'],
      rules2014: ItemEditionDetails(
        summary: 'A special item designed to channel the power of arcane spells, substituting for non-costly material components.',
        description: 'Crafted from crystal, orbs of glass, carved wands of weirwood, or polished rods.',
        properties: [
          'Substitutes for material components with no gp cost.',
          'Weight: 1–3 lbs.',
          'Cost: 5–20 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'A spellcasting focus designed to channel arcane spells, replacing non-costly material components.',
        description: 'Crafted from crystal, orbs of glass, carved wands of weirwood, or polished rods.',
        properties: [
          'Substitutes for material components with no gp cost.',
          'Weight: 1–3 lbs.',
          'Cost: 5–20 gp.',
        ],
      ),
    ),
    MagicItem(
      id: 'holy_symbol_amulet',
      name: 'Holy Symbol (Amulet / Emblem / Reliquary)',
      category: ItemCategory.adventuringGear,
      rarity: ItemRarity.nonmagical,
      requiresAttunement: false,
      tags: ['focus', 'spellcasting', 'divine', 'cleric', 'paladin'],
      damageAccent: DamageAccent.radiant,
      rules2014: ItemEditionDetails(
        summary: 'A representation of a deity or pantheon used as a divine spellcasting focus. Can be worn as an amulet or emblazoned on a shield.',
        description: 'Consecrated icon, sunburst, or miniature reliquary honoring a divine power.',
        properties: [
          'Can be emblazoned on a shield or worn openly.',
          'Substitutes for non-costly divine material components.',
          'Weight: 1 lb.',
          'Cost: 5 gp.',
        ],
      ),
      rules2024: ItemEditionDetails(
        summary: 'A representation of a deity or pantheon used as a divine spellcasting focus. Can be worn as an amulet or emblazoned on a shield.',
        description: 'Consecrated icon, sunburst, or miniature reliquary honoring a divine power.',
        properties: [
          'Can be emblazoned on a shield or worn openly.',
          'Substitutes for non-costly divine material components.',
          'Weight: 1 lb.',
          'Cost: 5 gp.',
        ],
      ),
    ),
  ];
}
