import 'package:flutter/material.dart';
import '../minion_stat_block.dart';
import '../summon_preset.dart';

class BeastSummons {
  // --- CR 1/4 BEASTS (8 Beasts summoned at 3rd level) ---
  static const wolf = MinionStatBlock(
    id: 'beast_wolf',
    name: 'Wolf',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 13,
    armorType: 'natural armor',
    maxHp: 11,
    hitDice: '2d8 + 2',
    speed: '40 ft.',
    strScore: 12,
    dexScore: 15,
    conScore: 12,
    intScore: 3,
    wisScore: 12,
    chaScore: 6,
    skills: 'Perception +3, Stealth +4',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 50,
    hasPackTactics: true,
    traits: [
      CreatureTrait(
        name: 'Keen Hearing and Smell',
        description: 'The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
      ),
      CreatureTrait(
        name: 'Pack Tactics',
        description: 'The wolf has advantage on an attack roll against a creature if at least one of the wolf\'s allies is within 5 feet of the creature and the ally isn\'t incapacitated.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '7 (2d4 + 2) piercing damage + DC 11 Str save or prone',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 2,
    damageDiceSides: 4,
    damageBonus: 2,
    damageType: 'Piercing',
    specialTrait: 'Pack Tactics + Trip (DC 11 Strength save)',
    accentColor: Color(0xFF8D6E63),
  );

  static const boar = MinionStatBlock(
    id: 'beast_boar',
    name: 'Boar',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 11,
    armorType: 'natural armor',
    maxHp: 11,
    hitDice: '2d8 + 2',
    speed: '40 ft.',
    strScore: 13,
    dexScore: 11,
    conScore: 12,
    intScore: 2,
    wisScore: 9,
    chaScore: 5,
    senses: 'passive Perception 9',
    languages: '—',
    xp: 50,
    traits: [
      CreatureTrait(
        name: 'Charge',
        description: 'If the boar moves at least 20 feet straight toward a target and then hits it with a tusk attack on the same turn, the target takes an extra 3 (1d6) slashing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.',
      ),
      CreatureTrait(
        name: 'Relentless (Recharges after a Short or Long Rest)',
        description: 'If the boar takes 7 damage or less that would reduce it to 0 hit points, it is reduced to 1 hit point instead.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Tusk',
        description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 3,
        reach: 'reach 5 ft.',
        hitDamage: '4 (1d6 + 1) slashing damage',
      ),
    ],
    attackBonus: 3,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 1,
    damageType: 'Slashing',
    specialTrait: 'Charge (Extra 1d6 damage, DC 11 Str save or prone) & Relentless',
    accentColor: Color(0xFF8D6E63),
  );

  static const panther = MinionStatBlock(
    id: 'beast_panther',
    name: 'Panther',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 13,
    hitDice: '3d8',
    speed: '50 ft., climb 40 ft.',
    strScore: 14,
    dexScore: 15,
    conScore: 10,
    intScore: 3,
    wisScore: 14,
    chaScore: 7,
    skills: 'Perception +4, Stealth +6',
    senses: 'passive Perception 14',
    languages: '—',
    xp: 50,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The panther has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
      CreatureTrait(
        name: 'Pounce',
        description: 'If the panther moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 12 Strength saving throw or be knocked prone. If the target is prone, the panther can make one bite attack against it as a bonus action.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '5 (1d6 + 2) piercing damage',
      ),
      CreatureAction(
        name: 'Claw',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '4 (1d4 + 2) slashing damage',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 2,
    damageType: 'Slashing',
    specialTrait: 'Keen Smell & Pounce (DC 12 Str save or prone + bonus bite)',
    accentColor: Color(0xFF546E7A),
  );

  static const giantBadger = MinionStatBlock(
    id: 'beast_giant_badger',
    name: 'Giant Badger',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 10,
    maxHp: 13,
    hitDice: '2d8 + 4',
    speed: '30 ft., burrow 10 ft.',
    strScore: 13,
    dexScore: 10,
    conScore: 15,
    intScore: 2,
    wisScore: 12,
    chaScore: 5,
    senses: 'darkvision 30 ft., passive Perception 11',
    languages: '—',
    xp: 50,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The badger has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The badger makes two attacks: one with its bite and one with its claws.',
      ),
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 3,
        reach: 'reach 5 ft.',
        hitDamage: '4 (1d6 + 1) piercing damage',
      ),
      CreatureAction(
        name: 'Claws',
        description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (2d4 + 1) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 3,
        reach: 'reach 5 ft.',
        hitDamage: '6 (2d4 + 1) slashing damage',
      ),
    ],
    attackBonus: 3,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 1,
    damageType: 'Slashing',
    specialTrait: 'Multiattack (Bite + Claws) & Burrow 10 ft.',
    accentColor: Color(0xFF455A64),
  );

  static const giantPoisonousSnake = MinionStatBlock(
    id: 'beast_giant_poisonous_snake',
    name: 'Giant Poisonous Snake',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 14,
    maxHp: 11,
    hitDice: '2d8 + 2',
    speed: '30 ft., swim 30 ft.',
    strScore: 10,
    dexScore: 18,
    conScore: 13,
    intScore: 2,
    wisScore: 10,
    chaScore: 3,
    skills: 'Perception +2',
    senses: 'blindsight 10 ft., passive Perception 12',
    languages: '—',
    xp: 50,
    traits: [],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 6 (1d4 + 4) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much damage on a successful one.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 10 ft.',
        hitDamage: '6 (1d4 + 4) piercing + 10 (3d6) poison',
      ),
    ],
    attackBonus: 6,
    damageDiceCount: 1,
    damageDiceSides: 4,
    damageBonus: 4,
    damageType: 'Piercing',
    secondaryDamageDiceCount: 3,
    secondaryDamageDiceSides: 6,
    secondaryDamageType: 'Poison',
    specialTrait: 'Bite (1d4+4 piercing + 3d6 poison, reach 10 ft.)',
    accentColor: Color(0xFF4CAF50),
  );

  // --- CR 1/2 BEASTS (4 Beasts summoned at 3rd level) ---
  static const ape = MinionStatBlock(
    id: 'beast_ape',
    name: 'Ape',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 19,
    hitDice: '3d8 + 6',
    speed: '30 ft., climb 30 ft.',
    strScore: 16,
    dexScore: 14,
    conScore: 14,
    intScore: 6,
    wisScore: 12,
    chaScore: 7,
    skills: 'Athletics +5, Perception +3',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 100,
    traits: [],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The ape makes two fist attacks.',
      ),
      CreatureAction(
        name: 'Fist',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) bludgeoning damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '6 (1d6 + 3) bludgeoning damage',
      ),
      CreatureAction(
        name: 'Rock',
        description: 'Ranged Weapon Attack: +5 to hit, range 25/50 ft., one target. Hit: 6 (1d6 + 3) bludgeoning damage.',
        attackType: 'Ranged Weapon Attack',
        attackBonus: 5,
        reach: 'range 25/50 ft.',
        hitDamage: '6 (1d6 + 3) bludgeoning damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 3,
    damageType: 'Bludgeoning',
    specialTrait: 'Multiattack (2 Fists) + Ranged Rock Throw',
    accentColor: Color(0xFF5D4037),
  );

  static const blackBear = MinionStatBlock(
    id: 'beast_black_bear',
    name: 'Black Bear',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 11,
    armorType: 'natural armor',
    maxHp: 19,
    hitDice: '3d8 + 6',
    speed: '40 ft., climb 30 ft.',
    strScore: 15,
    dexScore: 10,
    conScore: 14,
    intScore: 2,
    wisScore: 12,
    chaScore: 7,
    skills: 'Perception +3',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 100,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The bear has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The bear makes two attacks: one with its bite and one with its claws.',
      ),
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '5 (1d6 + 2) piercing damage',
      ),
      CreatureAction(
        name: 'Claws',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '7 (2d4 + 2) slashing damage',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 2,
    damageType: 'Slashing',
    specialTrait: 'Multiattack (Bite + Claws) & Keen Smell',
    accentColor: Color(0xFF4E342E),
  );

  static const crocodile = MinionStatBlock(
    id: 'beast_crocodile',
    name: 'Crocodile',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1/2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    armorType: 'natural armor',
    maxHp: 19,
    hitDice: '3d10 + 3',
    speed: '20 ft., swim 30 ft.',
    strScore: 15,
    dexScore: 10,
    conScore: 13,
    intScore: 2,
    wisScore: 10,
    chaScore: 5,
    skills: 'Stealth +2',
    senses: 'passive Perception 10',
    languages: '—',
    xp: 100,
    traits: [
      CreatureTrait(
        name: 'Hold Breath',
        description: 'The crocodile can hold its breath for 15 minutes.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10 + 2) piercing damage, and the target is grappled (escape DC 12). Until this grapple ends, the target is restrained, and the crocodile can\'t bite another target.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '7 (1d10 + 2) piercing damage + Grapple & Restrain',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 10,
    damageBonus: 2,
    damageType: 'Piercing',
    specialTrait: 'Bite & Grapple (DC 12 Str escape, target restrained)',
    accentColor: Color(0xFF2E7D32),
  );

  // --- CR 1 BEASTS (2 Beasts summoned at 3rd level) ---
  static const direWolf = MinionStatBlock(
    id: 'beast_dire_wolf',
    name: 'Dire Wolf',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 14,
    armorType: 'natural armor',
    maxHp: 37,
    hitDice: '5d10 + 10',
    speed: '50 ft.',
    strScore: 17,
    dexScore: 15,
    conScore: 15,
    intScore: 3,
    wisScore: 12,
    chaScore: 7,
    skills: 'Perception +3, Stealth +4',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 200,
    hasPackTactics: true,
    traits: [
      CreatureTrait(
        name: 'Keen Hearing and Smell',
        description: 'The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
      ),
      CreatureTrait(
        name: 'Pack Tactics',
        description: 'The wolf has advantage on an attack roll against a creature if at least one of the wolf\'s allies is within 5 feet of the creature and the ally isn\'t incapacitated.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '10 (2d6 + 3) piercing damage + DC 13 Str save or prone',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 3,
    damageType: 'Piercing',
    specialTrait: 'Pack Tactics + Trip (DC 13 Strength save)',
    accentColor: Color(0xFF6D4C41),
  );

  static const giantHyena = MinionStatBlock(
    id: 'beast_giant_hyena',
    name: 'Giant Hyena',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 45,
    hitDice: '6d10 + 12',
    speed: '50 ft.',
    strScore: 16,
    dexScore: 14,
    conScore: 14,
    intScore: 2,
    wisScore: 12,
    chaScore: 7,
    skills: 'Perception +3',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 200,
    traits: [
      CreatureTrait(
        name: 'Rampage',
        description: 'When the hyena reduces a creature to 0 hit points with a melee attack on its turn, the hyena can take a bonus action to move up to half its speed and make a bite attack.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '10 (2d6 + 3) piercing damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 3,
    damageType: 'Piercing',
    specialTrait: 'Rampage (Bonus bite attack when reducing creature to 0 HP)',
    accentColor: Color(0xFFA1887F),
  );

  static const giantSpider = MinionStatBlock(
    id: 'beast_giant_spider',
    name: 'Giant Spider',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 14,
    armorType: 'natural armor',
    maxHp: 26,
    hitDice: '4d10 + 4',
    speed: '30 ft., climb 30 ft.',
    strScore: 14,
    dexScore: 16,
    conScore: 12,
    intScore: 2,
    wisScore: 11,
    chaScore: 4,
    skills: 'Stealth +7',
    senses: 'blindsight 10 ft., darkvision 60 ft., passive Perception 10',
    languages: '—',
    xp: 200,
    traits: [
      CreatureTrait(
        name: 'Spider Climb',
        description: 'The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.',
      ),
      CreatureTrait(
        name: 'Web Sense',
        description: 'While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.',
      ),
      CreatureTrait(
        name: 'Web Walker',
        description: 'The spider ignores movement restrictions caused by webbing.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 7 (1d8 + 3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 9 (2d8) poison damage on a failed save, or half as much damage on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, even after regaining hit points, and is paralyzed while poisoned in this way.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '7 (1d8 + 3) piercing + 9 (2d8) poison',
      ),
      CreatureAction(
        name: 'Web (Recharge 5–6)',
        description: 'Ranged Weapon Attack: +5 to hit, range 30/60 ft., one creature. Hit: The target is restrained by webbing. As an action, the restrained target can make a DC 12 Strength check, bursting the webbing on a success.',
        attackType: 'Ranged Weapon Attack',
        attackBonus: 5,
        reach: 'range 30/60 ft.',
        hitDamage: 'Target is restrained by webbing (DC 12 Strength escape)',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 1,
    damageDiceSides: 8,
    damageBonus: 3,
    damageType: 'Piercing',
    secondaryDamageDiceCount: 2,
    secondaryDamageDiceSides: 8,
    secondaryDamageType: 'Poison',
    specialTrait: 'Bite (1d8+3 piercing + 2d8 poison) + Webbing & Spider Climb',
    accentColor: Color(0xFF43A047),
  );

  static const giantEagle = MinionStatBlock(
    id: 'beast_giant_eagle',
    name: 'Giant Eagle',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'neutral good',
    ac: 13,
    maxHp: 26,
    hitDice: '4d10 + 4',
    speed: '10 ft., fly 80 ft.',
    strScore: 16,
    dexScore: 17,
    conScore: 13,
    intScore: 8,
    wisScore: 14,
    chaScore: 10,
    skills: 'Perception +4',
    senses: 'passive Perception 14',
    languages: 'Giant Eagle, understands Common and Auran but can\'t speak them',
    xp: 200,
    traits: [
      CreatureTrait(
        name: 'Keen Sight',
        description: 'The eagle has advantage on Wisdom (Perception) checks that rely on sight.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The eagle makes two attacks: one with its beak and one with its talons.',
      ),
      CreatureAction(
        name: 'Beak',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '6 (1d6 + 3) piercing damage',
      ),
      CreatureAction(
        name: 'Talons',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '10 (2d6 + 3) slashing damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 3,
    damageType: 'Slashing',
    specialTrait: 'Multiattack (Beak + Talons) & Fly 80 ft.',
    accentColor: Color(0xFFFB8C00),
  );

  static const brownBear = MinionStatBlock(
    id: 'beast_brown_bear',
    name: 'Brown Bear',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 11,
    armorType: 'natural armor',
    maxHp: 34,
    hitDice: '4d10 + 12',
    speed: '40 ft., climb 30 ft.',
    strScore: 19,
    dexScore: 10,
    conScore: 16,
    intScore: 2,
    wisScore: 13,
    chaScore: 7,
    skills: 'Perception +3',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 200,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The bear has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The bear makes two attacks: one with its bite and one with its claws.',
      ),
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '8 (1d8 + 4) piercing damage',
      ),
      CreatureAction(
        name: 'Claws',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '11 (2d6 + 4) slashing damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 4,
    damageType: 'Slashing',
    specialTrait: 'Multiattack (Bite + Claws) & Keen Smell',
    accentColor: Color(0xFFFB8C00),
  );

  static const lion = MinionStatBlock(
    id: 'beast_lion',
    name: 'Lion',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 26,
    hitDice: '4d10 + 4',
    speed: '50 ft.',
    strScore: 17,
    dexScore: 15,
    conScore: 13,
    intScore: 3,
    wisScore: 12,
    chaScore: 8,
    skills: 'Perception +3, Stealth +6',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 200,
    hasPackTactics: true,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The lion has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
      CreatureTrait(
        name: 'Pack Tactics',
        description: 'The lion has advantage on an attack roll against a creature if at least one of the lion\'s allies is within 5 feet of the creature and the ally isn\'t incapacitated.',
      ),
      CreatureTrait(
        name: 'Pounce',
        description: 'If the lion moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the lion can make one bite attack against it as a bonus action.',
      ),
      CreatureTrait(
        name: 'Running Leap',
        description: 'With a 10-foot running start, the lion can long jump up to 25 feet.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '7 (1d8 + 3) piercing damage',
      ),
      CreatureAction(
        name: 'Claw',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '6 (1d6 + 3) slashing damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 1,
    damageDiceSides: 8,
    damageBonus: 3,
    damageType: 'Slashing',
    specialTrait: 'Pack Tactics & Pounce (DC 13 Str save or prone + bonus bite)',
    accentColor: Color(0xFFFFB74D),
  );

  static const tiger = MinionStatBlock(
    id: 'beast_tiger',
    name: 'Tiger',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 37,
    hitDice: '5d10 + 10',
    speed: '40 ft.',
    strScore: 17,
    dexScore: 15,
    conScore: 14,
    intScore: 3,
    wisScore: 12,
    chaScore: 8,
    skills: 'Perception +3, Stealth +6',
    senses: 'darkvision 60 ft., passive Perception 13',
    languages: '—',
    xp: 200,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The tiger has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
      CreatureTrait(
        name: 'Pounce',
        description: 'If the tiger moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the tiger can make one bite attack against it as a bonus action.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10 + 3) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '8 (1d10 + 3) piercing damage',
      ),
      CreatureAction(
        name: 'Claw',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '7 (1d8 + 3) slashing damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 1,
    damageDiceSides: 10,
    damageBonus: 3,
    damageType: 'Slashing',
    specialTrait: 'Pounce (DC 13 Str save or prone + bonus bite) & Darkvision',
    accentColor: Color(0xFFE65100),
  );

  static const giantToad = MinionStatBlock(
    id: 'beast_giant_toad',
    name: 'Giant Toad',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 11,
    maxHp: 39,
    hitDice: '6d10 + 6',
    speed: '20 ft., swim 40 ft.',
    strScore: 15,
    dexScore: 13,
    conScore: 13,
    intScore: 2,
    wisScore: 10,
    chaScore: 3,
    senses: 'darkvision 30 ft., passive Perception 10',
    languages: '—',
    xp: 200,
    traits: [
      CreatureTrait(
        name: 'Amphibious',
        description: 'The toad can breathe air and water.',
      ),
      CreatureTrait(
        name: 'Standing Leap',
        description: 'The toad\'s long jump is up to 20 feet and its high jump is up to 10 feet, with or without a running start.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10 + 2) piercing damage plus 5 (1d10) poison damage, and the target is grappled (escape DC 13). Until this grapple ends, the target is restrained.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '7 (1d10 + 2) piercing + 5 (1d10) poison + Grapple',
      ),
      CreatureAction(
        name: 'Swallow',
        description: 'The toad makes one bite attack against a Medium or smaller target it is grappling. If the attack hits, the target is swallowed, and the grapple ends. The swallowed target is blinded and restrained, it has total cover against attacks and other effects outside the toad, and it takes 10 (3d6) acid damage at the start of each of the toad\'s turns.',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 10,
    damageBonus: 2,
    damageType: 'Piercing',
    secondaryDamageDiceCount: 1,
    secondaryDamageDiceSides: 10,
    secondaryDamageType: 'Poison',
    specialTrait: 'Bite (1d10+2 piercing + 1d10 poison) & Swallow (3d6 acid)',
    accentColor: Color(0xFF689F38),
  );

  // --- CR 2 BEASTS (1 Beast summoned at 3rd level) ---
  static const rhinoceros = MinionStatBlock(
    id: 'beast_rhinoceros',
    name: 'Rhinoceros',
    sizeDisplay: 'Large',
    crDisplay: 'CR 2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 11,
    armorType: 'natural armor',
    maxHp: 45,
    hitDice: '6d10 + 12',
    speed: '40 ft.',
    strScore: 21,
    dexScore: 8,
    conScore: 15,
    intScore: 2,
    wisScore: 12,
    chaScore: 6,
    senses: 'passive Perception 11',
    languages: '—',
    xp: 450,
    traits: [
      CreatureTrait(
        name: 'Charge',
        description: 'If the rhinoceros moves at least 20 feet straight toward a target and then hits it with a gore attack on the same turn, the target takes an extra 9 (2d8) bludgeoning damage. If the target is a creature, it must succeed on a DC 15 Strength saving throw or be knocked prone.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Gore',
        description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) bludgeoning damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 7,
        reach: 'reach 5 ft.',
        hitDamage: '14 (2d8 + 5) bludgeoning damage',
      ),
    ],
    attackBonus: 7,
    damageDiceCount: 2,
    damageDiceSides: 8,
    damageBonus: 5,
    damageType: 'Bludgeoning',
    specialTrait: 'Charge (Extra 2d8 damage, DC 15 Strength save or knock prone)',
    accentColor: Color(0xFF78909C),
  );

  static const polarBear = MinionStatBlock(
    id: 'beast_polar_bear',
    name: 'Polar Bear',
    sizeDisplay: 'Large',
    crDisplay: 'CR 2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    armorType: 'natural armor',
    maxHp: 42,
    hitDice: '5d10 + 15',
    speed: '40 ft., swim 30 ft.',
    strScore: 20,
    dexScore: 10,
    conScore: 16,
    intScore: 2,
    wisScore: 13,
    chaScore: 7,
    skills: 'Perception +3',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 450,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The bear has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The bear makes two attacks: one with its bite and one with its claws.',
      ),
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 9 (1d8 + 5) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 7,
        reach: 'reach 5 ft.',
        hitDamage: '9 (1d8 + 5) piercing damage',
      ),
      CreatureAction(
        name: 'Claws',
        description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 12 (2d6 + 5) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 7,
        reach: 'reach 5 ft.',
        hitDamage: '12 (2d6 + 5) slashing damage',
      ),
    ],
    attackBonus: 7,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 5,
    damageType: 'Slashing',
    specialTrait: 'Multiattack (Bite + Claws) & Swim 30 ft.',
    accentColor: Color(0xFFB0BEC5),
  );

  static const giantBoar = MinionStatBlock(
    id: 'beast_giant_boar',
    name: 'Giant Boar',
    sizeDisplay: 'Large',
    crDisplay: 'CR 2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    armorType: 'natural armor',
    maxHp: 42,
    hitDice: '5d10 + 15',
    speed: '40 ft.',
    strScore: 17,
    dexScore: 10,
    conScore: 16,
    intScore: 2,
    wisScore: 7,
    chaScore: 5,
    senses: 'passive Perception 8',
    languages: '—',
    xp: 450,
    traits: [
      CreatureTrait(
        name: 'Charge',
        description: 'If the boar moves at least 20 feet straight toward a target and then hits it with a tusk attack on the same turn, the target takes an extra 7 (2d6) slashing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.',
      ),
      CreatureTrait(
        name: 'Relentless (Recharges after a Short or Long Rest)',
        description: 'If the boar takes 10 damage or less that would reduce it to 0 hit points, it is reduced to 1 hit point instead.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Tusk',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '10 (2d6 + 3) slashing damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 3,
    damageType: 'Slashing',
    specialTrait: 'Charge (Extra 2d6 damage, DC 13 Str save or prone) & Relentless',
    accentColor: Color(0xFF5D4037),
  );

  static const saberToothedTiger = MinionStatBlock(
    id: 'beast_saber_toothed_tiger',
    name: 'Saber-Toothed Tiger',
    sizeDisplay: 'Large',
    crDisplay: 'CR 2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 52,
    hitDice: '7d10 + 14',
    speed: '40 ft.',
    strScore: 18,
    dexScore: 14,
    conScore: 15,
    intScore: 3,
    wisScore: 12,
    chaScore: 8,
    skills: 'Perception +3, Stealth +6',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 450,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The tiger has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
      CreatureTrait(
        name: 'Pounce',
        description: 'If the tiger moves at least 20 feet straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 14 Strength saving throw or be knocked prone. If the target is prone, the tiger can make one bite attack against it as a bonus action.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (1d10 + 5) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '10 (1d10 + 5) piercing damage',
      ),
      CreatureAction(
        name: 'Claw',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 12 (2d6 + 5) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '12 (2d6 + 5) slashing damage',
      ),
    ],
    attackBonus: 6,
    damageDiceCount: 1,
    damageDiceSides: 10,
    damageBonus: 5,
    damageType: 'Slashing',
    specialTrait: 'Pounce (DC 14 Str save or prone + bonus bite) & Keen Smell',
    accentColor: Color(0xFFF57C00),
  );

  static const giantConstrictorSnake = MinionStatBlock(
    id: 'beast_giant_constrictor_snake',
    name: 'Giant Constrictor Snake',
    sizeDisplay: 'Huge',
    crDisplay: 'CR 2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 60,
    hitDice: '8d12 + 8',
    speed: '30 ft., swim 30 ft.',
    strScore: 19,
    dexScore: 14,
    conScore: 12,
    intScore: 1,
    wisScore: 10,
    chaScore: 3,
    skills: 'Perception +2',
    senses: 'blindsight 10 ft., passive Perception 12',
    languages: '—',
    xp: 450,
    traits: [],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one creature. Hit: 11 (2d6 + 4) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 10 ft.',
        hitDamage: '11 (2d6 + 4) piercing damage',
      ),
      CreatureAction(
        name: 'Constrict',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 13 (2d8 + 4) bludgeoning damage, and the target is grappled (escape DC 14). Until this grapple ends, the creature is restrained, and the snake can\'t constrict another target.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '13 (2d8 + 4) bludgeoning + Grapple & Restrain',
      ),
    ],
    attackBonus: 6,
    damageDiceCount: 2,
    damageDiceSides: 8,
    damageBonus: 4,
    damageType: 'Bludgeoning',
    specialTrait: 'Constrict (2d8+4 bludgeoning, DC 14 Strength save or grappled/restrained)',
    accentColor: Color(0xFF388E3C),
  );

  static const conjureAnimalsPreset = SummonPreset(
    id: 'conjure_animals',
    name: 'Conjure Animals',
    category: SummonCategory.spell,
    levelDisplay: '3rd-level Conjuration',
    castingTime: '1 Action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Concentration, up to 1 hour',
    description: 'You summon fey spirits that take the form of beasts and appear in unoccupied spaces that you can see within range. Choose CR options: 8 beasts of CR 1/4, 4 beasts of CR 1/2, 2 beasts of CR 1, or 1 beast of CR 2.',
    upcastRules: 'Twice as many beasts at 5th level (e.g. 16 CR 1/4), three times as many at 7th level (24), four times as many at 9th level (32).',
    statBlocks: [
      // CR 1/4
      wolf,
      boar,
      panther,
      giantBadger,
      giantPoisonousSnake,
      // CR 1/2
      ape,
      blackBear,
      crocodile,
      // CR 1
      direWolf,
      giantHyena,
      giantSpider,
      giantEagle,
      brownBear,
      lion,
      tiger,
      giantToad,
      // CR 2
      rhinoceros,
      polarBear,
      giantBoar,
      saberToothedTiger,
      giantConstrictorSnake,
    ],
    budgetCalculator: _calculateConjureAnimalsBudget,
    defaultMinionCount: 8,
  );

  static int _calculateConjureAnimalsBudget(int spellLevel) {
    if (spellLevel < 5) return 8;
    if (spellLevel < 7) return 16;
    if (spellLevel < 9) return 24;
    return 32;
  }
}
