import 'package:flutter/material.dart';
import '../minion_stat_block.dart';
import '../summon_preset.dart';

class UndeadSummons {
  static const skeleton = MinionStatBlock(
    id: 'undead_skeleton',
    name: 'Skeleton',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Undead',
    alignment: 'lawful evil',
    ac: 13,
    armorType: 'armor scraps',
    maxHp: 13,
    hitDice: '2d8 + 4',
    speed: '30 ft.',
    strScore: 10,
    dexScore: 14,
    conScore: 15,
    intScore: 6,
    wisScore: 8,
    chaScore: 5,
    damageVulnerabilities: 'bludgeoning',
    damageImmunities: 'poison',
    conditionImmunities: 'exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'understands all languages it knew in life but can\'t speak',
    xp: 50,
    traits: [],
    actions: [
      CreatureAction(
        name: 'Shortsword',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '5 (1d6 + 2) piercing damage',
      ),
      CreatureAction(
        name: 'Shortbow',
        description: 'Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackType: 'Ranged Weapon Attack',
        attackBonus: 4,
        reach: 'range 80/320 ft.',
        hitDamage: '5 (1d6 + 2) piercing damage',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 2,
    damageType: 'Piercing',
    specialTrait: 'Shortbow / Shortsword',
    accentColor: Color(0xFFB0BEC5),
  );

  static const zombie = MinionStatBlock(
    id: 'undead_zombie',
    name: 'Zombie',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Undead',
    alignment: 'neutral evil',
    ac: 8,
    maxHp: 22,
    hitDice: '3d8 + 9',
    speed: '20 ft.',
    strScore: 13,
    dexScore: 6,
    conScore: 16,
    intScore: 3,
    wisScore: 6,
    chaScore: 5,
    savingThrows: 'Wis +0',
    damageImmunities: 'poison',
    conditionImmunities: 'poisoned',
    senses: 'darkvision 60 ft., passive Perception 8',
    languages: 'understands the languages it knew in life but can\'t speak',
    xp: 50,
    traits: [
      CreatureTrait(
        name: 'Undead Fortitude',
        description: 'If damage reduces the zombie to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 hit point instead.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Slam',
        description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) bludgeoning damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 3,
        reach: 'reach 5 ft.',
        hitDamage: '4 (1d6 + 1) bludgeoning damage',
      ),
    ],
    attackBonus: 3,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 1,
    damageType: 'Bludgeoning',
    specialTrait: 'Undead Fortitude (DC 5+dmg Con save to stay at 1 HP)',
    accentColor: Color(0xFF78909C),
  );

  static const ghoul = MinionStatBlock(
    id: 'undead_ghoul',
    name: 'Ghoul',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1',
    typeDisplay: 'Undead',
    alignment: 'chaotic evil',
    ac: 12,
    maxHp: 22,
    hitDice: '5d8',
    speed: '30 ft.',
    strScore: 13,
    dexScore: 15,
    conScore: 10,
    intScore: 7,
    wisScore: 10,
    chaScore: 6,
    damageImmunities: 'poison',
    conditionImmunities: 'charmed, exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'Common',
    xp: 200,
    traits: [],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one creature. Hit: 9 (2d6 + 2) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 2,
        reach: 'reach 5 ft.',
        hitDamage: '9 (2d6 + 2) piercing damage',
      ),
      CreatureAction(
        name: 'Claws',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) slashing damage. If the target is a creature other than an elf or undead, it must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '7 (2d4 + 2) slashing damage + DC 10 Paralyze',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 2,
    damageDiceSides: 4,
    damageBonus: 2,
    damageType: 'Slashing',
    specialTrait: 'Claws (DC 10 Con save or paralyzed for 1 min)',
    accentColor: Color(0xFF546E7A),
  );

  static const ghast = MinionStatBlock(
    id: 'undead_ghast',
    name: 'Ghast',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 2',
    typeDisplay: 'Undead',
    alignment: 'chaotic evil',
    ac: 13,
    maxHp: 36,
    hitDice: '8d8',
    speed: '30 ft.',
    strScore: 16,
    dexScore: 17,
    conScore: 10,
    intScore: 11,
    wisScore: 10,
    chaScore: 8,
    damageResistances: 'necrotic',
    damageImmunities: 'poison',
    conditionImmunities: 'charmed, exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'Common',
    xp: 450,
    traits: [
      CreatureTrait(
        name: 'Stench',
        description: 'Any creature that starts its turn within 5 feet of the ghast must succeed on a DC 10 Constitution saving throw or be poisoned until the start of its next turn. On a successful saving throw, the creature is immune to the ghast\'s Stench for 24 hours.',
      ),
      CreatureTrait(
        name: 'Turning Defiance',
        description: 'The ghast and any ghouls within 30 feet of it have advantage on saving throws against effects that turn undead.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 12 (2d8 + 3) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 3,
        reach: 'reach 5 ft.',
        hitDamage: '12 (2d8 + 3) piercing damage',
      ),
      CreatureAction(
        name: 'Claws',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage. If the target is a creature other than an undead, it must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '10 (2d6 + 3) slashing damage + DC 10 Paralyze',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 3,
    damageType: 'Slashing',
    specialTrait: 'Stench (DC 10 Con save or poisoned within 5 ft) + Paralyze',
    accentColor: Color(0xFF37474F),
  );

  static const wight = MinionStatBlock(
    id: 'undead_wight',
    name: 'Wight',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 3',
    typeDisplay: 'Undead',
    alignment: 'neutral evil',
    ac: 14,
    armorType: 'studded leather',
    maxHp: 45,
    hitDice: '6d8 + 18',
    speed: '30 ft.',
    strScore: 15,
    dexScore: 14,
    conScore: 16,
    intScore: 10,
    wisScore: 13,
    chaScore: 15,
    skills: 'Perception +3, Stealth +4',
    damageResistances: 'necrotic; bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons',
    damageImmunities: 'poison',
    conditionImmunities: 'exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 13',
    languages: 'the languages it knew in life',
    xp: 700,
    traits: [
      CreatureTrait(
        name: 'Sunlight Sensitivity',
        description: 'While in sunlight, the wight has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The wight makes two longsword attacks or two longbow attacks. It can use its Life Drain in place of one longsword attack.',
      ),
      CreatureAction(
        name: 'Life Drain',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6 + 2) necrotic damage. The target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '5 (1d6 + 2) necrotic damage',
      ),
      CreatureAction(
        name: 'Longsword',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) slashing damage, or 7 (1d10 + 2) slashing damage if used with two hands.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '6 (1d8 + 2) slashing damage',
      ),
      CreatureAction(
        name: 'Longbow',
        description: 'Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8 + 2) piercing damage.',
        attackType: 'Ranged Weapon Attack',
        attackBonus: 4,
        reach: 'range 150/600 ft.',
        hitDamage: '6 (1d8 + 2) piercing damage',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 8,
    damageBonus: 2,
    damageType: 'Piercing',
    specialTrait: 'Multiattack / Life Drain (DC 13 Con save)',
    accentColor: Color(0xFF263238),
  );

  static const mummy = MinionStatBlock(
    id: 'undead_mummy',
    name: 'Mummy',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 3',
    typeDisplay: 'Undead',
    alignment: 'lawful evil',
    ac: 11,
    armorType: 'natural armor',
    maxHp: 58,
    hitDice: '8d8 + 22',
    speed: '20 ft.',
    strScore: 16,
    dexScore: 8,
    conScore: 15,
    intScore: 6,
    wisScore: 10,
    chaScore: 12,
    savingThrows: 'Wis +2',
    damageVulnerabilities: 'fire',
    damageResistances: 'necrotic; bludgeoning, piercing, and slashing from nonmagical attacks',
    damageImmunities: 'poison',
    conditionImmunities: 'charmed, exhaustion, frightened, paralyzed, poisoned',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'the languages it knew in life',
    xp: 700,
    traits: [],
    actions: [
      CreatureAction(
        name: 'Dreadful Glare',
        description: 'The mummy targets one creature it can see within 60 feet of it. If the target can see the mummy, it must succeed on a DC 11 Wisdom saving throw against this magic or become frightened until the end of the mummy\'s next turn. If the target fails the saving throw by 5 or more, it is also paralyzed for the same duration.',
      ),
      CreatureAction(
        name: 'Rotting Fist',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) bludgeoning damage plus 10 (3d6) necrotic damage. If the target is a creature, it must succeed on a DC 12 Constitution saving throw or be cursed with mummy rot.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '10 (2d6 + 3) bludgeoning + 10 (3d6) necrotic',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 3,
    damageType: 'Bludgeoning',
    secondaryDamageDiceCount: 3,
    secondaryDamageDiceSides: 6,
    secondaryDamageType: 'Necrotic',
    specialTrait: 'Rotting Fist (3d6 Necrotic + Mummy Rot) + Dreadful Glare',
    accentColor: Color(0xFF8D6E63),
  );

  static const animateDeadPreset = SummonPreset(
    id: 'animate_dead',
    name: 'Animate Dead',
    category: SummonCategory.spell,
    levelDisplay: '3rd-level Necromancy',
    castingTime: '1 Minute',
    range: '10 feet',
    components: 'V, S, M (a drop of blood, a piece of flesh, and a pinch of bone dust)',
    duration: '24 hours',
    description: 'This spell creates an undead servant. Choose a pile of bones or a corpse of a Medium or Small humanoid within range to animate a Skeleton or Zombie.',
    upcastRules: 'Animate or reassert control over 2 additional undead creatures for each slot level above 3rd.',
    statBlocks: [skeleton, zombie],
    budgetCalculator: _calculateAnimateDeadBudget,
    defaultMinionCount: 1,
  );

  static const createUndeadPreset = SummonPreset(
    id: 'create_undead',
    name: 'Create Undead',
    category: SummonCategory.spell,
    levelDisplay: '6th-level Necromancy',
    castingTime: '1 Minute',
    range: '10 feet',
    components: 'V, S, M (one clay pot per corpse filled with grave dirt, salt, and 150gp black onyx per corpse)',
    duration: '24 hours',
    description: 'You can animate up to three Ghouls from corpses within range. Higher levels allow Ghasts, Wights, or Mummies.',
    upcastRules: '7th level: 4 Ghouls or 2 Ghasts/Wights. 8th level: 5 Ghouls, 3 Ghasts/Wights, or 2 Mummies. 9th level: 6 Ghouls, 4 Ghasts/Wights, or 3 Mummies.',
    statBlocks: [ghoul, ghast, wight, mummy],
    budgetCalculator: _calculateCreateUndeadBudget,
    defaultMinionCount: 3,
  );

  static int _calculateAnimateDeadBudget(int spellLevel) =>
      1 + (spellLevel - 3).clamp(0, 6) * 2;

  static int _calculateCreateUndeadBudget(int spellLevel) =>
      3 + (spellLevel - 6).clamp(0, 3);
}
