import 'package:flutter/material.dart';
import '../minion_stat_block.dart';
import '../summon_preset.dart';

class FigurinesSummons {
  static const bronzeGriffon = MinionStatBlock(
    id: 'item_griffon',
    name: 'Bronze Griffon',
    sizeDisplay: 'Large',
    crDisplay: 'CR 2',
    typeDisplay: 'Monstrosity',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 59,
    hitDice: '7d10 + 21',
    speed: '30 ft., fly 80 ft.',
    strScore: 18,
    dexScore: 15,
    conScore: 16,
    intScore: 2,
    wisScore: 13,
    chaScore: 8,
    skills: 'Perception +5',
    senses: 'darkvision 60 ft., passive Perception 15',
    languages: '—',
    xp: 450,
    traits: [
      CreatureTrait(
        name: 'Keen Sight',
        description: 'The griffon has advantage on Wisdom (Perception) checks that rely on sight.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The griffon makes two attacks: one with its beak and one with its claws.',
      ),
      CreatureAction(
        name: 'Beak',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '8 (1d8 + 4) piercing damage',
      ),
      CreatureAction(
        name: 'Claws',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '11 (2d6 + 4) slashing damage',
      ),
    ],
    attackBonus: 6,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 4,
    damageType: 'Slashing',
    specialTrait: 'Multiattack (Beak + Claws) & Fly 80 ft.',
    accentColor: Color(0xFFFFB300),
  );

  static const onyxDog = MinionStatBlock(
    id: 'item_onyx_dog',
    name: 'Onyx Dog',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 11,
    hitDice: '2d8 + 2',
    speed: '40 ft.',
    strScore: 13,
    dexScore: 14,
    conScore: 12,
    intScore: 8,
    wisScore: 12,
    chaScore: 6,
    skills: 'Perception +5, Stealth +4',
    damageImmunities: 'poison',
    conditionImmunities: 'petrified, poisoned',
    senses: 'darkvision 60 ft., truesight 60 ft., passive Perception 15',
    languages: 'understands Common, Giant, and Goblin but can\'t speak',
    xp: 50,
    hasPackTactics: true,
    traits: [
      CreatureTrait(
        name: 'Keen Hearing and Smell',
        description: 'The dog has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
      ),
      CreatureTrait(
        name: 'Seeing the Invisible',
        description: 'The dog has truesight out to a range of 60 feet and can see invisible creatures and objects.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '4 (1d6 + 1) piercing damage + DC 11 Str save or prone',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 2,
    damageDiceSides: 4,
    damageBonus: 2,
    damageType: 'Piercing',
    specialTrait: 'Truesight 60 ft. & Trip (DC 11 Strength save)',
    accentColor: Color(0xFF424242),
  );

  static const marbleElephant = MinionStatBlock(
    id: 'item_elephant',
    name: 'Marble Elephant',
    sizeDisplay: 'Huge',
    crDisplay: 'CR 4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    armorType: 'natural armor',
    maxHp: 76,
    hitDice: '8d12 + 24',
    speed: '40 ft.',
    strScore: 22,
    dexScore: 9,
    conScore: 17,
    intScore: 3,
    wisScore: 11,
    chaScore: 6,
    senses: 'passive Perception 10',
    languages: '—',
    xp: 1100,
    traits: [
      CreatureTrait(
        name: 'Trampling Charge',
        description: 'If the elephant moves at least 20 feet straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 12 Strength saving throw or be knocked prone. If the target is prone, the elephant can make one stomp attack against it as a bonus action.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Gore',
        description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 19 (3d8 + 6) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 8,
        reach: 'reach 5 ft.',
        hitDamage: '19 (3d8 + 6) piercing damage',
      ),
      CreatureAction(
        name: 'Stomp',
        description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one prone creature. Hit: 22 (3d10 + 6) bludgeoning damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 8,
        reach: 'reach 5 ft.',
        hitDamage: '22 (3d10 + 6) bludgeoning damage',
      ),
    ],
    attackBonus: 8,
    damageDiceCount: 3,
    damageDiceSides: 10,
    damageBonus: 6,
    damageType: 'Bludgeoning',
    specialTrait: 'Trampling Charge & Stomp (3d10+6 bludgeoning)',
    accentColor: Color(0xFFB0BEC5),
  );

  static const figurinesPreset = SummonPreset(
    id: 'figurines_wondrous_power',
    name: 'Figurines of Wondrous Power',
    category: SummonCategory.magicItem,
    levelDisplay: 'Wondrous Item (Varies)',
    castingTime: '1 Action',
    range: '60 feet',
    components: 'Action (Command word)',
    duration: 'Varies (1 hr to 12 hrs)',
    description: 'Statues of animals that transform into real living creatures upon speaking the command word.',
    upcastRules: 'Cooldown varies per figurine.',
    statBlocks: [bronzeGriffon, onyxDog, marbleElephant],
  );
}
