import 'package:flutter/material.dart';
import '../minion_stat_block.dart';
import '../summon_preset.dart';

class FigurinesSummons {
  // 1. Bronze Griffon
  static const bronzeGriffon = MinionStatBlock(
    id: 'item_griffon',
    name: 'Bronze Griffon',
    sizeDisplay: 'Large',
    crDisplay: 'CR 2',
    typeDisplay: 'Monstrosity',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 59,
    hitDice: '7d10 + 21',
    speed: '30 ft., fly 80 ft.',
    strScore: 18,
    dexScore: 15,
    conScore: 16,
    intScore: 2,
    wisScore: 13,
    chaScore: 8,
    skills: 'Perception +5',
    senses: 'darkvision 60 ft., passive Perception 15',
    languages: '—',
    xp: 450,
    traits: [
      CreatureTrait(
        name: 'Keen Sight',
        description: 'The griffon has advantage on Wisdom (Perception) checks that rely on sight.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The griffon makes two attacks: one with its beak and one with its claws.',
      ),
      CreatureAction(
        name: 'Beak',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '8 (1d8 + 4) piercing damage',
      ),
      CreatureAction(
        name: 'Claws',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '11 (2d6 + 4) slashing damage',
      ),
    ],
    attackBonus: 6,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 4,
    damageType: 'Slashing',
    specialTrait: 'Multiattack (Beak + Claws) & Fly 80 ft.',
    accentColor: Color(0xFFCD7F32),
  );

  // 2. Ebony Fly
  static const ebonyFly = MinionStatBlock(
    id: 'item_ebony_fly',
    name: 'Ebony Fly',
    sizeDisplay: 'Large',
    crDisplay: 'CR 0',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 11,
    armorType: 'natural armor',
    maxHp: 19,
    hitDice: '3d10 + 3',
    speed: '30 ft., fly 60 ft.',
    strScore: 14,
    dexScore: 13,
    conScore: 13,
    intScore: 2,
    wisScore: 10,
    chaScore: 3,
    senses: 'blindsight 60 ft., passive Perception 10',
    languages: '—',
    xp: 10,
    traits: [
      CreatureTrait(
        name: 'Beast of Burden',
        description: 'The giant fly is considered to be a Large mount and can carry up to 240 pounds.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Proboscis',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '5 (1d6 + 2) piercing damage',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 2,
    damageType: 'Piercing',
    specialTrait: 'Fly 60 ft. & Blindsight 60 ft. (Mount up to 240 lbs)',
    accentColor: Color(0xFF334155),
  );

  // 3. Golden Lions (Lion)
  static const goldenLion = MinionStatBlock(
    id: 'item_golden_lion',
    name: 'Golden Lion',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 26,
    hitDice: '4d10 + 4',
    speed: '50 ft.',
    strScore: 17,
    dexScore: 15,
    conScore: 13,
    intScore: 3,
    wisScore: 12,
    chaScore: 8,
    skills: 'Perception +3, Stealth +6',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 200,
    hasPackTactics: true,
    traits: [
      CreatureTrait(
        name: 'Keen Smell',
        description: 'The lion has advantage on Wisdom (Perception) checks that rely on smell.',
      ),
      CreatureTrait(
        name: 'Pack Tactics',
        description: 'The lion has advantage on an attack roll against a creature if at least one of the lion\'s allies is within 5 feet of the creature and the ally isn\'t incapacitated.',
      ),
      CreatureTrait(
        name: 'Pounce',
        description: 'If the lion moves at least 20 feet straight toward a creature and hits with a claw attack on the same turn, target must succeed on a DC 13 Strength saving throw or be knocked prone. If prone, the lion can make one bite attack as a bonus action.',
      ),
      CreatureTrait(
        name: 'Running Leap',
        description: 'With a 10-foot running start, the lion can long jump up to 25 feet.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '7 (1d8 + 3) piercing damage',
      ),
      CreatureAction(
        name: 'Claw',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '6 (1d6 + 3) slashing damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 1,
    damageDiceSides: 8,
    damageBonus: 3,
    damageType: 'Piercing',
    specialTrait: 'Pounce (DC 13 Str or prone) & Pack Tactics',
    accentColor: Color(0xFFF59E0B),
  );

  // 4a. Ivory Goat of Traveling
  static const ivoryGoatTraveling = MinionStatBlock(
    id: 'item_ivory_goat_traveling',
    name: 'Ivory Goat of Traveling',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1/2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 10,
    maxHp: 24,
    hitDice: '4d10 + 4',
    speed: '40 ft.',
    strScore: 16,
    dexScore: 11,
    conScore: 12,
    intScore: 2,
    wisScore: 10,
    chaScore: 5,
    senses: 'passive Perception 10',
    languages: '—',
    xp: 100,
    traits: [
      CreatureTrait(
        name: 'Sure-Footed',
        description: 'The goat has advantage on Strength and Dexterity saving throws made against being knocked prone.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Horns',
        description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) bludgeoning damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 5,
        reach: 'reach 5 ft.',
        hitDamage: '6 (1d6 + 3) bludgeoning damage',
      ),
    ],
    attackBonus: 5,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 3,
    damageType: 'Bludgeoning',
    specialTrait: 'Sure-Footed & Mount (24 hrs / 30 days total)',
    accentColor: Color(0xFFFFFBEB),
  );

  // 4b. Ivory Goat of Travail
  static const ivoryGoatTravail = MinionStatBlock(
    id: 'item_ivory_goat_travail',
    name: 'Ivory Goat of Travail',
    sizeDisplay: 'Large',
    crDisplay: 'CR 2',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    armorType: 'natural armor',
    maxHp: 44,
    hitDice: '6d10 + 12',
    speed: '40 ft.',
    strScore: 18,
    dexScore: 11,
    conScore: 14,
    intScore: 2,
    wisScore: 10,
    chaScore: 5,
    senses: 'passive Perception 10',
    languages: '—',
    xp: 450,
    traits: [
      CreatureTrait(
        name: 'Charge (Travail)',
        description: 'If the goat moves at least 20 feet straight toward a target and then hits it with a horns attack on the same turn, the target takes an extra 16 (3d10) bludgeoning damage and must succeed on a DC 15 Strength saving throw or be knocked prone.',
      ),
      CreatureTrait(
        name: 'Sure-Footed',
        description: 'Advantage on Strength and Dexterity saving throws made against being knocked prone.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Multiattack',
        description: 'The goat of travail makes two horns attacks.',
      ),
      CreatureAction(
        name: 'Horns',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 9 (2d4 + 4) bludgeoning damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '9 (2d4 + 4) bludgeoning damage',
      ),
    ],
    attackBonus: 6,
    damageDiceCount: 2,
    damageDiceSides: 4,
    damageBonus: 4,
    damageType: 'Bludgeoning',
    specialTrait: 'Charge (+16 bludgeoning + DC 15 prone) & Multiattack',
    accentColor: Color(0xFFFDE68A),
  );

  // 4c. Ivory Goat of Terror
  static const ivoryGoatTerror = MinionStatBlock(
    id: 'item_ivory_goat_terror',
    name: 'Ivory Goat of Terror',
    sizeDisplay: 'Large',
    crDisplay: 'CR 3',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 15,
    armorType: 'natural armor',
    maxHp: 30,
    hitDice: '4d10 + 8',
    speed: '40 ft.',
    strScore: 18,
    dexScore: 11,
    conScore: 14,
    intScore: 2,
    wisScore: 10,
    chaScore: 5,
    senses: 'passive Perception 10',
    languages: '—',
    xp: 700,
    traits: [
      CreatureTrait(
        name: 'Aura of Terror',
        description: 'Creatures within 30 feet of the goat that can see it must succeed on a DC 15 Wisdom saving throw or become frightened for 1 minute. While frightened, attack rolls against that creature have advantage.',
      ),
      CreatureTrait(
        name: 'Sure-Footed',
        description: 'Advantage on Strength and Dexterity saving throws made against being knocked prone.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Horns (Lances of Terror)',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '11 (2d6 + 4) piercing damage',
      ),
    ],
    attackBonus: 6,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 4,
    damageType: 'Piercing',
    specialTrait: 'Aura of Terror (DC 15 Wis save or Frightened & Grant Adv)',
    accentColor: Color(0xFFD97706),
  );

  // 5. Marble Elephant
  static const marbleElephant = MinionStatBlock(
    id: 'item_elephant',
    name: 'Marble Elephant',
    sizeDisplay: 'Huge',
    crDisplay: 'CR 4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    armorType: 'natural armor',
    maxHp: 76,
    hitDice: '8d12 + 24',
    speed: '40 ft.',
    strScore: 22,
    dexScore: 9,
    conScore: 17,
    intScore: 3,
    wisScore: 11,
    chaScore: 6,
    senses: 'passive Perception 10',
    languages: '—',
    xp: 1100,
    traits: [
      CreatureTrait(
        name: 'Trampling Charge',
        description: 'If the elephant moves at least 20 feet straight toward a creature and then hits it with a gore attack on the same turn, that target must succeed on a DC 12 Strength saving throw or be knocked prone. If the target is prone, the elephant can make one stomp attack against it as a bonus action.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Gore',
        description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 19 (3d8 + 6) piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 8,
        reach: 'reach 5 ft.',
        hitDamage: '19 (3d8 + 6) piercing damage',
      ),
      CreatureAction(
        name: 'Stomp',
        description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one prone creature. Hit: 22 (3d10 + 6) bludgeoning damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 8,
        reach: 'reach 5 ft.',
        hitDamage: '22 (3d10 + 6) bludgeoning damage',
      ),
    ],
    attackBonus: 8,
    damageDiceCount: 3,
    damageDiceSides: 10,
    damageBonus: 6,
    damageType: 'Bludgeoning',
    specialTrait: 'Trampling Charge & Stomp (3d10+6 bludgeoning)',
    accentColor: Color(0xFFB0BEC5),
  );

  // 6. Obsidian Steed (Nightmare)
  static const obsidianSteed = MinionStatBlock(
    id: 'item_obsidian_steed',
    name: 'Obsidian Steed (Nightmare)',
    sizeDisplay: 'Large',
    crDisplay: 'CR 3',
    typeDisplay: 'Fiend',
    alignment: 'neutral evil',
    ac: 13,
    armorType: 'natural armor',
    maxHp: 68,
    hitDice: '8d10 + 24',
    speed: '60 ft., fly 90 ft.',
    strScore: 18,
    dexScore: 15,
    conScore: 16,
    intScore: 10,
    wisScore: 13,
    chaScore: 15,
    damageImmunities: 'fire',
    senses: 'passive Perception 11',
    languages: 'understands Abyssal, Common, and Infernal but can\'t speak',
    xp: 700,
    traits: [
      CreatureTrait(
        name: 'Confer Fire Resistance',
        description: 'The nightmare can grant resistance to fire damage to anyone riding it.',
      ),
      CreatureTrait(
        name: 'Illuminating Fire',
        description: 'The nightmare sheds bright light in a 10-foot radius and dim light for an additional 10 feet.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Hooves',
        description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage plus 7 (2d6) fire damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 6,
        reach: 'reach 5 ft.',
        hitDamage: '13 (2d8 + 4) bludgeoning + 7 (2d6) fire damage',
      ),
      CreatureAction(
        name: 'Ethereal Stride',
        description: 'The nightmare and up to three willing creatures within 5 feet of it magically enter the Ethereal Plane from the Material Plane, or vice versa.',
      ),
    ],
    attackBonus: 6,
    damageDiceCount: 2,
    damageDiceSides: 8,
    damageBonus: 4,
    damageType: 'Bludgeoning',
    specialTrait: 'Fly 90 ft., Fire Resistance to Rider & Ethereal Stride',
    accentColor: Color(0xFFDC2626),
  );

  // 7. Onyx Dog
  static const onyxDog = MinionStatBlock(
    id: 'item_onyx_dog',
    name: 'Onyx Dog',
    sizeDisplay: 'Medium',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 11,
    hitDice: '2d8 + 2',
    speed: '40 ft.',
    strScore: 13,
    dexScore: 14,
    conScore: 12,
    intScore: 8,
    wisScore: 12,
    chaScore: 6,
    skills: 'Perception +5, Stealth +4',
    damageImmunities: 'poison',
    conditionImmunities: 'petrified, poisoned',
    senses: 'darkvision 60 ft., truesight 60 ft., passive Perception 15',
    languages: 'understands Common, Giant, and Goblin but can\'t speak',
    xp: 50,
    hasPackTactics: true,
    traits: [
      CreatureTrait(
        name: 'Keen Hearing and Smell',
        description: 'The dog has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
      ),
      CreatureTrait(
        name: 'Seeing the Invisible',
        description: 'The dog has truesight out to a range of 60 feet and can see invisible creatures and objects.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Bite',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '4 (1d6 + 1) piercing damage + DC 11 Str save or prone',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 6,
    damageBonus: 1,
    damageType: 'Piercing',
    specialTrait: 'Truesight 60 ft. & Trip (DC 11 Strength save)',
    accentColor: Color(0xFF1E293B),
  );

  // 8. Serpentine Owl (Giant Owl)
  static const serpentineOwl = MinionStatBlock(
    id: 'item_serpentine_owl',
    name: 'Serpentine Owl',
    sizeDisplay: 'Large',
    crDisplay: 'CR 1/4',
    typeDisplay: 'Beast',
    alignment: 'neutral',
    ac: 12,
    maxHp: 19,
    hitDice: '3d10 + 3',
    speed: '10 ft., fly 60 ft.',
    strScore: 13,
    dexScore: 15,
    conScore: 12,
    intScore: 8,
    wisScore: 13,
    chaScore: 10,
    skills: 'Perception +5, Stealth +4',
    senses: 'darkvision 120 ft., passive Perception 15',
    languages: 'understands Common, Elvish, and Sylvan; telepathic bond 1 mile',
    xp: 50,
    traits: [
      CreatureTrait(
        name: 'Flyby',
        description: 'The owl doesn\'t provoke opportunity attacks when it flies out of an enemy\'s reach.',
      ),
      CreatureTrait(
        name: 'Keen Hearing and Sight',
        description: 'The owl has advantage on Wisdom (Perception) checks that rely on hearing or sight.',
      ),
      CreatureTrait(
        name: 'Telepathic Link',
        description: 'The owl can communicate telepathically with its user at a distance of up to 1 mile.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Talons',
        description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 8 (2d6 + 1) slashing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 3,
        reach: 'reach 5 ft.',
        hitDamage: '8 (2d6 + 1) slashing damage',
      ),
    ],
    attackBonus: 3,
    damageDiceCount: 2,
    damageDiceSides: 6,
    damageBonus: 1,
    damageType: 'Slashing',
    specialTrait: 'Flyby, Darkvision 120 ft., & Telepathic Link (1 mile)',
    accentColor: Color(0xFF059669),
  );

  // 9. Silver Raven
  static const silverRaven = MinionStatBlock(
    id: 'item_silver_raven',
    name: 'Silver Raven',
    sizeDisplay: 'Tiny',
    crDisplay: 'CR 0',
    typeDisplay: 'Beast',
    alignment: 'unaligned',
    ac: 12,
    maxHp: 1,
    hitDice: '1d4 - 1',
    speed: '10 ft., fly 50 ft.',
    strScore: 2,
    dexScore: 14,
    conScore: 8,
    intScore: 2,
    wisScore: 12,
    chaScore: 6,
    skills: 'Perception +3',
    senses: 'passive Perception 13',
    languages: '—',
    xp: 10,
    traits: [
      CreatureTrait(
        name: 'Animal Messenger Ability',
        description: 'The raven can be sent to deliver a message to a designated creature as if with an animal messenger spell. If so sent, it can remain animated for up to 24 hours.',
      ),
      CreatureTrait(
        name: 'Mimicry',
        description: 'The raven can mimic simple sounds it has heard with a successful DC 10 Wisdom (Insight) check to discern.',
      ),
    ],
    actions: [
      CreatureAction(
        name: 'Beak',
        description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 1 piercing damage.',
        attackType: 'Melee Weapon Attack',
        attackBonus: 4,
        reach: 'reach 5 ft.',
        hitDamage: '1 piercing damage',
      ),
    ],
    attackBonus: 4,
    damageDiceCount: 1,
    damageDiceSides: 1,
    damageBonus: 0,
    damageType: 'Piercing',
    specialTrait: 'Animal Messenger Delivery (24 hrs) & Mimicry',
    accentColor: Color(0xFF94A3B8),
  );

  static const figurinesPreset = SummonPreset(
    id: 'figurines_wondrous_power',
    name: 'Figurines of Wondrous Power',
    category: SummonCategory.magicItem,
    levelDisplay: 'Wondrous Item (Varies)',
    castingTime: '1 Action',
    range: '60 feet',
    components: 'Action (Command word)',
    duration: 'Varies (1 hr to 24 hrs)',
    description: 'Statues of animals that transform into real living creatures upon speaking the command word.',
    upcastRules: 'Select from all 9 SRD varieties (Bronze Griffon, Ebony Fly, Golden Lions, Ivory Goats, Marble Elephant, Obsidian Steed, Onyx Dog, Serpentine Owl, Silver Raven). Cooldown varies per figurine.',
    statBlocks: [
      bronzeGriffon,
      ebonyFly,
      goldenLion,
      ivoryGoatTraveling,
      ivoryGoatTravail,
      ivoryGoatTerror,
      marbleElephant,
      obsidianSteed,
      onyxDog,
      serpentineOwl,
      silverRaven,
    ],
  );
}
