import 'package:flutter/material.dart';
import '../../monster_codex_data.dart';
import '../../srd_summons/minion_stat_block.dart';

/// SRD 5.1 & 5.2 Bestiary entries for CR 5 through CR 8.
class BestiaryCrFiveToEight {
  BestiaryCrFiveToEight._();

  static final List<MonsterItem> entries = [
    // =========================================================================
    // CR 5 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_bulette',
      name: 'Bulette',
      statBlock: const MinionStatBlock(
        id: 'bulette',
        name: 'Bulette',
        sizeDisplay: 'Large',
        typeDisplay: 'Monstrosity',
        alignment: 'unaligned',
        ac: 17,
        armorType: 'natural armor',
        maxHp: 94,
        hitDice: '9d10 + 45',
        speed: '40 ft., burrow 40 ft.',
        strScore: 19,
        dexScore: 11,
        conScore: 21,
        intScore: 2,
        wisScore: 10,
        chaScore: 5,
        skills: 'Perception +6',
        senses: 'darkvision 60 ft., tremorsense 60 ft., passive Perception 16',
        languages: '—',
        crDisplay: 'CR 5',
        xp: 1800,
        attackBonus: 7,
        damageDiceCount: 4,
        damageDiceSides: 12,
        damageBonus: 4,
        damageType: 'piercing',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Standing Leap',
            description: 'The bulette\'s long jump is up to 30 ft. and its high jump is up to 15 ft., with or without a running start.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 30 (4d12 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '4d12 + 4',
          ),
          CreatureAction(
            name: 'Deadly Leap',
            description: 'If the bulette jumps at least 15 ft. as part of its movement, it can then use this action to land on its feet in a space that contains one or more other creatures. Each of those creatures must succeed on a DC 16 Strength or Dexterity saving throw or be knocked prone and take 14 (3d6 + 4) bludgeoning damage plus 14 (3d6 + 4) slashing damage.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_flesh_golem',
      name: 'Flesh Golem',
      statBlock: const MinionStatBlock(
        id: 'flesh_golem',
        name: 'Flesh Golem',
        sizeDisplay: 'Medium',
        typeDisplay: 'Construct',
        alignment: 'neutral',
        ac: 9,
        maxHp: 93,
        hitDice: '11d8 + 44',
        speed: '30 ft.',
        strScore: 19,
        dexScore: 9,
        conScore: 18,
        intScore: 6,
        wisScore: 10,
        chaScore: 5,
        damageImmunities: 'lightning, poison; bludgeoning, piercing, and slashing from nonmagical attacks not made with adamantine',
        conditionImmunities: 'charmed, exhaustion, frightened, paralyzed, petrified, poisoned',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'understands the languages of its creator but can\'t speak',
        crDisplay: 'CR 5',
        xp: 1800,
        attackBonus: 7,
        damageDiceCount: 2,
        damageDiceSides: 8,
        damageBonus: 4,
        damageType: 'bludgeoning',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Berserk',
            description: 'Whenever the golem starts its turn with 40 hit points or fewer, roll a d6. On a 6, the golem goes berserk and attacks the nearest creature it can see.',
          ),
          CreatureTrait(
            name: 'Aversion of Fire',
            description: 'If the golem takes fire damage, it has disadvantage on attack rolls and ability checks until the end of its next turn.',
          ),
          CreatureTrait(
            name: 'Lightning Absorption',
            description: 'Whenever the golem is subjected to lightning damage, it takes no damage and instead regains a number of hit points equal to the lightning damage dealt.',
          ),
          CreatureTrait(
            name: 'Magic Resistance',
            description: 'The golem has advantage on saving throws against spells and other magical effects.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The golem makes two slam attacks.',
          ),
          CreatureAction(
            name: 'Slam',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '2d8 + 4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_hill_giant',
      name: 'Hill Giant',
      statBlock: const MinionStatBlock(
        id: 'hill_giant',
        name: 'Hill Giant',
        sizeDisplay: 'Huge',
        typeDisplay: 'Giant',
        alignment: 'chaotic evil',
        ac: 13,
        armorType: 'natural armor',
        maxHp: 105,
        hitDice: '10d12 + 40',
        speed: '40 ft.',
        strScore: 21,
        dexScore: 8,
        conScore: 19,
        intScore: 5,
        wisScore: 9,
        chaScore: 6,
        skills: 'Perception +2',
        senses: 'passive Perception 12',
        languages: 'Giant',
        crDisplay: 'CR 5',
        xp: 1800,
        attackBonus: 8,
        damageDiceCount: 3,
        damageDiceSides: 8,
        damageBonus: 5,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF94A3B8),
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The giant makes two greatclub attacks.',
          ),
          CreatureAction(
            name: 'Greatclub',
            description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 18 (3d8 + 5) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 8,
            reach: '10 ft.',
            hitDamage: '3d8 + 5',
          ),
          CreatureAction(
            name: 'Rock',
            description: 'Ranged Weapon Attack: +8 to hit, range 60/240 ft., one target. Hit: 21 (3d10 + 5) bludgeoning damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 8,
            reach: 'range 60/240 ft.',
            hitDamage: '3d10 + 5',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_troll',
      name: 'Troll',
      statBlock: const MinionStatBlock(
        id: 'troll',
        name: 'Troll',
        sizeDisplay: 'Large',
        typeDisplay: 'Giant',
        alignment: 'chaotic evil',
        ac: 15,
        armorType: 'natural armor',
        maxHp: 84,
        hitDice: '8d10 + 40',
        speed: '30 ft.',
        strScore: 18,
        dexScore: 13,
        conScore: 20,
        intScore: 7,
        wisScore: 9,
        chaScore: 7,
        skills: 'Perception +2',
        senses: 'darkvision 60 ft., passive Perception 12',
        languages: 'Giant',
        crDisplay: 'CR 5',
        xp: 1800,
        attackBonus: 7,
        damageDiceCount: 2,
        damageDiceSides: 6,
        damageBonus: 4,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The troll has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
          CreatureTrait(
            name: 'Regeneration',
            description: 'The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, this trait doesn\'t function at the start of the troll\'s next turn. The troll dies only if it starts its turn with 0 hit points and doesn\'t regenerate.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The troll makes three attacks: one with its bite and two with its claws.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '1d6 + 4',
          ),
          CreatureAction(
            name: 'Claw',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '2d6 + 4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_unicorn',
      name: 'Unicorn',
      statBlock: const MinionStatBlock(
        id: 'unicorn',
        name: 'Unicorn',
        sizeDisplay: 'Large',
        typeDisplay: 'Celestial',
        alignment: 'lawful good',
        ac: 12,
        maxHp: 67,
        hitDice: '9d10 + 18',
        speed: '50 ft.',
        strScore: 18,
        dexScore: 14,
        conScore: 15,
        intScore: 11,
        wisScore: 17,
        chaScore: 16,
        damageImmunities: 'poison',
        conditionImmunities: 'charmed, paralyzed, poisoned',
        senses: 'darkvision 60 ft., passive Perception 13',
        languages: 'Celestial, Elvish, Sylvan, telepathy 60 ft.',
        crDisplay: 'CR 5',
        xp: 1800,
        attackBonus: 7,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 4,
        damageType: 'piercing',
        accentColor: Color(0xFFEAB308),
        traits: [
          CreatureTrait(
            name: 'Charge',
            description: 'If the unicorn moves at least 20 ft. straight toward a target and then hits it with a horn attack on the same turn, the target takes an extra 9 (2d8) piercing damage.',
          ),
          CreatureTrait(
            name: 'Magic Resistance',
            description: 'The unicorn has advantage on saving throws against spells and other magical effects.',
          ),
          CreatureTrait(
            name: 'Magic Weapons',
            description: 'The unicorn\'s weapon attacks are magical.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The unicorn makes two attacks: one with its hooves and one with its horn.',
          ),
          CreatureAction(
            name: 'Hooves',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '2d6 + 4',
          ),
          CreatureAction(
            name: 'Horn',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '1d8 + 4',
          ),
          CreatureAction(
            name: 'Healing Touch (3/Day)',
            description: 'The unicorn touches another creature with its horn. The target magically regains 11 (2d8 + 2) hit points. In addition, the touch removes all diseases and neutralizes all poisons afflicting the target.',
          ),
          CreatureAction(
            name: 'Teleport (1/Day)',
            description: 'The unicorn magically teleports itself and up to three willing creatures it can see within 5 ft. of it, along with any equipment they are wearing or carrying, to a location the unicorn is familiar with, up to 1 mile away.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_wraith',
      name: 'Wraith',
      statBlock: const MinionStatBlock(
        id: 'wraith',
        name: 'Wraith',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'neutral evil',
        ac: 13,
        maxHp: 67,
        hitDice: '9d8 + 27',
        speed: '0 ft., fly 60 ft. (hover)',
        strScore: 6,
        dexScore: 16,
        conScore: 16,
        intScore: 12,
        wisScore: 14,
        chaScore: 15,
        damageResistances: 'acid, cold, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons',
        damageImmunities: 'necrotic, poison',
        conditionImmunities: 'charmed, exhaustion, grappled, paralyzed, petrified, poisoned, prone, restrained',
        senses: 'darkvision 60 ft., passive Perception 12',
        languages: 'the languages it knew in life',
        crDisplay: 'CR 5',
        xp: 1800,
        attackBonus: 6,
        damageDiceCount: 4,
        damageDiceSides: 8,
        damageBonus: 3,
        damageType: 'necrotic',
        accentColor: Color(0xFFCBD5E1),
        traits: [
          CreatureTrait(
            name: 'Incorporeal Movement',
            description: 'The wraith can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.',
          ),
          CreatureTrait(
            name: 'Sunlight Sensitivity',
            description: 'While in sunlight, the wraith has disadvantage on attack rolls and Perception checks.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Life Drain',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 21 (4d8 + 3) necrotic damage. The target must succeed on a DC 14 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '4d8 + 3',
          ),
          CreatureAction(
            name: 'Create Specter',
            description: 'The wraith targets a humanoid within 10 ft. of it that has been dead for no longer than 1 minute and died violently. The target\'s spirit rises as a specter in the space of its corpse or in the nearest unoccupied space.',
          ),
        ],
      ),
    ),

    // =========================================================================
    // CR 6 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_chimera',
      name: 'Chimera',
      statBlock: const MinionStatBlock(
        id: 'chimera',
        name: 'Chimera',
        sizeDisplay: 'Large',
        typeDisplay: 'Monstrosity',
        alignment: 'chaotic evil',
        ac: 14,
        armorType: 'natural armor',
        maxHp: 114,
        hitDice: '12d10 + 48',
        speed: '30 ft., fly 60 ft.',
        strScore: 19,
        dexScore: 11,
        conScore: 19,
        intScore: 3,
        wisScore: 14,
        chaScore: 10,
        skills: 'Perception +8',
        senses: 'darkvision 60 ft., passive Perception 18',
        languages: 'understands Draconic but can\'t speak',
        crDisplay: 'CR 6',
        xp: 2300,
        attackBonus: 7,
        damageDiceCount: 2,
        damageDiceSides: 6,
        damageBonus: 4,
        damageType: 'slashing',
        accentColor: Color(0xFFD97706),
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The chimera makes three attacks: one with its bite, one with its horns, and one with its claws. When its fire breath is available, it can use the breath in place of its bite or horns.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '2d6 + 4',
          ),
          CreatureAction(
            name: 'Horns',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 10 (1d12 + 4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '1d12 + 4',
          ),
          CreatureAction(
            name: 'Claws',
            description: 'Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '5 ft.',
            hitDamage: '2d6 + 4',
          ),
          CreatureAction(
            name: 'Fire Breath (Recharge 5-6)',
            description: 'The dragon head exhales fire in a 15-foot cone. Each creature in that area must make a DC 15 Dexterity saving throw, taking 31 (7d8) fire damage on a failed save, or half as much damage on a successful one.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_cyclops',
      name: 'Cyclops',
      statBlock: const MinionStatBlock(
        id: 'cyclops',
        name: 'Cyclops',
        sizeDisplay: 'Huge',
        typeDisplay: 'Giant',
        alignment: 'chaotic neutral',
        ac: 14,
        armorType: 'natural armor',
        maxHp: 138,
        hitDice: '12d12 + 60',
        speed: '30 ft.',
        strScore: 22,
        dexScore: 11,
        conScore: 20,
        intScore: 8,
        wisScore: 6,
        chaScore: 10,
        senses: 'passive Perception 8',
        languages: 'Giant',
        crDisplay: 'CR 6',
        xp: 2300,
        attackBonus: 9,
        damageDiceCount: 3,
        damageDiceSides: 8,
        damageBonus: 6,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Poor Depth Perception',
            description: 'The cyclops has disadvantage on any attack roll against a target more than 30 ft. away.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The cyclops makes two greatclub attacks.',
          ),
          CreatureAction(
            name: 'Greatclub',
            description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 19 (3d8 + 6) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 9,
            reach: '10 ft.',
            hitDamage: '3d8 + 6',
          ),
          CreatureAction(
            name: 'Rock',
            description: 'Ranged Weapon Attack: +9 to hit, range 30/120 ft., one target. Hit: 28 (4d10 + 6) bludgeoning damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 9,
            reach: 'range 30/120 ft.',
            hitDamage: '4d10 + 6',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_medusa',
      name: 'Medusa',
      statBlock: const MinionStatBlock(
        id: 'medusa',
        name: 'Medusa',
        sizeDisplay: 'Medium',
        typeDisplay: 'Monstrosity',
        alignment: 'lawful evil',
        ac: 15,
        armorType: 'natural armor',
        maxHp: 127,
        hitDice: '17d8 + 51',
        speed: '30 ft.',
        strScore: 10,
        dexScore: 15,
        conScore: 16,
        intScore: 12,
        wisScore: 13,
        chaScore: 15,
        skills: 'Deception +5, Insight +4, Perception +4, Stealth +5',
        senses: 'darkvision 60 ft., passive Perception 14',
        languages: 'Common',
        crDisplay: 'CR 6',
        xp: 2300,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'piercing',
        secondaryDamageDiceCount: 4,
        secondaryDamageDiceSides: 6,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Petrifying Gaze',
            description: 'When a creature that can see the medusa\'s eyes starts its turn within 30 ft. of the medusa, the medusa can force it to make a DC 14 Constitution saving throw if the medusa isn\'t incapacitated. On a failed save, the creature magically begins to turn to stone and is restrained.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The medusa makes three attacks: either three with its snake hair, or two with its shortsword and one with its snake hair, or two with its longbow.',
          ),
          CreatureAction(
            name: 'Snake Hair',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 4 (1d4 + 2) piercing damage plus 14 (4d6) poison damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d4 + 2 + 4d6 poison',
          ),
          CreatureAction(
            name: 'Shortsword',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Longbow',
            description: 'Ranged Weapon Attack: +5 to hit, range 150/600 ft., one target. Hit: 6 (1d8 + 2) piercing damage plus 7 (2d6) poison damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 5,
            reach: 'range 150/600 ft.',
            hitDamage: '1d8 + 2 + 2d6 poison',
          ),
        ],
      ),
    ),

    // =========================================================================
    // CR 7 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_stone_giant',
      name: 'Stone Giant',
      statBlock: const MinionStatBlock(
        id: 'stone_giant',
        name: 'Stone Giant',
        sizeDisplay: 'Huge',
        typeDisplay: 'Giant',
        alignment: 'neutral',
        ac: 17,
        armorType: 'natural armor',
        maxHp: 126,
        hitDice: '11d12 + 55',
        speed: '40 ft.',
        strScore: 23,
        dexScore: 15,
        conScore: 20,
        intScore: 10,
        wisScore: 12,
        chaScore: 9,
        savingThrows: 'Dex +5, Con +8, Wis +4',
        skills: 'Athletics +12, Perception +4',
        senses: 'darkvision 60 ft., passive Perception 14',
        languages: 'Giant',
        crDisplay: 'CR 7',
        xp: 2900,
        attackBonus: 9,
        damageDiceCount: 3,
        damageDiceSides: 8,
        damageBonus: 6,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Stone Camouflage',
            description: 'The giant has advantage on Dexterity (Stealth) checks made to hide in rocky terrain.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The giant makes two greatclub attacks.',
          ),
          CreatureAction(
            name: 'Greatclub',
            description: 'Melee Weapon Attack: +9 to hit, reach 15 ft., one target. Hit: 19 (3d8 + 6) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 9,
            reach: '15 ft.',
            hitDamage: '3d8 + 6',
          ),
          CreatureAction(
            name: 'Rock',
            description: 'Ranged Weapon Attack: +9 to hit, range 60/240 ft., one target. Hit: 28 (4d10 + 6) bludgeoning damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 9,
            reach: 'range 60/240 ft.',
            hitDamage: '4d10 + 6',
          ),
        ],
        reactions: [
          CreatureAction(
            name: 'Rock Catching',
            description: 'If a rock or similar object is hurled at the giant, the giant can, with a successful DC 10 Dexterity saving throw, catch the missile and take no bludgeoning damage from it.',
          ),
        ],
      ),
    ),

    // =========================================================================
    // CR 8 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_hydra',
      name: 'Hydra',
      statBlock: const MinionStatBlock(
        id: 'hydra',
        name: 'Hydra',
        sizeDisplay: 'Huge',
        typeDisplay: 'Monstrosity',
        alignment: 'unaligned',
        ac: 15,
        armorType: 'natural armor',
        maxHp: 172,
        hitDice: '15d12 + 75',
        speed: '30 ft., swim 30 ft.',
        strScore: 20,
        dexScore: 12,
        conScore: 20,
        intScore: 2,
        wisScore: 10,
        chaScore: 7,
        skills: 'Perception +6',
        senses: 'darkvision 60 ft., passive Perception 16',
        languages: '—',
        crDisplay: 'CR 8',
        xp: 3900,
        attackBonus: 8,
        damageDiceCount: 1,
        damageDiceSides: 10,
        damageBonus: 5,
        damageType: 'piercing',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Hold Breath',
            description: 'The hydra can hold its breath for 1 hour.',
          ),
          CreatureTrait(
            name: 'Multiple Heads',
            description: 'The hydra has five heads. While it has more than one head, the hydra has advantage on saving throws against being blinded, charmed, deafened, frightened, stunned, and knocked unconscious.',
          ),
          CreatureTrait(
            name: 'Reactive Heads',
            description: 'For each head the hydra has beyond one, it gets an extra reaction that can be used only for opportunity attacks.',
          ),
          CreatureTrait(
            name: 'Wakeful',
            description: 'While the hydra sleeps, at least one of its heads is awake.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The hydra makes as many bite attacks as it has heads.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 10 (1d10 + 5) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 8,
            reach: '10 ft.',
            hitDamage: '1d10 + 5',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_frost_giant',
      name: 'Frost Giant',
      statBlock: const MinionStatBlock(
        id: 'frost_giant',
        name: 'Frost Giant',
        sizeDisplay: 'Huge',
        typeDisplay: 'Giant',
        alignment: 'neutral evil',
        ac: 15,
        armorType: 'patchwork armor',
        maxHp: 138,
        hitDice: '12d12 + 60',
        speed: '40 ft.',
        strScore: 23,
        dexScore: 9,
        conScore: 21,
        intScore: 9,
        wisScore: 10,
        chaScore: 12,
        savingThrows: 'Con +8, Wis +3, Cha +4',
        skills: 'Athletics +9, Perception +3',
        damageImmunities: 'cold',
        senses: 'passive Perception 13',
        languages: 'Giant',
        crDisplay: 'CR 8',
        xp: 3900,
        attackBonus: 9,
        damageDiceCount: 3,
        damageDiceSides: 12,
        damageBonus: 6,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The giant makes two greataxe attacks.',
          ),
          CreatureAction(
            name: 'Greataxe',
            description: 'Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 25 (3d12 + 6) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 9,
            reach: '10 ft.',
            hitDamage: '3d12 + 6',
          ),
          CreatureAction(
            name: 'Rock',
            description: 'Ranged Weapon Attack: +9 to hit, range 60/240 ft., one target. Hit: 28 (4d10 + 6) bludgeoning damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 9,
            reach: 'range 60/240 ft.',
            hitDamage: '4d10 + 6',
          ),
        ],
        reactions: [
          CreatureAction(
            name: 'Rock Catching',
            description: 'If a rock or similar object is hurled at the giant, the giant can, with a successful DC 10 Dexterity saving throw, catch the missile and take no bludgeoning damage from it.',
          ),
        ],
      ),
    ),
  ];
}
