import 'package:flutter/material.dart';
import '../../monster_codex_data.dart';
import '../../srd_summons/minion_stat_block.dart';

/// SRD 5.1 & 5.2 Bestiary entries for CR 1/2 through CR 1.
class BestiaryCrHalfToOne {
  BestiaryCrHalfToOne._();

  static final List<MonsterItem> entries = [
    // =========================================================================
    // CR 1/2 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_ape',
      name: 'Ape',
      statBlock: const MinionStatBlock(
        id: 'ape',
        name: 'Ape',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 19,
        hitDice: '3d8 + 6',
        speed: '30 ft., climb 30 ft.',
        strScore: 16,
        dexScore: 14,
        conScore: 14,
        intScore: 6,
        wisScore: 12,
        chaScore: 7,
        skills: 'Athletics +5, Perception +3',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 3,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The ape makes two fist attacks.',
          ),
          CreatureAction(
            name: 'Fist',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d6 + 3',
          ),
          CreatureAction(
            name: 'Rock',
            description: 'Ranged Weapon Attack: +5 to hit, range 25/50 ft., one target. Hit: 6 (1d6 + 3) bludgeoning damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 5,
            reach: 'range 25/50 ft.',
            hitDamage: '1d6 + 3',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_black_bear',
      name: 'Black Bear',
      statBlock: const MinionStatBlock(
        id: 'black_bear',
        name: 'Black Bear',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        armorType: 'natural armor',
        maxHp: 19,
        hitDice: '3d8 + 6',
        speed: '40 ft., climb 30 ft.',
        strScore: 15,
        dexScore: 10,
        conScore: 14,
        intScore: 2,
        wisScore: 12,
        chaScore: 7,
        skills: 'Perception +3',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'slashing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The bear has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The bear makes two attacks: one with its bite and one with its claws.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Claws',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '2d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_crocodile',
      name: 'Crocodile',
      statBlock: const MinionStatBlock(
        id: 'crocodile',
        name: 'Crocodile',
        sizeDisplay: 'Large',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        armorType: 'natural armor',
        maxHp: 19,
        hitDice: '3d10 + 3',
        speed: '20 ft., swim 30 ft.',
        strScore: 15,
        dexScore: 10,
        conScore: 13,
        intScore: 2,
        wisScore: 10,
        chaScore: 5,
        skills: 'Stealth +2',
        senses: 'passive Perception 10',
        languages: '—',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 10,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Hold Breath',
            description: 'The crocodile can hold its breath for 15 minutes.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10 + 2) piercing damage, and the target is grappled (escape DC 12). Until this grapple ends, the target is restrained, and the crocodile can\'t bite another target.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d10 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_gnoll',
      name: 'Gnoll',
      statBlock: const MinionStatBlock(
        id: 'gnoll',
        name: 'Gnoll',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (gnoll)',
        alignment: 'chaotic evil',
        ac: 15,
        armorType: 'hide armor, shield',
        maxHp: 22,
        hitDice: '5d8',
        speed: '30 ft.',
        strScore: 14,
        dexScore: 12,
        conScore: 11,
        intScore: 6,
        wisScore: 10,
        chaScore: 7,
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'Gnoll',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Rampage',
            description: 'When the gnoll reduces a creature to 0 hit points with a melee attack on its turn, the gnoll can take a bonus action to move up to half its speed and make a bite attack.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 4 (1d4 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d4 + 2',
          ),
          CreatureAction(
            name: 'Spear',
            description: 'Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 5 (1d6 + 2) piercing damage, or 6 (1d8 + 2) piercing damage if used with two hands to make a melee attack.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft. / range 20/60 ft.',
            hitDamage: '1d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_gray_ooze',
      name: 'Gray Ooze',
      statBlock: const MinionStatBlock(
        id: 'gray_ooze',
        name: 'Gray Ooze',
        sizeDisplay: 'Medium',
        typeDisplay: 'Ooze',
        alignment: 'unaligned',
        ac: 8,
        maxHp: 22,
        hitDice: '3d8 + 9',
        speed: '10 ft., climb 10 ft.',
        strScore: 12,
        dexScore: 6,
        conScore: 16,
        intScore: 1,
        wisScore: 6,
        chaScore: 2,
        skills: 'Stealth +2',
        damageResistances: 'acid, cold, fire',
        conditionImmunities: 'blinded, charmed, deafened, exhaustion, frightened, prone',
        senses: 'blindsight 60 ft. (blind beyond this radius), passive Perception 8',
        languages: '—',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'bludgeoning',
        secondaryDamageDiceCount: 2,
        secondaryDamageDiceSides: 6,
        secondaryDamageType: 'acid',
        accentColor: Color(0xFF84CC16),
        traits: [
          CreatureTrait(
            name: 'Amorphous',
            description: 'The ooze can move through a space as narrow as 1 inch wide without squeezing.',
          ),
          CreatureTrait(
            name: 'Corrode Metal',
            description: 'Any nonmagical weapon made of metal that hits the ooze corrodes. After dealing damage, the weapon takes a permanent and cumulative -1 penalty to damage rolls.',
          ),
          CreatureTrait(
            name: 'False Appearance',
            description: 'While the ooze remains motionless, it is indistinguishable from an oily pool or wet rock.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Pseudopod',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) bludgeoning damage plus 7 (2d6) acid damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d6 + 1 + 2d6 acid',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_hobgoblin',
      name: 'Hobgoblin',
      statBlock: const MinionStatBlock(
        id: 'hobgoblin',
        name: 'Hobgoblin',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (goblinoid)',
        alignment: 'lawful evil',
        ac: 18,
        armorType: 'chain mail, shield',
        maxHp: 11,
        hitDice: '2d8 + 2',
        speed: '30 ft.',
        strScore: 13,
        dexScore: 12,
        conScore: 12,
        intScore: 10,
        wisScore: 10,
        chaScore: 9,
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'Common, Goblin',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 1,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Martial Advantage',
            description: 'Once per turn, the hobgoblin can deal an extra 7 (2d6) damage to a creature it hits with a weapon attack if that creature is within 5 ft. of an ally of the hobgoblin that isn\'t incapacitated.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Longsword',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) slashing damage, or 6 (1d10 + 1) slashing damage if used with two hands.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d8 + 1',
          ),
          CreatureAction(
            name: 'Longbow',
            description: 'Ranged Weapon Attack: +3 to hit, range 150/600 ft., one target. Hit: 5 (1d8 + 1) piercing damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 3,
            reach: 'range 150/600 ft.',
            hitDamage: '1d8 + 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_lizardfolk',
      name: 'Lizardfolk',
      statBlock: const MinionStatBlock(
        id: 'lizardfolk',
        name: 'Lizardfolk',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (lizardfolk)',
        alignment: 'neutral',
        ac: 15,
        armorType: 'natural armor, shield',
        maxHp: 22,
        hitDice: '4d8 + 4',
        speed: '30 ft., swim 30 ft.',
        strScore: 15,
        dexScore: 10,
        conScore: 13,
        intScore: 7,
        wisScore: 12,
        chaScore: 7,
        skills: 'Perception +3, Stealth +4, Survival +5',
        senses: 'passive Perception 13',
        languages: 'Draconic',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Hold Breath',
            description: 'The lizardfolk can hold its breath for 15 minutes.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The lizardfolk makes two melee attacks, each one with a different weapon.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Heavy Club',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Javelin',
            description: 'Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft. / range 30/120 ft.',
            hitDamage: '1d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_orc',
      name: 'Orc',
      statBlock: const MinionStatBlock(
        id: 'orc',
        name: 'Orc',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (orc)',
        alignment: 'chaotic evil',
        ac: 13,
        armorType: 'hide armor',
        maxHp: 15,
        hitDice: '2d8 + 6',
        speed: '30 ft.',
        strScore: 16,
        dexScore: 12,
        conScore: 16,
        intScore: 7,
        wisScore: 11,
        chaScore: 10,
        skills: 'Intimidation +2',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'Common, Orc',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 12,
        damageBonus: 3,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Aggressive',
            description: 'As a bonus action, the orc can move up to its speed toward a hostile creature that it can see.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Greataxe',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d12 + 3',
          ),
          CreatureAction(
            name: 'Javelin',
            description: 'Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 6 (1d6 + 3) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft. / range 30/120 ft.',
            hitDamage: '1d6 + 3',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_shadow',
      name: 'Shadow',
      statBlock: const MinionStatBlock(
        id: 'shadow',
        name: 'Shadow',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'chaotic evil',
        ac: 12,
        maxHp: 16,
        hitDice: '3d8 + 3',
        speed: '40 ft.',
        strScore: 6,
        dexScore: 14,
        conScore: 13,
        intScore: 6,
        wisScore: 10,
        chaScore: 8,
        skills: 'Stealth +4',
        damageVulnerabilities: 'radiant',
        damageResistances: 'acid, cold, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks',
        damageImmunities: 'necrotic, poison',
        conditionImmunities: 'exhaustion, frightened, grappled, paralyzed, petrified, poisoned, prone, restrained',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: '—',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 4,
        damageDiceCount: 2,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'necrotic',
        accentColor: Color(0xFFCBD5E1),
        traits: [
          CreatureTrait(
            name: 'Amorphous',
            description: 'The shadow can move through a space as narrow as 1 inch wide without squeezing.',
          ),
          CreatureTrait(
            name: 'Shadow Stealth',
            description: 'While in dim light or darkness, the shadow can take the Hide action as a bonus action.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Strength Drain',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 9 (2d6 + 2) necrotic damage, and the target\'s Strength score is reduced by 1d4. The target dies if this reduces its Strength to 0. Otherwise, the reduction lasts until the target finishes a short or long rest.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '2d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_warhorse',
      name: 'Warhorse',
      statBlock: const MinionStatBlock(
        id: 'warhorse',
        name: 'Warhorse',
        sizeDisplay: 'Large',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        maxHp: 19,
        hitDice: '3d10 + 3',
        speed: '60 ft.',
        strScore: 18,
        dexScore: 12,
        conScore: 13,
        intScore: 2,
        wisScore: 12,
        chaScore: 7,
        senses: 'passive Perception 11',
        languages: '—',
        crDisplay: 'CR 1/2',
        xp: 100,
        attackBonus: 6,
        damageDiceCount: 2,
        damageDiceSides: 6,
        damageBonus: 4,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Trampling Charge',
            description: 'If the horse moves at least 20 ft. straight toward a creature and then hits it with a hooves attack on the same turn, that target must succeed on a DC 14 Strength saving throw or be knocked prone. If the target is prone, the horse can make another attack with its hooves against it as a bonus action.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Hooves',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '2d6 + 4',
          ),
        ],
      ),
    ),

    // =========================================================================
    // CR 1 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_animated_armor',
      name: 'Animated Armor',
      statBlock: const MinionStatBlock(
        id: 'animated_armor',
        name: 'Animated Armor',
        sizeDisplay: 'Medium',
        typeDisplay: 'Construct',
        alignment: 'unaligned',
        ac: 18,
        armorType: 'natural armor',
        maxHp: 33,
        hitDice: '6d8 + 6',
        speed: '25 ft.',
        strScore: 14,
        dexScore: 11,
        conScore: 13,
        intScore: 1,
        wisScore: 3,
        chaScore: 1,
        damageImmunities: 'poison, psychic',
        conditionImmunities: 'blinded, charmed, deafened, exhaustion, frightened, paralyzed, petrified, poisoned',
        senses: 'blindsight 60 ft. (blind beyond this radius), passive Perception 6',
        languages: '—',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'bludgeoning',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Antimagic Susceptibility',
            description: 'The armor is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the armor must succeed on a Con saving throw against the caster\'s spell save DC or fall unconscious for 1 minute.',
          ),
          CreatureTrait(
            name: 'False Appearance',
            description: 'While the armor remains motionless, it is indistinguishable from a normal suit of armor.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The armor makes two melee attacks.',
          ),
          CreatureAction(
            name: 'Slam',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_brown_bear',
      name: 'Brown Bear',
      statBlock: const MinionStatBlock(
        id: 'brown_bear',
        name: 'Brown Bear',
        sizeDisplay: 'Large',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        armorType: 'natural armor',
        maxHp: 34,
        hitDice: '4d10 + 12',
        speed: '40 ft., climb 30 ft.',
        strScore: 19,
        dexScore: 10,
        conScore: 16,
        intScore: 2,
        wisScore: 13,
        chaScore: 7,
        skills: 'Perception +3',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 6,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 4,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The bear has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The bear makes two attacks: one with its bite and one with its claws.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '1d8 + 4',
          ),
          CreatureAction(
            name: 'Claws',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '2d6 + 4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_bugbear',
      name: 'Bugbear',
      statBlock: const MinionStatBlock(
        id: 'bugbear',
        name: 'Bugbear',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (goblinoid)',
        alignment: 'chaotic evil',
        ac: 16,
        armorType: 'hide armor, shield',
        maxHp: 27,
        hitDice: '5d8 + 5',
        speed: '30 ft.',
        strScore: 15,
        dexScore: 14,
        conScore: 13,
        intScore: 8,
        wisScore: 11,
        chaScore: 9,
        skills: 'Stealth +6, Survival +2',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'Common, Goblin',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 4,
        damageDiceCount: 2,
        damageDiceSides: 8,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Brute',
            description: 'A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack).',
          ),
          CreatureTrait(
            name: 'Surprise Attack',
            description: 'If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 7 (2d6) damage from the attack.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Morningstar',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 11 (2d8 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '2d8 + 2',
          ),
          CreatureAction(
            name: 'Javelin',
            description: 'Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 9 (2d6 + 2) piercing damage in melee or 5 (1d6 + 2) piercing damage at range.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft. / range 30/120 ft.',
            hitDamage: '2d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_dire_wolf',
      name: 'Dire Wolf',
      statBlock: const MinionStatBlock(
        id: 'dire_wolf',
        name: 'Dire Wolf',
        sizeDisplay: 'Large',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 14,
        armorType: 'natural armor',
        maxHp: 37,
        hitDice: '5d10 + 10',
        speed: '50 ft.',
        strScore: 17,
        dexScore: 15,
        conScore: 15,
        intScore: 3,
        wisScore: 12,
        chaScore: 7,
        skills: 'Perception +3, Stealth +4',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 1',
        xp: 200,
        hasPackTactics: true,
        attackBonus: 5,
        damageDiceCount: 2,
        damageDiceSides: 6,
        damageBonus: 3,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Hearing and Smell',
            description: 'The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
          ),
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The wolf has advantage on attack rolls against a creature if at least one ally is within 5 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage. If the target is a creature, it must succeed on a DC 13 Strength saving throw or be knocked prone.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '2d6 + 3',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_dryad',
      name: 'Dryad',
      statBlock: const MinionStatBlock(
        id: 'dryad',
        name: 'Dryad',
        sizeDisplay: 'Medium',
        typeDisplay: 'Fey',
        alignment: 'neutral',
        ac: 11,
        armorType: '16 with barkskin',
        maxHp: 22,
        hitDice: '5d8',
        speed: '30 ft.',
        strScore: 10,
        dexScore: 12,
        conScore: 11,
        intScore: 14,
        wisScore: 15,
        chaScore: 18,
        skills: 'Perception +4, Stealth +5',
        senses: 'darkvision 60 ft., passive Perception 14',
        languages: 'Elvish, Sylvan',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 2,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 0,
        damageType: 'bludgeoning',
        accentColor: Color(0xFFC084FC),
        traits: [
          CreatureTrait(
            name: 'Magic Resistance',
            description: 'The dryad has advantage on saving throws against spells and other magical effects.',
          ),
          CreatureTrait(
            name: 'Tree Stride',
            description: 'Once on her turn, the dryad can use 10 ft. of her movement to step magically into one living tree within her reach and emerge from a second living tree within 60 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Club',
            description: 'Melee Weapon Attack: +2 to hit (+6 with shillelagh), reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage, or 8 (1d8 + 4) bludgeoning damage with shillelagh.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '1d4',
          ),
          CreatureAction(
            name: 'Fey Charm',
            description: 'The dryad targets one humanoid or beast that she can see within 30 ft. of her. If the target can see the dryad, it must succeed on a DC 14 Wisdom saving throw or be magically charmed for 1 day.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_ghoul',
      name: 'Ghoul',
      statBlock: const MinionStatBlock(
        id: 'ghoul',
        name: 'Ghoul',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'chaotic evil',
        ac: 12,
        maxHp: 22,
        hitDice: '5d8',
        speed: '30 ft.',
        strScore: 13,
        dexScore: 15,
        conScore: 10,
        intScore: 7,
        wisScore: 10,
        chaScore: 6,
        damageImmunities: 'poison',
        conditionImmunities: 'charmed, exhaustion, poisoned',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'Common',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 4,
        damageDiceCount: 2,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'slashing',
        accentColor: Color(0xFFCBD5E1),
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one creature. Hit: 9 (2d6 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '2d6 + 2',
          ),
          CreatureAction(
            name: 'Claws',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) slashing damage. If the target is a creature other than an elf or undead, it must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '2d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_giant_spider',
      name: 'Giant Spider',
      statBlock: const MinionStatBlock(
        id: 'giant_spider',
        name: 'Giant Spider',
        sizeDisplay: 'Large',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 14,
        armorType: 'natural armor',
        maxHp: 26,
        hitDice: '4d10 + 4',
        speed: '30 ft., climb 30 ft.',
        strScore: 14,
        dexScore: 16,
        conScore: 12,
        intScore: 2,
        wisScore: 11,
        chaScore: 4,
        skills: 'Stealth +7',
        senses: 'blindsight 10 ft., darkvision 60 ft., passive Perception 10',
        languages: '—',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 3,
        damageType: 'piercing',
        secondaryDamageDiceCount: 2,
        secondaryDamageDiceSides: 8,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Spider Climb',
            description: 'The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.',
          ),
          CreatureTrait(
            name: 'Web Sense',
            description: 'While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.',
          ),
          CreatureTrait(
            name: 'Web Walker',
            description: 'The spider ignores movement restrictions caused by webbing.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 7 (1d8 + 3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 9 (2d8) poison damage on a failed save, or half as much damage on a successful one.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d8 + 3 + 2d8 poison',
          ),
          CreatureAction(
            name: 'Web (Recharge 5-6)',
            description: 'Ranged Weapon Attack: +5 to hit, range 30/60 ft., one creature. Hit: The target is restrained by webbing. As an action, the restrained target can make a DC 12 Strength check, bursting the webbing on a success.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 5,
            reach: 'range 30/60 ft.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_harpy',
      name: 'Harpy',
      statBlock: const MinionStatBlock(
        id: 'harpy',
        name: 'Harpy',
        sizeDisplay: 'Medium',
        typeDisplay: 'Monstrosity',
        alignment: 'chaotic evil',
        ac: 11,
        maxHp: 38,
        hitDice: '7d8 + 7',
        speed: '20 ft., fly 40 ft.',
        strScore: 12,
        dexScore: 13,
        conScore: 12,
        intScore: 7,
        wisScore: 10,
        chaScore: 13,
        senses: 'passive Perception 10',
        languages: 'Common',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 3,
        damageDiceCount: 2,
        damageDiceSides: 4,
        damageBonus: 1,
        damageType: 'slashing',
        accentColor: Color(0xFFD97706),
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The harpy makes two attacks: one with its claws and one with its club.',
          ),
          CreatureAction(
            name: 'Claws',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (2d4 + 1) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '2d4 + 1',
          ),
          CreatureAction(
            name: 'Club',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 3 (1d4 + 1) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d4 + 1',
          ),
          CreatureAction(
            name: 'Luring Song',
            description: 'The harpy sings a magical melody. Every humanoid and giant within 300 ft. of the harpy that can hear the song must succeed on a DC 11 Wisdom saving throw or be charmed until the song ends.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_imp',
      name: 'Imp',
      statBlock: const MinionStatBlock(
        id: 'imp',
        name: 'Imp',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Fiend (Devil, Shapechanger)',
        alignment: 'lawful evil',
        ac: 13,
        maxHp: 10,
        hitDice: '3d4 + 3',
        speed: '20 ft., fly 40 ft.',
        strScore: 6,
        dexScore: 17,
        conScore: 13,
        intScore: 11,
        wisScore: 12,
        chaScore: 14,
        skills: 'Deception +4, Insight +3, Persuasion +4, Stealth +5',
        damageResistances: 'cold; bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons',
        damageImmunities: 'fire, poison',
        conditionImmunities: 'poisoned',
        senses: 'darkvision 120 ft., passive Perception 11',
        languages: 'Infernal, Common',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 3,
        damageType: 'piercing',
        secondaryDamageDiceCount: 3,
        secondaryDamageDiceSides: 6,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFFF43F5E),
        traits: [
          CreatureTrait(
            name: 'Devil\'s Sight',
            description: 'Magical darkness doesn\'t impede the imp\'s darkvision.',
          ),
          CreatureTrait(
            name: 'Magic Resistance',
            description: 'The imp has advantage on saving throws against spells and other magical effects.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Sting',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 5 (1d4 + 3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 10 (3d6) poison damage on a failed save, or half as much damage on a successful one.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d4 + 3 + 3d6 poison',
          ),
          CreatureAction(
            name: 'Invisibility',
            description: 'The imp magically turns invisible until it attacks or until its concentration ends (as if concentrating on a spell).',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_specter',
      name: 'Specter',
      statBlock: const MinionStatBlock(
        id: 'specter',
        name: 'Specter',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'chaotic evil',
        ac: 12,
        maxHp: 22,
        hitDice: '5d8',
        speed: '0 ft., fly 50 ft. (hover)',
        strScore: 1,
        dexScore: 14,
        conScore: 11,
        intScore: 10,
        wisScore: 10,
        chaScore: 11,
        damageResistances: 'acid, cold, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks',
        damageImmunities: 'necrotic, poison',
        conditionImmunities: 'charmed, exhaustion, grappled, paralyzed, petrified, poisoned, prone, restrained, unconscious',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'understands languages it knew in life but can\'t speak',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 4,
        damageDiceCount: 3,
        damageDiceSides: 6,
        damageBonus: 0,
        damageType: 'necrotic',
        accentColor: Color(0xFFCBD5E1),
        traits: [
          CreatureTrait(
            name: 'Incorporeal Movement',
            description: 'The specter can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.',
          ),
          CreatureTrait(
            name: 'Sunlight Sensitivity',
            description: 'While in sunlight, the specter has disadvantage on attack rolls and Perception checks.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Life Drain',
            description: 'Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 10 (3d6) necrotic damage. The target must succeed on a DC 10 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken.',
            attackType: 'Melee Spell Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '3d6',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_tiger',
      name: 'Tiger',
      statBlock: const MinionStatBlock(
        id: 'tiger',
        name: 'Tiger',
        sizeDisplay: 'Large',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 37,
        hitDice: '5d10 + 10',
        speed: '40 ft.',
        strScore: 17,
        dexScore: 15,
        conScore: 14,
        intScore: 3,
        wisScore: 12,
        chaScore: 8,
        skills: 'Perception +3, Stealth +6',
        senses: 'darkvision 60 ft., passive Perception 13',
        languages: '—',
        crDisplay: 'CR 1',
        xp: 200,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 10,
        damageBonus: 3,
        damageType: 'slashing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The tiger has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
          CreatureTrait(
            name: 'Pounce',
            description: 'If the tiger moves at least 20 ft. straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10 + 3) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d10 + 3',
          ),
          CreatureAction(
            name: 'Claw',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d8 + 3',
          ),
        ],
      ),
    ),
  ];
}
