import 'package:flutter/material.dart';
import '../../monster_codex_data.dart';
import '../../srd_summons/minion_stat_block.dart';

/// SRD 5.1 & 5.2 Bestiary entries for CR 0 through CR 1/4.
class BestiaryCr0ToQuarter {
  BestiaryCr0ToQuarter._();

  static final List<MonsterItem> entries = [
    // =========================================================================
    // CR 0 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_baboon',
      name: 'Baboon',
      statBlock: const MinionStatBlock(
        id: 'baboon',
        name: 'Baboon',
        sizeDisplay: 'Small',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 3,
        hitDice: '1d6',
        speed: '30 ft., climb 30 ft.',
        strScore: 8,
        dexScore: 14,
        conScore: 11,
        intScore: 4,
        wisScore: 12,
        chaScore: 6,
        senses: 'passive Perception 11',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        hasPackTactics: true,
        attackBonus: 1,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: -1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The baboon has advantage on an attack roll against a creature if at least one of the baboon\'s allies is within 5 feet of the creature and the ally isn\'t incapacitated.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +1 to hit, reach 5 ft., one target. Hit: 1 (1d4 - 1) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 1,
            reach: '5 ft.',
            hitDamage: '1d4 - 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_badger',
      name: 'Badger',
      statBlock: const MinionStatBlock(
        id: 'badger',
        name: 'Badger',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 10,
        maxHp: 3,
        hitDice: '1d4 + 1',
        speed: '20 ft., burrow 5 ft.',
        strScore: 4,
        dexScore: 11,
        conScore: 12,
        intScore: 2,
        wisScore: 12,
        chaScore: 5,
        senses: 'darkvision 30 ft., passive Perception 11',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 2,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The badger has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 1 piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_bat',
      name: 'Bat',
      statBlock: const MinionStatBlock(
        id: 'bat',
        name: 'Bat',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 1,
        hitDice: '1d4 - 1',
        speed: '5 ft., fly 30 ft.',
        strScore: 2,
        dexScore: 15,
        conScore: 8,
        intScore: 2,
        wisScore: 12,
        chaScore: 4,
        senses: 'blindsight 60 ft., passive Perception 11',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 0,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Echolocation',
            description: 'The bat can\'t use its blindsight while deafened.',
          ),
          CreatureTrait(
            name: 'Keen Hearing',
            description: 'The bat has advantage on Wisdom (Perception) checks that rely on hearing.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +0 to hit, reach 5 ft., one creature. Hit: 1 piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 0,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_cat',
      name: 'Cat',
      statBlock: const MinionStatBlock(
        id: 'cat',
        name: 'Cat',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 2,
        hitDice: '1d4',
        speed: '40 ft., climb 30 ft.',
        strScore: 3,
        dexScore: 15,
        conScore: 10,
        intScore: 3,
        wisScore: 12,
        chaScore: 7,
        skills: 'Perception +3, Stealth +4',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 0,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'slashing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The cat has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Claws',
            description: 'Melee Weapon Attack: +0 to hit, reach 5 ft., one target. Hit: 1 slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 0,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_commoner',
      name: 'Commoner',
      statBlock: const MinionStatBlock(
        id: 'commoner',
        name: 'Commoner',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any alignment',
        ac: 10,
        maxHp: 4,
        hitDice: '1d8',
        speed: '30 ft.',
        strScore: 10,
        dexScore: 10,
        conScore: 10,
        intScore: 10,
        wisScore: 10,
        chaScore: 10,
        senses: 'passive Perception 10',
        languages: 'any one language (usually Common)',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 2,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 0,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF94A3B8),
        actions: [
          CreatureAction(
            name: 'Club',
            description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '1d4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_crab',
      name: 'Crab',
      statBlock: const MinionStatBlock(
        id: 'crab',
        name: 'Crab',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        armorType: 'natural armor',
        maxHp: 2,
        hitDice: '1d4',
        speed: '20 ft., swim 20 ft.',
        strScore: 2,
        dexScore: 11,
        conScore: 10,
        intScore: 1,
        wisScore: 8,
        chaScore: 2,
        skills: 'Stealth +2',
        senses: 'blindsight 30 ft., passive Perception 9',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 0,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Amphibious',
            description: 'The crab can breathe air and water.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Claw',
            description: 'Melee Weapon Attack: +0 to hit, reach 5 ft., one target. Hit: 1 bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 0,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_deer',
      name: 'Deer',
      statBlock: const MinionStatBlock(
        id: 'deer',
        name: 'Deer',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 13,
        maxHp: 4,
        hitDice: '1d8',
        speed: '50 ft.',
        strScore: 11,
        dexScore: 16,
        conScore: 11,
        intScore: 2,
        wisScore: 14,
        chaScore: 5,
        senses: 'passive Perception 12',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 2,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 0,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '1d4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_eagle',
      name: 'Eagle',
      statBlock: const MinionStatBlock(
        id: 'eagle',
        name: 'Eagle',
        sizeDisplay: 'Small',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 3,
        hitDice: '1d6',
        speed: '10 ft., fly 60 ft.',
        strScore: 6,
        dexScore: 15,
        conScore: 10,
        intScore: 2,
        wisScore: 14,
        chaScore: 7,
        skills: 'Perception +4',
        senses: 'passive Perception 14',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'slashing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Sight',
            description: 'The eagle has advantage on Wisdom (Perception) checks that rely on sight.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Talons',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_frog',
      name: 'Frog',
      statBlock: const MinionStatBlock(
        id: 'frog',
        name: 'Frog',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        maxHp: 1,
        hitDice: '1d4 - 1',
        speed: '20 ft., swim 20 ft.',
        strScore: 1,
        dexScore: 13,
        conScore: 8,
        intScore: 1,
        wisScore: 8,
        chaScore: 3,
        skills: 'Perception +1, Stealth +3',
        senses: 'darkvision 30 ft., passive Perception 11',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 0,
        damageDiceCount: 0,
        damageDiceSides: 0,
        damageBonus: 0,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Amphibious',
            description: 'The frog can breathe air and water.',
          ),
          CreatureTrait(
            name: 'Standing Leap',
            description: 'The frog\'s long jump is up to 10 ft. and its high jump is up to 5 ft., with or without a running start.',
          ),
        ],
        actions: [],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_giant_fire_beetle',
      name: 'Giant Fire Beetle',
      statBlock: const MinionStatBlock(
        id: 'giant_fire_beetle',
        name: 'Giant Fire Beetle',
        sizeDisplay: 'Small',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 13,
        armorType: 'natural armor',
        maxHp: 4,
        hitDice: '1d6 + 1',
        speed: '30 ft.',
        strScore: 8,
        dexScore: 10,
        conScore: 12,
        intScore: 1,
        wisScore: 7,
        chaScore: 3,
        senses: 'blindsight 30 ft., passive Perception 8',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 1,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: -1,
        damageType: 'slashing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Illumination',
            description: 'The beetle sheds bright light in a 10-foot radius and dim light for an additional 10 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +1 to hit, reach 5 ft., one target. Hit: 2 (1d6 - 1) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 1,
            reach: '5 ft.',
            hitDamage: '1d6 - 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_goat',
      name: 'Goat',
      statBlock: const MinionStatBlock(
        id: 'goat',
        name: 'Goat',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 10,
        maxHp: 4,
        hitDice: '1d8',
        speed: '40 ft.',
        strScore: 12,
        dexScore: 10,
        conScore: 11,
        intScore: 2,
        wisScore: 10,
        chaScore: 5,
        senses: 'passive Perception 10',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 1,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Charge',
            description: 'If the goat moves at least 20 ft. straight toward a target and then hits it with a ram attack on the same turn, the target takes an extra 2 (1d4) bludgeoning damage.',
          ),
          CreatureTrait(
            name: 'Sure-Footed',
            description: 'The goat has advantage on Strength and Dexterity saving throws made against being knocked prone.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Ram',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 3 (1d4 + 1) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d4 + 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_hawk',
      name: 'Hawk',
      statBlock: const MinionStatBlock(
        id: 'hawk',
        name: 'Hawk',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 13,
        maxHp: 1,
        hitDice: '1d4 - 1',
        speed: '10 ft., fly 60 ft.',
        strScore: 5,
        dexScore: 16,
        conScore: 8,
        intScore: 2,
        wisScore: 14,
        chaScore: 6,
        skills: 'Perception +4',
        senses: 'passive Perception 14',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'slashing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Sight',
            description: 'The hawk has advantage on Wisdom (Perception) checks that rely on sight.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Talons',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 1 slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_homunculus',
      name: 'Homunculus',
      statBlock: const MinionStatBlock(
        id: 'homunculus',
        name: 'Homunculus',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Construct',
        alignment: 'neutral',
        ac: 13,
        armorType: 'natural armor',
        maxHp: 5,
        hitDice: '2d4',
        speed: '20 ft., fly 40 ft.',
        strScore: 4,
        dexScore: 15,
        conScore: 11,
        intScore: 10,
        wisScore: 10,
        chaScore: 7,
        damageImmunities: 'poison',
        conditionImmunities: 'charmed, poisoned',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'understands the languages of its creator but can\'t speak',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Telepathic Bond',
            description: 'While the homunculus is on the same plane of existence as its master, it can magically convey what it senses to its master, and the two can communicate telepathically.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 1 piercing damage, and the target must succeed on a DC 10 Constitution saving throw or be poisoned for 1 minute.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_hyena',
      name: 'Hyena',
      statBlock: const MinionStatBlock(
        id: 'hyena',
        name: 'Hyena',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        maxHp: 5,
        hitDice: '1d8 + 1',
        speed: '50 ft.',
        strScore: 11,
        dexScore: 12,
        conScore: 12,
        intScore: 2,
        wisScore: 12,
        chaScore: 5,
        skills: 'Perception +3',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        hasPackTactics: true,
        attackBonus: 2,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 0,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The hyena has advantage on an attack roll against a creature if at least one of the hyena\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 3 (1d6) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '1d6',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_jackal',
      name: 'Jackal',
      statBlock: const MinionStatBlock(
        id: 'jackal',
        name: 'Jackal',
        sizeDisplay: 'Small',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 3,
        hitDice: '1d6',
        speed: '40 ft.',
        strScore: 8,
        dexScore: 15,
        conScore: 11,
        intScore: 3,
        wisScore: 12,
        chaScore: 6,
        skills: 'Perception +3',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        hasPackTactics: true,
        attackBonus: 1,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: -1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Hearing and Smell',
            description: 'The jackal has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
          ),
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The jackal has advantage on attack rolls against a creature if at least one of the jackal\'s allies is within 5 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +1 to hit, reach 5 ft., one target. Hit: 1 (1d4 - 1) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 1,
            reach: '5 ft.',
            hitDamage: '1d4 - 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_lemure',
      name: 'Lemure',
      statBlock: const MinionStatBlock(
        id: 'lemure',
        name: 'Lemure',
        sizeDisplay: 'Medium',
        typeDisplay: 'Fiend (Devil)',
        alignment: 'lawful evil',
        ac: 7,
        maxHp: 13,
        hitDice: '3d8',
        speed: '15 ft.',
        strScore: 10,
        dexScore: 5,
        conScore: 11,
        intScore: 1,
        wisScore: 11,
        chaScore: 3,
        damageResistances: 'cold',
        damageImmunities: 'fire, poison',
        conditionImmunities: 'charmed, frightened, poisoned',
        senses: 'darkvision 120 ft., passive Perception 10',
        languages: 'understands Infernal but can\'t speak',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 0,
        damageType: 'bludgeoning',
        accentColor: Color(0xFFF43F5E),
        traits: [
          CreatureTrait(
            name: 'Devil\'s Sight',
            description: 'Magical darkness doesn\'t impede the lemure\'s darkvision.',
          ),
          CreatureTrait(
            name: 'Hellish Rejuvenation',
            description: 'A lemure that dies in the Nine Hells revives with all its hit points in 1d10 days unless it was killed by a good-aligned creature with a bless spell cast on that creature or its remains are sprinkled with holy water.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Fist',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_lizard',
      name: 'Lizard',
      statBlock: const MinionStatBlock(
        id: 'lizard',
        name: 'Lizard',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 10,
        maxHp: 2,
        hitDice: '1d4',
        speed: '20 ft., climb 20 ft.',
        strScore: 2,
        dexScore: 11,
        conScore: 10,
        intScore: 1,
        wisScore: 8,
        chaScore: 3,
        senses: 'darkvision 30 ft., passive Perception 9',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 0,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +0 to hit, reach 5 ft., one target. Hit: 1 piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 0,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_octopus',
      name: 'Octopus',
      statBlock: const MinionStatBlock(
        id: 'octopus',
        name: 'Octopus',
        sizeDisplay: 'Small',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 3,
        hitDice: '1d6',
        speed: '5 ft., swim 30 ft.',
        strScore: 4,
        dexScore: 15,
        conScore: 11,
        intScore: 3,
        wisScore: 10,
        chaScore: 4,
        skills: 'Perception +2, Stealth +4',
        senses: 'darkvision 30 ft., passive Perception 12',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Hold Breath',
            description: 'While out of water, the octopus can hold its breath for 30 minutes.',
          ),
          CreatureTrait(
            name: 'Underwater Camouflage',
            description: 'The octopus has advantage on Dexterity (Stealth) checks made while underwater.',
          ),
          CreatureTrait(
            name: 'Water Breathing',
            description: 'The octopus can breathe only underwater.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Tentacles',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 1 bludgeoning damage, and the target is grappled (escape DC 10).',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1',
          ),
          CreatureAction(
            name: 'Ink Cloud (Recharges after a Short or Long Rest)',
            description: 'A 5-foot-radius cloud of ink extends all around the octopus if it is underwater. The area is heavily obscured for 1 minute.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_owl',
      name: 'Owl',
      statBlock: const MinionStatBlock(
        id: 'owl',
        name: 'Owl',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        maxHp: 1,
        hitDice: '1d4 - 1',
        speed: '5 ft., fly 60 ft.',
        strScore: 3,
        dexScore: 13,
        conScore: 8,
        intScore: 2,
        wisScore: 12,
        chaScore: 7,
        skills: 'Perception +3, Stealth +3',
        senses: 'darkvision 120 ft., passive Perception 13',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'slashing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Flyby',
            description: 'The owl doesn\'t provoke opportunity attacks when it flies out of an enemy\'s reach.',
          ),
          CreatureTrait(
            name: 'Keen Hearing and Sight',
            description: 'The owl has advantage on Wisdom (Perception) checks that rely on hearing or sight.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Talons',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 1 slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_rat',
      name: 'Rat',
      statBlock: const MinionStatBlock(
        id: 'rat',
        name: 'Rat',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 10,
        maxHp: 1,
        hitDice: '1d4 - 1',
        speed: '20 ft.',
        strScore: 2,
        dexScore: 11,
        conScore: 9,
        intScore: 2,
        wisScore: 10,
        chaScore: 4,
        senses: 'darkvision 30 ft., passive Perception 10',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 0,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The rat has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +0 to hit, reach 5 ft., one target. Hit: 1 piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 0,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_raven',
      name: 'Raven',
      statBlock: const MinionStatBlock(
        id: 'raven',
        name: 'Raven',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 1,
        hitDice: '1d4 - 1',
        speed: '10 ft., fly 50 ft.',
        strScore: 2,
        dexScore: 14,
        conScore: 8,
        intScore: 2,
        wisScore: 12,
        chaScore: 6,
        skills: 'Perception +3',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Mimicry',
            description: 'The raven can mimic simple sounds it has heard. A creature that hears the sounds can tell they are imitations with a successful DC 10 Wisdom (Insight) check.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Beak',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 1 piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_scorpion',
      name: 'Scorpion',
      statBlock: const MinionStatBlock(
        id: 'scorpion',
        name: 'Scorpion',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        armorType: 'natural armor',
        maxHp: 1,
        hitDice: '1d4 - 1',
        speed: '10 ft.',
        strScore: 2,
        dexScore: 11,
        conScore: 8,
        intScore: 1,
        wisScore: 8,
        chaScore: 2,
        senses: 'blindsight 10 ft., passive Perception 9',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 2,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        secondaryDamageDiceCount: 1,
        secondaryDamageDiceSides: 8,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFF22C55E),
        actions: [
          CreatureAction(
            name: 'Sting',
            description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one creature. Hit: 1 piercing damage, and the target must make a DC 9 Constitution saving throw, taking 4 (1d8) poison damage on a failed save, or half as much damage on a successful one.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '1 + 1d8 poison',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_spider',
      name: 'Spider',
      statBlock: const MinionStatBlock(
        id: 'spider',
        name: 'Spider',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 1,
        hitDice: '1d4 - 1',
        speed: '20 ft., climb 20 ft.',
        strScore: 2,
        dexScore: 14,
        conScore: 8,
        intScore: 1,
        wisScore: 10,
        chaScore: 2,
        skills: 'Stealth +4',
        senses: 'darkvision 30 ft., passive Perception 10',
        languages: '—',
        crDisplay: 'CR 0',
        xp: 10,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        secondaryDamageDiceCount: 1,
        secondaryDamageDiceSides: 4,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Spider Climb',
            description: 'The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.',
          ),
          CreatureTrait(
            name: 'Web Sense',
            description: 'While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 1 piercing damage, and the target must succeed on a DC 9 Constitution saving throw or take 2 (1d4) poison damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1 + 1d4 poison',
          ),
        ],
      ),
    ),

    // =========================================================================
    // CR 1/8 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_bandit',
      name: 'Bandit',
      statBlock: const MinionStatBlock(
        id: 'bandit',
        name: 'Bandit',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any non-lawful alignment',
        ac: 12,
        armorType: 'leather armor',
        maxHp: 11,
        hitDice: '2d8 + 2',
        speed: '30 ft.',
        strScore: 11,
        dexScore: 12,
        conScore: 12,
        intScore: 10,
        wisScore: 10,
        chaScore: 10,
        senses: 'passive Perception 10',
        languages: 'any one language (usually Common)',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        actions: [
          CreatureAction(
            name: 'Scimitar',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d6 + 1',
          ),
          CreatureAction(
            name: 'Light Crossbow',
            description: 'Ranged Weapon Attack: +3 to hit, range 80/320 ft., one target. Hit: 5 (1d8 + 1) piercing damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 3,
            reach: 'range 80/320 ft.',
            hitDamage: '1d8 + 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_blood_hawk',
      name: 'Blood Hawk',
      statBlock: const MinionStatBlock(
        id: 'blood_hawk',
        name: 'Blood Hawk',
        sizeDisplay: 'Small',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 7,
        hitDice: '2d6',
        speed: '10 ft., fly 60 ft.',
        strScore: 6,
        dexScore: 14,
        conScore: 10,
        intScore: 3,
        wisScore: 14,
        chaScore: 5,
        skills: 'Perception +4',
        senses: 'passive Perception 14',
        languages: '—',
        crDisplay: 'CR 1/8',
        xp: 25,
        hasPackTactics: true,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Sight',
            description: 'The hawk has advantage on Wisdom (Perception) checks that rely on sight.',
          ),
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The hawk has advantage on an attack roll against a creature if at least one of the hawk\'s allies is within 5 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Beak',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_cultist',
      name: 'Cultist',
      statBlock: const MinionStatBlock(
        id: 'cultist',
        name: 'Cultist',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any non-good alignment',
        ac: 12,
        armorType: 'leather armor',
        maxHp: 9,
        hitDice: '2d8',
        speed: '30 ft.',
        strScore: 11,
        dexScore: 12,
        conScore: 10,
        intScore: 10,
        wisScore: 11,
        chaScore: 10,
        skills: 'Deception +2, Religion +2',
        senses: 'passive Perception 10',
        languages: 'any one language (usually Common)',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Dark Devotion',
            description: 'The cultist has advantage on saving throws against being charmed or frightened.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Scimitar',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 4 (1d6 + 1) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d6 + 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_flying_snake',
      name: 'Flying Snake',
      statBlock: const MinionStatBlock(
        id: 'flying_snake',
        name: 'Flying Snake',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 14,
        maxHp: 5,
        hitDice: '2d4',
        speed: '30 ft., fly 60 ft., swim 30 ft.',
        strScore: 4,
        dexScore: 18,
        conScore: 11,
        intScore: 2,
        wisScore: 12,
        chaScore: 5,
        senses: 'blindsight 10 ft., passive Perception 11',
        languages: '—',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 6,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        secondaryDamageDiceCount: 3,
        secondaryDamageDiceSides: 4,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Flyby',
            description: 'The snake doesn\'t provoke opportunity attacks when it flies out of an enemy\'s reach.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 1 piercing damage plus 7 (3d4) poison damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '1 + 3d4 poison',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_giant_rat',
      name: 'Giant Rat',
      statBlock: const MinionStatBlock(
        id: 'giant_rat',
        name: 'Giant Rat',
        sizeDisplay: 'Small',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 7,
        hitDice: '2d6',
        speed: '30 ft.',
        strScore: 7,
        dexScore: 15,
        conScore: 11,
        intScore: 2,
        wisScore: 10,
        chaScore: 4,
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: '—',
        crDisplay: 'CR 1/8',
        xp: 25,
        hasPackTactics: true,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The rat has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The rat has advantage on attack rolls against a creature if at least one of the rat\'s allies is within 5 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_guard',
      name: 'Guard',
      statBlock: const MinionStatBlock(
        id: 'guard',
        name: 'Guard',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any alignment',
        ac: 16,
        armorType: 'chain shirt, shield',
        maxHp: 11,
        hitDice: '2d8 + 2',
        speed: '30 ft.',
        strScore: 13,
        dexScore: 12,
        conScore: 12,
        intScore: 10,
        wisScore: 11,
        chaScore: 10,
        skills: 'Perception +2',
        senses: 'passive Perception 12',
        languages: 'any one language (usually Common)',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        actions: [
          CreatureAction(
            name: 'Spear',
            description: 'Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6 + 1) piercing damage, or 5 (1d8 + 1) piercing damage if used with two hands to make a melee attack.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft. / range 20/60 ft.',
            hitDamage: '1d6 + 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_kobold',
      name: 'Kobold',
      statBlock: const MinionStatBlock(
        id: 'kobold',
        name: 'Kobold',
        sizeDisplay: 'Small',
        typeDisplay: 'Humanoid (kobold)',
        alignment: 'lawful evil',
        ac: 12,
        armorType: 'leather armor',
        maxHp: 5,
        hitDice: '2d6 - 2',
        speed: '30 ft.',
        strScore: 7,
        dexScore: 15,
        conScore: 9,
        intScore: 8,
        wisScore: 7,
        chaScore: 8,
        senses: 'darkvision 60 ft., passive Perception 8',
        languages: 'Common, Draconic',
        crDisplay: 'CR 1/8',
        xp: 25,
        hasPackTactics: true,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Sunlight Sensitivity',
            description: 'While in sunlight, the kobold has disadvantage on attack rolls and Wisdom (Perception) checks.',
          ),
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The kobold has advantage on attack rolls against a creature if at least one ally is within 5 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Dagger',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d4 + 2',
          ),
          CreatureAction(
            name: 'Sling',
            description: 'Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 4 (1d4 + 2) bludgeoning damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 4,
            reach: 'range 30/120 ft.',
            hitDamage: '1d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_mastiff',
      name: 'Mastiff',
      statBlock: const MinionStatBlock(
        id: 'mastiff',
        name: 'Mastiff',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 12,
        maxHp: 5,
        hitDice: '1d8 + 1',
        speed: '40 ft.',
        strScore: 13,
        dexScore: 14,
        conScore: 12,
        intScore: 3,
        wisScore: 12,
        chaScore: 7,
        skills: 'Perception +3',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Hearing and Smell',
            description: 'The mastiff has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d6 + 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_mule',
      name: 'Mule',
      statBlock: const MinionStatBlock(
        id: 'mule',
        name: 'Mule',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 10,
        maxHp: 11,
        hitDice: '2d8 + 2',
        speed: '40 ft.',
        strScore: 14,
        dexScore: 10,
        conScore: 13,
        intScore: 2,
        wisScore: 10,
        chaScore: 5,
        senses: 'passive Perception 10',
        languages: '—',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 2,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Beast of Burden',
            description: 'The mule is considered to be a Large animal for the purpose of determining its carrying capacity.',
          ),
          CreatureTrait(
            name: 'Sure-Footed',
            description: 'The mule has advantage on Strength and Dexterity saving throws made against being knocked prone.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Hooves',
            description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '1d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_noble',
      name: 'Noble',
      statBlock: const MinionStatBlock(
        id: 'noble',
        name: 'Noble',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any alignment',
        ac: 15,
        armorType: 'breastplate',
        maxHp: 9,
        hitDice: '2d8',
        speed: '30 ft.',
        strScore: 11,
        dexScore: 12,
        conScore: 11,
        intScore: 12,
        wisScore: 14,
        chaScore: 16,
        skills: 'Deception +5, Insight +4, Persuasion +5',
        senses: 'passive Perception 12',
        languages: 'any two languages',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        actions: [
          CreatureAction(
            name: 'Rapier',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d8 + 1',
          ),
        ],
        reactions: [
          CreatureAction(
            name: 'Parry',
            description: 'The noble adds 2 to its AC against one melee attack that would hit it. To do so, the noble must see the attacker and be wielding a melee weapon.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_poisonous_snake',
      name: 'Poisonous Snake',
      statBlock: const MinionStatBlock(
        id: 'poisonous_snake',
        name: 'Poisonous Snake',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 13,
        maxHp: 2,
        hitDice: '1d4',
        speed: '30 ft., swim 30 ft.',
        strScore: 2,
        dexScore: 16,
        conScore: 11,
        intScore: 1,
        wisScore: 10,
        chaScore: 3,
        senses: 'blindsight 10 ft., passive Perception 10',
        languages: '—',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 1,
        damageBonus: 1,
        damageType: 'piercing',
        secondaryDamageDiceCount: 2,
        secondaryDamageDiceSides: 4,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFF22C55E),
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 1 piercing damage, and the target must make a DC 10 Constitution saving throw, taking 5 (2d4) poison damage on a failed save, or half as much damage on a successful one.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1 + 2d4 poison',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_pony',
      name: 'Pony',
      statBlock: const MinionStatBlock(
        id: 'pony',
        name: 'Pony',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 10,
        maxHp: 11,
        hitDice: '2d8 + 2',
        speed: '40 ft.',
        strScore: 15,
        dexScore: 10,
        conScore: 13,
        intScore: 2,
        wisScore: 11,
        chaScore: 7,
        senses: 'passive Perception 10',
        languages: '—',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 4,
        damageDiceCount: 2,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        actions: [
          CreatureAction(
            name: 'Hooves',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '2d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_stirge',
      name: 'Stirge',
      statBlock: const MinionStatBlock(
        id: 'stirge',
        name: 'Stirge',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Monstrosity',
        alignment: 'unaligned',
        ac: 14,
        armorType: 'natural armor',
        maxHp: 2,
        hitDice: '1d4',
        speed: '10 ft., fly 40 ft.',
        strScore: 4,
        dexScore: 16,
        conScore: 11,
        intScore: 2,
        wisScore: 8,
        chaScore: 6,
        senses: 'darkvision 60 ft., passive Perception 9',
        languages: '—',
        crDisplay: 'CR 1/8',
        xp: 25,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 3,
        damageType: 'piercing',
        accentColor: Color(0xFFD97706),
        actions: [
          CreatureAction(
            name: 'Blood Drain',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 5 (1d4 + 3) piercing damage, and the stirge attaches to the target. While attached, the stirge doesn\'t attack. Instead, at the start of each of the stirge\'s turns, the target loses 5 (1d4 + 3) hit points due to blood loss.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d4 + 3',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_tribal_warrior',
      name: 'Tribal Warrior',
      statBlock: const MinionStatBlock(
        id: 'tribal_warrior',
        name: 'Tribal Warrior',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any alignment',
        ac: 12,
        armorType: 'hide armor',
        maxHp: 11,
        hitDice: '2d8 + 2',
        speed: '30 ft.',
        strScore: 13,
        dexScore: 11,
        conScore: 12,
        intScore: 8,
        wisScore: 11,
        chaScore: 8,
        senses: 'passive Perception 10',
        languages: 'any one language',
        crDisplay: 'CR 1/8',
        xp: 25,
        hasPackTactics: true,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The warrior has advantage on attack rolls against a creature if at least one ally is within 5 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Spear',
            description: 'Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6 + 1) piercing damage, or 5 (1d8 + 1) piercing damage if used with two hands to make a melee attack.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft. / range 20/60 ft.',
            hitDamage: '1d6 + 1',
          ),
        ],
      ),
    ),

    // =========================================================================
    // CR 1/4 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_acolyte',
      name: 'Acolyte',
      statBlock: const MinionStatBlock(
        id: 'acolyte',
        name: 'Acolyte',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any alignment',
        ac: 10,
        maxHp: 9,
        hitDice: '2d8',
        speed: '30 ft.',
        strScore: 10,
        dexScore: 10,
        conScore: 10,
        intScore: 10,
        wisScore: 14,
        chaScore: 11,
        skills: 'Medicine +4, Religion +2',
        senses: 'passive Perception 12',
        languages: 'any any two languages',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 2,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 0,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Spellcasting',
            description: 'The acolyte is a 1st-level spellcaster (spell save DC 12, +4 to hit with spell attacks). Cantrips: light, sacred flame, thaumaturgy. 1st level (3 slots): bless, cure wounds, sanctuary.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Club',
            description: 'Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 2 (1d4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 2,
            reach: '5 ft.',
            hitDamage: '1d4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_blink_dog',
      name: 'Blink Dog',
      statBlock: const MinionStatBlock(
        id: 'blink_dog',
        name: 'Blink Dog',
        sizeDisplay: 'Medium',
        typeDisplay: 'Fey',
        alignment: 'lawful good',
        ac: 13,
        maxHp: 22,
        hitDice: '4d8 + 4',
        speed: '40 ft.',
        strScore: 12,
        dexScore: 17,
        conScore: 12,
        intScore: 10,
        wisScore: 13,
        chaScore: 11,
        skills: 'Perception +3, Stealth +5',
        senses: 'passive Perception 13',
        languages: 'Blink Dog, understands Sylvan but can\'t speak it',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFFC084FC),
        traits: [
          CreatureTrait(
            name: 'Keen Hearing and Smell',
            description: 'The dog has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d6 + 1',
          ),
          CreatureAction(
            name: 'Teleport (Recharge 4-6)',
            description: 'The dog magically teleports, along with any equipment it is wearing or carrying, up to 40 ft. to an unoccupied space it can see. Before or after teleporting, the dog can make one bite attack.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_drow',
      name: 'Drow',
      statBlock: const MinionStatBlock(
        id: 'drow',
        name: 'Drow',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (elf)',
        alignment: 'neutral evil',
        ac: 15,
        armorType: 'chain shirt',
        maxHp: 13,
        hitDice: '3d8',
        speed: '30 ft.',
        strScore: 10,
        dexScore: 14,
        conScore: 10,
        intScore: 11,
        wisScore: 11,
        chaScore: 12,
        skills: 'Perception +2, Stealth +4',
        senses: 'darkvision 120 ft., passive Perception 12',
        languages: 'Elvish, Undercommon',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Fey Ancestry',
            description: 'The drow has advantage on saving throws against being charmed, and magic can\'t put the drow to sleep.',
          ),
          CreatureTrait(
            name: 'Sunlight Sensitivity',
            description: 'While in sunlight, the drow has disadvantage on attack rolls and Perception checks.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Shortsword',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Hand Crossbow',
            description: 'Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 5 (1d6 + 2) piercing damage, and the target must succeed on a DC 13 Constitution saving throw or be poisoned for 1 hour.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 4,
            reach: 'range 30/120 ft.',
            hitDamage: '1d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_flying_sword',
      name: 'Flying Sword',
      statBlock: const MinionStatBlock(
        id: 'flying_sword',
        name: 'Flying Sword',
        sizeDisplay: 'Small',
        typeDisplay: 'Construct',
        alignment: 'unaligned',
        ac: 17,
        armorType: 'natural armor',
        maxHp: 17,
        hitDice: '5d6',
        speed: '0 ft., fly 50 ft. (hover)',
        strScore: 12,
        dexScore: 15,
        conScore: 11,
        intScore: 1,
        wisScore: 5,
        chaScore: 1,
        savingThrows: 'Dex +4',
        damageImmunities: 'poison, psychic',
        conditionImmunities: 'blinded, charmed, deafened, frightened, paralyzed, petrified, poisoned',
        senses: 'blindsight 60 ft. (blind beyond this radius), passive Perception 7',
        languages: '—',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 1,
        damageType: 'slashing',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Antimagic Susceptibility',
            description: 'The sword is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the sword must succeed on a Con saving throw against the caster\'s spell save DC or fall unconscious for 1 minute.',
          ),
          CreatureTrait(
            name: 'False Appearance',
            description: 'While the sword remains motionless, it is indistinguishable from a normal sword.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Longsword',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d8 + 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_giant_badger',
      name: 'Giant Badger',
      statBlock: const MinionStatBlock(
        id: 'giant_badger',
        name: 'Giant Badger',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 10,
        maxHp: 13,
        hitDice: '2d8 + 4',
        speed: '30 ft., burrow 10 ft.',
        strScore: 13,
        dexScore: 10,
        conScore: 15,
        intScore: 2,
        wisScore: 12,
        chaScore: 5,
        senses: 'darkvision 30 ft., passive Perception 11',
        languages: '—',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Smell',
            description: 'The badger has advantage on Wisdom (Perception) checks that rely on smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The badger makes two attacks: one with its bite and one with its claws.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d6 + 1',
          ),
          CreatureAction(
            name: 'Claws',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (2d4 + 1) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '2d4 + 1',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_giant_centipede',
      name: 'Giant Centipede',
      statBlock: const MinionStatBlock(
        id: 'giant_centipede',
        name: 'Giant Centipede',
        sizeDisplay: 'Small',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 13,
        armorType: 'natural armor',
        maxHp: 4,
        hitDice: '1d6 + 1',
        speed: '30 ft., climb 30 ft.',
        strScore: 5,
        dexScore: 14,
        conScore: 12,
        intScore: 1,
        wisScore: 7,
        chaScore: 3,
        senses: 'blindsight 30 ft., passive Perception 8',
        languages: '—',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'piercing',
        secondaryDamageDiceCount: 3,
        secondaryDamageDiceSides: 6,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFF22C55E),
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 4 (1d4 + 2) piercing damage, and the target must succeed on a DC 11 Constitution saving throw or take 10 (3d6) poison damage. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, even after regaining hit points, and is paralyzed while poisoned in this way.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d4 + 2 + 3d6 poison',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_giant_frog',
      name: 'Giant Frog',
      statBlock: const MinionStatBlock(
        id: 'giant_frog',
        name: 'Giant Frog',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 11,
        maxHp: 18,
        hitDice: '4d8',
        speed: '30 ft., swim 30 ft.',
        strScore: 12,
        dexScore: 13,
        conScore: 11,
        intScore: 2,
        wisScore: 10,
        chaScore: 3,
        skills: 'Perception +2, Stealth +3',
        senses: 'darkvision 30 ft., passive Perception 12',
        languages: '—',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Amphibious',
            description: 'The frog can breathe air and water.',
          ),
          CreatureTrait(
            name: 'Standing Leap',
            description: 'The frog\'s long jump is up to 20 ft. and its high jump is up to 10 ft., with or without a running start.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) piercing damage, and the target is grappled (escape DC 11). Until this grapple ends, the target is restrained, and the frog can\'t bite another target.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d6 + 1',
          ),
          CreatureAction(
            name: 'Swallow',
            description: 'The frog makes one bite attack against a Small or smaller target it is grappling. If the attack hits, the target is swallowed, and the grapple ends. The swallowed target is blinded and restrained, has total cover against attacks and other effects outside the frog, and takes 5 (2d4) acid damage at the start of each of the frog\'s turns.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_goblin',
      name: 'Goblin',
      statBlock: const MinionStatBlock(
        id: 'goblin',
        name: 'Goblin',
        sizeDisplay: 'Small',
        typeDisplay: 'Humanoid (goblinoid)',
        alignment: 'neutral evil',
        ac: 15,
        armorType: 'leather armor, shield',
        maxHp: 7,
        hitDice: '2d6',
        speed: '30 ft.',
        strScore: 8,
        dexScore: 14,
        conScore: 10,
        intScore: 10,
        wisScore: 8,
        chaScore: 8,
        skills: 'Stealth +6',
        senses: 'darkvision 60 ft., passive Perception 9',
        languages: 'Common, Goblin',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Nimble Escape',
            description: 'The goblin can take the Disengage or Hide action as a bonus action on each of its turns.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Scimitar',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Shortbow',
            description: 'Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 4,
            reach: 'range 80/320 ft.',
            hitDamage: '1d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_skeleton',
      name: 'Skeleton',
      statBlock: const MinionStatBlock(
        id: 'skeleton',
        name: 'Skeleton',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'lawful evil',
        ac: 13,
        armorType: 'armor scraps',
        maxHp: 13,
        hitDice: '2d8 + 4',
        speed: '30 ft.',
        strScore: 10,
        dexScore: 14,
        conScore: 15,
        intScore: 6,
        wisScore: 8,
        chaScore: 5,
        damageVulnerabilities: 'bludgeoning',
        damageImmunities: 'poison',
        conditionImmunities: 'exhaustion, poisoned',
        senses: 'darkvision 60 ft., passive Perception 9',
        languages: 'understands languages it knew in life but can\'t speak',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFFCBD5E1),
        actions: [
          CreatureAction(
            name: 'Shortsword',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Shortbow',
            description: 'Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 4,
            reach: 'range 80/320 ft.',
            hitDamage: '1d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_wolf',
      name: 'Wolf',
      statBlock: const MinionStatBlock(
        id: 'wolf',
        name: 'Wolf',
        sizeDisplay: 'Medium',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 13,
        armorType: 'natural armor',
        maxHp: 11,
        hitDice: '2d8 + 2',
        speed: '40 ft.',
        strScore: 12,
        dexScore: 15,
        conScore: 12,
        intScore: 3,
        wisScore: 12,
        chaScore: 6,
        skills: 'Perception +3, Stealth +4',
        senses: 'passive Perception 13',
        languages: '—',
        crDisplay: 'CR 1/4',
        xp: 50,
        hasPackTactics: true,
        attackBonus: 4,
        damageDiceCount: 2,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Keen Hearing and Smell',
            description: 'The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
          ),
          CreatureTrait(
            name: 'Pack Tactics',
            description: 'The wolf has advantage on attack rolls against a creature if at least one ally is within 5 ft.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) piercing damage. If the target is a creature, it must succeed on a DC 11 Strength saving throw or be knocked prone.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '2d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_zombie',
      name: 'Zombie',
      statBlock: const MinionStatBlock(
        id: 'zombie',
        name: 'Zombie',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'neutral evil',
        ac: 8,
        maxHp: 22,
        hitDice: '3d8 + 9',
        speed: '20 ft.',
        strScore: 13,
        dexScore: 6,
        conScore: 16,
        intScore: 3,
        wisScore: 6,
        chaScore: 5,
        savingThrows: 'Wis +0',
        damageImmunities: 'poison',
        conditionImmunities: 'poisoned',
        senses: 'darkvision 60 ft., passive Perception 8',
        languages: 'understands languages it knew in life but can\'t speak',
        crDisplay: 'CR 1/4',
        xp: 50,
        attackBonus: 3,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 1,
        damageType: 'bludgeoning',
        accentColor: Color(0xFFCBD5E1),
        traits: [
          CreatureTrait(
            name: 'Undead Fortitude',
            description: 'If damage reduces the zombie to 0 hit points, it must make a Con save DC 5 + damage taken, unless radiant or a critical hit. On success, zombie drops to 1 HP instead.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Slam',
            description: 'Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 3,
            reach: '5 ft.',
            hitDamage: '1d6 + 1',
          ),
        ],
      ),
    ),
  ];
}
