import 'package:flutter/material.dart';
import '../../monster_codex_data.dart';
import '../../srd_summons/minion_stat_block.dart';

/// SRD 5.1 & 5.2 Bestiary entries for CR 2 through CR 4.
class BestiaryCrTwoToFour {
  BestiaryCrTwoToFour._();

  static final List<MonsterItem> entries = [
    // =========================================================================
    // CR 2 CREATURES
    // =========================================================================
    MonsterItem.simple(
      id: 'srd_mon_allosaurus',
      name: 'Allosaurus',
      statBlock: const MinionStatBlock(
        id: 'allosaurus',
        name: 'Allosaurus',
        sizeDisplay: 'Large',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 13,
        armorType: 'natural armor',
        maxHp: 51,
        hitDice: '6d10 + 18',
        speed: '60 ft.',
        strScore: 19,
        dexScore: 13,
        conScore: 17,
        intScore: 2,
        wisScore: 12,
        chaScore: 5,
        skills: 'Perception +5',
        senses: 'passive Perception 15',
        languages: '—',
        crDisplay: 'CR 2',
        xp: 450,
        attackBonus: 6,
        damageDiceCount: 2,
        damageDiceSides: 10,
        damageBonus: 4,
        damageType: 'piercing',
        accentColor: Color(0xFF22C55E),
        traits: [
          CreatureTrait(
            name: 'Pounce',
            description: 'If the allosaurus moves at least 30 ft. straight toward a creature and then hits it with a claw attack on the same turn, that target must succeed on a DC 13 Strength saving throw or be knocked prone. If the target is prone, the allosaurus can make one bite attack against it as a bonus action.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Claw',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 8 (1d8 + 4) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '1d8 + 4',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 15 (2d10 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '2d10 + 4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_ankylosaurus',
      name: 'Ankylosaurus',
      statBlock: const MinionStatBlock(
        id: 'ankylosaurus',
        name: 'Ankylosaurus',
        sizeDisplay: 'Huge',
        typeDisplay: 'Beast',
        alignment: 'unaligned',
        ac: 15,
        armorType: 'natural armor',
        maxHp: 68,
        hitDice: '8d12 + 16',
        speed: '30 ft.',
        strScore: 19,
        dexScore: 11,
        conScore: 15,
        intScore: 2,
        wisScore: 12,
        chaScore: 5,
        senses: 'passive Perception 11',
        languages: '—',
        crDisplay: 'CR 3',
        xp: 700,
        attackBonus: 7,
        damageDiceCount: 4,
        damageDiceSides: 6,
        damageBonus: 4,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF22C55E),
        actions: [
          CreatureAction(
            name: 'Tail',
            description: 'Melee Weapon Attack: +7 to hit, reach 10 ft., one target. Hit: 18 (4d6 + 4) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Strength saving throw or be knocked prone.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 7,
            reach: '10 ft.',
            hitDamage: '4d6 + 4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_basilisk',
      name: 'Basilisk',
      statBlock: const MinionStatBlock(
        id: 'basilisk',
        name: 'Basilisk',
        sizeDisplay: 'Medium',
        typeDisplay: 'Monstrosity',
        alignment: 'unaligned',
        ac: 15,
        armorType: 'natural armor',
        maxHp: 52,
        hitDice: '8d8 + 16',
        speed: '20 ft.',
        strScore: 16,
        dexScore: 8,
        conScore: 15,
        intScore: 2,
        wisScore: 8,
        chaScore: 7,
        senses: 'darkvision 60 ft., passive Perception 9',
        languages: '—',
        crDisplay: 'CR 3',
        xp: 700,
        attackBonus: 5,
        damageDiceCount: 2,
        damageDiceSides: 6,
        damageBonus: 3,
        damageType: 'piercing',
        secondaryDamageDiceCount: 2,
        secondaryDamageDiceSides: 6,
        secondaryDamageType: 'poison',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Petrifying Gaze',
            description: 'If a creature starts its turn within 30 ft. of the basilisk and the two of them can see each other, the basilisk can force the creature to make a DC 12 Constitution saving throw if the basilisk isn\'t incapacitated. On a failure, the creature begins to turn to stone and is restrained.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage plus 7 (2d6) poison damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '2d6 + 3 + 2d6 poison',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_berserker',
      name: 'Berserker',
      statBlock: const MinionStatBlock(
        id: 'berserker',
        name: 'Berserker',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any chaotic alignment',
        ac: 13,
        armorType: 'hide armor',
        maxHp: 67,
        hitDice: '9d8 + 27',
        speed: '30 ft.',
        strScore: 16,
        dexScore: 12,
        conScore: 17,
        intScore: 9,
        wisScore: 11,
        chaScore: 9,
        senses: 'passive Perception 10',
        languages: 'any one language (usually Common)',
        crDisplay: 'CR 2',
        xp: 450,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 12,
        damageBonus: 3,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Reckless',
            description: 'At the start of its turn, the berserker can gain advantage on all melee weapon attack rolls during that turn, but attack rolls against it have advantage until the start of its next turn.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Greataxe',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d12 + 3',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_centaur',
      name: 'Centaur',
      statBlock: const MinionStatBlock(
        id: 'centaur',
        name: 'Centaur',
        sizeDisplay: 'Large',
        typeDisplay: 'Monstrosity',
        alignment: 'neutral good',
        ac: 12,
        maxHp: 45,
        hitDice: '6d10 + 12',
        speed: '50 ft.',
        strScore: 18,
        dexScore: 14,
        conScore: 14,
        intScore: 9,
        wisScore: 13,
        chaScore: 11,
        skills: 'Athletics +6, Perception +3, Survival +3',
        senses: 'passive Perception 13',
        languages: 'Elvish, Sylvan',
        crDisplay: 'CR 2',
        xp: 450,
        attackBonus: 6,
        damageDiceCount: 1,
        damageDiceSides: 10,
        damageBonus: 4,
        damageType: 'piercing',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Charge',
            description: 'If the centaur moves at least 30 ft. straight toward a target and then hits it with a pike attack on the same turn, the target takes an extra 10 (3d6) piercing damage.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The centaur makes two attacks: one with its pike and one with its hooves or two with its longbow.',
          ),
          CreatureAction(
            name: 'Pike',
            description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 9 (1d10 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '10 ft.',
            hitDamage: '1d10 + 4',
          ),
          CreatureAction(
            name: 'Hooves',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '2d6 + 4',
          ),
          CreatureAction(
            name: 'Longbow',
            description: 'Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8 + 2) piercing damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 4,
            reach: 'range 150/600 ft.',
            hitDamage: '1d8 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_couatl',
      name: 'Couatl',
      statBlock: const MinionStatBlock(
        id: 'couatl',
        name: 'Couatl',
        sizeDisplay: 'Medium',
        typeDisplay: 'Celestial',
        alignment: 'lawful good',
        ac: 19,
        armorType: 'natural armor',
        maxHp: 97,
        hitDice: '13d8 + 39',
        speed: '30 ft., fly 90 ft.',
        strScore: 16,
        dexScore: 20,
        conScore: 17,
        intScore: 18,
        wisScore: 20,
        chaScore: 18,
        savingThrows: 'Con +5, Wis +7, Cha +6',
        damageResistances: 'radiant',
        damageImmunities: 'psychic; bludgeoning, piercing, and slashing from nonmagical attacks',
        senses: 'truesight 120 ft., passive Perception 15',
        languages: 'all, telepathy 120 ft.',
        crDisplay: 'CR 4',
        xp: 1100,
        attackBonus: 8,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 5,
        damageType: 'piercing',
        secondaryDamageDiceCount: 2,
        secondaryDamageDiceSides: 6,
        secondaryDamageType: 'radiant',
        accentColor: Color(0xFFEAB308),
        traits: [
          CreatureTrait(
            name: 'Magic Resistance',
            description: 'The couatl has advantage on saving throws against spells and other magical effects.',
          ),
          CreatureTrait(
            name: 'Shielded Mind',
            description: 'The couatl is immune to scrying and to any effect that would sense its emotions, read its thoughts, or detect its location.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +8 to hit, reach 5 ft., one creature. Hit: 8 (1d6 + 5) piercing damage, and the target must succeed on a DC 13 Constitution saving throw or be poisoned for 24 hours. Until this poison ends, the target is unconscious.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 8,
            reach: '5 ft.',
            hitDamage: '1d6 + 5',
          ),
          CreatureAction(
            name: 'Constrict',
            description: 'Melee Weapon Attack: +6 to hit, reach 10 ft., one Medium or smaller creature. Hit: 10 (2d6 + 3) bludgeoning damage, and the target is grappled (escape DC 15).',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '10 ft.',
            hitDamage: '2d6 + 3',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_cult_fanatic',
      name: 'Cult Fanatic',
      statBlock: const MinionStatBlock(
        id: 'cult_fanatic',
        name: 'Cult Fanatic',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (any race)',
        alignment: 'any non-good alignment',
        ac: 13,
        armorType: 'leather armor',
        maxHp: 33,
        hitDice: '6d8 + 6',
        speed: '30 ft.',
        strScore: 11,
        dexScore: 14,
        conScore: 12,
        intScore: 10,
        wisScore: 13,
        chaScore: 14,
        skills: 'Deception +4, Persuasion +4, Religion +2',
        senses: 'passive Perception 11',
        languages: 'any one language',
        crDisplay: 'CR 2',
        xp: 450,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 4,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Dark Devotion',
            description: 'The fanatic has advantage on saving throws against being charmed or frightened.',
          ),
          CreatureTrait(
            name: 'Spellcasting',
            description: 'The fanatic is a 4th-level spellcaster (spell save DC 11, +3 to hit with spell attacks). Cantrips: light, sacred flame, thaumaturgy. 1st level (4 slots): command, inflict wounds, shield of faith. 2nd level (3 slots): hold person, spiritual weapon.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The fanatic makes two melee attacks.',
          ),
          CreatureAction(
            name: 'Dagger',
            description: 'Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one creature. Hit: 4 (1d4 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft. / range 20/60 ft.',
            hitDamage: '1d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_doppelganger',
      name: 'Doppelganger',
      statBlock: const MinionStatBlock(
        id: 'doppelganger',
        name: 'Doppelganger',
        sizeDisplay: 'Medium',
        typeDisplay: 'Monstrosity (shapechanger)',
        alignment: 'neutral',
        ac: 14,
        maxHp: 52,
        hitDice: '8d8 + 16',
        speed: '30 ft.',
        strScore: 11,
        dexScore: 18,
        conScore: 14,
        intScore: 11,
        wisScore: 12,
        chaScore: 14,
        skills: 'Deception +6, Insight +3',
        conditionImmunities: 'charmed',
        senses: 'darkvision 60 ft., passive Perception 11',
        languages: 'Common',
        crDisplay: 'CR 3',
        xp: 700,
        attackBonus: 6,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 4,
        damageType: 'bludgeoning',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Ambusher',
            description: 'The doppelganger has advantage on attack rolls against any creature it has surprised.',
          ),
          CreatureTrait(
            name: 'Surprise Attack',
            description: 'If the doppelganger surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 10 (3d6) damage from the attack.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The doppelganger makes two slam attacks.',
          ),
          CreatureAction(
            name: 'Slam',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '1d6 + 4',
          ),
          CreatureAction(
            name: 'Read Thoughts',
            description: 'The doppelganger magically reads the surface thoughts of one creature within 60 ft. of it.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_gargoyle',
      name: 'Gargoyle',
      statBlock: const MinionStatBlock(
        id: 'gargoyle',
        name: 'Gargoyle',
        sizeDisplay: 'Medium',
        typeDisplay: 'Elemental',
        alignment: 'chaotic evil',
        ac: 15,
        armorType: 'natural armor',
        maxHp: 52,
        hitDice: '7d8 + 21',
        speed: '30 ft., fly 60 ft.',
        strScore: 15,
        dexScore: 11,
        conScore: 16,
        intScore: 6,
        wisScore: 11,
        chaScore: 7,
        damageResistances: 'bludgeoning, piercing, and slashing from nonmagical attacks not made with adamantine',
        damageImmunities: 'poison',
        conditionImmunities: 'exhaustion, petrified, poisoned',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'Terran',
        crDisplay: 'CR 2',
        xp: 450,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 6,
        damageBonus: 2,
        damageType: 'piercing',
        accentColor: Color(0xFF0EA5E9),
        traits: [
          CreatureTrait(
            name: 'False Appearance',
            description: 'While the gargoyle remains motionless, it is indistinguishable from an inanimate statue.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The gargoyle makes two attacks: one with its bite and one with its claws.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Claws',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_gelatinous_cube',
      name: 'Gelatinous Cube',
      statBlock: const MinionStatBlock(
        id: 'gelatinous_cube',
        name: 'Gelatinous Cube',
        sizeDisplay: 'Large',
        typeDisplay: 'Ooze',
        alignment: 'unaligned',
        ac: 6,
        maxHp: 84,
        hitDice: '8d10 + 40',
        speed: '15 ft.',
        strScore: 14,
        dexScore: 3,
        conScore: 20,
        intScore: 1,
        wisScore: 6,
        chaScore: 1,
        conditionImmunities: 'blinded, charmed, deafened, exhaustion, frightened, prone',
        senses: 'blindsight 60 ft. (blind beyond this radius), passive Perception 8',
        languages: '—',
        crDisplay: 'CR 2',
        xp: 450,
        attackBonus: 4,
        damageDiceCount: 3,
        damageDiceSides: 6,
        damageBonus: 0,
        damageType: 'acid',
        accentColor: Color(0xFF84CC16),
        traits: [
          CreatureTrait(
            name: 'Ooze Cube',
            description: 'The cube takes up its entire space. Other creatures can enter the space, but a creature that does so is subjected to the cube\'s Engulf and has disadvantage on the saving throw.',
          ),
          CreatureTrait(
            name: 'Transparent',
            description: 'Even when the cube is in plain sight, it takes a successful DC 15 Wisdom (Perception) check to spot a cube that has neither moved nor attacked.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Pseudopod',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 10 (3d6) acid damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '3d6 acid',
          ),
          CreatureAction(
            name: 'Engulf',
            description: 'The cube moves up to its speed. While doing so, it can enter Large or smaller creatures\' spaces. Whenever the cube enters a creature\'s space, the creature must make a DC 12 Dexterity saving throw. On a failure, the creature takes 10 (3d6) acid damage and is engulfed.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_ghost',
      name: 'Ghost',
      statBlock: const MinionStatBlock(
        id: 'ghost',
        name: 'Ghost',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'any alignment',
        ac: 11,
        maxHp: 45,
        hitDice: '10d8',
        speed: '0 ft., fly 40 ft. (hover)',
        strScore: 7,
        dexScore: 13,
        conScore: 10,
        intScore: 10,
        wisScore: 12,
        chaScore: 17,
        damageResistances: 'acid, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks',
        damageImmunities: 'cold, necrotic, poison',
        conditionImmunities: 'charmed, exhaustion, frightened, grappled, paralyzed, petrified, poisoned, prone, restrained',
        senses: 'darkvision 60 ft., passive Perception 11',
        languages: 'any languages it knew in life',
        crDisplay: 'CR 4',
        xp: 1100,
        attackBonus: 5,
        damageDiceCount: 4,
        damageDiceSides: 6,
        damageBonus: 3,
        damageType: 'necrotic',
        accentColor: Color(0xFFCBD5E1),
        traits: [
          CreatureTrait(
            name: 'Ethereal Sight',
            description: 'The ghost can see 60 ft. into the Ethereal Plane when it is on the Material Plane, and vice versa.',
          ),
          CreatureTrait(
            name: 'Incorporeal Movement',
            description: 'The ghost can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Withering Touch',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 17 (4d6 + 3) necrotic damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '4d6 + 3',
          ),
          CreatureAction(
            name: 'Etherealness',
            description: 'The ghost enters the Ethereal Plane from the Material Plane, or vice versa.',
          ),
          CreatureAction(
            name: 'Horrifying Visage',
            description: 'Each non-undead creature within 60 ft. of the ghost that can see it must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute.',
          ),
          CreatureAction(
            name: 'Possession (Recharge 6)',
            description: 'One humanoid that the ghost can see within 5 ft. of it must succeed on a DC 13 Charisma saving throw or be possessed by the ghost.',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_manticore',
      name: 'Manticore',
      statBlock: const MinionStatBlock(
        id: 'manticore',
        name: 'Manticore',
        sizeDisplay: 'Large',
        typeDisplay: 'Monstrosity',
        alignment: 'lawful evil',
        ac: 14,
        armorType: 'natural armor',
        maxHp: 68,
        hitDice: '8d10 + 24',
        speed: '30 ft., fly 50 ft.',
        strScore: 17,
        dexScore: 16,
        conScore: 17,
        intScore: 7,
        wisScore: 12,
        chaScore: 8,
        senses: 'darkvision 60 ft., passive Perception 11',
        languages: 'Common',
        crDisplay: 'CR 3',
        xp: 700,
        attackBonus: 5,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 3,
        damageType: 'piercing',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Tail Spike Regrowth',
            description: 'The manticore has twenty-four tail spikes. Used spikes regrow when the manticore finishes a long rest.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The manticore makes three attacks: one with its bite and two with its claws or three with its tail spikes.',
          ),
          CreatureAction(
            name: 'Bite',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d8 + 3',
          ),
          CreatureAction(
            name: 'Claw',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '1d6 + 3',
          ),
          CreatureAction(
            name: 'Tail Spike',
            description: 'Ranged Weapon Attack: +5 to hit, range 100/200 ft., one target. Hit: 7 (1d8 + 3) piercing damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 5,
            reach: 'range 100/200 ft.',
            hitDamage: '1d8 + 3',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_minotaur',
      name: 'Minotaur',
      statBlock: const MinionStatBlock(
        id: 'minotaur',
        name: 'Minotaur',
        sizeDisplay: 'Large',
        typeDisplay: 'Monstrosity',
        alignment: 'chaotic evil',
        ac: 14,
        armorType: 'natural armor',
        maxHp: 76,
        hitDice: '9d10 + 27',
        speed: '40 ft.',
        strScore: 18,
        dexScore: 11,
        conScore: 16,
        intScore: 6,
        wisScore: 16,
        chaScore: 9,
        skills: 'Perception +7',
        senses: 'darkvision 60 ft., passive Perception 17',
        languages: 'Abyssal',
        crDisplay: 'CR 3',
        xp: 700,
        attackBonus: 6,
        damageDiceCount: 2,
        damageDiceSides: 12,
        damageBonus: 4,
        damageType: 'slashing',
        accentColor: Color(0xFFD97706),
        traits: [
          CreatureTrait(
            name: 'Charge',
            description: 'If the minotaur moves at least 10 ft. straight toward a target and then hits it with a gore attack on the same turn, the target takes an extra 9 (2d8) piercing damage. If the target is a creature, it must succeed on a DC 14 Strength saving throw or be pushed up to 10 ft. away and knocked prone.',
          ),
          CreatureTrait(
            name: 'Labyrinthine Recall',
            description: 'The minotaur can perfectly recall any path it has traveled.',
          ),
          CreatureTrait(
            name: 'Reckless',
            description: 'At the start of its turn, the minotaur can gain advantage on all melee weapon attack rolls during that turn, but attack rolls against it have advantage until the start of its next turn.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Greataxe',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 17 (2d12 + 4) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '2d12 + 4',
          ),
          CreatureAction(
            name: 'Gore',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '2d8 + 4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_mummy',
      name: 'Mummy',
      statBlock: const MinionStatBlock(
        id: 'mummy',
        name: 'Mummy',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'lawful evil',
        ac: 11,
        armorType: 'natural armor',
        maxHp: 58,
        hitDice: '8d8 + 24',
        speed: '20 ft.',
        strScore: 16,
        dexScore: 8,
        conScore: 15,
        intScore: 6,
        wisScore: 10,
        chaScore: 12,
        savingThrows: 'Wis +2',
        damageVulnerabilities: 'fire',
        damageResistances: 'bludgeoning, piercing, and slashing from nonmagical attacks',
        damageImmunities: 'necrotic, poison',
        conditionImmunities: 'charmed, exhaustion, frightened, paralyzed, poisoned',
        senses: 'darkvision 60 ft., passive Perception 10',
        languages: 'the languages it knew in life',
        crDisplay: 'CR 3',
        xp: 700,
        attackBonus: 5,
        damageDiceCount: 2,
        damageDiceSides: 6,
        damageBonus: 3,
        damageType: 'bludgeoning',
        secondaryDamageDiceCount: 3,
        secondaryDamageDiceSides: 6,
        secondaryDamageType: 'necrotic',
        accentColor: Color(0xFFCBD5E1),
        actions: [
          CreatureAction(
            name: 'Dreadful Glare',
            description: 'The mummy targets one creature it can see within 60 ft. of it. If the target can see the mummy, it must succeed on a DC 11 Wisdom saving throw against this magic or become frightened until the end of the mummy\'s next turn. If the target fails the saving throw by 5 or more, it is also paralyzed for the same duration.',
          ),
          CreatureAction(
            name: 'Rotting Fist',
            description: 'Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) bludgeoning damage plus 10 (3d6) necrotic damage. If the target is a creature, it must succeed on a DC 12 Constitution saving throw or be cursed with mummy rot.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 5,
            reach: '5 ft.',
            hitDamage: '2d6 + 3 + 3d6 necrotic',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_ogre',
      name: 'Ogre',
      statBlock: const MinionStatBlock(
        id: 'ogre',
        name: 'Ogre',
        sizeDisplay: 'Large',
        typeDisplay: 'Giant',
        alignment: 'chaotic evil',
        ac: 11,
        armorType: 'hide armor',
        maxHp: 59,
        hitDice: '7d10 + 21',
        speed: '40 ft.',
        strScore: 19,
        dexScore: 8,
        conScore: 16,
        intScore: 5,
        wisScore: 7,
        chaScore: 7,
        senses: 'darkvision 60 ft., passive Perception 8',
        languages: 'Common, Giant',
        crDisplay: 'CR 2',
        xp: 450,
        attackBonus: 6,
        damageDiceCount: 2,
        damageDiceSides: 8,
        damageBonus: 4,
        damageType: 'bludgeoning',
        accentColor: Color(0xFF94A3B8),
        actions: [
          CreatureAction(
            name: 'Greatclub',
            description: 'Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft.',
            hitDamage: '2d8 + 4',
          ),
          CreatureAction(
            name: 'Javelin',
            description: 'Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 11 (2d6 + 4) piercing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 6,
            reach: '5 ft. / range 30/120 ft.',
            hitDamage: '2d6 + 4',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_werewolf',
      name: 'Werewolf',
      statBlock: const MinionStatBlock(
        id: 'werewolf',
        name: 'Werewolf',
        sizeDisplay: 'Medium',
        typeDisplay: 'Humanoid (human, shapechanger)',
        alignment: 'chaotic evil',
        ac: 11,
        armorType: '12 in wolf/hybrid form',
        maxHp: 58,
        hitDice: '9d8 + 18',
        speed: '30 ft. (40 ft. in wolf form)',
        strScore: 15,
        dexScore: 13,
        conScore: 14,
        intScore: 10,
        wisScore: 11,
        chaScore: 10,
        skills: 'Perception +4, Stealth +3',
        damageImmunities: 'bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons',
        senses: 'passive Perception 14',
        languages: 'Common (can\'t speak in wolf form)',
        crDisplay: 'CR 3',
        xp: 700,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 2,
        damageType: 'slashing',
        accentColor: Color(0xFF94A3B8),
        traits: [
          CreatureTrait(
            name: 'Shapechanger',
            description: 'The werewolf can use its action to polymorph into a wolf-humanoid hybrid or into a wolf, or back into its true form, which is humanoid.',
          ),
          CreatureTrait(
            name: 'Keen Hearing and Smell',
            description: 'The werewolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack (Hybrid Form Only)',
            description: 'The werewolf makes two attacks: one with its bite and one with its claws or spear.',
          ),
          CreatureAction(
            name: 'Bite (Wolf or Hybrid Form Only)',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) piercing damage. If the target is a humanoid, it must succeed on a DC 12 Constitution saving throw or be cursed with werewolf lycanthropy.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d8 + 2',
          ),
          CreatureAction(
            name: 'Claws (Hybrid Form Only)',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 7 (2d4 + 2) slashing damage.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '2d4 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_wight',
      name: 'Wight',
      statBlock: const MinionStatBlock(
        id: 'wight',
        name: 'Wight',
        sizeDisplay: 'Medium',
        typeDisplay: 'Undead',
        alignment: 'neutral evil',
        ac: 14,
        armorType: 'studded leather',
        maxHp: 45,
        hitDice: '6d8 + 18',
        speed: '30 ft.',
        strScore: 15,
        dexScore: 14,
        conScore: 16,
        intScore: 10,
        wisScore: 13,
        chaScore: 15,
        skills: 'Perception +3, Stealth +4',
        damageResistances: 'necrotic; bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons',
        damageImmunities: 'poison',
        conditionImmunities: 'exhaustion, poisoned',
        senses: 'darkvision 60 ft., passive Perception 13',
        languages: 'the languages it knew in life',
        crDisplay: 'CR 3',
        xp: 700,
        attackBonus: 4,
        damageDiceCount: 1,
        damageDiceSides: 8,
        damageBonus: 2,
        damageType: 'slashing',
        accentColor: Color(0xFFCBD5E1),
        traits: [
          CreatureTrait(
            name: 'Sunlight Sensitivity',
            description: 'While in sunlight, the wight has disadvantage on attack rolls and Perception checks.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Multiattack',
            description: 'The wight makes two longsword attacks or two longbow attacks. It can use its Life Drain in place of one longsword attack.',
          ),
          CreatureAction(
            name: 'Life Drain',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6 + 2) necrotic damage. The target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d6 + 2',
          ),
          CreatureAction(
            name: 'Longsword',
            description: 'Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) slashing damage, or 7 (1d10 + 2) slashing damage if used with two hands.',
            attackType: 'Melee Weapon Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '1d8 + 2',
          ),
          CreatureAction(
            name: 'Longbow',
            description: 'Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8 + 2) piercing damage.',
            attackType: 'Ranged Weapon Attack',
            attackBonus: 4,
            reach: 'range 150/600 ft.',
            hitDamage: '1d8 + 2',
          ),
        ],
      ),
    ),
    MonsterItem.simple(
      id: 'srd_mon_will_o_wisp',
      name: 'Will-o\'-Wisp',
      statBlock: const MinionStatBlock(
        id: 'will_o_wisp',
        name: 'Will-o\'-Wisp',
        sizeDisplay: 'Tiny',
        typeDisplay: 'Undead',
        alignment: 'chaotic evil',
        ac: 19,
        maxHp: 22,
        hitDice: '9d4',
        speed: '0 ft., fly 50 ft. (hover)',
        strScore: 1,
        dexScore: 28,
        conScore: 10,
        intScore: 13,
        wisScore: 14,
        chaScore: 11,
        damageResistances: 'acid, cold, fire, necrotic, thunder; bludgeoning, piercing, and slashing from nonmagical attacks',
        damageImmunities: 'lightning, poison',
        conditionImmunities: 'exhaustion, grappled, paralyzed, poisoned, prone, restrained, unconscious',
        senses: 'darkvision 120 ft., passive Perception 12',
        languages: 'the languages it knew in life',
        crDisplay: 'CR 2',
        xp: 450,
        attackBonus: 4,
        damageDiceCount: 2,
        damageDiceSides: 8,
        damageBonus: 0,
        damageType: 'lightning',
        accentColor: Color(0xFFCBD5E1),
        traits: [
          CreatureTrait(
            name: 'Consume Life',
            description: 'As a bonus action, the will-o\'-wisp can target one creature it can see within 5 ft. of it that has 0 hit points and is still alive. The target must succeed on a DC 10 Constitution saving throw against this magic or die. If the target dies, the will-o\'-wisp regains 10 (3d6) hit points.',
          ),
          CreatureTrait(
            name: 'Ephemeral',
            description: 'The will-o\'-wisp can\'t wear or carry anything.',
          ),
          CreatureTrait(
            name: 'Incorporeal Movement',
            description: 'The will-o\'-wisp can move through other creatures and objects as if they were difficult terrain. It takes 5 (1d10) force damage if it ends its turn inside an object.',
          ),
        ],
        actions: [
          CreatureAction(
            name: 'Shock',
            description: 'Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 9 (2d8) lightning damage.',
            attackType: 'Melee Spell Attack',
            attackBonus: 4,
            reach: '5 ft.',
            hitDamage: '2d8 lightning',
          ),
          CreatureAction(
            name: 'Invisibility',
            description: 'The will-o\'-wisp and its light magically become invisible until it attacks or uses its Life Drain, or until its concentration ends.',
          ),
        ],
      ),
    ),
  ];
}
